# Add set(CONFIG_USE_middleware_wireless_framework_sfc true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

      if(CONFIG_CORE_ID STREQUAL cm33_core1 AND (CONFIG_DEVICE_ID STREQUAL KW47B42Z83xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z96xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z97xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB3xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB6xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB7xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42082xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42092xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B3xxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727CxxxA))
    target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
          ${CMAKE_CURRENT_LIST_DIR}/services/SFC/fwk_rf_sfc.c
        )
    endif()

  
      target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/services/SFC
        )

  
