# Add set(CONFIG_USE_middleware_wireless_framework_private_interfaces true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

      target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/Common
          ${CMAKE_CURRENT_LIST_DIR}/platform/include
          ${CMAKE_CURRENT_LIST_DIR}/services/DBG
          ${CMAKE_CURRENT_LIST_DIR}/services/FactoryDataProvider
          ${CMAKE_CURRENT_LIST_DIR}/services/FileSystem
          ${CMAKE_CURRENT_LIST_DIR}/services/FSCI/Interface
          ${CMAKE_CURRENT_LIST_DIR}/services/FunctionLib
          ${CMAKE_CURRENT_LIST_DIR}/services/HWParameter
          ${CMAKE_CURRENT_LIST_DIR}/services/LowPower
          ${CMAKE_CURRENT_LIST_DIR}/services/ModuleInfo
          ${CMAKE_CURRENT_LIST_DIR}/services/NVM/Interface
          ${CMAKE_CURRENT_LIST_DIR}/services/NVM/Source
          ${CMAKE_CURRENT_LIST_DIR}/services/OtaSupport/Interface
          ${CMAKE_CURRENT_LIST_DIR}/services/OTW/Interface
          ${CMAKE_CURRENT_LIST_DIR}/services/PDM/Include
          ${CMAKE_CURRENT_LIST_DIR}/services/PDUM/Include
          ${CMAKE_CURRENT_LIST_DIR}/services/SecLib_RNG
          ${CMAKE_CURRENT_LIST_DIR}/services/Sensors
          ${CMAKE_CURRENT_LIST_DIR}/services/SFC
          ${CMAKE_CURRENT_LIST_DIR}/../XCVR/drv
          ${CMAKE_CURRENT_LIST_DIR}/../XCVR/drv/nb2p4ghz
        )

        if((CONFIG_CORE_ID STREQUAL cm33_core0 OR CONFIG_CORE_ID STREQUAL cm33) AND (CONFIG_DEVICE_ID STREQUAL KW45B41Z52xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z53xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z82xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z83xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z83xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z96xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z97xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB3xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB6xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB7xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42082xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42092xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B3xxxA OR CONFIG_DEVICE_ID STREQUAL MCXW716CxxxA OR CONFIG_DEVICE_ID STREQUAL MCXW716AxxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727CxxxA))
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/platform/wireless_mcu
        )
    endif()

        if(CONFIG_CORE_ID STREQUAL cm33_core1 AND (CONFIG_DEVICE_ID STREQUAL KW47B42Z83xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z96xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z97xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB3xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB6xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB7xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42082xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42092xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B3xxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727CxxxA))
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/platform/wireless_nbu
        )
    endif()

        if((CONFIG_DEVICE_ID STREQUAL RW610 OR CONFIG_DEVICE_ID STREQUAL RW612))
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/platform/rw61x
        )
    endif()

        if(CONFIG_CORE_ID STREQUAL cm33 AND (CONFIG_DEVICE_ID STREQUAL KW45B41Z52xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z53xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z82xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z83xxxA OR CONFIG_DEVICE_ID STREQUAL MCXW716CxxxA OR CONFIG_DEVICE_ID STREQUAL MCXW716AxxxA))
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/../XCVR/drv/nb2p4ghz/configs/gen45
        )
    endif()

        if((CONFIG_CORE_ID STREQUAL cm33_core0 OR CONFIG_CORE_ID STREQUAL cm33_core1) AND (CONFIG_DEVICE_ID STREQUAL KW47B42Z83xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z96xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z97xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB3xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB6xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB7xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42082xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42092xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B3xxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727CxxxA))
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/../XCVR/drv/nb2p4ghz/configs/gen47
        )
    endif()

  
