# Add set(CONFIG_USE_middleware_wireless_framework_platform_reset true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

      if((CONFIG_CORE_ID STREQUAL cm33_core0 OR CONFIG_CORE_ID STREQUAL cm33) AND (CONFIG_DEVICE_ID STREQUAL KW45B41Z52xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z53xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z82xxxA OR CONFIG_DEVICE_ID STREQUAL KW45B41Z83xxxA OR CONFIG_DEVICE_ID STREQUAL K32W1480xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z83xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z96xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z97xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB3xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB6xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB7xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42082xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42092xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B3xxxA OR CONFIG_DEVICE_ID STREQUAL MCXW716CxxxA OR CONFIG_DEVICE_ID STREQUAL MCXW716AxxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727CxxxA))
    target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
          ${CMAKE_CURRENT_LIST_DIR}/platform/wireless_mcu/fwk_platform_reset.c
        )
    endif()

  

