/**
 * Copyright 2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

/*
 * This allows to inject source code before lwipopts_gen.h is included.
 * It can be used for example to provide function signatures for
 * the functions configured there, because if it is generated
 * from Kconfig, it is not possible to place signatures in lwipopts_gen.h.
 */
#ifdef LWIP_OPT_H_CODE_LINE_1
LWIP_OPT_H_CODE_LINE_1
#endif
#ifdef LWIP_OPT_H_CODE_LINE_2
LWIP_OPT_H_CODE_LINE_2
#endif
#ifdef LWIP_OPT_H_CODE_LINE_3
LWIP_OPT_H_CODE_LINE_3
#endif
#ifdef LWIP_OPT_H_CODE_LINE_4
LWIP_OPT_H_CODE_LINE_4
#endif
#ifdef LWIP_OPT_H_CODE_LINE_5
LWIP_OPT_H_CODE_LINE_5
#endif
#ifdef LWIP_OPT_H_CODE_LINE_6
LWIP_OPT_H_CODE_LINE_6
#endif
#ifdef LWIP_OPT_H_CODE_LINE_7
LWIP_OPT_H_CODE_LINE_7
#endif
#ifdef LWIP_OPT_H_CODE_LINE_8
LWIP_OPT_H_CODE_LINE_8
#endif
#ifdef LWIP_OPT_H_CODE_LINE_9
LWIP_OPT_H_CODE_LINE_9
#endif
#ifdef LWIP_OPT_H_CODE_LINE_10
LWIP_OPT_H_CODE_LINE_10
#endif
#ifdef LWIP_OPT_H_CODE_LINE_11
LWIP_OPT_H_CODE_LINE_11
#endif
#ifdef LWIP_OPT_H_CODE_LINE_12
LWIP_OPT_H_CODE_LINE_12
#endif
#ifdef LWIP_OPT_H_CODE_LINE_13
LWIP_OPT_H_CODE_LINE_13
#endif
#ifdef LWIP_OPT_H_CODE_LINE_14
LWIP_OPT_H_CODE_LINE_14
#endif
#ifdef LWIP_OPT_H_CODE_LINE_15
LWIP_OPT_H_CODE_LINE_15
#endif
#ifdef LWIP_OPT_H_CODE_LINE_16
LWIP_OPT_H_CODE_LINE_16
#endif
#ifdef LWIP_OPT_H_CODE_LINE_17
LWIP_OPT_H_CODE_LINE_17
#endif
#ifdef LWIP_OPT_H_CODE_LINE_18
LWIP_OPT_H_CODE_LINE_18
#endif
#ifdef LWIP_OPT_H_CODE_LINE_19
LWIP_OPT_H_CODE_LINE_19
#endif
#ifdef LWIP_OPT_H_CODE_LINE_20
LWIP_OPT_H_CODE_LINE_20
#endif
#ifdef LWIP_OPT_H_CODE_LINE_21
LWIP_OPT_H_CODE_LINE_21
#endif
#ifdef LWIP_OPT_H_CODE_LINE_22
LWIP_OPT_H_CODE_LINE_22
#endif
#ifdef LWIP_OPT_H_CODE_LINE_23
LWIP_OPT_H_CODE_LINE_23
#endif
#ifdef LWIP_OPT_H_CODE_LINE_24
LWIP_OPT_H_CODE_LINE_24
#endif
#ifdef LWIP_OPT_H_CODE_LINE_25
LWIP_OPT_H_CODE_LINE_25
#endif
#ifdef LWIP_OPT_H_CODE_LINE_26
LWIP_OPT_H_CODE_LINE_26
#endif
#ifdef LWIP_OPT_H_CODE_LINE_27
LWIP_OPT_H_CODE_LINE_27
#endif
#ifdef LWIP_OPT_H_CODE_LINE_28
LWIP_OPT_H_CODE_LINE_28
#endif
#ifdef LWIP_OPT_H_CODE_LINE_29
LWIP_OPT_H_CODE_LINE_29
#endif
#ifdef LWIP_OPT_H_CODE_LINE_30
LWIP_OPT_H_CODE_LINE_30
#endif
#ifdef LWIP_OPT_H_CODE_LINE_31
LWIP_OPT_H_CODE_LINE_31
#endif
#ifdef LWIP_OPT_H_CODE_LINE_32
LWIP_OPT_H_CODE_LINE_32
#endif
#ifdef LWIP_OPT_H_CODE_LINE_33
LWIP_OPT_H_CODE_LINE_33
#endif
#ifdef LWIP_OPT_H_CODE_LINE_34
LWIP_OPT_H_CODE_LINE_34
#endif
#ifdef LWIP_OPT_H_CODE_LINE_35
LWIP_OPT_H_CODE_LINE_35
#endif
#ifdef LWIP_OPT_H_CODE_LINE_36
LWIP_OPT_H_CODE_LINE_36
#endif
#ifdef LWIP_OPT_H_CODE_LINE_37
LWIP_OPT_H_CODE_LINE_37
#endif
#ifdef LWIP_OPT_H_CODE_LINE_38
LWIP_OPT_H_CODE_LINE_38
#endif
#ifdef LWIP_OPT_H_CODE_LINE_39
LWIP_OPT_H_CODE_LINE_39
#endif
#ifdef LWIP_OPT_H_CODE_LINE_40
LWIP_OPT_H_CODE_LINE_40
#endif
#ifdef LWIP_OPT_H_CODE_LINE_41
LWIP_OPT_H_CODE_LINE_41
#endif
#ifdef LWIP_OPT_H_CODE_LINE_42
LWIP_OPT_H_CODE_LINE_42
#endif
#ifdef LWIP_OPT_H_CODE_LINE_43
LWIP_OPT_H_CODE_LINE_43
#endif
#ifdef LWIP_OPT_H_CODE_LINE_44
LWIP_OPT_H_CODE_LINE_44
#endif
#ifdef LWIP_OPT_H_CODE_LINE_45
LWIP_OPT_H_CODE_LINE_45
#endif
#ifdef LWIP_OPT_H_CODE_LINE_46
LWIP_OPT_H_CODE_LINE_46
#endif
#ifdef LWIP_OPT_H_CODE_LINE_47
LWIP_OPT_H_CODE_LINE_47
#endif
#ifdef LWIP_OPT_H_CODE_LINE_48
LWIP_OPT_H_CODE_LINE_48
#endif
#ifdef LWIP_OPT_H_CODE_LINE_49
LWIP_OPT_H_CODE_LINE_49
#endif
#ifdef LWIP_OPT_H_CODE_LINE_50
LWIP_OPT_H_CODE_LINE_50
#endif
#ifdef LWIP_OPT_H_CODE_LINE_51
LWIP_OPT_H_CODE_LINE_51
#endif
#ifdef LWIP_OPT_H_CODE_LINE_52
LWIP_OPT_H_CODE_LINE_52
#endif
#ifdef LWIP_OPT_H_CODE_LINE_53
LWIP_OPT_H_CODE_LINE_53
#endif
#ifdef LWIP_OPT_H_CODE_LINE_54
LWIP_OPT_H_CODE_LINE_54
#endif
#ifdef LWIP_OPT_H_CODE_LINE_55
LWIP_OPT_H_CODE_LINE_55
#endif
#ifdef LWIP_OPT_H_CODE_LINE_56
LWIP_OPT_H_CODE_LINE_56
#endif
#ifdef LWIP_OPT_H_CODE_LINE_57
LWIP_OPT_H_CODE_LINE_57
#endif
#ifdef LWIP_OPT_H_CODE_LINE_58
LWIP_OPT_H_CODE_LINE_58
#endif
#ifdef LWIP_OPT_H_CODE_LINE_59
LWIP_OPT_H_CODE_LINE_59
#endif
#ifdef LWIP_OPT_H_CODE_LINE_60
LWIP_OPT_H_CODE_LINE_60
#endif
#ifdef LWIP_OPT_H_CODE_LINE_61
LWIP_OPT_H_CODE_LINE_61
#endif
#ifdef LWIP_OPT_H_CODE_LINE_62
LWIP_OPT_H_CODE_LINE_62
#endif
#ifdef LWIP_OPT_H_CODE_LINE_63
LWIP_OPT_H_CODE_LINE_63
#endif
#ifdef LWIP_OPT_H_CODE_LINE_64
LWIP_OPT_H_CODE_LINE_64
#endif
#ifdef LWIP_OPT_H_CODE_LINE_65
LWIP_OPT_H_CODE_LINE_65
#endif
#ifdef LWIP_OPT_H_CODE_LINE_66
LWIP_OPT_H_CODE_LINE_66
#endif
#ifdef LWIP_OPT_H_CODE_LINE_67
LWIP_OPT_H_CODE_LINE_67
#endif
#ifdef LWIP_OPT_H_CODE_LINE_68
LWIP_OPT_H_CODE_LINE_68
#endif
#ifdef LWIP_OPT_H_CODE_LINE_69
LWIP_OPT_H_CODE_LINE_69
#endif
#ifdef LWIP_OPT_H_CODE_LINE_70
LWIP_OPT_H_CODE_LINE_70
#endif
#ifdef LWIP_OPT_H_CODE_LINE_71
LWIP_OPT_H_CODE_LINE_71
#endif
#ifdef LWIP_OPT_H_CODE_LINE_72
LWIP_OPT_H_CODE_LINE_72
#endif
#ifdef LWIP_OPT_H_CODE_LINE_73
LWIP_OPT_H_CODE_LINE_73
#endif
#ifdef LWIP_OPT_H_CODE_LINE_74
LWIP_OPT_H_CODE_LINE_74
#endif
#ifdef LWIP_OPT_H_CODE_LINE_75
LWIP_OPT_H_CODE_LINE_75
#endif
#ifdef LWIP_OPT_H_CODE_LINE_76
LWIP_OPT_H_CODE_LINE_76
#endif
#ifdef LWIP_OPT_H_CODE_LINE_77
LWIP_OPT_H_CODE_LINE_77
#endif
#ifdef LWIP_OPT_H_CODE_LINE_78
LWIP_OPT_H_CODE_LINE_78
#endif
#ifdef LWIP_OPT_H_CODE_LINE_79
LWIP_OPT_H_CODE_LINE_79
#endif
#ifdef LWIP_OPT_H_CODE_LINE_80
LWIP_OPT_H_CODE_LINE_80
#endif
#ifdef LWIP_OPT_H_CODE_LINE_81
LWIP_OPT_H_CODE_LINE_81
#endif
#ifdef LWIP_OPT_H_CODE_LINE_82
LWIP_OPT_H_CODE_LINE_82
#endif
#ifdef LWIP_OPT_H_CODE_LINE_83
LWIP_OPT_H_CODE_LINE_83
#endif
#ifdef LWIP_OPT_H_CODE_LINE_84
LWIP_OPT_H_CODE_LINE_84
#endif
#ifdef LWIP_OPT_H_CODE_LINE_85
LWIP_OPT_H_CODE_LINE_85
#endif
#ifdef LWIP_OPT_H_CODE_LINE_86
LWIP_OPT_H_CODE_LINE_86
#endif
#ifdef LWIP_OPT_H_CODE_LINE_87
LWIP_OPT_H_CODE_LINE_87
#endif
#ifdef LWIP_OPT_H_CODE_LINE_88
LWIP_OPT_H_CODE_LINE_88
#endif
#ifdef LWIP_OPT_H_CODE_LINE_89
LWIP_OPT_H_CODE_LINE_89
#endif
#ifdef LWIP_OPT_H_CODE_LINE_90
LWIP_OPT_H_CODE_LINE_90
#endif
#ifdef LWIP_OPT_H_CODE_LINE_91
LWIP_OPT_H_CODE_LINE_91
#endif
#ifdef LWIP_OPT_H_CODE_LINE_92
LWIP_OPT_H_CODE_LINE_92
#endif
#ifdef LWIP_OPT_H_CODE_LINE_93
LWIP_OPT_H_CODE_LINE_93
#endif
#ifdef LWIP_OPT_H_CODE_LINE_94
LWIP_OPT_H_CODE_LINE_94
#endif
#ifdef LWIP_OPT_H_CODE_LINE_95
LWIP_OPT_H_CODE_LINE_95
#endif
#ifdef LWIP_OPT_H_CODE_LINE_96
LWIP_OPT_H_CODE_LINE_96
#endif
#ifdef LWIP_OPT_H_CODE_LINE_97
LWIP_OPT_H_CODE_LINE_97
#endif
#ifdef LWIP_OPT_H_CODE_LINE_98
LWIP_OPT_H_CODE_LINE_98
#endif
#ifdef LWIP_OPT_H_CODE_LINE_99
LWIP_OPT_H_CODE_LINE_99
#endif
#ifdef LWIP_OPT_H_CODE_LINE_100
LWIP_OPT_H_CODE_LINE_100
#endif

/* Include the lwIP options header generated by Kconfig. */
#include "lwipopts_gen.h"

/*
 * Since Kconfig does not generate bool items with value 'n',
 * let define them here to 0 explicitly if not defined.
 * If it would stay undefined and opt.h would have default as 1,
 * it would end up set to 1 even if user selected 'n'.
 */

#ifndef ETH_DISABLE_RX_INT_WHEN_OUT_OF_BUFFERS
#define ETH_DISABLE_RX_INT_WHEN_OUT_OF_BUFFERS 0
#endif

#ifndef ETH_DO_RX_IN_SEPARATE_TASK
#define ETH_DO_RX_IN_SEPARATE_TASK 0
#endif

#ifndef ETH_USE_GPIO_ADAPTER
#define ETH_USE_GPIO_ADAPTER 0
#endif

#ifndef NETC_PROMISCUOUS
#define NETC_PROMISCUOUS 0
#endif

#ifndef NETC_PORT_USE_INCLUDES
#define NETC_PORT_USE_INCLUDES 0
#endif

#ifndef NETC_USE_SWT
#define NETC_USE_SWT 0
#endif

#ifndef LWIP_STATS
#define LWIP_STATS 0
#endif

#ifndef LWIP_STATS_DISPLAY
#define LWIP_STATS_DISPLAY 0
#endif

#ifndef LINK_STATS
#define LINK_STATS 0
#endif

#ifndef ETHARP_STATS
#define ETHARP_STATS 0
#endif

#ifndef IP_STATS
#define IP_STATS 0
#endif

#ifndef IPFRAG_STATS
#define IPFRAG_STATS 0
#endif

#ifndef ICMP_STATS
#define ICMP_STATS 0
#endif

#ifndef IGMP_STATS
#define IGMP_STATS 0
#endif

#ifndef UDP_STATS
#define UDP_STATS 0
#endif

#ifndef TCP_STATS
#define TCP_STATS 0
#endif

#ifndef MEM_STATS
#define MEM_STATS 0
#endif

#ifndef MEMP_STATS
#define MEMP_STATS 0
#endif

#ifndef SYS_STATS
#define SYS_STATS 0
#endif

#ifndef IP6_STATS
#define IP6_STATS 0
#endif

#ifndef ICMP6_STATS
#define ICMP6_STATS 0
#endif

#ifndef IP6_FRAG_STATS
#define IP6_FRAG_STATS 0
#endif

#ifndef MLD6_STATS
#define MLD6_STATS 0
#endif

#ifndef ND6_STATS
#define ND6_STATS 0
#endif

#ifndef MIB2_STATS
#define MIB2_STATS 0
#endif

#ifndef LWIP_PERF
#define LWIP_PERF 0
#endif

#ifndef NO_SYS
#define NO_SYS 0
#endif

#ifndef LWIP_TIMERS
#define LWIP_TIMERS 0
#endif

#ifndef LWIP_TIMERS_CUSTOM
#define LWIP_TIMERS_CUSTOM 0
#endif

#ifndef LWIP_MPU_COMPATIBLE
#define LWIP_MPU_COMPATIBLE 0
#endif

#ifndef LWIP_TCPIP_CORE_LOCKING
#define LWIP_TCPIP_CORE_LOCKING 0
#endif

#ifndef LWIP_TCPIP_CORE_LOCKING_INPUT
#define LWIP_TCPIP_CORE_LOCKING_INPUT 0
#endif

#ifndef SYS_LIGHTWEIGHT_PROT
#define SYS_LIGHTWEIGHT_PROT 0
#endif

#ifndef MEM_LIBC_MALLOC
#define MEM_LIBC_MALLOC 0
#endif

#ifndef MEM_CUSTOM_ALLOCATOR
#define MEM_CUSTOM_ALLOCATOR 0
#endif

#ifndef MEMP_MEM_MALLOC
#define MEMP_MEM_MALLOC 0
#endif

#ifndef MEMP_MEM_INIT
#define MEMP_MEM_INIT 0
#endif

#ifndef MEMP_SANITY_CHECK
#define MEMP_SANITY_CHECK 0
#endif

#ifndef MEM_SANITY_CHECK
#define MEM_SANITY_CHECK 0
#endif

#ifndef MEM_USE_POOLS
#define MEM_USE_POOLS 0
#endif

#ifndef MEM_USE_POOLS_TRY_BIGGER_POOL
#define MEM_USE_POOLS_TRY_BIGGER_POOL 0
#endif

#ifndef MEMP_USE_CUSTOM_POOLS
#define MEMP_USE_CUSTOM_POOLS 0
#endif

#ifndef LWIP_ALLOW_MEM_FREE_FROM_OTHER_CONTEXT
#define LWIP_ALLOW_MEM_FREE_FROM_OTHER_CONTEXT 0
#endif

#ifndef LWIP_MIB2_CALLBACKS
#define LWIP_MIB2_CALLBACKS 0
#endif

#ifndef LWIP_MULTICAST_TX_OPTIONS
#define LWIP_MULTICAST_TX_OPTIONS 0
#endif

#ifndef LWIP_CHECKSUM_CTRL_PER_NETIF
#define LWIP_CHECKSUM_CTRL_PER_NETIF 0
#endif

#ifndef CHECKSUM_GEN_IP
#define CHECKSUM_GEN_IP 0
#endif

#ifndef CHECKSUM_GEN_UDP
#define CHECKSUM_GEN_UDP 0
#endif

#ifndef CHECKSUM_GEN_TCP
#define CHECKSUM_GEN_TCP 0
#endif

#ifndef CHECKSUM_GEN_ICMP
#define CHECKSUM_GEN_ICMP 0
#endif

#ifndef CHECKSUM_GEN_ICMP6
#define CHECKSUM_GEN_ICMP6 0
#endif

#ifndef CHECKSUM_CHECK_IP
#define CHECKSUM_CHECK_IP 0
#endif

#ifndef CHECKSUM_CHECK_UDP
#define CHECKSUM_CHECK_UDP 0
#endif

#ifndef CHECKSUM_CHECK_TCP
#define CHECKSUM_CHECK_TCP 0
#endif

#ifndef CHECKSUM_CHECK_ICMP
#define CHECKSUM_CHECK_ICMP 0
#endif

#ifndef CHECKSUM_CHECK_ICMP6
#define CHECKSUM_CHECK_ICMP6 0
#endif

#ifndef LWIP_CHECKSUM_ON_COPY
#define LWIP_CHECKSUM_ON_COPY 0
#endif

#ifndef LWIP_RAW
#define LWIP_RAW 0
#endif

#ifndef LWIP_DNS
#define LWIP_DNS 0
#endif

#ifndef DNS_DOES_NAME_CHECK
#define DNS_DOES_NAME_CHECK 0
#endif

#ifndef DNS_LOCAL_HOSTLIST
#define DNS_LOCAL_HOSTLIST 0
#endif

#ifndef DNS_LOCAL_HOSTLIST_IS_DYNAMIC
#define DNS_LOCAL_HOSTLIST_IS_DYNAMIC 0
#endif

#ifndef LWIP_DNS_SUPPORT_MDNS_QUERIESE
#define LWIP_DNS_SUPPORT_MDNS_QUERIESE 0
#endif

#ifndef LWIP_UDP
#define LWIP_UDP 0
#endif

#ifndef LWIP_UDPLITE
#define LWIP_UDPLITE 0
#endif

#ifndef LWIP_NETBUF_RECVINFO
#define LWIP_NETBUF_RECVINFO 0
#endif

#ifndef LWIP_TCP
#define LWIP_TCP 0
#endif

#ifndef TCP_QUEUE_OOSEQ
#define TCP_QUEUE_OOSEQ 0
#endif

#ifndef LWIP_TCP_SACK_OUT
#define LWIP_TCP_SACK_OUT 0
#endif

#ifndef TCP_CALCULATE_EFF_SEND_MSS
#define TCP_CALCULATE_EFF_SEND_MSS 0
#endif

#ifndef TCP_LISTEN_BACKLOG
#define TCP_LISTEN_BACKLOG 0
#endif

#ifndef LWIP_TCP_TIMESTAMPS
#define LWIP_TCP_TIMESTAMPS 0
#endif

#ifndef LWIP_EVENT_API
#define LWIP_EVENT_API 0
#endif

#ifndef LWIP_CALLBACK_API
#define LWIP_CALLBACK_API 0
#endif

#ifndef LWIP_WND_SCALE
#define LWIP_WND_SCALE 0
#endif

#ifndef LWIP_ALTCP
#define LWIP_ALTCP 0
#endif

#ifndef LWIP_ALTCP_TLS
#define LWIP_ALTCP_TLS 0
#endif

#ifndef LWIP_ALTCP_TLS_MBEDTLS
#define LWIP_ALTCP_TLS_MBEDTLS 0
#endif

#ifndef ALTCP_MBEDTLS_USE_SESSION_CACHE
#define ALTCP_MBEDTLS_USE_SESSION_CACHE 0
#endif

#ifndef ALTCP_MBEDTLS_USE_SESSION_TICKETS
#define ALTCP_MBEDTLS_USE_SESSION_TICKETS 0
#endif

#ifndef LWIP_NETCONN
#define LWIP_NETCONN 0
#endif

#ifndef LWIP_TCPIP_TIMEOUT
#define LWIP_TCPIP_TIMEOUT 0
#endif

#ifndef LWIP_NETCONN_SEM_PER_THREAD
#define LWIP_NETCONN_SEM_PER_THREAD 0
#endif

#ifndef LWIP_NETCONN_FULLDUPLEX
#define LWIP_NETCONN_FULLDUPLEX 0
#endif

#ifndef LWIP_SOCKET
#define LWIP_SOCKET 0
#endif

#ifndef LWIP_POSIX_SOCKETS_IO_NAMES
#define LWIP_POSIX_SOCKETS_IO_NAMES 0
#endif

#ifndef LWIP_SOCKET_EXTERNAL_HEADERS
#define LWIP_SOCKET_EXTERNAL_HEADERS 0
#endif

#ifndef LWIP_TCP_KEEPALIVE
#define LWIP_TCP_KEEPALIVE 0
#endif

#ifndef LWIP_SO_SNDTIMEO
#define LWIP_SO_SNDTIMEO 0
#endif

#ifndef LWIP_SO_RCVTIMEO
#define LWIP_SO_RCVTIMEO 0
#endif

#ifndef LWIP_TCP_USER_TIMEOUT
#define LWIP_TCP_USER_TIMEOUT 0
#endif

#ifndef LWIP_SO_SNDRCVTIMEO_NONSTANDARD
#define LWIP_SO_SNDRCVTIMEO_NONSTANDARD 0
#endif

#ifndef LWIP_SO_RCVBUF
#define LWIP_SO_RCVBUF 0
#endif

#ifndef LWIP_SIOCOUTQ
#define LWIP_SIOCOUTQ 0
#endif

#ifndef LWIP_SO_LINGER
#define LWIP_SO_LINGER 0
#endif

#ifndef SO_REUSE
#define SO_REUSE 0
#endif

#ifndef SO_REUSE_RXTOALL
#define SO_REUSE_RXTOALL 0
#endif

#ifndef LWIP_SOCKET_SELECT
#define LWIP_SOCKET_SELECT 0
#endif

#ifndef LWIP_SOCKET_POLL
#define LWIP_SOCKET_POLL 0
#endif

#ifndef LWIP_ARP
#define LWIP_ARP 0
#endif

#ifndef ARP_QUEUEING
#define ARP_QUEUEING 0
#endif

#ifndef ETHARP_SUPPORT_VLAN
#define ETHARP_SUPPORT_VLAN 0
#endif

#ifndef LWIP_VLAN_PCP
#define LWIP_VLAN_PCP 0
#endif

#ifndef LWIP_ETHERNET
#define LWIP_ETHERNET 0
#endif

#ifndef ETHARP_SUPPORT_STATIC_ENTRIES
#define ETHARP_SUPPORT_STATIC_ENTRIES 0
#endif

#ifndef ETHARP_TABLE_MATCH_NETIF
#define ETHARP_TABLE_MATCH_NETIF 0
#endif

#ifndef LWIP_ICMP
#define LWIP_ICMP 0
#endif

#ifndef LWIP_BROADCAST_PING
#define LWIP_BROADCAST_PING 0
#endif

#ifndef LWIP_MULTICAST_PING
#define LWIP_MULTICAST_PING 0
#endif

#ifndef LWIP_DHCP
#define LWIP_DHCP 0
#endif

#ifndef LWIP_DHCP_DOES_ACD_CHECK
#define LWIP_DHCP_DOES_ACD_CHECK 0
#endif

#ifndef LWIP_DHCP_BOOTP_FILE
#define LWIP_DHCP_BOOTP_FILE 0
#endif

#ifndef LWIP_DHCP_GET_NTP_SRV
#define LWIP_DHCP_GET_NTP_SRV 0
#endif

#ifndef LWIP_DHCP_DISCOVER_ADD_HOSTNAME
#define LWIP_DHCP_DISCOVER_ADD_HOSTNAME 0
#endif

#ifndef LWIP_AUTOIP
#define LWIP_AUTOIP 0
#endif

#ifndef LWIP_DHCP_AUTOIP_COOP
#define LWIP_DHCP_AUTOIP_COOP 0
#endif

#ifndef LWIP_ACD
#define LWIP_ACD 0
#endif

#ifndef LWIP_IGMP
#define LWIP_IGMP 0
#endif

#ifndef LWIP_IPV4
#define LWIP_IPV4 0
#endif

#ifndef IP_FORWARD
#define IP_FORWARD 0
#endif

#ifndef IP_REASSEMBLY
#define IP_REASSEMBLY 0
#endif

#ifndef IP_FRAG
#define IP_FRAG 0
#endif

#ifndef IP_OPTIONS_ALLOWED
#define IP_OPTIONS_ALLOWED 0
#endif

#ifndef IP_SOF_BROADCAST
#define IP_SOF_BROADCAST 0
#endif

#ifndef IP_SOF_BROADCAST_RECV
#define IP_SOF_BROADCAST_RECV 0
#endif

#ifndef IP_FORWARD_ALLOW_TX_ON_RX_NETIF
#define IP_FORWARD_ALLOW_TX_ON_RX_NETIF 0
#endif

#ifndef LWIP_SUPPORT_CUSTOM_PBUF
#define LWIP_SUPPORT_CUSTOM_PBUF 0
#endif

#ifndef LWIP_HAVE_LOOPIF
#define LWIP_HAVE_LOOPIF 0
#endif

#ifndef LWIP_LOOPIF_MULTICAST
#define LWIP_LOOPIF_MULTICAST 0
#endif

#ifndef LWIP_NETIF_LOOPBACK
#define LWIP_NETIF_LOOPBACK 0
#endif

#ifndef LWIP_NETIF_LOOPBACK_MULTITHREADING
#define LWIP_NETIF_LOOPBACK_MULTITHREADING 0
#endif

#ifndef LWIP_SINGLE_NETIF
#define LWIP_SINGLE_NETIF 0
#endif

#ifndef LWIP_NETIF_HOSTNAME
#define LWIP_NETIF_HOSTNAME 0
#endif

#ifndef LWIP_NETIF_API
#define LWIP_NETIF_API 0
#endif

#ifndef LWIP_NETIF_STATUS_CALLBACK
#define LWIP_NETIF_STATUS_CALLBACK 0
#endif

#ifndef LWIP_NETIF_EXT_STATUS_CALLBACK
#define LWIP_NETIF_EXT_STATUS_CALLBACK 0
#endif

#ifndef LWIP_NETIF_LINK_CALLBACK
#define LWIP_NETIF_LINK_CALLBACK 0
#endif

#ifndef LWIP_NETIF_REMOVE_CALLBACK
#define LWIP_NETIF_REMOVE_CALLBACK 0
#endif

#ifndef LWIP_NETIF_HWADDRHINT
#define LWIP_NETIF_HWADDRHINT 0
#endif

#ifndef LWIP_NETIF_TX_SINGLE_PBUF
#define LWIP_NETIF_TX_SINGLE_PBUF 0
#endif

#ifndef LWIP_ICMP6
#define LWIP_ICMP6 0
#endif

#ifndef LWIP_IPV6_MLD
#define LWIP_IPV6_MLD 0
#endif

#ifndef LWIP_ND6_QUEUEING
#define LWIP_ND6_QUEUEING 0
#endif

#ifndef LWIP_ND6_ALLOW_RA_UPDATES
#define LWIP_ND6_ALLOW_RA_UPDATES 0
#endif

#ifndef LWIP_ND6_TCP_REACHABILITY_HINTS
#define LWIP_ND6_TCP_REACHABILITY_HINTS 0
#endif

#ifndef LWIP_IPV6_DHCP6
#define LWIP_IPV6_DHCP6 0
#endif

#ifndef LWIP_IPV6_DHCP6_PD
#define LWIP_IPV6_DHCP6_PD 0
#endif

#ifndef LWIP_IPV6_DHCP6_STATEFUL
#define LWIP_IPV6_DHCP6_STATEFUL 0
#endif

#ifndef LWIP_IPV6_DHCP6_STATELESS
#define LWIP_IPV6_DHCP6_STATELESS 0
#endif

#ifndef LWIP_DHCP6_GET_NTP_SRV
#define LWIP_DHCP6_GET_NTP_SRV 0
#endif

#ifndef LWIP_IPV6
#define LWIP_IPV6 0
#endif

#ifndef LWIP_IPV6_SCOPES
#define LWIP_IPV6_SCOPES 0
#endif

#ifndef LWIP_IPV6_SCOPES_DEBUG
#define LWIP_IPV6_SCOPES_DEBUG 0
#endif

#ifndef LWIP_IPV6_FORWARD
#define LWIP_IPV6_FORWARD 0
#endif

#ifndef LWIP_IPV6_FRAG
#define LWIP_IPV6_FRAG 0
#endif

#ifndef LWIP_IPV6_REASS
#define LWIP_IPV6_REASS 0
#endif

#ifndef LWIP_IPV6_SEND_ROUTER_SOLICIT
#define LWIP_IPV6_SEND_ROUTER_SOLICIT 0
#endif

#ifndef LWIP_IPV6_SEND_ROUTER_ADVERTISE
#define LWIP_IPV6_SEND_ROUTER_ADVERTISE 0
#endif

#ifndef LWIP_IPV6_AUTOCONFIG
#define LWIP_IPV6_AUTOCONFIG 0
#endif

#ifndef LWIP_IPV6_ADDRESS_LIFETIMES
#define LWIP_IPV6_ADDRESS_LIFETIMES 0
#endif

#ifndef LWIP_HTTPD_CGI
#define LWIP_HTTPD_CGI 0
#endif

#ifndef LWIP_HTTPD_CGI_SSI
#define LWIP_HTTPD_CGI_SSI 0
#endif

#ifndef LWIP_HTTPD_SSI
#define LWIP_HTTPD_SSI 0
#endif

#ifndef LWIP_HTTPD_SSI_RAW
#define LWIP_HTTPD_SSI_RAW 0
#endif

#ifndef LWIP_HTTPD_SUPPORT_POST
#define LWIP_HTTPD_SUPPORT_POST 0
#endif

#ifndef LWIP_HTTPD_SSI_MULTIPART
#define LWIP_HTTPD_SSI_MULTIPART 0
#endif

#ifndef LWIP_HTTPD_POST_MANUAL_WND
#define LWIP_HTTPD_POST_MANUAL_WND 0
#endif

#ifndef LWIP_HTTPD_DYNAMIC_HEADERS
#define LWIP_HTTPD_DYNAMIC_HEADERS 0
#endif

#ifndef HTTPD_USE_MEM_POOL
#define HTTPD_USE_MEM_POOL 0
#endif

#ifndef HTTPD_ENABLE_HTTPS
#define HTTPD_ENABLE_HTTPS 0
#endif

#ifndef LWIP_HTTPD_TIMING
#define LWIP_HTTPD_TIMING 0
#endif

#ifndef LWIP_HTTPD_SUPPORT_EXTSTATUS
#define LWIP_HTTPD_SUPPORT_EXTSTATUS 0
#endif

#ifndef LWIP_HTTPD_SUPPORT_V09
#define LWIP_HTTPD_SUPPORT_V09 0
#endif

#ifndef LWIP_HTTPD_SUPPORT_11_KEEPALIVE
#define LWIP_HTTPD_SUPPORT_11_KEEPALIVE 0
#endif

#ifndef LWIP_HTTPD_SUPPORT_REQUESTLIST
#define LWIP_HTTPD_SUPPORT_REQUESTLIST 0
#endif

#ifndef LWIP_HTTPD_SSI_INCLUDE_TAG
#define LWIP_HTTPD_SSI_INCLUDE_TAG 0
#endif

#ifndef LWIP_HTTPD_ABORT_ON_CLOSE_MEM_ERROR
#define LWIP_HTTPD_ABORT_ON_CLOSE_MEM_ERROR 0
#endif

#ifndef LWIP_HTTPD_KILL_OLD_ON_CONNECTIONS_EXCEEDED
#define LWIP_HTTPD_KILL_OLD_ON_CONNECTIONS_EXCEEDED 0
#endif

#ifndef LWIP_HTTPD_OMIT_HEADER_FOR_EXTENSIONLESS_URI
#define LWIP_HTTPD_OMIT_HEADER_FOR_EXTENSIONLESS_URI 0
#endif

#ifndef HTTPD_LIMIT_SENDING_TO_2MSS
#define HTTPD_LIMIT_SENDING_TO_2MSS 0
#endif

#ifndef LWIP_HTTPD_CUSTOM_FILES
#define LWIP_HTTPD_CUSTOM_FILES 0
#endif

#ifndef LWIP_HTTPD_DYNAMIC_FILE_READ
#define LWIP_HTTPD_DYNAMIC_FILE_READ 0
#endif

#ifndef LWIP_HTTPD_FILE_STATE
#define LWIP_HTTPD_FILE_STATE 0
#endif

#ifndef LWIP_HTTPD_FILE_EXTENSION
#define LWIP_HTTPD_FILE_EXTENSION 0
#endif

#ifndef HTTPD_PRECALCULATED_CHECKSUM
#define HTTPD_PRECALCULATED_CHECKSUM 0
#endif

#ifndef LWIP_HTTPD_FS_ASYNC_READ
#define LWIP_HTTPD_FS_ASYNC_READ 0
#endif

#ifndef HTTPSRV_CFG_KEEPALIVE_ENABLED
#define HTTPSRV_CFG_KEEPALIVE_ENABLED 0
#endif

#ifndef HTTPSRV_CFG_WEBSOCKET_ENABLED
#define HTTPSRV_CFG_WEBSOCKET_ENABLED 0
#endif

#ifndef HTTPSRV_CFG_WOLFSSL_ENABLE
#define HTTPSRV_CFG_WOLFSSL_ENABLE 0
#endif

#ifndef HTTPSRV_CFG_MBEDTLS_ENABLE
#define HTTPSRV_CFG_MBEDTLS_ENABLE 0
#endif

#ifndef LWIP_MDNS_RESPONDER
#define LWIP_MDNS_RESPONDER 0
#endif

#ifndef MDNS_RESP_USENETIF_EXTCALLBACK
#define MDNS_RESP_USENETIF_EXTCALLBACK 0
#endif

#ifndef LWIP_MDNS_SEARCH
#define LWIP_MDNS_SEARCH 0
#endif

#ifndef SNTP_GET_SERVERS_FROM_DHCP
#define SNTP_GET_SERVERS_FROM_DHCP 0
#endif

#ifndef SNTP_SERVER_DNS
#define SNTP_SERVER_DNS 0
#endif

#ifndef SNTP_COMP_ROUNDTRIP
#define SNTP_COMP_ROUNDTRIP 0
#endif

#ifndef SNTP_RETRY_TIMEOUT_EXP
#define SNTP_RETRY_TIMEOUT_EXP 0
#endif

#ifndef SNTP_MONITOR_SERVER_REACHABILITY
#define SNTP_MONITOR_SERVER_REACHABILITY 0
#endif

#ifndef PING_USE_SOCKETS
#define PING_USE_SOCKETS 0
#endif

#ifndef LWIP_TESTMODE
#define LWIP_TESTMODE 0
#endif

#ifndef LWIP_DISABLE_PBUF_POOL_SIZE_SANITY_CHECKS
#define LWIP_DISABLE_PBUF_POOL_SIZE_SANITY_CHECKS 0
#endif

#ifndef LWIP_DHCP_FINE_TIMERS_ONDEMAND
#define LWIP_DHCP_FINE_TIMERS_ONDEMAND 0
#endif

#ifndef LWIP_DNS_TIMERS_ONDEMAND
#define LWIP_DNS_TIMERS_ONDEMAND 0
#endif

#ifndef LWIP_IGMP_TIMERS_ONDEMAND
#define LWIP_IGMP_TIMERS_ONDEMAND 0
#endif

#ifndef LWIP_IP4_REASSEMBLY_TIMERS_ONDEMAND
#define LWIP_IP4_REASSEMBLY_TIMERS_ONDEMAND 0
#endif

#ifndef LWIP_IP6_REASSEMBLY_TIMERS_ONDEMAND
#define LWIP_IP6_REASSEMBLY_TIMERS_ONDEMAND 0
#endif

#ifndef LWIP_MLD6_TIMERS_ONDEMAND
#define LWIP_MLD6_TIMERS_ONDEMAND 0
#endif

/*
 * Some behaviour is considered enabled if some macro is just defined.
 * If such macros are defined to 0 in Kconfig, undefine them so they are not
 * causing #ifdef XYZ to evaluate to true in preprocessor.
 */

#if defined(LWIP_DEBUG) && (LWIP_DEBUG == 0)
#undef LWIP_DEBUG
#endif

#if defined(LWIP_PROVIDE_ERRNO) && (LWIP_PROVIDE_ERRNO == 0)
#undef LWIP_PROVIDE_ERRNO
#endif

#if defined(LWIP_ENET_FLEXIBLE_CONFIGURATION) && (LWIP_ENET_FLEXIBLE_CONFIGURATION == 0)
#undef LWIP_ENET_FLEXIBLE_CONFIGURATION
#endif

#endif /* __LWIPOPTS_H__ */
