# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_component_serial_manager_usb_cdc_MIMXRT117H true)
set(CONFIG_USE_middleware_usb_device_ehci_MIMXRT117H true)
set(CONFIG_USE_CMSIS_Include_core_cm7_MIMXRT117H true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT117H true)
set(CONFIG_USE_driver_lpuart_MIMXRT117H true)
set(CONFIG_USE_middleware_baremetal_MIMXRT117H true)
