# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_usb_host_ehci_MIMXRT1024 true)
set(CONFIG_USE_middleware_lwip_usb_ethernetif_MIMXRT1024 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT1024 true)
set(CONFIG_USE_driver_lpuart_MIMXRT1024 true)
set(CONFIG_USE_driver_common_MIMXRT1024 true)
set(CONFIG_USE_middleware_baremetal_MIMXRT1024 true)
