# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/MIMXRT798S/all_lib_device.cmake

set(CONFIG_COMPILER riscvllvm)
set(CONFIG_TOOLCHAIN riscvllvm)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_RISCV_Include_Core true)
set(CONFIG_USE_device_CMSIS true)
set(CONFIG_USE_device_system true)
set(CONFIG_USE_device_startup true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_iopctl_soc true)
set(CONFIG_USE_driver_reset true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_driver_gpio true)
set(CONFIG_USE_driver_lpflexcomm true)
set(CONFIG_USE_driver_lpflexcomm_lpuart true)
set(CONFIG_USE_driver_sema42 true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_utility_str true)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_component_lpuart_adapter true)
set(CONFIG_CORE ezhv)
set(CONFIG_DEVICE MIMXRT798S)
set(CONFIG_BOARD mimxrt700evk)
set(CONFIG_KIT mimxrt700evk)
set(CONFIG_DEVICE_ID MIMXRT798S)
set(CONFIG_FPU NO_FPU)
set(CONFIG_DSP NO_DSP)
set(CONFIG_CORE_ID ezhv)
