# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_component_da7212_adapter_MK66F18 true)
set(CONFIG_USE_component_i2c_adapter_MK66F18 true)
set(CONFIG_USE_middleware_fatfs_sd_MK66F18 true)
set(CONFIG_USE_middleware_sdmmc_host_sdhc_MK66F18 true)
set(CONFIG_USE_middleware_sdmmc_host_sdhc_interrupt_MK66F18 true)
set(CONFIG_USE_driver_uart_MK66F18 true)
