/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _EDGEFAST_BLUETOOTH_AUDIO_CONFIG_GEN_H_
#define _EDGEFAST_BLUETOOTH_AUDIO_CONFIG_GEN_H_

#define CONFIG_BT_AUDIO 1
// #define CONFIG_BT_AUDIO_RX 0
#define CONFIG_BT_AUDIO_TX 1
#define CONFIG_BT_AUDIO_NOTIFY_RETRY_DELAY 20
// #define CONFIG_BT_CCID 0
// #define CONFIG_BT_BAP_UNICAST_CLIENT 0
#define CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE 19
#define CONFIG_BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE 4
#define CONFIG_BT_BAP_BASS_MAX_SUBGROUPS 1
#define CONFIG_BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE 19
#define CONFIG_BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE 4
#define CONFIG_BT_BAP_BROADCAST_SOURCE 1
#define CONFIG_BT_BAP_BROADCAST_SRC_SUBGROUP_COUNT 1
#define CONFIG_BT_BAP_BROADCAST_SRC_COUNT 1
#define CONFIG_BT_BAP_BROADCAST_SRC_STREAM_COUNT 2
// #define CONFIG_BT_BAP_SCAN_DELEGATOR 0
// #define CONFIG_BT_BAP_BROADCAST_ASSISTANT 0
#define CONFIG_BT_BAP_STREAM 1
// #define CONFIG_BT_PAC_SNK 0
// #define CONFIG_BT_PAC_SRC 0
// #define CONFIG_BT_ASCS 0
#define CONFIG_BT_VOCS_MAX_INSTANCE_COUNT 0
#define CONFIG_BT_VOCS_CLIENT_MAX_INSTANCE_COUNT 0
#define CONFIG_BT_AICS_MAX_INSTANCE_COUNT 0
#define CONFIG_BT_AICS_CLIENT_MAX_INSTANCE_COUNT 0
// #define CONFIG_BT_VCP_VOL_REND 0
// #define CONFIG_BT_VCP_VOL_CTLR 0
// #define CONFIG_BT_MICP_MIC_DEV 0
// #define CONFIG_BT_MICP_MIC_CTLR 0
// #define CONFIG_BT_CSIP_SET_MEMBER 0
// #define CONFIG_BT_CSIP_SET_COORDINATOR 0
// #define CONFIG_BT_TBS 0
// #define CONFIG_BT_TBS_CLIENT_GTBS 0
// #define CONFIG_BT_TBS_CLIENT_TBS 0
// #define CONFIG_BT_MCC 0
// #define CONFIG_BT_HAS_CLIENT 0
// #define CONFIG_BT_MPL 0
// #define CONFIG_MCTL 0
// #define CONFIG_BT_CAP_INITIATOR 0
// #define CONFIG_BT_PBP 0
// #define LE_AUDIO_SYNC_ENABLE 0
// #define CONFIG_BT_AUDIO_CAPABILITY 0
#define CONFIG_BT_AUDIO_BROADCAST_SRC_SUBGROUP_COUNT 0
// #define CONFIG_BT_AUDIO_BROADCAST_SOURCE 0
// #define CONFIG_BT_AUDIO_BROADCAST_SINK 0
#define CONFIG_BT_AUDIO_BROADCAST_SRC_STREAM_COUNT 0
// #define CONFIG_UTF8 0
#define LE_CONN_COUNT 0
#define CONFIG_BT_AUDIO_BROADCAST_SNK_STREAM_COUNT 0
#define CONFIG_BT_PACS_SNK_CONTEXT 0x0007
#define CONFIG_BT_PACS_SRC_CONTEXT 0x0007
// #define CONFIG_TMAP_PERIPHERAL_SINGLE 0
// #define CONFIG_BT_OTS 0
// #define CONFIG_BT_OTS_CLIENT 0

#endif /* _EDGEFAST_BLUETOOTH_AUDIO_CONFIG_GEN_H_ */
