/*
 * Copyright 2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA4 (number 26), J2[4]/PTA4
  @{ */
#define BOOT_PIN_SW3_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOOT_PIN_SW3_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOOT_PIN_SW3_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOOT_PIN_SW3_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBootPin(void);

/*! @name PORTB16 (number 39), J1[6]/U3[4]/UART0_RX_TGTMCU
  @{ */
#define UART0_POLLFORACTIVITY_RX_GPIO_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define UART0_POLLFORACTIVITY_RX_GPIO_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define UART0_POLLFORACTIVITY_RX_GPIO_PORT PORTB /*!<@brief PORT device name: PORTB */
#define UART0_POLLFORACTIVITY_RX_GPIO_PIN 16U    /*!<@brief PORTB pin index: 16 */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void UART0_PollForActivity(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART 0 Receive Data Source Select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 Transmit Data Source Select: UART0_TX pin */

/*! @name PORTB16 (number 39), J1[6]/U3[4]/UART0_RX_TGTMCU
  @{ */
#define UART0_RX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define UART0_RX_PIN 16U    /*!<@brief PORTB pin index: 16 */
                            /* @} */

/*! @name PORTB17 (number 40), U5[1]/UART0_TX_TGTMCU
  @{ */
#define UART0_TX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define UART0_TX_PIN 17U    /*!<@brief PORTB pin index: 17 */
                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void UART0_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void UART0_RestoreDefault(void);

/*! @name PORTB0 (number 35), J1[10]/J1[11]/PTB0
  @{ */
#define I2C0_SCL_PORT PORTB /*!<@brief PORT device name: PORTB */
#define I2C0_SCL_PIN 0U     /*!<@brief PORTB pin index: 0 */
                            /* @} */

/*! @name PORTB1 (number 36), J2[3]/PTB1-ADC0_SE9
  @{ */
#define I2C0_SDA_PORT PORTB /*!<@brief PORT device name: PORTB */
#define I2C0_SDA_PIN 1U     /*!<@brief PORTB pin index: 1 */
                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C0_InitPins(void);

/*! @name PORTB0 (number 35), J1[10]/J1[11]/PTB0
  @{ */
#define I2C0_RESTOREDEFAULT_SCL_PORT PORTB /*!<@brief PORT device name: PORTB */
#define I2C0_RESTOREDEFAULT_SCL_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                           /* @} */

/*! @name PORTB1 (number 36), J2[3]/PTB1-ADC0_SE9
  @{ */
#define I2C0_RESTOREDEFAULT_SDA_PORT PORTB /*!<@brief PORT device name: PORTB */
#define I2C0_RESTOREDEFAULT_SDA_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C0_RestoreDefault(void);

/*! @name PORTE16 (number 5), J4[4]/PTE16
  @{ */
#define SPI0_PCS_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_PCS_PIN 16U    /*!<@brief PORTE pin index: 16 */
                            /* @} */

/*! @name PORTE17 (number 6), J2[7]/PTE17-ADC0_SE5
  @{ */
#define SPI0_SCK_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_SCK_PIN 17U    /*!<@brief PORTE pin index: 17 */
                            /* @} */

/*! @name PORTE18 (number 7), J2[1]/PTE18-ADC0_SE6
  @{ */
#define SPI0_SOUT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_SOUT_PIN 18U    /*!<@brief PORTE pin index: 18 */
                             /* @} */

/*! @name PORTE19 (number 8), J2[5]/PTE19-ADC0_SE7
  @{ */
#define SPI0_SIN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_SIN_PIN 19U    /*!<@brief PORTE pin index: 19 */
                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SPI0_InitPins(void);

/*! @name PORTE16 (number 5), J4[4]/PTE16
  @{ */
#define SPI0_RESTOREDEFAULT_PCS_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_RESTOREDEFAULT_PCS_PIN 16U    /*!<@brief PORTE pin index: 16 */
                                           /* @} */

/*! @name PORTE17 (number 6), J2[7]/PTE17-ADC0_SE5
  @{ */
#define SPI0_RESTOREDEFAULT_SCK_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_RESTOREDEFAULT_SCK_PIN 17U    /*!<@brief PORTE pin index: 17 */
                                           /* @} */

/*! @name PORTE18 (number 7), J2[1]/PTE18-ADC0_SE6
  @{ */
#define SPI0_RESTOREDEFAULT_SOUT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_RESTOREDEFAULT_SOUT_PIN 18U    /*!<@brief PORTE pin index: 18 */
                                            /* @} */

/*! @name PORTE19 (number 8), J2[5]/PTE19-ADC0_SE7
  @{ */
#define SPI0_RESTOREDEFAULT_SIN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define SPI0_RESTOREDEFAULT_SIN_PIN 19U    /*!<@brief PORTE pin index: 19 */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SPI0_RestoreDefault(void);

/*! @name PORTE25 (number 21), J1[5]/J1[12]/LD1[3]/U9[4]/PTE25
  @{ */
#define CAN0_RX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define CAN0_RX_PIN 25U    /*!<@brief PORTE pin index: 25 */
                           /* @} */

/*! @name PORTE24 (number 20), J1[1]/J1[8]/U9[1]/PTE24
  @{ */
#define CAN0_TX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define CAN0_TX_PIN 24U    /*!<@brief PORTE pin index: 24 */
                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void CAN0_InitPins(void);

/*! @name PORTE25 (number 21), J1[5]/J1[12]/LD1[3]/U9[4]/PTE25
  @{ */
#define CAN0_RESTOREDEFAULT_RX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define CAN0_RESTOREDEFAULT_RX_PIN 25U    /*!<@brief PORTE pin index: 25 */
                                          /* @} */

/*! @name PORTE24 (number 20), J1[1]/J1[8]/U9[1]/PTE24
  @{ */
#define CAN0_RESTOREDEFAULT_TX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define CAN0_RESTOREDEFAULT_TX_PIN 24U    /*!<@brief PORTE pin index: 24 */
                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void CAN0_RestoreDefault(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
