/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define DMA_DESCRIPTOR_NUM 2U
#define DEMO_CADC_SAMPLE_COUNT 3U
#define CONFIG_FLASH_BASE_ADDRESS 0x08000000
#define CONFIG_LPADC_CONVERSION_COMPLETE_TIMEOUT 0
#define CONFIG_LPADC_CALIBRATION_READY_TIMEOUT 0
#define CONFIG_LPADC_GAIN_CAL_READY_TIMEOUT 0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
