# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_sdmmc_host_usdhc_MIMXRT1064 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT1064 true)
set(CONFIG_USE_driver_lpuart_MIMXRT1064 true)
set(CONFIG_USE_middleware_usb_device_ehci_MIMXRT1064 true)
set(CONFIG_USE_middleware_baremetal_MIMXRT1064 true)
