# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_driver_cache_armv7_m7_MIMXRT1176_cm7 true)
set(CONFIG_USE_middleware_mbedtls_rt2_MIMXRT1176_cm7 true)
set(CONFIG_USE_middleware_wifi_MIMXRT1176_cm7 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_MIMXRT1176_cm7 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT1176_cm7 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT1176_cm7 true)
set(CONFIG_USE_driver_lpuart_MIMXRT1176_cm7 true)
