/*
 * Copyright 2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_09 (number 3), LPUART1_RXD/J56[2] */
#define UART1_POLLFORACTIVITY_RX_GPIO_PERIPHERAL                           GPIO1   /*!< Device name: GPIO1 */
#define UART1_POLLFORACTIVITY_RX_GPIO_SIGNAL                          gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define UART1_POLLFORACTIVITY_RX_GPIO_CHANNEL                                 9U   /*!< GPIO1 gpiomux_io channel: 09 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void UART1_PollForActivity(void);

/* GPIO_09 (number 3), LPUART1_RXD/J56[2] */
#define UART1_RX_PERIPHERAL                                              LPUART1   /*!< Device name: LPUART1 */
#define UART1_RX_SIGNAL                                                      RXD   /*!< LPUART1 signal: RXD */

/* GPIO_10 (number 2), LPUART1_TXD/J56[4] */
#define UART1_TX_PERIPHERAL                                              LPUART1   /*!< Device name: LPUART1 */
#define UART1_TX_SIGNAL                                                      TXD   /*!< LPUART1 signal: TXD */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void UART1_InitPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void UART1_RestoreDefault(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
