/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define APP_FB_NUM 3
#define DEMO_PANEL 2
// #define CONFIG_DEMO_PANEL_RK055AHD091 0
// #define CONFIG_DEMO_PANEL_RK055IQH091 0
#define CONFIG_DEMO_PANEL_RK055MHD091A0 1
#define DEMO_DISPLAY_CONTROLLER 1
// #define CONFIG_DEMO_PANEL_elcdif 0
#define CONFIG_DEMO_PANEL_lcdifv2 1
// #define DEMO_USE_XRGB8888 0
// #define DEMO_USE_LUT8 0
#define CONFIG_FLASH_BASE_ADDRESS 0x30000400
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
