/*
 * Copyright 2018 NXP
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_device_registers.h"
#include "fsl_iomuxc.h"

////////////////////////////////////////////////////////////////////////////////
// Definitions
////////////////////////////////////////////////////////////////////////////////

/*====================== SOC Definitions ===========================*/
#if FSL_FEATURE_SOC_RGPIO_COUNT
//! Convert RGPIO to common GPIO code.
#define GPIO_Type RGPIO_Type
#define GPIO_PinInit RGPIO_PinInit
#define GPIO_WritePinOutput RGPIO_WritePinOutput
#define GPIO_GetPinsInterruptFlags(base) RGPIO_GetPinsInterruptFlags(base, UART1_RX_GPIO_IRQOutput)
#define GPIO_ClearPinsInterruptFlags(base, mask) RGPIO_ClearPinsInterruptFlags(base, UART1_RX_GPIO_IRQOutput, mask)
#define GPIO_SetPinInterruptConfig(base, pin, mode) \
    RGPIO_SetPinInterruptConfig(base, pin, UART1_RX_GPIO_IRQOutput, mode)
#define gpio_pin_config_t rgpio_pin_config_t
#define kGPIO_DigitalInput kRGPIO_DigitalInput
#define kGPIO_DigitalOutput kRGPIO_DigitalOutput
#define kGPIO_IntFallingEdge kRGPIO_InterruptFallingEdge
#define kGPIO_NoIntmode kRGPIO_InterruptOrDMADisabled
#endif

static inline void IOMUXC_RestoreDefault(uint32_t muxRegister,
                                         uint32_t muxMode,
                                         uint32_t inputRegister,
                                         uint32_t inputDaisy,
                                         uint32_t configRegister,
                                         uint32_t muxDefaultMode,
                                         uint32_t configDefaultValue)
{
    *((volatile uint32_t *)muxRegister) = muxDefaultMode;
    if (inputRegister)
    {
        *((volatile uint32_t *)inputRegister) = 0 /*Daisy defualt value*/;
    }
    if (configRegister)
    {
        *((volatile uint32_t *)configRegister) = configDefaultValue;
    }
}

/*====================== LPUART IOMUXC Definitions ===========================*/
//! peripheral enable configurations
#define BL_ENABLE_PINMUX_UART1 (BL_CONFIG_LPUART_1)

//! UART configurations
#define UART1_RX_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_09_LPUART1_RX
#define UART1_RX_IOMUXC_DEFAULT 0x5U, 0x6U
#define UART1_TX_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_08_LPUART1_TX
#define UART1_TX_IOMUXC_DEFAULT 0x5U, 0x6U
#define UART1_PAD_CTRL \
    (IOMUXC_AON_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_AON_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_AON_SW_PAD_CTL_PAD_PUS(1))

//! Autobaud configurations.
#define UART1_RX_IOMUXC_MUX_GPIO IOMUXC_GPIO_AON_09_GPIO1_IO09
#define UART1_RX_GPIO_BASE RGPIO1
#define UART1_RX_GPIO_PIN_NUM (9)
#define UART1_RX_GPIO_IRQn GPIO1_0_IRQn
#define UART1_RX_GPIO_IRQHandler GPIO1_0_IRQHandler
#define UART1_RX_GPIO_IRQOutput kRGPIO_InterruptOutput0

/*====================== LPSPI Slave IOMUXC Definitions (for Serial Boot) ===========================*/
//! peripheral enable configurations
#define BL_ENABLE_PINMUX_LPSPI1 (BL_CONFIG_LPSPI_1)

#define SPI1_SDO_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_06_LPSPI1_SDO
#define SPI1_SDO_IOMUXC_DEFAULT 0x5U, 0x6U
#define SPI1_PCS_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_05_LPSPI1_PCS0
#define SPI1_PCS_IOMUXC_DEFAULT 0x5U, 0x6U
#define SPI1_SCK_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_04_LPSPI1_SCK
#define SPI1_SCK_IOMUXC_DEFAULT 0x5U, 0x6U
#define SPI1_SDI_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_07_LPSPI1_SDI
#define SPI1_SDI_IOMUXC_DEFAULT 0x5U, 0x6U
#define SPI1_PAD_CTRL (IOMUXC_AON_SW_PAD_CTL_PAD_DSE(1))

/*====================== LPSPI Master IOMUXC Definitions (for SPI NOR FLASH) ===========================*/
#define RECOVERY_SPI1_PCS0_IOMUXC_MUX_GPIO IOMUXC_GPIO_AON_05_GPIO1_IO05
#define RECOVERY_SPI1_PCS0_GPIO_BASE RGPIO1
#define RECOVERY_SPI1_PCS0_GPIO_PIN_NUM (5)
#define RECOVERY_SPI1_PCS2_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_09_LPSPI1_PCS2
#define RECOVERY_SPI1_PCS3_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_03_LPSPI1_PCS3
#define RECOVERY_SPI1_SCK_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_04_LPSPI1_SCK
#define RECOVERY_SPI1_SDO_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_06_LPSPI1_SDO
#define RECOVERY_SPI1_SDI_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_07_LPSPI1_SDI

#define RECOVERY_SPI2_PCS0_IOMUXC_MUX_GPIO IOMUXC_GPIO_AON_25_GPIO1_IO25
#define RECOVERY_SPI2_PCS0_GPIO_BASE RGPIO1
#define RECOVERY_SPI2_PCS0_GPIO_PIN_NUM (25)
#define RECOVERY_SPI2_PCS2_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_26_LPSPI2_PCS2
#define RECOVERY_SPI2_PCS3_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_27_LPSPI2_PCS3
#define RECOVERY_SPI2_SCK_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_22_LPSPI2_SCK
#define RECOVERY_SPI2_SDO_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_23_LPSPI2_SDO
#define RECOVERY_SPI2_SDI_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_24_LPSPI2_SDI

#define RECOVERY_SPI4_PCS0_IOMUXC_MUX_GPIO IOMUXC_GPIO_SD_B2_09_GPIO5_IO19
#define RECOVERY_SPI4_PCS0_GPIO_BASE RGPIO5
#define RECOVERY_SPI4_PCS0_GPIO_PIN_NUM (19)
#define RECOVERY_SPI4_PCS2_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_06_LPSPI4_PCS2
#define RECOVERY_SPI4_PCS3_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_05_LPSPI4_PCS3
#define RECOVERY_SPI4_SCK_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_08_LPSPI4_SCK
#define RECOVERY_SPI4_SDO_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_10_LPSPI4_SDO
#define RECOVERY_SPI4_SDI_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_11_LPSPI4_SDI

#define RECOVERY_SPI5_PCS0_IOMUXC_MUX_GPIO IOMUXC_GPIO_AD_29_GPIO4_IO29
#define RECOVERY_SPI5_PCS0_GPIO_BASE RGPIO4
#define RECOVERY_SPI5_PCS0_GPIO_PIN_NUM (29)
#define RECOVERY_SPI5_PCS2_IOMUXC_MUX_FUNC IOMUXC_GPIO_AD_26_LPSPI5_PCS2
#define RECOVERY_SPI5_PCS3_IOMUXC_MUX_FUNC IOMUXC_GPIO_AD_25_LPSPI5_PCS3
#define RECOVERY_SPI5_SCK_IOMUXC_MUX_FUNC IOMUXC_GPIO_AD_28_LPSPI5_SCK
#define RECOVERY_SPI5_SDO_IOMUXC_MUX_FUNC IOMUXC_GPIO_AD_30_LPSPI5_SDO
#define RECOVERY_SPI5_SDI_IOMUXC_MUX_FUNC IOMUXC_GPIO_AD_31_LPSPI5_SDI

#define RECOVERY_SPI_PCS_PAD_CTRL \
    (IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(1))
#define RECOVERY_SPI_PAD_CTRL \
    (IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(1))

/*====================== FLEXSPI IOMUXC Definitions ===========================*/
/* FLEXSPI1 PORTA Primary Group */
#define FLEXSPI1A_PRIMARY_SS0_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_09_FLEXSPI1_BUS2BIT_A_SS0_B
#define FLEXSPI1A_PRIMARY_SS1_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_01_FLEXSPI1_BUS2BIT_A_SS1_B
#define FLEXSPI1A_PRIMARY_SCLK_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_08_FLEXSPI1_BUS2BIT_A_SCLK
#define FLEXSPI1A_PRIMARY_SCLKB_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_02_FLEXSPI1_BUS2BIT_B_SCLK
#define FLEXSPI1A_PRIMARY_DQS_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_07_FLEXSPI1_BUS2BIT_A_DQS
#define FLEXSPI1A_PRIMARY_DQS_DUMMY_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_12_DUMMY_FLEXSPI1_BUS2BIT_A_DQS
#define FLEXSPI1A_PRIMARY_DATA0_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_10_FLEXSPI1_BUS2BIT_A_DATA00
#define FLEXSPI1A_PRIMARY_DATA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_11_FLEXSPI1_BUS2BIT_A_DATA01
#define FLEXSPI1A_PRIMARY_DATA2_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_12_FLEXSPI1_BUS2BIT_A_DATA02
#define FLEXSPI1A_PRIMARY_DATA3_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_13_FLEXSPI1_BUS2BIT_A_DATA03
#define FLEXSPI1A_PRIMARY_DATA4_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_03_FLEXSPI1_BUS2BIT_A_DATA04
#define FLEXSPI1A_PRIMARY_DATA5_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_04_FLEXSPI1_BUS2BIT_A_DATA05
#define FLEXSPI1A_PRIMARY_DATA6_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_05_FLEXSPI1_BUS2BIT_A_DATA06
#define FLEXSPI1A_PRIMARY_DATA7_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_06_FLEXSPI1_BUS2BIT_A_DATA07

#define FLEXSPI1A_PRIMARY_SS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)        // No-Pull
#define FLEXSPI1A_PRIMARY_SCLK_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)      // No-Pull
#define FLEXSPI1A_PRIMARY_DQS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2)       // Pull down
#define FLEXSPI1A_PRIMARY_DQS_DUMMY_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2) // Pull down
#define FLEXSPI1A_PRIMARY_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)      // No-Pull

/* FLEXSPI1 PORTA Secondary Group */
// No Available

/* FLEXSPI1 PORTB Primary Group */
#define FLEXSPI1B_PRIMARY_SS0_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_06_FLEXSPI1_BUS2BIT_B_SS0_B
#define FLEXSPI1B_PRIMARY_SS1_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_04_FLEXSPI1_BUS2BIT_B_SS1_B
#define FLEXSPI1B_PRIMARY_SCLK_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_07_FLEXSPI1_BUS2BIT_B_SCLK
//#define FLEXSPI1B_PRIMARY_SCLKB_IOMUXC_MUX_FUNC 0 //No Available.
#define FLEXSPI1B_PRIMARY_DQS_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_05_FLEXSPI1_BUS2BIT_B_DQS
#define FLEXSPI1B_PRIMARY_DQS_DUMMY_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_12_DUMMY_FLEXSPI1_BUS2BIT_B_DQS
#define FLEXSPI1B_PRIMARY_DATA0_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_08_FLEXSPI1_BUS2BIT_B_DATA00
#define FLEXSPI1B_PRIMARY_DATA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_09_FLEXSPI1_BUS2BIT_B_DATA01
#define FLEXSPI1B_PRIMARY_DATA2_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_10_FLEXSPI1_BUS2BIT_B_DATA02
#define FLEXSPI1B_PRIMARY_DATA3_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_11_FLEXSPI1_BUS2BIT_B_DATA03
#define FLEXSPI1B_PRIMARY_DATA4_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_00_FLEXSPI1_BUS2BIT_B_DATA04
#define FLEXSPI1B_PRIMARY_DATA5_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_01_FLEXSPI1_BUS2BIT_B_DATA05
#define FLEXSPI1B_PRIMARY_DATA6_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_02_FLEXSPI1_BUS2BIT_B_DATA06
#define FLEXSPI1B_PRIMARY_DATA7_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_03_FLEXSPI1_BUS2BIT_B_DATA07

#define FLEXSPI1B_PRIMARY_SS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)        // No-Pull
#define FLEXSPI1B_PRIMARY_SCLK_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)      // No-Pull
#define FLEXSPI1B_PRIMARY_DQS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2)       // Pull down
#define FLEXSPI1B_PRIMARY_DQS_DUMMY_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2) // Pull down
#define FLEXSPI1B_PRIMARY_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)      // No-Pull

/* FLEXSPI1 PORTB Secondary Group */
#define FLEXSPI1B_SECONDARY_SS0_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_04_FLEXSPI1_BUS2BIT_B_SS0_B
#define FLEXSPI1B_SECONDARY_SS1_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_02_FLEXSPI1_BUS2BIT_B_SS1_B
#define FLEXSPI1B_SECONDARY_SCLK_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_05_FLEXSPI1_BUS2BIT_B_SCLK
//#define FLEXSPI1B_SECONDARY_SCLKB_IOMUXC_MUX_FUNC 0 //No Available.
#define FLEXSPI1B_SECONDARY_DQS_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_03_FLEXSPI1_BUS2BIT_B_DQS
#define FLEXSPI1B_SECONDARY_DQS_DUMMY_IOMUXC_MUX_FUNC IOMUXC_GPIO_SD_B2_12_DUMMY_FLEXSPI1_BUS2BIT_B_DQS
#define FLEXSPI1B_SECONDARY_DATA0_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_13_FLEXSPI1_BUS2BIT_B_DATA00
#define FLEXSPI1B_SECONDARY_DATA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_12_FLEXSPI1_BUS2BIT_B_DATA01
#define FLEXSPI1B_SECONDARY_DATA2_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_11_FLEXSPI1_BUS2BIT_B_DATA02
#define FLEXSPI1B_SECONDARY_DATA3_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_10_FLEXSPI1_BUS2BIT_B_DATA03
#define FLEXSPI1B_SECONDARY_DATA4_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_09_FLEXSPI1_BUS2BIT_B_DATA04
#define FLEXSPI1B_SECONDARY_DATA5_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_08_FLEXSPI1_BUS2BIT_B_DATA05
#define FLEXSPI1B_SECONDARY_DATA6_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_07_FLEXSPI1_BUS2BIT_B_DATA06
#define FLEXSPI1B_SECONDARY_DATA7_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_06_FLEXSPI1_BUS2BIT_B_DATA07

#define FLEXSPI1B_SECONDARY_SS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)        // No-Pull
#define FLEXSPI1B_SECONDARY_SCLK_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)      // No-Pull
#define FLEXSPI1B_SECONDARY_DQS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2)       // Pull down
#define FLEXSPI1B_SECONDARY_DQS_DUMMY_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2) // Pull down
#define FLEXSPI1B_SECONDARY_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)      // No-Pull

/* FLEXSPI2 PORTA Primary Group */
#define FLEXSPI2A_PRIMARY_SS0_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_22_FLEXSPI2_BUS2BIT_A_SS0_B
#define FLEXSPI2A_PRIMARY_SS1_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_20_FLEXSPI2_BUS2BIT_A_SS1_B
#define FLEXSPI2A_PRIMARY_SCLK_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_23_FLEXSPI2_BUS2BIT_A_SCLK
// #define FLEXSPI2A_PRIMARY_SCLKB_IOMUXC_MUX_FUNC 0 //No Available.
#define FLEXSPI2A_PRIMARY_DQS_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_21_FLEXSPI2_BUS2BIT_A_DQS
#define FLEXSPI2A_PRIMARY_DQS_DUMMY_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_28_DUMMY_FLEXSPI2_BUS2BIT_A_DQS
#define FLEXSPI2A_PRIMARY_DATA0_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_24_FLEXSPI2_BUS2BIT_A_DATA00
#define FLEXSPI2A_PRIMARY_DATA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_25_FLEXSPI2_BUS2BIT_A_DATA01
#define FLEXSPI2A_PRIMARY_DATA2_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_26_FLEXSPI2_BUS2BIT_A_DATA02
#define FLEXSPI2A_PRIMARY_DATA3_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_27_FLEXSPI2_BUS2BIT_A_DATA03

#define FLEXSPI2A_PRIMARY_SS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(0)   // No-Pull
#define FLEXSPI2A_PRIMARY_SCLK_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(0) // No-Pull
#define FLEXSPI2A_PRIMARY_DQS_PAD_CTRL \
    IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(0) // Pull down
#define FLEXSPI2A_PRIMARY_DQS_DUMMY_PAD_CTRL \
    IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(0)      // Pull down
#define FLEXSPI2A_PRIMARY_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(0) // No-Pull

/* FLEXSPI2 PORTA Secondary Group */
#define FLEXSPI2A_SECONDARY_SS0_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_39_FLEXSPI2_BUS2BIT_A_SS0_B
#define FLEXSPI2A_SECONDARY_SS1_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_26_FLEXSPI2_BUS2BIT_A_SS1_B
#define FLEXSPI2A_SECONDARY_SCLK_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_41_FLEXSPI2_BUS2BIT_A_SCLK
//#define FLEXSPI2A_SECONDARY_SCLKB_IOMUXC_MUX_FUNC 0 //No Available.
#define FLEXSPI2A_SECONDARY_DQS_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_40_FLEXSPI2_BUS2BIT_A_DQS
#define FLEXSPI2A_SECONDARY_DQS_DUMMY_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_28_DUMMY_FLEXSPI2_BUS2BIT_A_DQS
#define FLEXSPI2A_SECONDARY_DATA0_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_35_FLEXSPI2_BUS2BIT_A_DATA00
#define FLEXSPI2A_SECONDARY_DATA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_36_FLEXSPI2_BUS2BIT_A_DATA01
#define FLEXSPI2A_SECONDARY_DATA2_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_37_FLEXSPI2_BUS2BIT_A_DATA02
#define FLEXSPI2A_SECONDARY_DATA3_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_38_FLEXSPI2_BUS2BIT_A_DATA03

#define FLEXSPI2A_SECONDARY_SS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)   // No-Pull
#define FLEXSPI2A_SECONDARY_SCLK_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3) // No-Pull
#define FLEXSPI2A_SECONDARY_DQS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2)  // Pull down
#define FLEXSPI2A_SECONDARY_DQS_DUMMY_PAD_CTRL \
    IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(0) // Pull down
#define FLEXSPI2A_SECONDARY_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)                        // No-Pull

/* FLEXSPI2 PORTB Primary Group */
#define FLEXSPI2B_PRIMARY_SS0_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_21_FLEXSPI2_BUS2BIT_B_SS0_B
//#define FLEXSPI2B_PRIMARY_SS1_IOMUXC_MUX_FUNC 0 //No Available.
#define FLEXSPI2B_PRIMARY_SCLK_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_19_FLEXSPI2_BUS2BIT_B_SCLK
//#define FLEXSPI2B_PRIMARY_SCLKB_IOMUXC_MUX_FUNC 0 //No Available.
#define FLEXSPI2B_PRIMARY_DQS_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_20_FLEXSPI2_BUS2BIT_B_DQS
#define FLEXSPI2B_PRIMARY_DQS_DUMMY_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_28_DUMMY_FLEXSPI2_BUS2BIT_B_DQS
#define FLEXSPI2B_PRIMARY_DATA0_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_18_FLEXSPI2_BUS2BIT_B_DATA00
#define FLEXSPI2B_PRIMARY_DATA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_17_FLEXSPI2_BUS2BIT_B_DATA01
#define FLEXSPI2B_PRIMARY_DATA2_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_16_FLEXSPI2_BUS2BIT_B_DATA02
#define FLEXSPI2B_PRIMARY_DATA3_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_15_FLEXSPI2_BUS2BIT_B_DATA03

#define FLEXSPI2B_PRIMARY_SS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(0)   // No-Pull
#define FLEXSPI2B_PRIMARY_SCLK_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(0) // No-Pull
#define FLEXSPI2B_PRIMARY_DQS_PAD_CTRL \
    IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(0) // Pull down
#define FLEXSPI2B_PRIMARY_DQS_DUMMY_PAD_CTRL \
    IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(0)      // Pull down
#define FLEXSPI2B_PRIMARY_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(0) // No-Pull

/* FLEXSPI2 PORTB Secondary Group */
#define FLEXSPI2B_SECONDARY_SS0_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_28_FLEXSPI2_BUS2BIT_B_SS0_B
#define FLEXSPI2B_SECONDARY_SS1_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_27_FLEXSPI2_BUS2BIT_B_SS1_B
#define FLEXSPI2B_SECONDARY_SCLK_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_34_FLEXSPI2_BUS2BIT_B_SCLK
//#define FLEXSPI2B_SECONDARY_SCLKB_IOMUXC_MUX_FUNC 0 //No Available.
#define FLEXSPI2B_SECONDARY_DQS_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_29_FLEXSPI2_BUS2BIT_B_DQS
#define FLEXSPI2B_SECONDARY_DQS_DUMMY_IOMUXC_MUX_FUNC IOMUXC_GPIO_AON_28_DUMMY_FLEXSPI2_BUS2BIT_B_DQS
#define FLEXSPI2B_SECONDARY_DATA0_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_33_FLEXSPI2_BUS2BIT_B_DATA00
#define FLEXSPI2B_SECONDARY_DATA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_32_FLEXSPI2_BUS2BIT_B_DATA01
#define FLEXSPI2B_SECONDARY_DATA2_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_31_FLEXSPI2_BUS2BIT_B_DATA02
#define FLEXSPI2B_SECONDARY_DATA3_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_30_FLEXSPI2_BUS2BIT_B_DATA03

#define FLEXSPI2B_SECONDARY_SS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)   // No-Pull
#define FLEXSPI2B_SECONDARY_SCLK_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3) // No-Pull
#define FLEXSPI2B_SECONDARY_DQS_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(2)  // Pull down
#define FLEXSPI2B_SECONDARY_DQS_DUMMY_PAD_CTRL \
    IOMUXC_SW_PAD_CTL_PAD_DSE(0) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(0) // Pull down
#define FLEXSPI2B_SECONDARY_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)                        // No-Pull

// Fast Slew Rate
#define FLEXSPI_SW_PAD_CTL_VAL (IOMUXC_SW_PAD_CTL_PAD_SRE(1))

// Pull-down
#define FLEXSPI_DQS_SW_PAD_CTL_VAL (IOMUXC_SW_PAD_CTL_PAD_PULL(2))

// Fast Slew Rate
// Drive
// Pulldown
#define FLEXSPI_DQS_SW_PAD_AD_CTL_VAL \
    (IOMUXC_SW_PAD_CTL_PAD_SRE(1) | IOMUXC_SW_PAD_CTL_PAD_PUE(1) | IOMUXC_SW_PAD_CTL_PAD_PUS(0))

/*====================== FLEXSPI Reset IOMUXC Definitions ===========================*/
#define SW_MUX_CTL_PAD_FLEXSPI_RESET_IDX kIOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B1_00
#define SW_PAD_CTL_PAD_FLEXSPI_RESET_IDX kIOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B1_00
#define FLEXSPI_RESET_PIN_MUX IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(5)
#define FLEXSPI_RESET_PIN_SW_PAD_CTRL_VAL                                                           \
    (IOMUXC_SW_PAD_CTL_PAD_PDRV(1) | IOMUXC_SW_PAD_CTL_PAD_PULL(0) | IOMUXC_SW_PAD_CTL_PAD_ODE(0) | \
     IOMUXC_SW_PAD_CTL_PAD_APC(0))
#define FLEXSPI_RESET_PIN_GPIO GPIO4
#define FLEXSPI_RESET_PIN_INDEX 3

#define SW_MUX_CTL_PAD_FLEXSPI_SEC_RESET_IDX kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_B1_40
#define SW_PAD_CTL_PAD_FLEXSPI_SEC_RESET_IDX kIOMUXC_SW_PAD_CTL_PAD_GPIO_EMC_B1_40
#define FLEXSPI_RESET_SEC_PIN_MUX IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(5)
#define FLEXSPI_RESET_SEC_PIN_SW_PAD_CTRL_VAL                                                     \
    (IOMUXC_SW_PAD_CTL_PAD_DSE(4) | IOMUXC_SW_PAD_CTL_PAD_PKE(1) | IOMUXC_SW_PAD_CTL_PAD_PUE(0) | \
     IOMUXC_SW_PAD_CTL_PAD_PUS(0))
#define FLEXSPI_RESET_SEC_PIN_GPIO GPIO2
#define FLEXSPI_RESET_SEC_PIN_INDEX 8

/*====================== SEMC IOMUXC Definitions ===========================*/
#define SEMC_DATA00_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_00_SEMC_DATA00
#define SEMC_DATA01_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_01_SEMC_DATA01
#define SEMC_DATA02_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_02_SEMC_DATA02
#define SEMC_DATA03_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_03_SEMC_DATA03
#define SEMC_DATA04_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_04_SEMC_DATA04
#define SEMC_DATA05_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_05_SEMC_DATA05
#define SEMC_DATA06_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_06_SEMC_DATA06
#define SEMC_DATA07_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_07_SEMC_DATA07
#define SEMC_DATA08_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_30_SEMC_DATA08
#define SEMC_DATA09_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_31_SEMC_DATA09
#define SEMC_DATA10_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_32_SEMC_DATA10
#define SEMC_DATA11_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_33_SEMC_DATA11
#define SEMC_DATA12_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_34_SEMC_DATA12
#define SEMC_DATA13_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_35_SEMC_DATA13
#define SEMC_DATA14_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_36_SEMC_DATA14
#define SEMC_DATA15_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_37_SEMC_DATA15

#define SEMC_ADDR09_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_18_SEMC_ADDR09 // CLE for NAND.
#define SEMC_ADDR11_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_19_SEMC_ADDR11 // WE# for NAND/NOR.
#define SEMC_ADDR12_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_20_SEMC_ADDR12 // RE# for NAND, OE# for NOR.

#define SEMC_BA1_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_22_SEMC_BA1      // ALE for NAND ADV# for NOR.
#define SEMC_RDY_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_40_SEMC_RDY      // R/B# for NAND
#define SEMC_CSX0_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_41_SEMC_CSX00   // CE# for NAND/NOR
#define SEMC_CSX1_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_00_SEMC_CSX01       // CE# for NAND/NOR
#define SEMC_CSX2_IOMUXC_MUX_FUNC IOMUXC_GPIO_B1_01_SEMC_CSX02       // CE# for NAND/NOR
#define SEMC_CSX3_IOMUXC_MUX_FUNC IOMUXC_GPIO_B2_00_SEMC_CSX03       // CE# for NAND/NOR
#define SEMC_CSXA8_IOMUXC_MUX_FUNC IOMUXC_GPIO_EMC_B1_17_SEMC_ADDR08 // CE# for NAND/NOR

#define SEMC_DATA_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3) // No-pull
#define SEMC_CLE_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)  // No-pull
#define SEMC_WE_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)   // No-pull
#define SEMC_RE_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)   // No-pull
#define SEMC_ALE_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)  // No-pull
#define SEMC_RB_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(1)   // Pull-up
#define SEMC_CSX_PAD_CTRL IOMUXC_SW_PAD_CTL_PAD_PULL(3)  // No-pull
////////////////////////////////////////////////////////////////////////////////
// EOF
////////////////////////////////////////////////////////////////////////////////
