language: ruby

os:
  - linux

rvm:
  - "2.3"
  - "2.4"
  - "2.6"

before_install:
  - sudo apt-get install --assume-yes --quiet gcc-multilib

install:
  - bundle install
  - gem install rspec
  - gem install rubocop -v 0.57.2

script:
  - cd test && rake ci
  - cd ..
  - cd examples && cd make_example
  - make clean
  - make setup
  - make test
  - cd ..
  - cd temp_sensor
  - rake ci
