/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define INPUT_BUF_WIDTH 128
#define INPUT_BUF_HEIGHT 64
#define OUTPUT_BUF_WIDTH 64
#define OUTPUT_BUF_HEIGHT 32
#define COPY_WIDTH 16
#define COPY_HEIGHT 8
#define SRC_OFFSET_X 0
#define SRC_OFFSET_Y 0
#define DEST_OFFSET_X 10
#define DEST_OFFSET_Y 20
#define CONFIG_FLASH_BASE_ADDRESS 0x60000000
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
