# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_component_flexcomm_i2c_adapter_MIMXRT685S_cm33 true)
set(CONFIG_USE_component_cs42448_adapter_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_fatfs_sd_MIMXRT685S_cm33 true)
set(CONFIG_USE_driver_flexcomm_usart_MIMXRT685S_cm33 true)
