BEGIN:BMSG
VERSION:1.0
STATUS:UNREAD
TYPE:EMAIL
FOLDER:telecom/msg/outbox
BEGIN:VCARD
VERSION:2.1
N:
FN:iHeartRadio
EMAIL:iheartradio@email.iheart.com
END:VCARD
BEGIN:BENV
BEGIN:VCARD
VERSION:2.1
N:
FN:hkvtest3@gmail.com
EMAIL:hkvtest3@gmail.com
END:VCARD
BEGIN:BBODY
CHARSET:UTF-8
LENGTH:23871
BEGIN:MSG
From: iHeartRadio<iheartradio@email.iheart.com>
To: hkvtest3@gmail.com<hkvtest3@gmail.com>
MIME-Version: 1.0
Content-Type: text/html
Content-Transfer-Encoding: 8bit
Date: Tue, 25 Mar 2014 03:30:25 +0800
Subject: Malaysian Flight 370 reportedly went down in the Indian Ocean. Hear the latest!

<html><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>October 2013 New Layout</title>
	<style type="text/css">
			
	.ExternalClass {width:100%;} 
	.ExternalClass,
	.ExternalClass p,
	.ExternalClass span,
	.ExternalClass font,
	.ExternalClass td,
	.ExternalClass div { line-height: 100%; } 
	
	body {-webkit-text-size-adjust:none; -ms-text-size-adjust:none;} 
	body {margin:0; padding:0;} 
	table td {border-collapse:collapse;}	
	
	p {margin:0; padding:0; margin-bottom:0;}		
	
	h1, h2, h3, h4, h5, h6 {
	   color: black; 
	   line-height: 100%; 
	   }  
	
	a, a:link {
	   color:#2A5DB0;
	   text-decoration: underline;
	   }  	   
	
	body, #body_style {
	   background:#ececec;
	   min-height:1000px;
	   color:#000;
	   font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
	   font-size:12px;
	   } 
	   
	span.yshortcuts { color:#000; background-color:none; border:none;}
	span.yshortcuts:hover,
	span.yshortcuts:active,
	span.yshortcuts:focus {color:#000; background-color:none; border:none;}
	
	a:visited { color: #3c96e2; text-decoration: none} 
	a:focus   { color: #3c96e2; text-decoration: underline}  
	a:hover   { color: #3c96e2; text-decoration: underline}  
	
	
	.responsiveTable {
		
	}
	.hideOnMobile {
		
	}
	@media only screen and (max-device-width: 320px) {
		*[class=headerTable] {}
		*[class=hideOnMobile] {
			display: none;
		}
		table[id=pageTable] {}
		
		table[class=responsiveTable] { 
			width:320px !important;
		}
		table[class=footerIconsTable] {
			width: 240px !important;
		}
		table[class=footer-icon-table] {
			width: 240px !important;
		}
		td[class=footer-icon-cell] {
			width: 80px !important;
		}
		img[class=footer-icon-img] {
			width: 64px !important;
			height: 64px !important;
		}
		td[class=station-name] {}
		td[class=station-tagline] {}
		table[class=mainContentTable] {
			width: 320px !important;
		}
		table[class=blurbTable] {
			width: 100% !important;
		}
		table[class=blurbActionTable] {}
		table[class=blurbTableLeft],
		table[class=blurbTableRight] {
			width: 100% !important;
			float: left !important;
			margin-top: 10px;
		}
		table[class=blurbTableRight] table[class=actionBtnTable] {
			float: left !important;
		}
		table[class=actionBtnTable] {}
		table[class=stationTable] {
			margin: 0px !important;
		}
		table[class=stationTable],
		table[class=stationTableText] {
		}
		table[class=stationTableImage] {}
	}
</style></head><body style="background: #ececec;min-height: 1000px;color: #000000;font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;font-size: 12px;" alink="#ff0000" link="#ff0000" bgcolor="#ececec" text="#000000" align="center" yahoo="fix" >

<div style="display:none;">

</div>
<div id="body_style" style="padding: 0px;">
	


<table width="100%" id="pageTable" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
	<tr>
		<td align="center" valign="middle" class="pageheader" style="text-align: center;vertical-align: middle;">			
<!-- BEGIN SECTION HEADER -->


<table width="100%" height="50" id="headerTable" class="headerTable" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
	<tr>
		<td bgcolor="#b9181b" height="50" align="left" valign="middle" style="background-color: #b9181b;height: 50px;text-align: left;vertical-align: middle;">			
<table width="720" height="50" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
				<tr>
					<td width="70%" align="left" valign="middle" style="width: 70%;text-align: left;vertical-align: middle;"><a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c05fcfcbb341c25f78b8fdcc21bb75d7e8ad239e332a8fb2c5d02ed2166362bd8" style="color: #fff;text-decoration: none;" ><span style="color: #fff;text-decoration: none;"><img src="http://static.iheart.com/emails/template/images/logo/ihr-horizontal-logo-3.png" width="205" height="28" alt="iHeartRadio" style="display: block;" class="image_fix" title="iHeartRadio"  border="0" /></span></a>					</td>
					<td width="30%" height="50" align="center" valign="middle" style="border-left: 1px solid #a11215;width: 30%;height: 50px;text-align: center;vertical-align: middle;"><a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c05fcfcbb341c25f78b8fdcc21bb75d7e8ad239e332a8fb2c5d02ed2166362bd8" style="color: #ffffff; font-size: 14px; text-decoration: none;"><strong>Listen Now</strong></a>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<!-- END SECTION HEADER -->
		</td>
	</tr>
	<tr>
		<td height="25"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
	<tr>
		<td align="center" valign="middle" class="pagecontent" style="text-align: center;vertical-align: middle;">			
<table bgcolor="#ddd" class="contentOuterTable" cellpadding="1" cellspacing="0" border="0" style="background-color:#ddd;" align="center" >
<!-- ddd -->
				<tr>
					<td>
						
<!-- CONTENT BEGIN -->

<table bgcolor="#fff" width="718" id="contentTable" cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;" align="center" >
	<tr>
		<td>
			<!-- BEGIN TEMPLATE newsletter -->
<table cellpadding="0" class="mainContentTable" cellspacing="0" border="0" align="center" >
	
	<!-- top gutter 25px -->
	<tr>
		<td height="25" colspan="3"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
	
	<!-- left and right gutters 30px -->
	<tr>
		<td width="30"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
		<td width="560">

<table width="100%" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
		<tr>
		<td width="100%" align="center" valign="top">
			<table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><font face="Arial" size="2"><table class="bigimage" style="width:600px;" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
	<tbody><tr>
		<td colspan="3" style="text-align: left;vertical-align: middle;" align="left" valign="middle"><a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c770d76da16cb3dfed5478ae24f8f1b5b6f24ef982b11a2ffbcf52b6681635477" title="Malaysian Flight 370"  ><img src="http://image.email.iheart.com/lib/fe9c15707265067575/m/1/malaysia_flight370_email_4.png" style="display: block; width: 600px; height: 250px; border-color: rgb(0, 0, 0); margin: 0px;" class="image_fix" height="250" width="600" title="Updates on the Malaysian Flight 370" alt="Updates on the Malaysian Flight 370" thid="396543f7-3a89-41f7-a158-f083ddc386a5"></a></td>
	</tr>
</tbody></table></font></td></tr></table></td></tr></table>
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			<table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><table style="width: 100%;" class="ebspacer" cellpadding="0" cellspacing="0" bgcolor="#9a9a9a" border="0" width="100%">
	<tbody>
		<tr>
			<td style="height: 6px;max-height:6px;line-height: 6px;font-size: 1px;" bgcolor="#9a9a9a" height="6" width="100%"><span style="font-size: 1px;line-height: 1px;">&nbsp;</span></td>
		</tr>
	</tbody>
</table></td></tr></table></td></tr></table>
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			<table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><font face="Arial"><table class="headline_only" style="width:560px;" align="center" border="0" cellpadding="0" cellspacing="0" width="560">
	<tbody><tr>
		<td style="width: 100%;height: 30px;text-align: left;vertical-align: middle;" align="left" height="30" valign="middle" width="100%">			<span style="line-height: 27px; margin: 0px; padding: 0px; color: rgb(165, 21, 17); font-family: Helvetica, Arial, sans-serif; font-weight: bold;"><font size="3"><br>Rely on iHeartRadio for the latest on missing Malaysian Flight 370</font></span></td>
	</tr>
	<tr>
		<td colspan="2" style="height: 10px;text-align: left;vertical-align: middle;" align="left" height="10" valign="middle"><p style="width: 100%;height: 1px;background-color: #cccccc;margin: 0px;padding: 0px;font-size: 1px;" class="hrule">&nbsp;</p></td>
	</tr>
</tbody></table>
</font><br></td></tr></table></td></tr></table>
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			<table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><font face="Arial" size="2">
<table class="blackbox" style="background-color:#ffffff;width:600px;" align="center" bgcolor="#000000" border="0" cellpadding="0" cellspacing="0" width="600">
	<tbody>
		<tr>
			<td style="vertical-align: middle;" valign="middle"><span style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><table style="text-align: center; width: 560px;" align="center" border="0" cellpadding="0" cellspacing="0" width="560"><tbody><tr><td style="text-align: left;vertical-align: middle;" align="left" valign="middle"><font size="3"><font color="#cdcdcd" face="Helvetica, Arial, sans-serif"><span style="line-height: 20px;"><span style="color: rgb(0, 0, 0);">Combining the international resources of ABC News, CNN, and iHeartRadio News for the latest and most in depth coverage until the mystery is solved. Download the iHeartRadio App, or listen at iHeartRadio.com</span></span>
</font></font><font size="3"><font color="#cdcdcd" face="Helvetica, Arial, sans-serif"><span style="line-height: 20px;"><span style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><br></span>
						</span></span></font><br>
						<div style="text-align: center;">
						<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c3f502e74bc10637db456cd96eeefb9955d9d3c60785ad32aec04f37bb2910463" title="Malaysian Air Investigation"  ><img src="http://image.email.iheart.com/lib/fe9c15707265067575/m/1/listenNow.jpg" title="Malaysian Air Investigation" alt="Malaysian Air Investigation" border="0" width="171" style="width: 171px; height: 36px; border-color: rgb(0, 0, 0); margin: 0px;" height="36" thid="093fa9c6-2553-42e4-bdb8-7b5fc52ef6d5"></a>
						</div>
						</font></td>
					</tr>
				</tbody>
			</table></span>
			</span></td>
		</tr>
	</tbody>
</table>
</font></td></tr></table></td></tr></table>
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
		<tr>
		<td width="100%" align="center" valign="top">
			
		</td>
	</tr>
	</table>
		</td>	
		<td width="30"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
	
	<!-- bottom gutter 25px -->
	<tr>
		<td height="25" colspan="3"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
</table>		</td>
	</tr>
</table>
<!-- CONTENT END -->
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center" valign="middle" class="pagefooter" style="text-align: center;vertical-align: middle;">			<!-- BEGIN SECTION FOOTER -->

<table width="100%" id="pageFooter" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
	<tr>
		<td height="25"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
	<tr>
		<td>
			<table width="720" border="0" cellpadding="0" cellspacing="0" style="background: none; border-bottom: 1px solid #dddddd;" align="center">
	<tr>
<td width="170" align="left" valign="middle"><a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c17d7f836e5871493ffadf2c2f45376a7348626c537b6b7d6caa5aa9c01d9f071" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/button/liveradio.png" width="123" height="38" style="display: inline;" class="image_fix"  border="0" /></span></a>
</td>
<td width="170" align="center" valign="middle"><a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24ca7b939e58d85b7a97872e05a152e69f1472a6983cb3e6d50c6bde3b4dc8e8673" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/button/perfectfor.png" width="135" height="38" style="display: inline;" class="image_fix"  border="0" /></span></a>
</td>
<td width="190" align="center" valign="middle"><a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c548a93e51dcf590b51fe94f96a987b0c7ea68898eb7776c22dcfc0d502191a1b" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/button/create.png" width="155" height="38" style="display: inline;" class="image_fix"  border="0" /></span></a>
</td>
<td width="190" align="right" valign="middle"><a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c0496f724b40508c31cea14f2de2191ab7d21351b64e2f773093dc3d3f315b97d" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/button/shows-personalities-icon.png" width="154" height="38" style="display: inline;" class="image_fix"  border="0" /></span></a>
</td>
	</tr>
	<tr>
		<td height="30" colspan="4"></td>
	</tr>
</table>		</td>
	</tr>
	<tr>
		<td height="15"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
	<tr>
		<td>
			
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
				<tr>
					<td>
					

<table id="footerLinks" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
	<tr>
		<td height="20" colspan="3"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
	<tr>
		<td align="center">
				<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c91da206f0035408fcc186bf057dc7d3086221d32a809e4b49a773c8ef0bdec65" style="color: #333333;" ><span style="color: #333333;">Unsubscribe</span></a> | 				<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24cba7f24f133495710ab5943c35fd6c65e1590b12b2486d131508477b4f4fc3d1f" style="color: #333333;" ><span style="color: #333333;">Terms & Conditions</span></a> | 				<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24cfea811c5f9777a3fe56fd43a57be508ebaffd40239869eda6f0f88397adc471b" style="color: #333333;" ><span style="color: #333333;">Privacy Policy</span></a>			</td>
	</tr>
	<tr>
		<td height="20" colspan="3"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
	</tr>
</table>

					</td>
				</tr>
				<tr>
					<td height="20"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
				</tr>
				<tr>
					<td>
						
<table width="274" class="footerIconsTable" cellpadding="0" cellspacing="0" border="0" style="" align="center" >
	<tr>
			<td>
		<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24cc2dffbdf3fc70032a2ba657cc7d181e27676362827b811f337f055318091d09e" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/social-red/twitter.png" width="36" height="36" style="display: block;" class="footer-icon-img"  border="0" /></span></a>		</td>
			<td>
		<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24cea6efddee61871a13ccbe2a178c2f92ea9ca1ff9150bca0cfe95ff34e0d84698" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/social-red/facebook.png" width="36" height="36" style="display: block;" class="footer-icon-img"  border="0" /></span></a>		</td>
			<td>
		<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c0ea91891e3c09c289afbae9ea676e5bf095573e3959ee5437c8337fb9273d521" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/social-red/gplus.png" width="36" height="36" style="display: block;" class="footer-icon-img"  border="0" /></span></a>		</td>
			<td>
		<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24ca5898fbca936838f664723d78c9133374345260e1633a277003bd63754173c61" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/social-red/youtube.png" width="36" height="36" style="display: block;" class="footer-icon-img"  border="0" /></span></a>		</td>
			<td>
		<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24ce9e00a74bb62a9a7f601e6d3b1108c172675fedc37eb072ba2264c8ddac89cde" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/social-red/instagram.png" width="36" height="36" style="display: block;" class="footer-icon-img"  border="0" /></span></a>		</td>
			<td>
		<a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c7f923a3cf2dc5b911c7f106cd9b5efe6617e121c81ced442e7ab9dba9efceff4" style=";" ><span style=";"><img src="http://static.iheart.com/emails/template/images/footer/social-red/pinterest.png" width="36" height="36" style="display: block;" class="footer-icon-img"  border="0" /></span></a>		</td>
		</tr>
</table>
					</td>
				</tr>
				<tr>
					<td height="20"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
				</tr>
				<tr>
					<td align="center" valign="middle" style="text-align: center;vertical-align: middle;">						<strong>iHeartRadio &copy; 2014</strong><br />
						32 Avenue of the Americas<br>
New York, NY 10013
					</td>
				</tr>
				<tr>
					<td height="20"><p style="width: 1px;height: 1px;margin: 0px;padding: 0px;font-size: 1px;" class="ebspacer">&nbsp;</p></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<!-- END SECTION FOOTER -->
		</td>
	</tr>
</table>

<P><center><table width="600" cellpadding="0" cellspacing="0" border="0"> <tr>  <td width="100%" align="center">  <font face="verdana" size="1" color="#444444"> To view this email as a web page, go   <a href="http://click.email.iheart.com/?qs=a03b66e8d66bf24c4a47ff46a666c254fa7e898a7487d5bc97d8bbb45c074ec2ca99e6b254be626a" > here.</a><br>  </font>  </td> </tr> </table> </center></P>
</div>

<style type="text/css">
		
	.ExternalClass {width:100%;} 
	.ExternalClass,
	.ExternalClass p,
	.ExternalClass span,
	.ExternalClass font,
	.ExternalClass td,
	.ExternalClass div { line-height: 100%; } 
	
	body {-webkit-text-size-adjust:none; -ms-text-size-adjust:none;} 
	body {margin:0; padding:0;} 
	table td {border-collapse:collapse;}	
	
	p {margin:0; padding:0; margin-bottom:0;}		
	
	h1, h2, h3, h4, h5, h6 {
	   color: black; 
	   line-height: 100%; 
	   }  
	
	a, a:link {
	   color:#2A5DB0;
	   text-decoration: underline;
	   }  	   
	
	body, #body_style {
	   background:#ececec;
	   min-height:1000px;
	   color:#000;
	   font-family:Helvetica, Arial, sans-serif;
	   font-size:12px;
	   } 
	   
	span.yshortcuts { color:#000; background-color:none; border:none;}
	span.yshortcuts:hover,
	span.yshortcuts:active,
	span.yshortcuts:focus {color:#000; background-color:none; border:none;}
	
	a:visited { color: #3c96e2; text-decoration: none} 
	a:focus   { color: #3c96e2; text-decoration: underline}  
	a:hover   { color: #3c96e2; text-decoration: underline}  
	
	
	.responsiveTable {
		
	}
	.hideOnMobile {
		
	}
	@media only screen and (max-device-width: 320px) {
		*[class=headerTable] {}
		*[class=hideOnMobile] {
			display: none;
		}
		table[id=pageTable] {}
		
		table[class=responsiveTable] { 
			width:320px !important;
		}
		table[class=footerIconsTable] {
			width: 240px !important;
		}
		table[class=footer-icon-table] {
			width: 240px !important;
		}
		td[class=footer-icon-cell] {
			width: 80px !important;
		}
		img[class=footer-icon-img] {
			width: 64px !important;
			height: 64px !important;
		}
		td[class=station-name] {}
		td[class=station-tagline] {}
		table[class=mainContentTable] {
			width: 320px !important;
		}
		table[class=blurbTable] {
			width: 100% !important;
		}
		table[class=blurbActionTable] {}
		table[class=blurbTableLeft],
		table[class=blurbTableRight] {
			width: 100% !important;
			float: left !important;
			margin-top: 10px;
		}
		table[class=blurbTableRight] table[class=actionBtnTable] {
			float: left !important;
		}
		table[class=actionBtnTable] {}
		table[class=stationTable] {
			margin: 0px !important;
		}
		table[class=stationTable],
		table[class=stationTableText] {
		}
		table[class=stationTableImage] {}
	}
</style><img src="http://click.email.iheart.com/open.aspx?ffcb10-fec817777166037d-fe2f1574776d0d7d741072-fe9c15707265067575-ff961578-fe5617737d6202797c16-fef31579706d00&d=40027" width="1" height="1">
</body></html>
</body></html>

END:MSG
END:BBODY
END:BENV
END:BMSG
