;/************************************************************************************************
;* Copyright 2015 Freescale Semiconductor, Inc.
;* Copyright 2015-2019 NXP.
;*
;*  License: LA_OPT_NXP_Software_License
;*
;*************************************************************************** 
;*
;* NXP Confidential. This software is owned or controlled by NXP and may
;* only be used strictly in accordance with the applicable license terms.
;* By expressly accepting such terms or by downloading, installing,
;* activating and/or otherwise using the software, you are agreeing that
;* you have read, and that you agree to comply with and are bound by,
;* such license terms.  If you do not agree to be bound by the applicable
;* license terms, then you may not retain, install, activate or otherwise
;* use the software.  This code may only be used in a microprocessor,
;* microcontroller, sensor or digital signal processor ("NXP Product")
;* supplied directly or indirectly from NXP.  See the full NXP Software
;* License Agreement in LA_OPT_NXP_Software_License.pdf
;*
;**************************************************************************
;*
;* $Version : 4.0$
;*
;* Comments:
;*
;***********************************************************************************************/

  AREA KERNEL_DATA_START, DATA, ALIGN=4, READWRITE
  EXPORT __KERNEL_DATA_START
__KERNEL_DATA_START
  DCD 0


  END

; EOF

