/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _RPMSG_CONFIG_H_
#define _RPMSG_CONFIG_H_

#define RL_MS_PER_INTERVAL 1
// #define RL_ALLOW_CUSTOM_SHMEM_CONFIG 0
#define CONFIG_RL_BUFFER_PAYLOAD_SIZE_VALUE 240U
#define CONFIG_RL_BUFFER_COUNT_VALUE 2U
#define CONFIG_RL_BUFFER_PAYLOAD_SIZE_SHMEM(link_id) (496U)
#define CONFIG_RL_BUFFER_PAYLOAD_COUNT_SHMEM(link_id) (((link_id) == 0U) ? 256U : 2U)
#define RL_BUFFER_PAYLOAD_SIZE 240
#define RL_BUFFER_COUNT 2
#define RL_API_HAS_ZEROCOPY 1
#define RL_USE_STATIC_API 1
// #define RL_CLEAR_USED_BUFFERS 0
#define RL_USE_DCACHE 1
#define RL_USE_MCMGR_IPC_ISR_HANDLER 1
// #define RL_USE_ENVIRONMENT_CONTEXT 0
// #define RL_DEBUG_CHECK_BUFFERS 0
// #define RL_ALLOW_CONSUMED_BUFFERS_NOTIFICATION 0

#endif /* _RPMSG_CONFIG_H_ */
