/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MKE16Z64xxx4
package_id: MKE16Z64VLF4
mcu_data: ksdk2_0
processor_version: 0.10.1
board: FRDM-KE16Z
pin_labels:
- {pin_num: '26', pin_signal: ADC0_SE5/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, label: UART0_TX_TGTMCU, identifier: DEBUG_UART_TX;TX}
- {pin_num: '27', pin_signal: ADC0_SE4/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, label: UART0_RX_TGTMCU, identifier: DEBUG_UART_RX;RX}
- {pin_num: '28', pin_signal: ADC0_SE3/PTA7/FTM0_FLT2/LPSPI0_PCS3/RTC_CLKIN/LPUART1_RTS, label: 'J4[6]/THERM_0/Arduino_A2', identifier: THER_A;PCS}
- {pin_num: '35', pin_signal: PTA3/LPI2C0_SCL/EWM_IN/LPUART0_TX, label: 'J2[20]/U12[2]/FXOS_SCL/Arduino_D15', identifier: ACCEL_SCL;SCL}
- {pin_num: '36', pin_signal: PTA2/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX, label: 'J2[18]/U12[3]/FXOS_SDA/Arduino_D14', identifier: ACCEL_SDA;SDA}
- {pin_num: '42', pin_signal: TSI0_CH19/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/PWT_IN3/LPUART1_CTS, label: 'J4[7]/TOUCH_S_3/GES_C2', identifier: MISO}
- {pin_num: '43', pin_signal: TSI0_CH14/PTE1/LPSPI0_SIN/LPI2C0_HREQ, label: 'J4[5]/TOUCH_S_2/GES_C3', identifier: MOSI}
- {pin_num: '44', pin_signal: TSI0_CH13/PTE0/LPSPI0_SCK/TCLK1, label: 'J4[3]/TOUCH_S_1/GES_C4', identifier: SCK}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'false'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBootPin:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '34', peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: PTD2, direction: INPUT, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPin
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPin(void)
{

    gpio_pin_config_t SW3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin 34)  */
    GPIO_PinInit(BOARD_INITBOOTPIN_SW3_GPIO, BOARD_INITBOOTPIN_SW3_PIN, &SW3_config);

    const port_pin_config_t SW3 = {/* Internal pull-up resistor is enabled */
                                   kPORT_PullUp,
                                   /* Passive filter is disabled */
                                   kPORT_PassiveFilterDisable,
                                   /* Low drive strength is configured */
                                   kPORT_LowDriveStrength,
                                   /* Pin is configured as PTD2 */
                                   kPORT_MuxAsGpio,
                                   /* Pin Control Register fields [15:0] are not locked */
                                   kPORT_UnlockRegister};
    /* PORTD2 (pin 34) is configured as PTD2 */
    PORT_SetPinConfig(BOARD_INITBOOTPIN_SW3_PORT, BOARD_INITBOOTPIN_SW3_PIN, &SW3);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
UART0_InitPins:
- options: {callFromInitBoot: 'false', prefix: LPUART0_, coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '26', peripheral: LPUART0, signal: TX, pin_signal: ADC0_SE5/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, identifier: TX}
  - {pin_num: '27', peripheral: LPUART0, signal: RX, pin_signal: ADC0_SE4/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, identifier: RX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : UART0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void UART0_InitPins(void)
{

    /* PORTB0 (pin 27) is configured as LPUART0_RX */
    PORT_SetPinMux(LPUART0_RX_PORT, LPUART0_RX_PIN, kPORT_MuxAlt2);

    /* PORTB1 (pin 26) is configured as LPUART0_TX */
    PORT_SetPinMux(LPUART0_TX_PORT, LPUART0_TX_PIN, kPORT_MuxAlt2);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
UART0_RestoreDefault:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '26', peripheral: ADC0, signal: 'SE, 5', pin_signal: ADC0_SE5/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0}
  - {pin_num: '27', peripheral: ADC0, signal: 'SE, 4', pin_signal: ADC0_SE4/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : UART0_RestoreDefault
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void UART0_RestoreDefault(void)
{

    /* PORTB0 (pin 27) is configured as ADC0_SE4 */
    PORT_SetPinMux(PORTB, 0U, kPORT_PinDisabledOrAnalog);

    /* PORTB1 (pin 26) is configured as ADC0_SE5 */
    PORT_SetPinMux(PORTB, 1U, kPORT_PinDisabledOrAnalog);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
UART0_PollForActivity:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '27', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE4/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, identifier: RX, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : UART0_PollForActivity
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void UART0_PollForActivity(void)
{

    gpio_pin_config_t RX_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 27)  */
    GPIO_PinInit(UART0_POLLFORACTIVITY_RX_GPIO, UART0_POLLFORACTIVITY_RX_PIN, &RX_config);

    /* PORTB0 (pin 27) is configured as PTB0 */
    PORT_SetPinMux(UART0_POLLFORACTIVITY_RX_PORT, UART0_POLLFORACTIVITY_RX_PIN, kPORT_MuxAsGpio);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
I2C0_InitPins:
- options: {callFromInitBoot: 'false', prefix: LPI2C0_, coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '35', peripheral: LPI2C0, signal: SCL, pin_signal: PTA3/LPI2C0_SCL/EWM_IN/LPUART0_TX, identifier: SCL}
  - {pin_num: '36', peripheral: LPI2C0, signal: SDA, pin_signal: PTA2/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX, identifier: SDA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : I2C0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void I2C0_InitPins(void)
{

    /* PORTA2 (pin 36) is configured as LPI2C0_SDA */
    PORT_SetPinMux(LPI2C0_SDA_PORT, LPI2C0_SDA_PIN, kPORT_MuxAlt3);

    /* PORTA3 (pin 35) is configured as LPI2C0_SCL */
    PORT_SetPinMux(LPI2C0_SCL_PORT, LPI2C0_SCL_PIN, kPORT_MuxAlt3);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
I2C0_RestoreDefault:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '35', peripheral: n/a, signal: disabled, pin_signal: PTA3/LPI2C0_SCL/EWM_IN/LPUART0_TX, identifier: SCL}
  - {pin_num: '36', peripheral: n/a, signal: disabled, pin_signal: PTA2/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX, identifier: SDA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : I2C0_RestoreDefault
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void I2C0_RestoreDefault(void)
{

    /* PORTA2 (pin 36) is disabled */
    PORT_SetPinMux(I2C0_RESTOREDEFAULT_SDA_PORT, I2C0_RESTOREDEFAULT_SDA_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTA3 (pin 35) is disabled */
    PORT_SetPinMux(I2C0_RESTOREDEFAULT_SCL_PORT, I2C0_RESTOREDEFAULT_SCL_PIN, kPORT_PinDisabledOrAnalog);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SPI0_InitPins:
- options: {callFromInitBoot: 'false', prefix: LPSPI0_, coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '28', peripheral: LPSPI0, signal: PCS3, pin_signal: ADC0_SE3/PTA7/FTM0_FLT2/LPSPI0_PCS3/RTC_CLKIN/LPUART1_RTS, identifier: PCS}
  - {pin_num: '44', peripheral: LPSPI0, signal: SCK, pin_signal: TSI0_CH13/PTE0/LPSPI0_SCK/TCLK1}
  - {pin_num: '42', peripheral: LPSPI0, signal: SOUT, pin_signal: TSI0_CH19/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/PWT_IN3/LPUART1_CTS}
  - {pin_num: '43', peripheral: LPSPI0, signal: SIN, pin_signal: TSI0_CH14/PTE1/LPSPI0_SIN/LPI2C0_HREQ}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SPI0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void SPI0_InitPins(void)
{

    /* PORTA7 (pin 28) is configured as LPSPI0_PCS3 */
    PORT_SetPinMux(LPSPI0_PCS_PORT, LPSPI0_PCS_PIN, kPORT_MuxAlt3);

    /* PORTE0 (pin 44) is configured as LPSPI0_SCK */
    PORT_SetPinMux(LPSPI0_SCK_PORT, LPSPI0_SCK_PIN, kPORT_MuxAlt2);

    /* PORTE1 (pin 43) is configured as LPSPI0_SIN */
    PORT_SetPinMux(LPSPI0_MOSI_PORT, LPSPI0_MOSI_PIN, kPORT_MuxAlt2);

    /* PORTE2 (pin 42) is configured as LPSPI0_SOUT */
    PORT_SetPinMux(LPSPI0_MISO_PORT, LPSPI0_MISO_PIN, kPORT_MuxAlt2);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SPI0_RestoreDefault:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '28', peripheral: ADC0, signal: 'SE, 3', pin_signal: ADC0_SE3/PTA7/FTM0_FLT2/LPSPI0_PCS3/RTC_CLKIN/LPUART1_RTS, identifier: PCS}
  - {pin_num: '44', peripheral: TSI, signal: 'CH, 13', pin_signal: TSI0_CH13/PTE0/LPSPI0_SCK/TCLK1}
  - {pin_num: '43', peripheral: TSI, signal: 'CH, 14', pin_signal: TSI0_CH14/PTE1/LPSPI0_SIN/LPI2C0_HREQ}
  - {pin_num: '42', peripheral: TSI, signal: 'CH, 19', pin_signal: TSI0_CH19/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/PWT_IN3/LPUART1_CTS}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SPI0_RestoreDefault
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void SPI0_RestoreDefault(void)
{

    /* PORTA7 (pin 28) is configured as ADC0_SE3 */
    PORT_SetPinMux(SPI0_RESTOREDEFAULT_PCS_PORT, SPI0_RESTOREDEFAULT_PCS_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE0 (pin 44) is configured as TSI0_CH13 */
    PORT_SetPinMux(SPI0_RESTOREDEFAULT_SCK_PORT, SPI0_RESTOREDEFAULT_SCK_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE1 (pin 43) is configured as TSI0_CH14 */
    PORT_SetPinMux(SPI0_RESTOREDEFAULT_MOSI_PORT, SPI0_RESTOREDEFAULT_MOSI_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE2 (pin 42) is configured as TSI0_CH19 */
    PORT_SetPinMux(SPI0_RESTOREDEFAULT_MISO_PORT, SPI0_RESTOREDEFAULT_MISO_PIN, kPORT_PinDisabledOrAnalog);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
CAN0_InitPins:
- options: {callFromInitBoot: 'false', prefix: CAN0_, coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '40', peripheral: MSCAN, signal: RX, pin_signal: TSI0_CH15/PTC6/LPUART1_RX/CAN0_RX}
  - {pin_num: '39', peripheral: MSCAN, signal: TX, pin_signal: TSI0_CH16/PTC7/LPUART1_TX/CAN0_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : CAN0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void CAN0_InitPins(void)
{

    /* PORTC6 (pin 40) is configured as CAN0_RX */
    PORT_SetPinMux(CAN0_CAN_RX_PORT, CAN0_CAN_RX_PIN, kPORT_MuxAlt5);

    /* PORTC7 (pin 39) is configured as CAN0_TX */
    PORT_SetPinMux(CAN0_CAN_TX_PORT, CAN0_CAN_TX_PIN, kPORT_MuxAlt5);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
CAN0_RestoreDefault:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '40', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: TSI0_CH15/PTC6/LPUART1_RX/CAN0_RX}
  - {pin_num: '39', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: TSI0_CH16/PTC7/LPUART1_TX/CAN0_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : CAN0_RestoreDefault
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void CAN0_RestoreDefault(void)
{

    /* PORTC6 (pin 40) is configured as PTC6 */
    PORT_SetPinMux(CAN0_RESTOREDEFAULT_CAN_RX_PORT, CAN0_RESTOREDEFAULT_CAN_RX_PIN, kPORT_MuxAsGpio);

    /* PORTC7 (pin 39) is configured as PTC7 */
    PORT_SetPinMux(CAN0_RESTOREDEFAULT_CAN_TX_PORT, CAN0_RESTOREDEFAULT_CAN_TX_PIN, kPORT_MuxAsGpio);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
