/** @file key_cert.h
 *
 *  @brief This file provides CA certificate, own csertificate and own private key.
 *
 *  Copyright 2024 NXP
 *
 *  SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "ncp_tlv_adapter.h"

#define CONFIG_TLS_CIPHERSUITE  MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

const char CA_CERT[] = 
"-----BEGIN CERTIFICATE-----\n\
MIICDjCCAbOgAwIBAgIUf556rYfAGUKR64LzlQPEWb50nIUwCgYIKoZIzj0EAwIw\n\
XDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQHDAdTQU5KT1NFMQww\n\
CgYDVQQKDANOWFAxDDAKBgNVBAsMA1dDUzESMBAGA1UEAwwJbG9jYWxob3N0MB4X\n\
DTI1MDEwMzA1NDUyOFoXDTI3MDkzMDA1NDUyOFowXDELMAkGA1UEBhMCVVMxCzAJ\n\
BgNVBAgMAkNBMRAwDgYDVQQHDAdTQU5KT1NFMQwwCgYDVQQKDANOWFAxDDAKBgNV\n\
BAsMA1dDUzESMBAGA1UEAwwJbG9jYWxob3N0MFkwEwYHKoZIzj0CAQYIKoZIzj0D\n\
AQcDQgAEvuG2utSVL65vcCk/39aSqiWY3ZVOuxyefyocgpv6f3GD7IadSkVF3ysC\n\
HDgGd8oDdXsYqDDH7vu/WUEfWfdwr6NTMFEwHQYDVR0OBBYEFA4jJyiex+sOVu3p\n\
+LxodG0NLfkBMB8GA1UdIwQYMBaAFA4jJyiex+sOVu3p+LxodG0NLfkBMA8GA1Ud\n\
EwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAPs6Q7j1MWuX6n7U5OHVJr+L\n\
2AnzSxoviJ6SmC6ovhlrAiEA181gQp8aiYYfm8ahlKKlQPn/JdSBtgX4Aqpf9wPV\n\
UHY=\n\
-----END CERTIFICATE-----\n";

const char OWN_CERT[] = 
"-----BEGIN CERTIFICATE-----\n\
MIIBszCCAVkCFFImL9tk8t0lE9PCt/orf0WAf1rwMAoGCCqGSM49BAMCMFwxCzAJ\n\
BgNVBAYTAlVTMQswCQYDVQQIDAJDQTEQMA4GA1UEBwwHU0FOSk9TRTEMMAoGA1UE\n\
CgwDTlhQMQwwCgYDVQQLDANXQ1MxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0yNTAx\n\
MDMwNTQ3MjBaFw0yNzA5MzAwNTQ3MjBaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQI\n\
DAJDQTEQMA4GA1UEBwwHU0FOSk9TRTEMMAoGA1UECgwDTlhQMQwwCgYDVQQLDANX\n\
Q1MxEjAQBgNVBAMMCWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA\n\
BNORW3ash6MZyQM76EPKOJmWvbozeLniMC8NGNTWnyJlymC0ApLI85wsLAX48DUB\n\
JyxEmO+Sd0irq8eT9t9miu8wCgYIKoZIzj0EAwIDSAAwRQIhALSrIUCJVydq7u5/\n\
ogL96+B0XvnnN/SIB19vfPAs2yPxAiBZJe14069dxWm4Gl4bwTb6cbG5KwBvRFGo\n\
2IvWa+rUFA==\n\
-----END CERTIFICATE-----\n";


#if !CONFIG_NCP_IS_PVTKEY_ENCRYPTED

#define TLS_KEY_PASSWORD                 NULL
#define TLS_KEY_PASSWORD_LEN             0

const char OWN_PVTKEY[] = 
"-----BEGIN PRIVATE KEY-----\n\
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgJ1F/iJZl/9ksXioz\n\
ywyMUxAZD4Xy8yhRFTDNSFwpwqShRANCAATTkVt2rIejGckDO+hDyjiZlr26M3i5\n\
4jAvDRjU1p8iZcpgtAKSyPOcLCwF+PA1AScsRJjvkndIq6vHk/bfZorv\n\
-----END PRIVATE KEY-----\n";

#else

#define TLS_KEY_PASSWORD                 "12345678"
#define TLS_KEY_PASSWORD_LEN             8

const char OWN_PVTKEY[] = 
"-----BEGIN ENCRYPTED PRIVATE KEY-----\n\
MIHjME4GCSqGSIb3DQEFDTBBMCkGCSqGSIb3DQEFDDAcBAgMeqXZ5BvBiAICCAAw\n\
DAYIKoZIhvcNAgkFADAUBggqhkiG9w0DBwQI2DD2jezkbXIEgZATPqOx7Pi9cyIZ\n\
smsQCpmrbinA6rJCqspS4RCSAMXBDNexYZnrMubnphU0r7MG2NtPNqLCB9qCmS6E\n\
kJ9GLjSqvtSSvZvxgv2KtbfhHlR4nQl45FlelEDjPC1kLaK0hf+3Q1sMlAszypcO\n\
Fv5Lfb3dW+bBfhVKtp5xwEMhM9xRReJTsU8qYyQd2jhzfEFETLg=\n\
-----END ENCRYPTED PRIVATE KEY-----";

#endif
