if(NOT CMSIS_DSP_LIB_ARM_CORTEXM7LFDP_MATH_MIMXRT1176_cm7_INCLUDED)
    
    set(CMSIS_DSP_LIB_ARM_CORTEXM7LFDP_MATH_MIMXRT1176_cm7_INCLUDED true CACHE BOOL "CMSIS_DSP_Lib_arm_cortexM7lfdp_math component is included.")

endif()
