# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_multicore_rpmsg_lite_freertos_MIMXRT595S_cm33 true)
set(CONFIG_USE_component_wm8904_adapter_MIMXRT595S_cm33 true)
set(CONFIG_USE_component_i3c_adapter_MIMXRT595S_cm33 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT595S_cm33 true)
set(CONFIG_USE_driver_flexcomm_usart_MIMXRT595S_cm33 true)
set(CONFIG_USE_middleware_freertos-kernel_MIMXRT595S_cm33 true)
