/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define EXAMPLE_I2C_BAUDRATE 400000U
#define EXAMPLE_I3C_OD_BAUDRATE 2000000U
#define EXAMPLE_I3C_PP_BAUDRATE 4000000U
#define EXAMPLE_EVENT_WAIT_DELAY_NS 10000U
#define CONFIG_FLASH_BASE_ADDRESS 0x0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
