/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _EDGEFAST_BLUETOOTH_AUDIO_CONFIG_GEN_H_
#define _EDGEFAST_BLUETOOTH_AUDIO_CONFIG_GEN_H_

#define CONFIG_BT_AUDIO 1
#define CONFIG_BT_AUDIO_RX 1
#define CONFIG_BT_AUDIO_TX 1
#define CONFIG_BT_AUDIO_NOTIFY_RETRY_DELAY 20
// #define CONFIG_BT_CCID 0
#define CONFIG_BT_BAP_UNICAST 1
#define CONFIG_BT_BAP_UNICAST_SERVER 1
// #define CONFIG_BT_BAP_UNICAST_CLIENT 0
#define CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE 19
#define CONFIG_BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE 4
#define CONFIG_BT_BAP_BASS_MAX_SUBGROUPS 1
#define CONFIG_BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE 19
#define CONFIG_BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE 4
// #define CONFIG_BT_BAP_BROADCAST_SOURCE 0
// #define CONFIG_BT_BAP_SCAN_DELEGATOR 0
// #define CONFIG_BT_BAP_BROADCAST_ASSISTANT 0
#define CONFIG_BT_BAP_STREAM 1
#define CONFIG_BT_PAC_SNK 1
// #define CONFIG_BT_PAC_SNK_NOTIFIABLE 0
#define CONFIG_BT_PAC_SNK_LOC 1
// #define CONFIG_BT_PAC_SNK_LOC_WRITEABLE 0
// #define CONFIG_BT_PAC_SNK_LOC_NOTIFIABLE 0
#define CONFIG_BT_PAC_SRC 1
// #define CONFIG_BT_PAC_SRC_NOTIFIABLE 0
#define CONFIG_BT_PAC_SRC_LOC 1
// #define CONFIG_BT_PAC_SRC_LOC_WRITEABLE 0
// #define CONFIG_BT_PAC_SRC_LOC_NOTIFIABLE 0
#define CONFIG_BT_PACS 1
// #define CONFIG_BT_PACS_SUPPORTED_CONTEXT_NOTIFIABLE 0
#define CONFIG_BT_ASCS 1
#define CONFIG_BT_ASCS_ASE_SNK_COUNT 1
#define CONFIG_BT_ASCS_ASE_SRC_COUNT 1
#define CONFIG_BT_ASCS_ASE_SNK 1
#define CONFIG_BT_ASCS_ASE_SRC 1
#define CONFIG_BT_ASCS_MAX_ACTIVE_ASES 2
#define CONFIG_BT_ASCS_ISO_DISCONNECT_DELAY 500
#define CONFIG_BT_ASCS_ASE_BUF_TIMEOUT 50
#define CONFIG_BT_VOCS_MAX_INSTANCE_COUNT 0
#define CONFIG_BT_VOCS_CLIENT_MAX_INSTANCE_COUNT 0
#define CONFIG_BT_AICS_MAX_INSTANCE_COUNT 0
#define CONFIG_BT_AICS_CLIENT_MAX_INSTANCE_COUNT 0
#define CONFIG_BT_VCP_VOL_REND 1
#define CONFIG_BT_VCP_VOL_REND_VOCS_INSTANCE_COUNT 0
#define CONFIG_BT_VCP_VOL_REND_AICS_INSTANCE_COUNT 0
// #define CONFIG_BT_VCP_VOL_REND_VOL_FLAGS_NOTIFIABLE 0
// #define CONFIG_BT_VCP_VOL_CTLR 0
// #define CONFIG_BT_MICP_MIC_DEV 0
// #define CONFIG_BT_MICP_MIC_CTLR 0
// #define CONFIG_BT_CSIP_SET_MEMBER 0
// #define CONFIG_BT_CSIP_SET_COORDINATOR 0
// #define CONFIG_BT_TBS 0
#define CONFIG_BT_TBS_CLIENT_GTBS 1
#define CONFIG_BT_TBS_CLIENT_TBS 1
#define CONFIG_BT_TBS_CLIENT 1
#define CONFIG_BT_TBS_CLIENT_MAX_CALLS 1
#define CONFIG_BT_TBS_CLIENT_MAX_TBS_INSTANCES 1
// #define CONFIG_BT_TBS_CLIENT_MINIMAL 0
#define CONFIG_BT_TBS_CLIENT_BEARER_PROVIDER_NAME 1
#define CONFIG_BT_TBS_CLIENT_BEARER_UCI 1
#define CONFIG_BT_TBS_CLIENT_BEARER_TECHNOLOGY 1
#define CONFIG_BT_TBS_CLIENT_BEARER_URI_SCHEMES_SUPPORTED_LIST 1
#define CONFIG_BT_TBS_CLIENT_BEARER_SIGNAL_STRENGTH 1
#define CONFIG_BT_TBS_CLIENT_READ_BEARER_SIGNAL_INTERVAL 1
#define CONFIG_BT_TBS_CLIENT_SET_BEARER_SIGNAL_INTERVAL 1
#define CONFIG_BT_TBS_CLIENT_BEARER_LIST_CURRENT_CALLS 1
#define CONFIG_BT_TBS_CLIENT_CCID 1
#define CONFIG_BT_TBS_CLIENT_INCOMING_URI 1
#define CONFIG_BT_TBS_CLIENT_STATUS_FLAGS 1
#define CONFIG_BT_TBS_CLIENT_CP_PROCEDURES 1
#define CONFIG_BT_TBS_CLIENT_ACCEPT_CALL 1
#define CONFIG_BT_TBS_CLIENT_TERMINATE_CALL 1
#define CONFIG_BT_TBS_CLIENT_HOLD_CALL 1
#define CONFIG_BT_TBS_CLIENT_RETRIEVE_CALL 1
#define CONFIG_BT_TBS_CLIENT_ORIGINATE_CALL 1
#define CONFIG_BT_TBS_CLIENT_OPTIONAL_OPCODES 1
#define CONFIG_BT_TBS_CLIENT_INCOMING_CALL 1
#define CONFIG_BT_TBS_CLIENT_CALL_FRIENDLY_NAME 1
#define CONFIG_BT_TBS_MAX_URI_LENGTH 30
#define CONFIG_BT_TBS_MAX_PROVIDER_NAME_LENGTH 30
#define CONFIG_BT_MCC 1
#define CONFIG_BT_MCC_MEDIA_PLAYER_NAME_MAX 20
#define CONFIG_BT_MCC_ICON_URL_MAX 40
#define CONFIG_BT_MCC_TRACK_TITLE_MAX 40
#define CONFIG_BT_MCC_SEGMENT_NAME_MAX 25
// #define CONFIG_BT_MCC_SHELL 0
// #define CONFIG_BT_MCC_MINIMAL 0
#define CONFIG_BT_MCC_READ_MEDIA_PLAYER_ICON_URL 1
#define CONFIG_BT_MCC_READ_TRACK_TITLE 1
#define CONFIG_BT_MCC_READ_TRACK_TITLE_ENABLE_SUBSCRIPTION 1
#define CONFIG_BT_MCC_READ_TRACK_DURATION 1
#define CONFIG_BT_MCC_READ_TRACK_POSITION 1
#define CONFIG_BT_MCC_SET_TRACK_POSITION 1
#define CONFIG_BT_MCC_READ_PLAYBACK_SPEED 1
#define CONFIG_BT_MCC_SET_PLAYBACK_SPEED 1
#define CONFIG_BT_MCC_READ_SEEKING_SPEED 1
#define CONFIG_BT_MCC_READ_PLAYING_ORDER 1
#define CONFIG_BT_MCC_SET_PLAYING_ORDER 1
#define CONFIG_BT_MCC_READ_PLAYING_ORDER_SUPPORTED 1
#define CONFIG_BT_MCC_READ_MEDIA_STATE 1
#define CONFIG_BT_MCC_SET_MEDIA_CONTROL_POINT 1
#define CONFIG_BT_MCC_READ_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED 1
#define CONFIG_BT_MCC_READ_CONTENT_CONTROL_ID 1
// #define CONFIG_BT_HAS 0
// #define CONFIG_BT_HAS_CLIENT 0
// #define CONFIG_BT_MPL 0
// #define CONFIG_MCTL 0
// #define CONFIG_BT_CAP_ACCEPTOR 0
// #define CONFIG_BT_CAP_COMMANDER 0
// #define CONFIG_BT_PBP 0
// #define LE_AUDIO_SYNC_ENABLE 0
#define CONFIG_BT_AUDIO_CAPABILITY 1
#define CONFIG_BT_AUDIO_BROADCAST_SRC_SUBGROUP_COUNT 0
// #define CONFIG_BT_AUDIO_BROADCAST_SOURCE 0
// #define CONFIG_BT_AUDIO_BROADCAST_SINK 0
#define CONFIG_BT_AUDIO_BROADCAST_SRC_STREAM_COUNT 0
// #define CONFIG_UTF8 0
#define LE_CONN_COUNT 0
#define CONFIG_BT_AUDIO_BROADCAST_SNK_STREAM_COUNT 2
#define CONFIG_BT_PACS_SNK_CONTEXT 0x0007
#define CONFIG_BT_PACS_SRC_CONTEXT 0x0007
// #define CONFIG_TMAP_PERIPHERAL_SINGLE 0
// #define CONFIG_BT_OTS 0
// #define CONFIG_BT_OTS_CLIENT 0

#endif /* _EDGEFAST_BLUETOOTH_AUDIO_CONFIG_GEN_H_ */
