/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _EDGEFAST_BLUETOOTH_DEBUG_CONFIG_GEN_H_
#define _EDGEFAST_BLUETOOTH_DEBUG_CONFIG_GEN_H_

#define CONFIG_BT_LOG_LEGACY 1
#define CONFIG_BT_LOG 1
// #define CONFIG_BT_DEBUG 0
// #define CONFIG_BT_DEBUG_HFP_AG 0
// #define CONFIG_BT_DEBUG_LOG 0
// #define CONFIG_BT_DEBUG_HCI_DRIVER 0
// #define CONFIG_BT_DEBUG_RPA 0
// #define CONFIG_BT_DEBUG_AICS 0
// #define CONFIG_BT_DEBUG_AICS_CLIENT 0
// #define CONFIG_BT_BAP_DEBUG_STREAM 0
// #define CONFIG_BT_DEBUG_ASCS 0
// #define CONFIG_BT_DEBUG_BAP_UNICAST_SERVER 0
// #define CONFIG_BT_DEBUG_CSIP_SET_MEMBER 0
// #define CONFIG_BT_DEBUG_CSIP_SET_COORDINATOR 0
// #define CONFIG_BT_DEBUG_HAS 0
// #define CONFIG_BT_DEBUG_MCS 0
// #define CONFIG_BT_DEBUG_MCC 0
// #define CONFIG_MCTL_DEBUG 0
// #define CONFIG_BT_DEBUG_MICP_MIC_DEV 0
// #define CONFIG_BT_DEBUG_MICP_MIC_CTLR 0
// #define CONFIG_BT_MPL_LOG_LEVEL_DBG 0
// #define CONFIG_BT_DEBUG_PACS 0
// #define CONFIG_BT_DEBUG_TBS 0
// #define CONFIG_BT_DEBUG_TBS_CLIENT 0
// #define CONFIG_BT_DEBUG_VCP_VOL_REND 0
// #define CONFIG_BT_DEBUG_VCP_VOL_CTLR 0
// #define CONFIG_BT_DEBUG_VOCS 0
// #define CONFIG_BT_DEBUG_VOCS_CLIENT 0
// #define CONFIG_BT_DEBUG_ATT 0
// #define CONFIG_BT_DEBUG_GATT 0
// #define CONFIG_BT_DEBUG_L2CAP 0
// #define CONFIG_BT_DEBUG_DF 0
// #define CONFIG_BT_DEBUG_HCI_CORE 0
// #define CONFIG_BT_DEBUG_CONN 0
// #define CONFIG_BT_DEBUG_ISO 0
// #define CONFIG_BT_DEBUG_KEYS 0
// #define CONFIG_BT_DEBUG_SMP 0
// #define CONFIG_BT_DEBUG_SERVICE 0
// #define CONFIG_BT_MESH_DEBUG 0
// #define CONFIG_BT_MESH_DEBUG_NET 0
// #define CONFIG_BT_MESH_DEBUG_RPL 0
// #define CONFIG_BT_MESH_DEBUG_TRANS 0
// #define CONFIG_BT_MESH_DEBUG_BEACON 0
// #define CONFIG_BT_MESH_DEBUG_CRYPTO 0
// #define CONFIG_BT_MESH_DEBUG_KEYS 0
// #define CONFIG_BT_MESH_DEBUG_PROV 0
// #define CONFIG_BT_MESH_DEBUG_PROVISIONER 0
// #define CONFIG_BT_MESH_DEBUG_PROV_DEVICE 0
// #define CONFIG_BT_MESH_DEBUG_ACCESS 0
// #define CONFIG_BT_MESH_DEBUG_MODEL 0
// #define CONFIG_BT_MESH_DEBUG_ADV 0
// #define CONFIG_BT_MESH_DEBUG_LOW_POWER 0
// #define CONFIG_BT_MESH_DEBUG_FRIEND 0
// #define CONFIG_BT_MESH_DEBUG_PROXY 0
// #define CONFIG_BT_MESH_DEBUG_SETTINGS 0
// #define CONFIG_BT_MESH_DEBUG_CFG 0
// #define CONFIG_BT_DEBUG_OTS_CLIENT 0

#endif /* _EDGEFAST_BLUETOOTH_DEBUG_CONFIG_GEN_H_ */
