ISSDK: driverexamples/demos/FRDM-KL25Z/mpl3115_demo.c File Reference
mpl3115_demo.c File Reference
#include "board.h"
#include "pin_mux.h"
#include "fsl_lpsci.h"
#include "clock_config.h"
#include "Driver_I2C.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_lpsci_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "mpl3115_drv.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define MPL3115_SAMPLING_EXPONENT 1 /* 2 seconds */
#define MPL3115_DATA_SIZE 5 /* 3 byte Pressure and 2 byte Temperature. */
#define MPL3115_STREAM_DATA_SIZE 10 /* 6 byte Data */
#define APPLICATION_NAME "MPL3115A2"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Functions
void mpl3115_int_data_ready_callback (void *pUserData)
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerwritelist_t cMpl3115ConfigNormal []
Register settings for Interrupt (non buffered) mode.
const registerreadlist_t cMpl3115OutputNormal []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bMpl3115DataReady = false
volatile bool bMpl3115Ready = false
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Macro Definition Documentation
#define APPLICATION_NAME "MPL3115A2"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 74 of file mpl3115_demo.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 76 of file mpl3115_demo.c.
Referenced by main().
#define MPL3115_DATA_SIZE 5 /* 3 byte Pressure and 2 byte Temperature. */
Definition at line 70 of file mpl3115_demo.c.
Referenced by main().
#define MPL3115_SAMPLING_EXPONENT 1 /* 2 seconds */
In MPL3115 the Auto Acquisition Time Step (ODR) can be set only in powers of 2 (i.e. 2^x, where x is the SAMPLING_EXPONENT). This gives a range of 1 second to 2^15 seconds (9 hours).
Definition at line 69 of file mpl3115_demo.c.
#define MPL3115_STREAM_DATA_SIZE 10 /* 6 byte Data */
Definition at line 71 of file mpl3115_demo.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize INT1 MPL3115 pin used by FRDM board
Initialize GREEN LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize the MPL3115 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MPL3115 sensor driver.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Clear the data ready flag, it will be set again by the ISR.
Read raw sensor data from the MPL3115.
Convert the raw sensor data to signed 32-bit and 16-bit containers for display to the debug port.
Definition at line 204 of file mpl3115_demo.c.
References ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bMpl3115DataReady, bMpl3115Ready, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, mpl3115_i2c_sensorhandle_t::deviceInfo, embAppName, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, GREEN_LED, gStreamID, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MPL3115_DATA_SIZE, MPL3115_I2C_ADDR, MPL3115_I2C_Configure(), MPL3115_I2C_Initialize(), MPL3115_I2C_ReadData(), MPL3115_I2C_SetIdleTask(), MPL3115_INT1, mpl3115_int_data_ready_callback(), MPL3115_STREAM_DATA_SIZE, MPL3115_WHOAMI_VALUE, mpl3115_i2c_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, mpl3115_pressuredata_t::pressure, process_host_command(), SENSOR_ERROR_NONE, SHIELD_NAME, shieldString, SMC, SMC_SetPowerModeWait(), STREAMING_HEADER_LEN, mpl3115_pressuredata_t::temperature, mpl3115_pressuredata_t::timestamp, and GENERIC_DRIVER_GPIO::toggle_pin.
void mpl3115_int_data_ready_callback (void * pUserData)
Set flag to indicate Sensor has signalled data ready.
Definition at line 116 of file mpl3115_demo.c.
References bMpl3115DataReady.
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 122 of file mpl3115_demo.c.
References bMpl3115Ready, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, GREEN_LED, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, and shieldString.
Variable Documentation
volatile bool bMpl3115DataReady = false
Definition at line 108 of file mpl3115_demo.c.
volatile bool bMpl3115Ready = false
Definition at line 108 of file mpl3115_demo.c.
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 106 of file mpl3115_demo.c.
volatile bool bStreamingEnabled = false
Definition at line 108 of file mpl3115_demo.c.
const registerwritelist_t cMpl3115ConfigNormal[]
Initial value:
= {
    {MPL3115_PT_DATA_CFG,
     MPL3115_PT_DATA_CFG_TDEFE_ENABLED | MPL3115_PT_DATA_CFG_PDEFE_ENABLED | MPL3115_PT_DATA_CFG_DREM_ENABLED,
     MPL3115_PT_DATA_CFG_TDEFE_MASK | MPL3115_PT_DATA_CFG_PDEFE_MASK | MPL3115_PT_DATA_CFG_DREM_MASK},
    {MPL3115_CTRL_REG1, MPL3115_CTRL_REG1_OS_OSR_128, MPL3115_CTRL_REG1_OS_MASK},
    {MPL3115_CTRL_REG2, MPL3115_SAMPLING_EXPONENT, MPL3115_CTRL_REG2_ST_MASK},
    {MPL3115_CTRL_REG3, MPL3115_CTRL_REG3_IPOL1_HIGH, MPL3115_CTRL_REG3_IPOL1_MASK},
    {MPL3115_CTRL_REG4, MPL3115_CTRL_REG4_INT_EN_DRDY_INTENABLED, MPL3115_CTRL_REG4_INT_EN_DRDY_MASK},
    {MPL3115_CTRL_REG5, MPL3115_CTRL_REG5_INT_CFG_DRDY_INT1, MPL3115_CTRL_REG5_INT_CFG_DRDY_MASK},
    __END_WRITE_DATA__}
Register settings for Interrupt (non buffered) mode.
Definition at line 82 of file mpl3115_demo.c.
const registerreadlist_t cMpl3115OutputNormal[]
Initial value:
= {{.readFrom = MPL3115_OUT_P_MSB, .numBytes = MPL3115_DATA_SIZE},
                                                   __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 100 of file mpl3115_demo.c.
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 107 of file mpl3115_demo.c.
uint8_t gStreamID
Definition at line 109 of file mpl3115_demo.c.
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 110 of file mpl3115_demo.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 106 of file mpl3115_demo.c.