ISSDK: driverexamples/demos/FRDM-K64F/mag3110_demo.c File Reference
mag3110_demo.c File Reference
#include "board.h"
#include "pin_mux.h"
#include "fsl_uart.h"
#include "clock_config.h"
#include "Driver_I2C.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_uart_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "mag3110_drv.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define MAG3110_DATA_SIZE 6 /* 2 byte X,Y,Z Axis Data each. */
#define MAG3110_STREAM_DATA_SIZE 10 /* 6 byte Data */
#define APPLICATION_NAME "MAG3110"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Functions
void mag3110_int_data_ready_callback (void *pUserData)
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerwritelist_t cMag3110ConfigNormal []
Register settings for Normal (non buffered) mode since Interrupt is enabled implicitly.
const registerreadlist_t cMag3110OutputNormal []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bMag3110DataReady = false
volatile bool bMag3110Ready = false
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Macro Definition Documentation
#define APPLICATION_NAME "MAG3110"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 70 of file mag3110_demo.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 72 of file mag3110_demo.c.
Referenced by main().
#define MAG3110_DATA_SIZE 6 /* 2 byte X,Y,Z Axis Data each. */
Definition at line 66 of file mag3110_demo.c.
Referenced by main().
#define MAG3110_STREAM_DATA_SIZE 10 /* 6 byte Data */
Definition at line 67 of file mag3110_demo.c.
Referenced by main().
Function Documentation
void mag3110_int_data_ready_callback (void * pUserData)
Set flag to indicate Sensor has signalled data ready.
Definition at line 103 of file mag3110_demo.c.
References bMag3110DataReady.
int main (void)
Main function.
Initialize the MCU hardware.
Initialize INT1 MAG3110 pin used by FRDM board
Initialize GREEN LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize the MAG3110 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MAG3110 sensor driver.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Clear the data ready flag, it will be set again by the ISR.
Read raw sensor data from the MAG3110.
Convert the raw sensor data to signed 32-bit and 16-bit containers for display to the debug port.
Definition at line 191 of file mag3110_demo.c.
References ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bMag3110DataReady, bMag3110Ready, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, mag3110_i2c_sensorhandle_t::deviceInfo, embAppName, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, GREEN_LED, gStreamID, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), mag3110_magdata_t::mag, MAG3110_DATA_SIZE, MAG3110_I2C_ADDR, MAG3110_I2C_Configure(), MAG3110_I2C_Initialize(), MAG3110_I2C_ReadData(), MAG3110_I2C_SetIdleTask(), MAG3110_INT1, mag3110_int_data_ready_callback(), MAG3110_STREAM_DATA_SIZE, MAG3110_WHOAMI_VALUE, mag3110_i2c_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, process_host_command(), SENSOR_ERROR_NONE, SHIELD_NAME, shieldString, SMC, SMC_SetPowerModeWait(), STREAMING_HEADER_LEN, mag3110_magdata_t::timestamp, and GENERIC_DRIVER_GPIO::toggle_pin.
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 109 of file mag3110_demo.c.
References bMag3110Ready, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, GREEN_LED, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, and shieldString.
Variable Documentation
volatile bool bMag3110DataReady = false
Definition at line 95 of file mag3110_demo.c.
volatile bool bMag3110Ready = false
Definition at line 95 of file mag3110_demo.c.
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 93 of file mag3110_demo.c.
volatile bool bStreamingEnabled = false
Definition at line 95 of file mag3110_demo.c.
const registerwritelist_t cMag3110ConfigNormal[]
Initial value:
= {
    {MAG3110_CTRL_REG1, MAG3110_CTRL_REG1_DR_ODR_2 | MAG3110_CTRL_REG1_OS_OSR_32,
     MAG3110_CTRL_REG1_DR_MASK | MAG3110_CTRL_REG1_OS_MASK},
    {MAG3110_CTRL_REG2, MAG3110_CTRL_REG2_AUTO_MSRT_EN_EN, MAG3110_CTRL_REG2_AUTO_MSRT_EN_MASK},
    __END_WRITE_DATA__}
Register settings for Normal (non buffered) mode since Interrupt is enabled implicitly.
Definition at line 78 of file mag3110_demo.c.
const registerreadlist_t cMag3110OutputNormal[]
Initial value:
= {{.readFrom = MAG3110_OUT_X_MSB, .numBytes = MAG3110_DATA_SIZE},
                                                   __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 87 of file mag3110_demo.c.
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 94 of file mag3110_demo.c.
uint8_t gStreamID
Definition at line 96 of file mag3110_demo.c.
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 97 of file mag3110_demo.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 93 of file mag3110_demo.c.