ISSDK: driverexamples/demos/FRDM-K64F/fxos8700_demo.c File Reference
fxos8700_demo.c File Reference
#include "board.h"
#include "pin_mux.h"
#include "fsl_uart.h"
#include "clock_config.h"
#include "Driver_I2C.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_uart_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "fxos8700_drv.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define RAW_ACCEL_MAG_DATA_SIZE 12
#define FXOS8700_STREAM_DATA_SIZE 16
#define APPLICATION_NAME "FXOS8700CQ"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Functions
void fxos8700_isr_callback (void *pUserData)
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerwritelist_t fxos8700_Config_InterruptHybrid []
const registerreadlist_t FXOS8700_ACCEL_READ []
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bFxos8700DataReady = false
volatile bool bFxos8700Ready = false
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Macro Definition Documentation
#define APPLICATION_NAME "FXOS8700CQ"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 70 of file fxos8700_demo.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 72 of file fxos8700_demo.c.
Referenced by main().
#define FXOS8700_STREAM_DATA_SIZE 16
Definition at line 67 of file fxos8700_demo.c.
Referenced by main().
#define RAW_ACCEL_MAG_DATA_SIZE 12
Definition at line 66 of file fxos8700_demo.c.
Referenced by main().
Function Documentation
void fxos8700_isr_callback (void * pUserData)
Set flag to indicate Sensor has signalled data ready.
Definition at line 110 of file fxos8700_demo.c.
References bFxos8700DataReady.
int main (void)
Main function.
Initialize the MCU hardware.
Initialize INT1_FXAS21002 pin used by FRDM board
Initialize RGB LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize the FXOS8700 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the fxos8700 sensor driver.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Clear the data ready flag, it will be set again by the ISR.
Read the raw sensor data from the fxos8700.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 198 of file fxos8700_demo.c.
References fxos8700_accelmagdata_t::accel, ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bFxos8700DataReady, bFxos8700Ready, BLUE_LED, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, fxos8700_i2c_sensorhandle_t::deviceInfo, embAppName, FXOS8700_I2C_ADDR, FXOS8700_I2C_Configure(), FXOS8700_I2C_Initialize(), FXOS8700_I2C_ReadData(), FXOS8700_I2C_SetIdleTask(), FXOS8700_INT2, fxos8700_isr_callback(), FXOS8700_STREAM_DATA_SIZE, FXOS8700_WHO_AM_I_PROD_VALUE, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, gStreamID, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), fxos8700_accelmagdata_t::mag, fxos8700_i2c_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, process_host_command(), RAW_ACCEL_MAG_DATA_SIZE, SENSOR_ERROR_NONE, SHIELD_NAME, shieldString, SMC, SMC_SetPowerModeWait(), STREAMING_HEADER_LEN, fxos8700_accelmagdata_t::timestamp, and GENERIC_DRIVER_GPIO::toggle_pin.
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 116 of file fxos8700_demo.c.
References bFxos8700Ready, BLUE_LED, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, and shieldString.
Variable Documentation
volatile bool bFxos8700DataReady = false
Definition at line 102 of file fxos8700_demo.c.
volatile bool bFxos8700Ready = false
Definition at line 102 of file fxos8700_demo.c.
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 100 of file fxos8700_demo.c.
volatile bool bStreamingEnabled = false
Definition at line 102 of file fxos8700_demo.c.
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 101 of file fxos8700_demo.c.
const registerreadlist_t FXOS8700_ACCEL_READ[]
Initial value:
= {{.readFrom = FXOS8700_OUT_X_MSB, .numBytes = RAW_ACCEL_MAG_DATA_SIZE},
                                                  __END_READ_DATA__}
Command definition to read the Accel+Mag Data
Definition at line 94 of file fxos8700_demo.c.
const registerwritelist_t fxos8700_Config_InterruptHybrid[]
Initial value:
= {
    {FXOS8700_CTRL_REG1, FXOS8700_CTRL_REG1_DR_HYBRID_25_HZ, FXOS8700_CTRL_REG1_DR_MASK},
    {FXOS8700_CTRL_REG3, FXOS8700_CTRL_REG3_IPOL_ACTIVE_HIGH | FXOS8700_CTRL_REG3_PP_OD_PUSH_PULL,
     FXOS8700_CTRL_REG3_IPOL_MASK | FXOS8700_CTRL_REG3_PP_OD_MASK},
    {FXOS8700_CTRL_REG4, FXOS8700_CTRL_REG4_INT_EN_DRDY_EN,
     FXOS8700_CTRL_REG4_INT_EN_DRDY_MASK},
    {FXOS8700_CTRL_REG5, FXOS8700_CTRL_REG5_INT_CFG_DRDY_INT2, FXOS8700_CTRL_REG5_INT_CFG_DRDY_MASK},
    {FXOS8700_M_CTRL_REG1, FXOS8700_M_CTRL_REG1_M_HMS_HYBRID_MODE,
     FXOS8700_M_CTRL_REG1_M_HMS_MASK},
    {FXOS8700_M_CTRL_REG2, FXOS8700_M_CTRL_REG2_M_AUTOINC_HYBRID_MODE,
     FXOS8700_M_CTRL_REG2_M_AUTOINC_MASK},
    __END_WRITE_DATA__}
Prepare the register write list to configure FXAS21002 in non-FIFO mode.
Definition at line 78 of file fxos8700_demo.c.
uint8_t gStreamID
Definition at line 103 of file fxos8700_demo.c.
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 104 of file fxos8700_demo.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 100 of file fxos8700_demo.c.