ISSDK: driverexamples/demos/LPC-54114/fxls8962_demo.c File Reference
fxls8962_demo.c File Reference
#include "board.h"
#include "pin_mux.h"
#include "fsl_uart.h"
#include "clock_config.h"
#include "Driver_SPI.h"
#include "Driver_USART.h"
#include "fsl_uart_cmsis.h"
#include "fsl_spi_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "fxls8962_drv.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define FXLS8962_DATA_SIZE 6
#define FXLS8962_STREAM_DATA_SIZE 10
#define APPLICATION_NAME "FXLS8962AF"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Functions
void fxls8962_int_data_ready_callback (void *pUserData)
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerwritelist_t cFxls8962ConfigNormal []
Register settings for Interrupt (non buffered) mode.
const registerreadlist_t cFxls8962OutputNormal []
Address of Raw Accel Data in Normal Mode.
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bFxls8962DataReady = false
volatile bool bFxls8962Ready = false
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Macro Definition Documentation
#define APPLICATION_NAME "FXLS8962AF"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 74 of file fxls8962_demo.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 76 of file fxls8962_demo.c.
Referenced by main().
#define FXLS8962_DATA_SIZE 6
Definition at line 70 of file fxls8962_demo.c.
Referenced by main().
#define FXLS8962_STREAM_DATA_SIZE 10
Definition at line 71 of file fxls8962_demo.c.
Referenced by main().
Function Documentation
void fxls8962_int_data_ready_callback (void * pUserData)
Set flag to indicate Sensor has signalled data ready.
Definition at line 108 of file fxls8962_demo.c.
References bFxls8962DataReady.
int main (void)
Main function.
Initialize the MCU hardware.
Initialize FXLS8962 pin used by FRDM board
Initialize RGB LED pin used by FRDM board
Initialize the SPI driver.
Set the SPI Power mode.
Set the SPI Slave speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize FXLS8962 sensor driver.
Set the task to be executed while waiting for SPI transactions to complete.
Configure the FXLS8962 sensor.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Clear the data ready flag, it will be set again by the ISR.
Read new raw sensor data from the FXLS8962.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 196 of file fxls8962_demo.c.
References fxls8962_acceldata_t::accel, ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bFxls8962DataReady, bFxls8962Ready, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, fxls8962_spi_sensorhandle_t::deviceInfo, embAppName, FXLS8962_CS, FXLS8962_DATA_SIZE, FXLS8962_I2C_ADDR, FXLS8962_INT1, fxls8962_int_data_ready_callback(), FXLS8962_SPI_Configure(), FXLS8962_SPI_Initialize(), FXLS8962_SPI_ReadData(), FXLS8962_SPI_SetIdleTask(), FXLS8962_STREAM_DATA_SIZE, FXLS8962_WHOAMI_VALUE, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, gStreamID, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, int32_t(), fxls8962_spi_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, process_host_command(), RED_LED, SENSOR_ERROR_NONE, SHIELD_NAME, shieldString, fxls8962_spi_sensorhandle_t::slaveParams, SMC, SMC_SetPowerModeWait(), SPI_S_BAUDRATE, SPI_S_DEVICE_INDEX, SPI_S_DRIVER, SPI_S_SIGNAL_EVENT, STREAMING_HEADER_LEN, fxls8962_acceldata_t::timestamp, and GENERIC_DRIVER_GPIO::toggle_pin.
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 114 of file fxls8962_demo.c.
References bFxls8962Ready, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, RED_LED, and shieldString.
Variable Documentation
volatile bool bFxls8962DataReady = false
Definition at line 100 of file fxls8962_demo.c.
volatile bool bFxls8962Ready = false
Definition at line 100 of file fxls8962_demo.c.
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 98 of file fxls8962_demo.c.
volatile bool bStreamingEnabled = false
Definition at line 100 of file fxls8962_demo.c.
const registerwritelist_t cFxls8962ConfigNormal[]
Initial value:
= {
    {FXLS8962_SENS_CONFIG1, FXLS8962_SENS_CONFIG1_FSR_2G, FXLS8962_SENS_CONFIG1_FSR_MASK},
    {FXLS8962_SENS_CONFIG3, FXLS8962_SENS_CONFIG3_WAKE_ODR_6_25HZ, FXLS8962_SENS_CONFIG3_WAKE_ODR_MASK},
    {FXLS8962_INT_EN, FXLS8962_INT_EN_DRDY_EN_EN, FXLS8962_INT_EN_DRDY_EN_MASK},
    __END_WRITE_DATA__}
Register settings for Interrupt (non buffered) mode.
Definition at line 82 of file fxls8962_demo.c.
const registerreadlist_t cFxls8962OutputNormal[]
Initial value:
= {{.readFrom = FXLS8962_OUT_X_LSB, .numBytes = FXLS8962_DATA_SIZE},
                                                    __END_READ_DATA__}
Address of Raw Accel Data in Normal Mode.
Definition at line 92 of file fxls8962_demo.c.
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 99 of file fxls8962_demo.c.
uint8_t gStreamID
Definition at line 101 of file fxls8962_demo.c.
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 102 of file fxls8962_demo.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 98 of file fxls8962_demo.c.