ISSDK: driverexamples/demos/ads_demo.c File Reference
ads_demo.c File Reference
The ads_demo.c file implements the ISSDK ADS Demo.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Functions
int main (void)
Main function.
Detailed Description
The ads_demo.c file implements the ISSDK ADS Demo.
Definition in file ads_demo.c.
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Definition at line 52 of file ads_demo.c.
References ADS_MAX_STRING_LENGTH, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_RunADS(), BOARD_SystickEnable(), boardString, embAppName, and shieldString.