ISSDK: algorithms/sensorfusion/sources/calibration_storage.h File Reference
calibration_storage.h File Reference
Provides functions to store calibration to NVM.
Functions
void SaveMagCalibrationToNVM (SensorFusionGlobals *sfg)
void SaveGyroCalibrationToNVM (SensorFusionGlobals *sfg)
void SaveAccelCalibrationToNVM (SensorFusionGlobals *sfg)
void EraseMagCalibrationFromNVM (void)
void EraseGyroCalibrationFromNVM (void)
void EraseAccelCalibrationFromNVM (void)
Detailed Description
Provides functions to store calibration to NVM.
Users who are not using NXP hardware will need to supply their own drivers in place of those defined here.
Definition in file calibration_storage.h.
Function Documentation
void EraseAccelCalibrationFromNVM (void)
Definition at line 192 of file calibration_storage.c.
References ACCEL_NVM_OFFSET, CALIBRATION_NVM_ADDR, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
void EraseGyroCalibrationFromNVM (void)
Definition at line 171 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, GYRO_NVM_OFFSET, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
void EraseMagCalibrationFromNVM (void)
Definition at line 150 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, MAG_NVM_OFFSET, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
void SaveAccelCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 116 of file calibration_storage.c.
References ACCEL_NVM_OFFSET, CALIBRATION_NVM_ADDR, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
void SaveGyroCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 77 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, F_6DOF_GY_KALMAN, GYRO_NVM_OFFSET, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().
void SaveMagCalibrationToNVM (SensorFusionGlobals * sfg)
Definition at line 43 of file calibration_storage.c.
References CALIBRATION_NVM_ADDR, MAG_NVM_OFFSET, SensorFusionGlobals::MagCal, and NVM_SetBlockFlash().
Referenced by DecodeCommandBytes().