ISSDK: driverexamples/demos/FRDM-K22F/demo_11axis.c File Reference
demo_11axis.c File Reference
The demo_11axis.c file implements the ISSDK FXLS8962, MAG3110, FXAS21002 and MPL3115 sensors 12-Axis demo example demonstration for FRDM-K22F.
#include "board.h"
#include "pin_mux.h"
#include "fsl_uart.h"
#include "clock_config.h"
#include "Driver_I2C.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_uart_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "mag3110_drv.h"
#include "mpl3115_drv.h"
#include "fxls8962_drv.h"
#include "fxas21002_drv.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define MPL3115_PADDING_SIZE (1)
#define MPL3115_PRESSURE_DATA_SIZE (3)
#define MPL3115_TEMPERATURE_DATA_SIZE (2)
#define STREAMING_PKT_TIMESTAMP_LEN (4)
#define FXLS8962_DATA_SIZE (6)
#define MAG3110_DATA_SIZE (6)
#define FXAS21002_DATA_SIZE (FXAS21002_GYRO_DATA_SIZE)
#define MPL3115_DATA_SIZE (MPL3115_PRESSURE_DATA_SIZE + MPL3115_TEMPERATURE_DATA_SIZE)
#define STREAMING_PAYLOAD_LEN
#define APPLICATION_NAME "11_AXIS_DEMO"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
#define SDCD_WT_DBCNT 0x0A /* Debounce count value. */
#define SDCD_LTHS_LSB 0x33 /* Lower Threshold LSB value. */
#define SDCD_LTHS_MSB 0x0F /* Lower Threshold MSB value. */
#define SDCD_UTHS_LSB 0xCD /* Upper Threshold LSB value. */
#define SDCD_UTHS_MSB 0x00 /* Upper Threshold MSB value. */
#define SDCD_FF_EVT_ID (0x01)
#define EVENT_PAYLOAD_LEN (1)
Functions
void fxas21002_int_data_ready_callback (void *pUserData)
void fxls8962_int_event_ready_callback (void *pUserData)
This is the Sensor WT Event Ready ISR implementation.
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerwritelist_t cFxls8962ConfigINT []
Register settings for FreeFall detection and Data Interrupt (non buffered) mode.
const registerreadlist_t cFxls8962OutputNormal []
Address of Raw Accel Data in Normal Mode.
const registerreadlist_t cFxls8962FreeFallEvent []
Address of Free-Fall Status Register.
const registerwritelist_t cMag3110ConfigNormal []
Register settings for Normal (non buffered) mode.
const registerreadlist_t cMag3110OutputNormal []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
const registerwritelist_t fxas21002_Config_Normal []
const registerreadlist_t fxas21002_Output_Values []
const registerwritelist_t cMpl3115SetOST []
Register settings for Triggring One-Shot Sampling.
const registerreadlist_t mpl3115_Output_Values []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bFxas21002DataReady = false
volatile bool bFxls8962EventReady = false
volatile bool bAgmp03Ready = false
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Detailed Description
The demo_11axis.c file implements the ISSDK FXLS8962, MAG3110, FXAS21002 and MPL3115 sensors 12-Axis demo example demonstration for FRDM-K22F.
Definition in file demo_11axis.c.
Macro Definition Documentation
#define APPLICATION_NAME "11_AXIS_DEMO"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 84 of file demo_11axis.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 86 of file demo_11axis.c.
Referenced by main().
#define EVENT_PAYLOAD_LEN (1)
Definition at line 98 of file demo_11axis.c.
Referenced by main().
#define FXAS21002_DATA_SIZE (FXAS21002_GYRO_DATA_SIZE)
Definition at line 76 of file demo_11axis.c.
Referenced by main().
#define FXLS8962_DATA_SIZE (6)
Definition at line 74 of file demo_11axis.c.
Referenced by main().
#define MAG3110_DATA_SIZE (6)
Definition at line 75 of file demo_11axis.c.
Referenced by main().
#define MPL3115_DATA_SIZE (MPL3115_PRESSURE_DATA_SIZE + MPL3115_TEMPERATURE_DATA_SIZE)
Definition at line 77 of file demo_11axis.c.
Referenced by main().
#define MPL3115_PADDING_SIZE (1)
Definition at line 69 of file demo_11axis.c.
Referenced by main().
#define MPL3115_PRESSURE_DATA_SIZE (3)
Definition at line 70 of file demo_11axis.c.
Referenced by main().
#define MPL3115_TEMPERATURE_DATA_SIZE (2)
Definition at line 71 of file demo_11axis.c.
#define SDCD_FF_EVT_ID (0x01)
Definition at line 97 of file demo_11axis.c.
Referenced by main().
#define SDCD_LTHS_LSB 0x33 /* Lower Threshold LSB value. */
Definition at line 92 of file demo_11axis.c.
#define SDCD_LTHS_MSB 0x0F /* Lower Threshold MSB value. */
Definition at line 93 of file demo_11axis.c.
#define SDCD_UTHS_LSB 0xCD /* Upper Threshold LSB value. */
Definition at line 94 of file demo_11axis.c.
#define SDCD_UTHS_MSB 0x00 /* Upper Threshold MSB value. */
Definition at line 95 of file demo_11axis.c.
#define SDCD_WT_DBCNT 0x0A /* Debounce count value. */
Definition at line 91 of file demo_11axis.c.
#define STREAMING_PAYLOAD_LEN
Value:
(STREAMING_PKT_TIMESTAMP_LEN + FXLS8962_DATA_SIZE + MAG3110_DATA_SIZE + FXAS21002_DATA_SIZE + MPL3115_DATA_SIZE + \
     MPL3115_PADDING_SIZE)
Definition at line 79 of file demo_11axis.c.
Referenced by main().
#define STREAMING_PKT_TIMESTAMP_LEN (4)
Definition at line 73 of file demo_11axis.c.
Referenced by main().
Function Documentation
void fxas21002_int_data_ready_callback (void * pUserData)
Set flag to indicate Sensor has signalled data ready.
Definition at line 193 of file demo_11axis.c.
References bFxas21002DataReady.
Referenced by main().
void fxls8962_int_event_ready_callback (void * pUserData)
This is the Sensor WT Event Ready ISR implementation.
Set flag to indicate Sensor has signalled event ready.
Definition at line 199 of file demo_11axis.c.
References bFxls8962EventReady.
Referenced by main().
int main (void)
Main function.
Initialize the MCU hardware.
Initialize FXAS21002 INT1 pin used by FRDM board
Initialize FXLS8962 INT2 pin used by FRDM board
Initialize RGB LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize FXLS8962 sensor driver.
Initialize MAG3110 sensor driver.
Initialize the FXAS21002 sensor driver.
Initialize the MPL3115 sensor driver.
Set the task to be executed while waiting for SPI transactions to complete.
Configure the FXLS8962 sensor.
Configure the MAG3110 sensor driver.
Configure the FXAS21002 sensor driver.
In One-Shot Mode we do not need to Configure MPL3115, instead we will set OST bit directly.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Populate event header and freefall event ID.
Read the Freefall event FLAGs from FXLS8962 to clear INT2.
Clear the data ready flag, it will be set again by the ISR.
Read new raw sensor data from the FXLS8962.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Read raw sensor data from the MAG3110.
Convert the raw sensor data to signed 32-bit and 16-bit containers for display to the debug port.
Read the raw sensor data from the FXAS21002.
Read raw sensor data from the MPL3115.
Definition at line 287 of file demo_11axis.c.
References fxls8962_acceldata_t::accel, ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bAgmp03Ready, bFxas21002DataReady, bFxls8962EventReady, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, mag3110_i2c_sensorhandle_t::deviceInfo, mpl3115_i2c_sensorhandle_t::deviceInfo, fxls8962_i2c_sensorhandle_t::deviceInfo, fxas21002_i2c_sensorhandle_t::deviceInfo, embAppName, EVENT_PAYLOAD_LEN, EVENT_STREAM_ID, FXAS21002_DATA_SIZE, FXAS21002_I2C_ADDR, FXAS21002_I2C_Configure(), FXAS21002_I2C_Initialize(), FXAS21002_I2C_ReadData(), FXAS21002_I2C_SetIdleTask(), FXAS21002_INT1, fxas21002_int_data_ready_callback(), FXAS21002_WHO_AM_I_WHOAMI_PROD_VALUE, FXLS8962_DATA_SIZE, FXLS8962_I2C_ADDR, FXLS8962_I2C_Configure(), FXLS8962_I2C_Initialize(), FXLS8962_I2C_ReadData(), FXLS8962_I2C_SetIdleTask(), FXLS8962_INT2, fxls8962_int_event_ready_callback(), FXLS8962_SDCD_INT_SRC2_WT_EA_EVENT_YES, FXLS8962_SDCD_INT_SRC2_WT_EA_MASK, FXLS8962_WHOAMI_VALUE, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, gStreamID, fxas21002_gyrodata_t::gyro, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), mag3110_magdata_t::mag, MAG3110_DATA_SIZE, MAG3110_I2C_ADDR, MAG3110_I2C_Configure(), MAG3110_I2C_Initialize(), MAG3110_I2C_ReadData(), MAG3110_I2C_SetIdleTask(), MAG3110_WHOAMI_VALUE, MPL3115_DATA_SIZE, MPL3115_I2C_ADDR, MPL3115_I2C_Initialize(), MPL3115_I2C_ReadData(), MPL3115_I2C_SetIdleTask(), MPL3115_PADDING_SIZE, MPL3115_PRESSURE_DATA_SIZE, MPL3115_WHOAMI_VALUE, mag3110_i2c_sensorhandle_t::pCommDrv, mpl3115_i2c_sensorhandle_t::pCommDrv, fxls8962_i2c_sensorhandle_t::pCommDrv, fxas21002_i2c_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, mpl3115_pressuredata_t::pressure, process_host_command(), RED_LED, SDCD_FF_EVT_ID, SENSOR_ERROR_NONE, Sensor_I2C_Write(), SHIELD_NAME, shieldString, mpl3115_i2c_sensorhandle_t::slaveAddress, SMC, SMC_SetPowerModeWait(), STREAMING_HEADER_LEN, STREAMING_PAYLOAD_LEN, STREAMING_PKT_TIMESTAMP_LEN, mpl3115_pressuredata_t::temperature, and GENERIC_DRIVER_GPIO::toggle_pin.
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 205 of file demo_11axis.c.
References bAgmp03Ready, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, RED_LED, and shieldString.
Referenced by Host_IO_Receive(), and main().
Variable Documentation
volatile bool bAgmp03Ready = false
Definition at line 185 of file demo_11axis.c.
Referenced by main(), and process_host_command().
volatile bool bFxas21002DataReady = false
Definition at line 185 of file demo_11axis.c.
Referenced by fxas21002_int_data_ready_callback(), and main().
volatile bool bFxls8962EventReady = false
Definition at line 185 of file demo_11axis.c.
Referenced by fxls8962_int_event_ready_callback(), and main().
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 183 of file demo_11axis.c.
Referenced by main(), and process_host_command().
volatile bool bStreamingEnabled = false
Definition at line 185 of file demo_11axis.c.
Referenced by main(), and process_host_command().
const registerwritelist_t cFxls8962ConfigINT[]
Initial value:
= {
    {FXLS8962_SENS_CONFIG1, FXLS8962_SENS_CONFIG1_FSR_2G, FXLS8962_SENS_CONFIG1_FSR_MASK},
    {FXLS8962_SENS_CONFIG3, FXLS8962_SENS_CONFIG3_WAKE_ODR_100HZ, FXLS8962_SENS_CONFIG3_WAKE_ODR_MASK},
    {FXLS8962_SDCD_CONFIG1, FXLS8962_SDCD_CONFIG1_WT_ELE_EN | FXLS8962_SDCD_CONFIG1_X_WT_EN_EN |
                                FXLS8962_SDCD_CONFIG1_Y_WT_EN_EN | FXLS8962_SDCD_CONFIG1_Z_WT_EN_EN,
    FXLS8962_SDCD_CONFIG1_WT_ELE_MASK | FXLS8962_SDCD_CONFIG1_X_WT_EN_MASK | FXLS8962_SDCD_CONFIG1_Y_WT_EN_MASK |
    FXLS8962_SDCD_CONFIG1_Z_WT_EN_MASK},
    {FXLS8962_SDCD_CONFIG2, FXLS8962_SDCD_CONFIG2_SDCD_EN_EN | FXLS8962_SDCD_CONFIG2_REF_UPDM_FIXED_VAL |
                            FXLS8962_SDCD_CONFIG2_WT_DBCTM_CLEARED,
     FXLS8962_SDCD_CONFIG2_SDCD_EN_MASK | FXLS8962_SDCD_CONFIG2_REF_UPDM_MASK | FXLS8962_SDCD_CONFIG2_WT_DBCTM_MASK},
    {FXLS8962_INT_EN, FXLS8962_INT_EN_SDCD_WT_EN_EN, FXLS8962_INT_EN_SDCD_WT_EN_MASK},
    {FXLS8962_INT_PIN_SEL, FXLS8962_INT_PIN_SEL_SDCD_WT_INT2_EN, FXLS8962_INT_PIN_SEL_SDCD_WT_INT2_MASK},
    {FXLS8962_SDCD_WT_DBCNT, SDCD_WT_DBCNT, 0},
    {FXLS8962_SDCD_LTHS_LSB, SDCD_LTHS_LSB, 0},
    {FXLS8962_SDCD_LTHS_MSB, SDCD_LTHS_MSB, 0},
    {FXLS8962_SDCD_UTHS_LSB, SDCD_UTHS_LSB, 0},
    {FXLS8962_SDCD_UTHS_MSB, SDCD_UTHS_MSB, 0},
    __END_WRITE_DATA__}
Register settings for FreeFall detection and Data Interrupt (non buffered) mode.
Definition at line 104 of file demo_11axis.c.
const registerreadlist_t cFxls8962FreeFallEvent[]
Initial value:
= {{.readFrom = FXLS8962_SDCD_INT_SRC2, .numBytes = 1},
                                                     __END_READ_DATA__}
Address of Free-Fall Status Register.
Definition at line 140 of file demo_11axis.c.
const registerreadlist_t cFxls8962OutputNormal[]
Initial value:
= {{.readFrom = FXLS8962_OUT_X_LSB, .numBytes = FXLS8962_DATA_SIZE},
                                                    __END_READ_DATA__}
Address of Raw Accel Data in Normal Mode.
Definition at line 136 of file demo_11axis.c.
const registerwritelist_t cMag3110ConfigNormal[]
Initial value:
= {
    {MAG3110_CTRL_REG1, MAG3110_CTRL_REG1_DR_ODR_1 | MAG3110_CTRL_REG1_OS_OSR_16,
     MAG3110_CTRL_REG1_DR_MASK | MAG3110_CTRL_REG1_OS_MASK},
    {MAG3110_CTRL_REG2, MAG3110_CTRL_REG2_AUTO_MSRT_EN_EN, MAG3110_CTRL_REG2_AUTO_MSRT_EN_MASK},
    __END_WRITE_DATA__}
Register settings for Normal (non buffered) mode.
Definition at line 144 of file demo_11axis.c.
const registerreadlist_t cMag3110OutputNormal[]
Initial value:
= {{.readFrom = MAG3110_OUT_X_MSB, .numBytes = MAG3110_DATA_SIZE},
                                                   __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 153 of file demo_11axis.c.
const registerwritelist_t cMpl3115SetOST[]
Initial value:
= {
    {MPL3115_CTRL_REG1, MPL3115_CTRL_REG1_OST_SET, MPL3115_CTRL_REG1_OST_MASK},
    __END_WRITE_DATA__}
Register settings for Triggring One-Shot Sampling.
Definition at line 171 of file demo_11axis.c.
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 184 of file demo_11axis.c.
Referenced by main(), and process_host_command().
const registerwritelist_t fxas21002_Config_Normal[]
Initial value:
= {
    {FXAS21002_CTRL_REG1, FXAS21002_CTRL_REG1_DR_25HZ, FXAS21002_CTRL_REG1_DR_MASK},
    {FXAS21002_CTRL_REG2, FXAS21002_CTRL_REG2_IPOL_ACTIVE_HIGH | FXAS21002_CTRL_REG2_INT_EN_DRDY_ENABLE |
                              FXAS21002_CTRL_REG2_INT_CFG_DRDY_INT1,
     FXAS21002_CTRL_REG2_IPOL_MASK | FXAS21002_CTRL_REG2_INT_EN_DRDY_MASK | FXAS21002_CTRL_REG2_INT_CFG_DRDY_MASK},
    __END_WRITE_DATA__}
Prepare the register write list to configure FXAS21002 in non-FIFO mode.
Definition at line 157 of file demo_11axis.c.
const registerreadlist_t fxas21002_Output_Values[]
Initial value:
= {
    {.readFrom = FXAS21002_OUT_X_MSB, .numBytes = FXAS21002_DATA_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw gyro data from the FXAS21002.
Definition at line 167 of file demo_11axis.c.
uint8_t gStreamID
Definition at line 186 of file demo_11axis.c.
Referenced by main(), and process_host_command().
const registerreadlist_t mpl3115_Output_Values[]
Initial value:
= {{.readFrom = MPL3115_OUT_P_MSB, .numBytes = MPL3115_DATA_SIZE},
                                                    __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 177 of file demo_11axis.c.
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 187 of file demo_11axis.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 183 of file demo_11axis.c.
Referenced by main(), and process_host_command().