ISSDK: driverexamples/dp5004/dp5004_interrupt.c File Reference
dp5004_interrupt.c File Reference
The dp5004_interrupt.c file implements the ISSDK MPXVDP5004 analog sensor driver example demonstration with interrupt mode.
#include "board.h"
#include "fsl_smc.h"
#include "pin_mux.h"
#include "fsl_lptmr.h"
#include "fsl_adc12.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
Macros
#define dp5004_odr_callback PWT_LPTMR0_IRQHandler
#define adc12_irq_callback ADC0_IRQHandler
#define MPXV5004DR_ODR_ms 1000U
Functions
void dp5004_odr_callback (void)
void adc12_irq_callback (void)
void KE15Z_LPTMR0_ADC0_Initialize (void)
int main (void)
Main function.
Variables
volatile uint32_t gAdcConversionValue
volatile bool bAdcCompletedFlag = false
adc12_channel_config_t gAdcChannelConfigStruct
Detailed Description
The dp5004_interrupt.c file implements the ISSDK MPXVDP5004 analog sensor driver example demonstration with interrupt mode.
Definition in file dp5004_interrupt.c.
Macro Definition Documentation
#define adc12_irq_callback ADC0_IRQHandler
Definition at line 60 of file dp5004_interrupt.c.
#define dp5004_odr_callback PWT_LPTMR0_IRQHandler
Definition at line 58 of file dp5004_interrupt.c.
#define MPXV5004DR_ODR_ms 1000U
Definition at line 63 of file dp5004_interrupt.c.
Referenced by KE15Z_LPTMR0_ADC0_Initialize().
Function Documentation
void adc12_irq_callback (void)
Definition at line 84 of file dp5004_interrupt.c.
References bAdcCompletedFlag, gAdcConversionValue, and MPXVDP5004_ADC12_CHANNEL_GROUP.
void dp5004_odr_callback (void)
Definition at line 76 of file dp5004_interrupt.c.
References gAdcChannelConfigStruct, and MPXVDP5004_ADC12_CHANNEL_GROUP.
void KE15Z_LPTMR0_ADC0_Initialize (void)
Definition at line 91 of file dp5004_interrupt.c.
References gAdcChannelConfigStruct, MPXV5004DR_ODR_ms, and MPXVDP5004_ADC12_CHANNEL.
Referenced by main().
int main (void)
Main function.
Initialize GREEN LED pin used by FRDM board
Definition at line 127 of file dp5004_interrupt.c.
References bAdcCompletedFlag, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), Driver_GPIO_KSDK, gAdcConversionValue, GPIO_DIRECTION_OUT, GREEN_LED, KE15Z_LPTMR0_ADC0_Initialize(), MPXV5004DP_PRESSURE_FROM_ADC_VALUE, GENERIC_DRIVER_GPIO::pin_init, SMC, SMC_SetPowerModeWait(), and GENERIC_DRIVER_GPIO::toggle_pin.
Variable Documentation
volatile bool bAdcCompletedFlag = false
Definition at line 69 of file dp5004_interrupt.c.
Referenced by adc12_irq_callback(), and main().
adc12_channel_config_t gAdcChannelConfigStruct
Definition at line 70 of file dp5004_interrupt.c.
Referenced by dp5004_odr_callback(), and KE15Z_LPTMR0_ADC0_Initialize().
volatile uint32_t gAdcConversionValue
Definition at line 68 of file dp5004_interrupt.c.
Referenced by adc12_irq_callback(), and main().