ISSDK: driverexamples/fxas21002/fxas21002_fifo.c File Reference
fxas21002_fifo.c File Reference
The fxas21002_fifo.c file implements the ISSDK FXAS21002 sensor driver example demonstration with FIFO mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "fxas21002_drv.h"
#include "systick_utils.h"
Macros
#define FIFO_SIZE 4
The watermark value configured for FXAS21002 FIFO Buffer.
Functions
int main (void)
Main function.
Variables
const registerwritelist_t fxas21002_Config_with_Fifo []
const registerreadlist_t fxas21002_Fifo_Event [] = {{.readFrom = FXAS21002_F_EVENT, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t fxas21002_Output_Values []
Detailed Description
The fxas21002_fifo.c file implements the ISSDK FXAS21002 sensor driver example demonstration with FIFO mode.
Definition in file fxas21002_fifo.c.
Macro Definition Documentation
#define FIFO_SIZE 4
The watermark value configured for FXAS21002 FIFO Buffer.
Definition at line 59 of file fxas21002_fifo.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the FXAS21002 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the FXAS21002 sensor driver.
Wait for the FIFO watermark event.
Read the raw sensor data from the FXAS21002.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 87 of file fxas21002_fifo.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), FIFO_SIZE, FXAS21002_F_EVENT_F_EVENT_MASK, FXAS21002_GYRO_DATA_SIZE, FXAS21002_I2C_ADDR, FXAS21002_I2C_Configure(), FXAS21002_I2C_Initialize(), FXAS21002_I2C_ReadData(), FXAS21002_I2C_SetIdleTask(), FXAS21002_WHO_AM_I_WHOAMI_PROD_VALUE, fxas21002_gyrodata_t::gyro, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), SENSOR_ERROR_NONE, SMC, and SMC_SetPowerModeWait().
Variable Documentation
const registerwritelist_t fxas21002_Config_with_Fifo[]
Initial value:
= {
    {FXAS21002_CTRL_REG1, FXAS21002_CTRL_REG1_DR_12_5HZ, FXAS21002_CTRL_REG1_DR_MASK},
    {FXAS21002_F_SETUP, FXAS21002_F_SETUP_F_MODE_STOP_MODE | (FIFO_SIZE << FXAS21002_F_SETUP_F_WMRK_SHIFT),
     FXAS21002_F_SETUP_F_MODE_MASK | FXAS21002_F_SETUP_F_WMRK_MASK},
    {FXAS21002_CTRL_REG3, FXAS21002_CTRL_REG3_WRAPTOONE_ROLL_DATA, FXAS21002_CTRL_REG3_WRAPTOONE_MASK},
    __END_WRITE_DATA__}
Prepare the register write list to configure FXAS21002 in FIFO mode.
Definition at line 65 of file fxas21002_fifo.c.
const registerreadlist_t fxas21002_Fifo_Event[] = {{.readFrom = FXAS21002_F_EVENT, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read FXAS21002 FIFO event.
Definition at line 75 of file fxas21002_fifo.c.
const registerreadlist_t fxas21002_Output_Values[]
Initial value:
= {
    {.readFrom = FXAS21002_OUT_X_MSB, .numBytes = FXAS21002_GYRO_DATA_SIZE * FIFO_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw gyro data from the FXAS21002.
Definition at line 78 of file fxas21002_fifo.c.