ISSDK: driverexamples/fxlc95000/fxlc95000_accel_spi.c File Reference
fxlc95000_accel_spi.c File Reference
The fxlc95000_accel_spi.c file implements the ISSDK FXLC95000 sensor driver example demonstration as for SPI Mode.
#include "board.h"
#include "pin_mux.h"
#include "fsl_lptmr.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "issdk_hal.h"
#include "fxlc95000_drv.h"
#include "systick_utils.h"
#include "gpio_driver.h"
#include "Driver_SPI.h"
#include "Driver_GPIO.h"
#include "fsl_spi_cmsis.h"
Macros
#define SAMPLING_RATE_us (100000) /* Timeout for the ODR Timer. */
#define FXLC95000_SAMPLE_SIZE (10) /* 4-Byte timestamp and 2-Byte X,Y,Z Data each. */
#define fxlc95000_odr_callback LPTMR0_IRQHandler /* Timer timeout Callback. */
Functions
void fxlc95000_odr_callback (void)
int main (void)
Main function.
Variables
const uint8_t cFxlc95000_SetODR_Cmd []
const uint8_t cFxlc95000_SetResolution_Cmd []
const uint8_t cFxlc95000_SetRange_Cmd []
const registercommandlist_t cFxlc95000ConfigMBox []
const registercommandlist_t cFxlc95000ConfigSensor []
const registerreadlist_t cFxlc95000ReadSample []
volatile bool gFxlc95000DataRead
Detailed Description
The fxlc95000_accel_spi.c file implements the ISSDK FXLC95000 sensor driver example demonstration as for SPI Mode.
Definition in file fxlc95000_accel_spi.c.
Macro Definition Documentation
#define fxlc95000_odr_callback LPTMR0_IRQHandler /* Timer timeout Callback. */
Definition at line 70 of file fxlc95000_accel_spi.c.
#define FXLC95000_SAMPLE_SIZE (10) /* 4-Byte timestamp and 2-Byte X,Y,Z Data each. */
Definition at line 69 of file fxlc95000_accel_spi.c.
Referenced by main().
#define SAMPLING_RATE_us (100000) /* Timeout for the ODR Timer. */
Definition at line 68 of file fxlc95000_accel_spi.c.
Referenced by main().
Function Documentation
void fxlc95000_odr_callback (void)
Definition at line 112 of file fxlc95000_accel_spi.c.
References gFxlc95000DataRead.
int main (void)
Main function.
Initialize the MCU hardware.
Initialize the SPI driver.
Set the SPI Power mode.
Set the SPI Slave speed.
Initialize the FXLC95000 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the FXLC95000 with MBox settings.
Configure the FXLC95000 with Sampling settings.
Read the raw sensor data from the FXLC95000.
Convert the raw bytes to sensor data with correct endianness.
Definition at line 121 of file fxlc95000_accel_spi.c.
References fxlc95000_acceldata_t::accel, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), FXLC95000_BUILD_ID, FXLC95000_PDB_B, FXLC95000_RST_GPIO, FXLC95000_SAMPLE_SIZE, FXLC95000_SPI_CommandResponse(), FXLC95000_SPI_Initialize(), FXLC95000_SPI_SetIdleTask(), FXLC95000_SSB_IO3, fxlc95000Driver, gFxlc95000DataRead, int32_t(), SAMPLING_RATE_us, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), SPI_S_BAUDRATE, SPI_S_DEVICE_INDEX, SPI_S_DRIVER, SPI_S_SIGNAL_EVENT, and fxlc95000_acceldata_t::timestamp.
Variable Documentation
const uint8_t cFxlc95000_SetODR_Cmd[]
Initial value:
= {FXLC95000_SET_ODR_CMD_HDR,
                                         FXLC95000_SST_ODR_PAYLOAD(SAMPLING_RATE_us)}
Create commands for setting FXLC95000L desired configuration.
Definition at line 76 of file fxlc95000_accel_spi.c.
const uint8_t cFxlc95000_SetRange_Cmd[]
Initial value:
= {FXLC95000_SET_RANGE_CMD_HDR,
                                           FXLC95000_ACCEL_RANGE_2G}
Definition at line 80 of file fxlc95000_accel_spi.c.
const uint8_t cFxlc95000_SetResolution_Cmd[]
Initial value:
= {FXLC95000_SET_RESOLUTION_CMD_HDR,
                                                FXLC95000_ACCEL_RESOLUTION_14_BIT}
Definition at line 78 of file fxlc95000_accel_spi.c.
const registercommandlist_t cFxlc95000ConfigMBox[]
Initial value:
= {
    {QuickReadInterruptDisable, 0, sizeof(QuickReadInterruptDisable)},
    {ConfigureMBoxCmd, 0, sizeof(ConfigureMBoxCmd)},
    __END_WRITE_CMD__
}
Prepare the register write list to initialize FXLC95000L with desired MBox Settings.
Definition at line 84 of file fxlc95000_accel_spi.c.
const registercommandlist_t cFxlc95000ConfigSensor[]
Initial value:
= {
    {StopDataCmd, 0, sizeof(StopDataCmd)},
    {cFxlc95000_SetODR_Cmd, 0, sizeof(cFxlc95000_SetODR_Cmd)},
    {cFxlc95000_SetRange_Cmd, 0, sizeof(cFxlc95000_SetRange_Cmd)},
    {cFxlc95000_SetResolution_Cmd, 0, sizeof(cFxlc95000_SetResolution_Cmd)},
    {StartDataCmd, 0, sizeof(StartDataCmd)},
    __END_WRITE_CMD__}
Prepare the register write list to configure FXLC95000L with desired Sampling Settings.
Definition at line 91 of file fxlc95000_accel_spi.c.
const registerreadlist_t cFxlc95000ReadSample[]
Initial value:
= {
    {.readFrom = FXLC95000_SAMPLE_OFFSET, .numBytes = FXLC95000_SAMPLE_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the Timestamp and Accel data from FXLC95000.
Definition at line 100 of file fxlc95000_accel_spi.c.
volatile bool gFxlc95000DataRead
Definition at line 106 of file fxlc95000_accel_spi.c.
Referenced by fxlc95000_odr_callback(), and main().