ISSDK: driverexamples/fxos8700/fxos8700_poll_spi.c File Reference
fxos8700_poll_spi.c File Reference
The fxos8700_poll_spi.c file implements the ISSDK FXOS8700 SPI sensor driver example demonstration for SPI Mode with polling.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "issdk_hal.h"
#include "fxos8700_drv.h"
#include "systick_utils.h"
#include "Driver_SPI.h"
#include "Driver_gpio.h"
#include "fsl_spi_cmsis.h"
Macros
#define RAW_ACCELMAG_DATA_SIZE (12)
Functions
int main (void)
Main function.
Variables
const registerwritelist_t fxos8700_Config_Hybrid []
const registerreadlist_t FXOS8700_STATUS_READ [] = {{.readFrom = FXOS8700_STATUS, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t FXOS8700_ACCELMAG_READ []
Detailed Description
The fxos8700_poll_spi.c file implements the ISSDK FXOS8700 SPI sensor driver example demonstration for SPI Mode with polling.
Definition in file fxos8700_poll_spi.c.
Macro Definition Documentation
#define RAW_ACCELMAG_DATA_SIZE (12)
Definition at line 66 of file fxos8700_poll_spi.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize the SPI driver.
Set the SPI Power mode.
Set the SPI Slave speed.
Initialize the FXOS8700 sensor driver.
Set the task to be executed while waiting for SPI transactions to complete.
Configure the FXAS21002 sensor driver.
Wait for data ready from the FXAS21002.
Read the raw sensor data from the fxos8700.
Convert the raw sensor data for display to the debug port.
Definition at line 96 of file fxos8700_poll_spi.c.
References fxos8700_accelmagdata_t::accel, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), FXOS8700_CS, FXOS8700_DR_STATUS_ZYXDR_MASK, FXOS8700_SPI_Configure(), FXOS8700_SPI_Initialize(), FXOS8700_SPI_ReadData(), FXOS8700_SPI_SetIdleTask(), FXOS8700_WHO_AM_I_PROD_VALUE, int32_t(), fxos8700_accelmagdata_t::mag, RAW_ACCELMAG_DATA_SIZE, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), SPI_S_BAUDRATE, SPI_S_DEVICE_INDEX, SPI_S_DRIVER, and SPI_S_SIGNAL_EVENT.
Variable Documentation
const registerreadlist_t FXOS8700_ACCELMAG_READ[]
Initial value:
= {{.readFrom = FXOS8700_OUT_X_MSB, .numBytes = 12},
                                                     __END_READ_DATA__}
Command definition to read the Accel + Mag Data
Definition at line 87 of file fxos8700_poll_spi.c.
const registerwritelist_t fxos8700_Config_Hybrid[]
Initial value:
= {
    {FXOS8700_CTRL_REG1, FXOS8700_CTRL_REG1_DR_SINGLE_12P5_HZ, FXOS8700_CTRL_REG1_DR_MASK},
    {FXOS8700_M_CTRL_REG1, FXOS8700_M_CTRL_REG1_M_HMS_HYBRID_MODE,
     FXOS8700_M_CTRL_REG1_M_HMS_MASK},
    {FXOS8700_M_CTRL_REG2,
     FXOS8700_M_CTRL_REG2_M_AUTOINC_HYBRID_MODE | FXOS8700_M_CTRL_REG2_M_RST_CNT_DISABLE,
     FXOS8700_M_CTRL_REG2_M_AUTOINC_MASK | FXOS8700_M_CTRL_REG2_M_RST_CNT_MASK},
    __END_WRITE_DATA__}
Prepare the register write list to configure FXOS8700 in Hybrid mode.
Definition at line 72 of file fxos8700_poll_spi.c.
const registerreadlist_t FXOS8700_STATUS_READ[] = {{.readFrom = FXOS8700_STATUS, .numBytes = 1}, __END_READ_DATA__}
Command definition to read the Data Ready Status
Definition at line 84 of file fxos8700_poll_spi.c.