ISSDK: driverexamples/demos/FRDM-KL27Z/fxpq3115_demo.c File Reference
fxpq3115_demo.c File Reference
The fxpq3115_demo.c file implements the ISSDK FXPQ3115 sensor demo example demonstration with interrupt mode for FRDM-KL27Z.
#include "board.h"
#include "pin_mux.h"
#include "fsl_lpuart.h"
#include "clock_config.h"
#include "Driver_I2C.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_lpuart_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "fxpq3115_drv.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define FXPQ3115_SAMPLING_EXPONENT 1 /* 2 seconds */
#define FXPQ3115_DATA_SIZE 5 /* 3 byte Pressure and 2 byte Temperature. */
#define FXPQ3115_STREAM_DATA_SIZE 10 /* 6 byte Data */
#define APPLICATION_NAME "FXPQ3115BV"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Functions
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerwritelist_t fxpq3115ConfigPoll []
Register settings for Normal (non buffered) mode.
const registerreadlist_t fxpq3115Status [] = {{.readFrom = FXPQ3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t fxpq3115OutputNormal []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bFxpq3115Ready = false
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Detailed Description
The fxpq3115_demo.c file implements the ISSDK FXPQ3115 sensor demo example demonstration with interrupt mode for FRDM-KL27Z.
Definition in file fxpq3115_demo.c.
Macro Definition Documentation
#define APPLICATION_NAME "FXPQ3115BV"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 74 of file fxpq3115_demo.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 76 of file fxpq3115_demo.c.
Referenced by main().
#define FXPQ3115_DATA_SIZE 5 /* 3 byte Pressure and 2 byte Temperature. */
Definition at line 70 of file fxpq3115_demo.c.
Referenced by main().
#define FXPQ3115_SAMPLING_EXPONENT 1 /* 2 seconds */
In FXPQ3115 the Auto Acquisition Time Step (ODR) can be set only in powers of 2 (i.e. 2^x, where x is the SAMPLING_EXPONENT). This gives a range of 1 second to 2^15 seconds (9 hours).
Definition at line 69 of file fxpq3115_demo.c.
#define FXPQ3115_STREAM_DATA_SIZE 10 /* 6 byte Data */
Definition at line 71 of file fxpq3115_demo.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize GREEN LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize the FXPQ3115 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the FXPQ3115 sensor driver.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Wait for data ready from the FXPQ3115.
Read raw sensor data from the FXPQ3115.
Convert the raw sensor data to signed 32-bit and 16-bit containers for display to the debug port.
Definition at line 195 of file fxpq3115_demo.c.
References ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bFxpq3115Ready, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, fxpq3115_i2c_sensorhandle_t::deviceInfo, embAppName, FXPQ3115_DATA_SIZE, FXPQ3115_DR_STATUS_PTDR_MASK, FXPQ3115_I2C_ADDR, FXPQ3115_I2C_Configure(), FXPQ3115_I2C_Initialize(), FXPQ3115_I2C_ReadData(), FXPQ3115_I2C_SetIdleTask(), FXPQ3115_STREAM_DATA_SIZE, FXPQ3115_WHOAMI_VALUE, GPIO_DIRECTION_OUT, GREEN_LED, gStreamID, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), fxpq3115_i2c_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, fxpq3115_pressuredata_t::pressure, process_host_command(), SENSOR_ERROR_NONE, SHIELD_NAME, shieldString, SMC, SMC_SetPowerModeWait(), STREAMING_HEADER_LEN, fxpq3115_pressuredata_t::temperature, fxpq3115_pressuredata_t::timestamp, and GENERIC_DRIVER_GPIO::toggle_pin.
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 113 of file fxpq3115_demo.c.
References bFxpq3115Ready, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, GREEN_LED, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, and shieldString.
Referenced by main().
Variable Documentation
volatile bool bFxpq3115Ready = false
Definition at line 105 of file fxpq3115_demo.c.
Referenced by main(), and process_host_command().
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 103 of file fxpq3115_demo.c.
Referenced by main(), and process_host_command().
volatile bool bStreamingEnabled = false
Definition at line 105 of file fxpq3115_demo.c.
Referenced by main(), and process_host_command().
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 104 of file fxpq3115_demo.c.
Referenced by main(), and process_host_command().
const registerwritelist_t fxpq3115ConfigPoll[]
Initial value:
= {
    {FXPQ3115_PT_DATA_CFG,
     FXPQ3115_PT_DATA_CFG_TDEFE_ENABLED | FXPQ3115_PT_DATA_CFG_PDEFE_ENABLED | FXPQ3115_PT_DATA_CFG_DREM_ENABLED,
     FXPQ3115_PT_DATA_CFG_TDEFE_MASK | FXPQ3115_PT_DATA_CFG_PDEFE_MASK | FXPQ3115_PT_DATA_CFG_DREM_MASK},
    {FXPQ3115_CTRL_REG1, FXPQ3115_CTRL_REG1_OS_OSR_128, FXPQ3115_CTRL_REG1_OS_MASK},
    {FXPQ3115_CTRL_REG2, FXPQ3115_SAMPLING_EXPONENT, FXPQ3115_CTRL_REG2_ST_MASK},
    __END_WRITE_DATA__}
Register settings for Normal (non buffered) mode.
Definition at line 82 of file fxpq3115_demo.c.
const registerreadlist_t fxpq3115OutputNormal[]
Initial value:
= {{.readFrom = FXPQ3115_OUT_P_MSB, .numBytes = FXPQ3115_DATA_SIZE},
                                                   __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 97 of file fxpq3115_demo.c.
const registerreadlist_t fxpq3115Status[] = {{.readFrom = FXPQ3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 94 of file fxpq3115_demo.c.
uint8_t gStreamID
Definition at line 106 of file fxpq3115_demo.c.
Referenced by main(), and process_host_command().
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 107 of file fxpq3115_demo.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 103 of file fxpq3115_demo.c.
Referenced by main(), and process_host_command().