ISSDK: driverexamples/fxpq3115/fxpq3115_altitude.c File Reference
fxpq3115_altitude.c File Reference
The fxpq3115_altitude.c file implements the ISSDK FXPQ3115BV sensor driver example demonstration for Altitude mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "fxpq3115_drv.h"
#include "systick_utils.h"
Macros
#define FXPQ3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
#define FXPQ3115_SAMPLING_EXPONENT (1) /* 2 seconds */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t B3115ConfigAltitude []
Register settings for Altitude readings in Poll (non buffered) mode.
const registerreadlist_t B3115Status [] = {{.readFrom = FXPQ3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t B3115OutputPoll []
Address and size of Raw Altitude+Temperature Data in Poll Mode.
Detailed Description
The fxpq3115_altitude.c file implements the ISSDK FXPQ3115BV sensor driver example demonstration for Altitude mode.
Definition in file fxpq3115_altitude.c.
Macro Definition Documentation
#define FXPQ3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
Definition at line 59 of file fxpq3115_altitude.c.
Referenced by main().
#define FXPQ3115_SAMPLING_EXPONENT (1) /* 2 seconds */
In FXPQ3115 the Auto Acquisition Time Step (ODR) can be set only in powers of 2 (i.e. 2^x, where x is the SAMPLING_EXPONENT). This gives a range of 1 second to 2^15 seconds (9 hours).
Definition at line 63 of file fxpq3115_altitude.c.
Function Documentation
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize FXPQ3115 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the FXPQ3115 sensor.
Wait for data ready from the FXPQ3115.
Read new raw sensor data from the FXPQ3115.
Process the sample and convert the raw sensor data.
Definition at line 94 of file fxpq3115_altitude.c.
References fxpq3115_altitudedata_t::altitude, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), FXPQ3115_ALTITUDE_CONV_FACTOR, FXPQ3115_DATA_SIZE, FXPQ3115_DR_STATUS_PTDR_MASK, FXPQ3115_I2C_ADDR, FXPQ3115_I2C_Configure(), FXPQ3115_I2C_Initialize(), FXPQ3115_I2C_ReadData(), FXPQ3115_I2C_SetIdleTask(), FXPQ3115_TEMPERATURE_CONV_FACTOR, FXPQ3115_WHOAMI_VALUE, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), and fxpq3115_altitudedata_t::temperature.
Variable Documentation
const registerwritelist_t B3115ConfigAltitude[]
Initial value:
= {
    {FXPQ3115_PT_DATA_CFG,
     FXPQ3115_PT_DATA_CFG_TDEFE_ENABLED | FXPQ3115_PT_DATA_CFG_PDEFE_ENABLED | FXPQ3115_PT_DATA_CFG_DREM_ENABLED,
     FXPQ3115_PT_DATA_CFG_TDEFE_MASK | FXPQ3115_PT_DATA_CFG_PDEFE_MASK | FXPQ3115_PT_DATA_CFG_DREM_MASK},
    {FXPQ3115_CTRL_REG1, FXPQ3115_CTRL_REG1_ALT_ALT | FXPQ3115_CTRL_REG1_OS_OSR_128,
     FXPQ3115_CTRL_REG1_ALT_MASK | FXPQ3115_CTRL_REG1_OS_MASK},
    {FXPQ3115_CTRL_REG2, FXPQ3115_SAMPLING_EXPONENT, FXPQ3115_CTRL_REG2_ST_MASK},
    __END_WRITE_DATA__}
Register settings for Altitude readings in Poll (non buffered) mode.
Definition at line 69 of file fxpq3115_altitude.c.
const registerreadlist_t B3115OutputPoll[]
Initial value:
= {{.readFrom = FXPQ3115_OUT_P_MSB, .numBytes = FXPQ3115_DATA_SIZE},
                                              __END_READ_DATA__}
Address and size of Raw Altitude+Temperature Data in Poll Mode.
Definition at line 85 of file fxpq3115_altitude.c.
const registerreadlist_t B3115Status[] = {{.readFrom = FXPQ3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 82 of file fxpq3115_altitude.c.