ISSDK: algorithms/sensorfusion/sources/hal_frdm_fxs_mult2_b.c File Reference
hal_frdm_fxs_mult2_b.c File Reference
Hardware Abstraction layer for the FRDM-FXS-MULT2-B sensor shield.
#include "sensor_fusion.h"
Functions
void ApplyAccelHAL (struct AccelSensor *Accel)
Apply the accelerometer Hardware Abstraction Layer.
void ApplyMagHAL (struct MagSensor *Mag)
Apply the magnetometer Hardware Abstraction Layer.
void ApplyGyroHAL (struct GyroSensor *Gyro)
Apply the gyroscope Hardware Abstraction Layer.
Detailed Description
Hardware Abstraction layer for the FRDM-FXS-MULT2-B sensor shield.
Definition in file hal_frdm_fxs_mult2_b.c.
Function Documentation
void ApplyAccelHAL (struct AccelSensor * Accel)
Apply the accelerometer Hardware Abstraction Layer.
Parameters
Accel pointer to accelerometer logical sensor
Definition at line 44 of file hal_frdm_fxs_mult2_b.c.
References CHX, CHY, CHZ, AccelSensor::iFIFOCount, and AccelSensor::iGsFIFO.
Referenced by initializeSensors().
void ApplyGyroHAL (struct GyroSensor * Gyro)
Apply the gyroscope Hardware Abstraction Layer.
Parameters
Gyro pointer to gyroscope logical sensor
Definition at line 99 of file hal_frdm_fxs_mult2_b.c.
References CHX, CHY, CHZ, GyroSensor::iFIFOCount, and GyroSensor::iYsFIFO.
Referenced by processMagData().
void ApplyMagHAL (struct MagSensor * Mag)
Apply the magnetometer Hardware Abstraction Layer.
Parameters
Mag pointer to magnetometer logical sensor
Definition at line 71 of file hal_frdm_fxs_mult2_b.c.
References CHX, CHY, CHZ, MagSensor::iBsFIFO, and MagSensor::iFIFOCount.
Referenced by processMagData().