ISSDK: drivers/gpio/kinetis/gpio_driver_irq.c File Reference
gpio_driver_irq.c File Reference
#include "fsl_gpio.h"
#include "gpio_driver.h"
Functions
void ksdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t portNumber)
void PORTA_IRQHandler (void)
void PORTB_IRQHandler (void)
void PORTC_IRQHandler (void)
void PORTD_IRQHandler (void)
void PORTE_IRQHandler (void)
Function Documentation
void ksdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t portNumber)
Definition at line 177 of file gpio_driver.c.
Referenced by PORTA_IRQHandler(), PORTB_IRQHandler(), PORTC_IRQHandler(), PORTD_IRQHandler(), and PORTE_IRQHandler().
void PORTA_IRQHandler (void)
Definition at line 44 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTA_NUM.
void PORTB_IRQHandler (void)
Definition at line 48 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTB_NUM.
void PORTC_IRQHandler (void)
Definition at line 52 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTC_NUM.
void PORTD_IRQHandler (void)
Definition at line 56 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTD_NUM.
void PORTE_IRQHandler (void)
Definition at line 60 of file gpio_driver_irq.c.
References ksdk_gpio_handle_interrupt(), and PORTE_NUM.