ISSDK: drivers/gpio/kinetis/gpio_driver.c File Reference
gpio_driver.c File Reference
#include "fsl_gpio.h"
#include "fsl_port.h"
#include "gpio_driver.h"
Macros
#define GPIO_DRV_VERSION ARM_DRIVER_VERSION_MAJOR_MINOR(2, 0) /* driver version */
#define GPIO_NUMBER_OF_PIN 0x20
Functions
void ksdk_gpio_handle_interrupt (GPIO_Type *base, port_number_t portNumber)
GENERIC_DRIVER_VERSION ksdk_gpio_get_version (void)
void ksdk_gpio_pin_init (pinID_t aPinId, gpio_direction_t dir, void *apPinConfig, gpio_isr_handler_t aIsrHandler, void *apUserData)
void ksdk_gpio_set_pin (pinID_t aPinId)
void ksdk_gpio_clr_pin (pinID_t aPinId)
void ksdk_gpio_toggle_pin (pinID_t aPinId)
void ksdk_gpio_write_pin (pinID_t aPinId, uint8_t aValue)
uint32_t ksdk_gpio_read_pin (pinID_t aPinId)
Variables
GENERIC_DRIVER_GPIO Driver_GPIO_KSDK
Macro Definition Documentation
#define GPIO_DRV_VERSION ARM_DRIVER_VERSION_MAJOR_MINOR(2, 0) /* driver version */
Definition at line 43 of file gpio_driver.c.
#define GPIO_NUMBER_OF_PIN 0x20
Definition at line 45 of file gpio_driver.c.
Referenced by ksdk_gpio_handle_interrupt().
Function Documentation
void ksdk_gpio_clr_pin (pinID_t aPinId)
Definition at line 131 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::mask.
GENERIC_DRIVER_VERSION ksdk_gpio_get_version (void)
Definition at line 71 of file gpio_driver.c.
void ksdk_gpio_handle_interrupt (GPIO_Type * base, port_number_t portNumber)
Definition at line 177 of file gpio_driver.c.
References GPIO_NUMBER_OF_PIN, and gpioIsrObj::isrHandle.
Referenced by PORTA_IRQHandler(), PORTAE_IRQHandler(), PORTB_IRQHandler(), PORTB_PORTC_IRQHandler(), PORTB_PORTC_PORTD_PORTE_IRQHandler(), PORTBCD_IRQHandler(), PORTC_IRQHandler(), PORTD_IRQHandler(), and PORTE_IRQHandler().
void ksdk_gpio_pin_init (pinID_t aPinId, gpio_direction_t dir, void * apPinConfig, gpio_isr_handler_t aIsrHandler, void * apUserData)
Definition at line 82 of file gpio_driver.c.
References gpioHandleKSDK::base, gpioHandleKSDK::clockName, GPIO_DIRECTION_IN, gpioConfigKSDK::interruptMode, gpioHandleKSDK::irq, gpioIsrObj::isrHandle, gpioConfigKSDK::pinConfig, gpioHandleKSDK::pinNumber, gpioHandleKSDK::portBase, gpioHandleKSDK::portNumber, gpioConfigKSDK::portPinConfig, and gpioIsrObj::pUserData.
uint32_t ksdk_gpio_read_pin (pinID_t aPinId)
Definition at line 165 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::pinNumber.
void ksdk_gpio_set_pin (pinID_t aPinId)
Definition at line 120 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::mask.
void ksdk_gpio_toggle_pin (pinID_t aPinId)
Definition at line 143 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::mask.
void ksdk_gpio_write_pin (pinID_t aPinId, uint8_t aValue)
Definition at line 154 of file gpio_driver.c.
References gpioHandleKSDK::base, and gpioHandleKSDK::pinNumber.
Variable Documentation
GENERIC_DRIVER_GPIO Driver_GPIO_KSDK
Initial value:
= {
    ksdk_gpio_get_version, ksdk_gpio_pin_init,  ksdk_gpio_set_pin,  ksdk_gpio_clr_pin,
    ksdk_gpio_toggle_pin,  ksdk_gpio_write_pin, ksdk_gpio_read_pin,
}
Definition at line 196 of file gpio_driver.c.
Referenced by FXAS21002_SPI_Initialize(), FXLC95000_SPI_Initialize(), FXLS8471Q_Init(), FXLS8471Q_SPI_Initialize(), FXLS8962_SPI_Initialize(), FXOS8700_SPI_Initialize(), main(), and MMA9553_SPI_Initialize().