ISSDK: boardkit/lpcxpresso54114/lpc54114.c File Reference
lpc54114.c File Reference
The lpc54114.c file defines GPIO pins and I2C CMSIS utilities for LPCXpresso54114 board.
#include "lpc54114.h"
Functions
status_t SMC_SetPowerModeWait (void *arg)
Configures the system to WAIT power mode. API name used from Kinetis family to maintain compatibility.
uint32_t USART0_GetFreq (void)
Determines the Clock Frequency feature.
uint32_t I2C4_GetFreq (void)
Determines the Clock Frequency feature.
uint32_t I2C5_GetFreq (void)
Determines the Clock Frequency feature.
uint32_t SPI3_GetFreq (void)
Determines the Clock Frequency feature.
uint32_t SPI5_GetFreq (void)
Determines the Clock Frequency feature.
Variables
gpioHandleKSDK_t D14
gpioHandleKSDK_t D15
gpioHandleKSDK_t D11
gpioHandleKSDK_t D12
gpioHandleKSDK_t D13
gpioHandleKSDK_t D0
gpioHandleKSDK_t D1
gpioHandleKSDK_t A0
gpioHandleKSDK_t A1
gpioHandleKSDK_t A2
gpioHandleKSDK_t A3
gpioHandleKSDK_t A4
gpioHandleKSDK_t A5
gpioHandleKSDK_t D2
gpioHandleKSDK_t D3
gpioHandleKSDK_t D4
gpioHandleKSDK_t D5
gpioHandleKSDK_t D6
gpioHandleKSDK_t D7
gpioHandleKSDK_t D8
gpioHandleKSDK_t D9
gpioHandleKSDK_t D10
gpioHandleKSDK_t RED_LED
gpioHandleKSDK_t GREEN_LED
gpioHandleKSDK_t BLUE_LED
Detailed Description
The lpc54114.c file defines GPIO pins and I2C CMSIS utilities for LPCXpresso54114 board.
Definition in file lpc54114.c.
Function Documentation
uint32_t I2C4_GetFreq (void)
Determines the Clock Frequency feature.
The Clock Frequecny computation API required by fsl_i2c_cmsis.c.
Parameters
[in] void
Constraints:
None
Reentrant: Yes
Returns
uint32_t Returns the clock frequency .
Definition at line 203 of file lpc54114.c.
uint32_t I2C5_GetFreq (void)
Determines the Clock Frequency feature.
The Clock Frequecny computation API required by fsl_i2c_cmsis.c.
Parameters
[in] void
Constraints:
None
Reentrant: Yes
Returns
uint32_t Returns the clock frequency .
Definition at line 215 of file lpc54114.c.
status_t SMC_SetPowerModeWait (void * arg)
Configures the system to WAIT power mode. API name used from Kinetis family to maintain compatibility.
Parameters
Power peripheral base address (dummy).
Returns
Configuration error code.
Definition at line 177 of file lpc54114.c.
Referenced by fxlc95000_enSensor(), main(), mma8491q_mode_activate(), and mma8491q_mode_fwk_init().
uint32_t SPI3_GetFreq (void)
Determines the Clock Frequency feature.
The Clock Frequecny computation API required by fsl_spi_cmsis.c.
Parameters
[in] void
Constraints:
None
Reentrant: Yes
Returns
uint32_t Returns the clock frequency .
Definition at line 227 of file lpc54114.c.
uint32_t SPI5_GetFreq (void)
Determines the Clock Frequency feature.
The Clock Frequecny computation API required by fsl_spi_cmsis.c.
Parameters
[in] void
Constraints:
None
Reentrant: Yes
Returns
uint32_t Returns the clock frequency .
Definition at line 239 of file lpc54114.c.
uint32_t USART0_GetFreq (void)
Determines the Clock Frequency feature.
The Clock Frequecny computation API required by fsl_uart_cmsis.c.
Parameters
[in] void
Constraints:
None
Reentrant: Yes
Returns
uint32_t Returns the clock frequency .
Definition at line 191 of file lpc54114.c.
Variable Documentation
gpioHandleKSDK_t A0
Initial value:
= {.base = GPIO,
                       .pinNumber = 30,
                       .mask = 1 << (30),
                       .clockName = kCLOCK_Gpio0,
                       .portNumber = kGINT_Port0}
Definition at line 80 of file lpc54114.c.
gpioHandleKSDK_t A1
Definition at line 85 of file lpc54114.c.
gpioHandleKSDK_t A2
Initial value:
= {.base = GPIO,
                       .pinNumber = 8,
                       .mask = 1 << (8),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 86 of file lpc54114.c.
gpioHandleKSDK_t A3
Initial value:
= {.base = GPIO,
                       .pinNumber = 10,
                       .mask = 1 << (10),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 91 of file lpc54114.c.
gpioHandleKSDK_t A4
Initial value:
= {.base = GPIO,
                       .pinNumber = 4,
                       .mask = 1 << (4),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 96 of file lpc54114.c.
gpioHandleKSDK_t A5
Initial value:
= {.base = GPIO,
                       .pinNumber = 5,
                       .mask = 1 << (5),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 101 of file lpc54114.c.
gpioHandleKSDK_t BLUE_LED
Initial value:
= {.base = GPIO,
                             .pinNumber = 9,
                             .mask = 1 << (9),
                             .clockName = kCLOCK_Gpio1,
                             .portNumber = kGINT_Port1}
Definition at line 164 of file lpc54114.c.
gpioHandleKSDK_t D0
Initial value:
= {.base = GPIO,
                       .pinNumber = 8,
                       .mask = 1 << (8),
                       .clockName = kCLOCK_Gpio0,
                       .portNumber = kGINT_Port0}
Definition at line 68 of file lpc54114.c.
gpioHandleKSDK_t D1
Initial value:
= {.base = GPIO,
                       .pinNumber = 9,
                       .mask = 1 << (9),
                       .clockName = kCLOCK_Gpio0,
                       .portNumber = kGINT_Port0}
Definition at line 73 of file lpc54114.c.
gpioHandleKSDK_t D10
Initial value:
= {.base = GPIO,
                        .pinNumber = 1,
                        .mask = 1 << (1),
                        .clockName = kCLOCK_Gpio1,
                        .portNumber = kGINT_Port1}
Definition at line 147 of file lpc54114.c.
gpioHandleKSDK_t D11
Initial value:
= {.base = GPIO,
                        .pinNumber = 20,
                        .mask = 1 << (20),
                        .clockName = kCLOCK_Gpio0,
                        .portNumber = kGINT_Port0}
Definition at line 51 of file lpc54114.c.
gpioHandleKSDK_t D12
Initial value:
= {.base = GPIO,
                        .pinNumber = 18,
                        .mask = 1 << (18),
                        .clockName = kCLOCK_Gpio0,
                        .portNumber = kGINT_Port0}
Definition at line 56 of file lpc54114.c.
gpioHandleKSDK_t D13
Initial value:
= {.base = GPIO,
                        .pinNumber = 19,
                        .mask = 1 << (19),
                        .clockName = kCLOCK_Gpio0,
                        .portNumber = kGINT_Port0}
Definition at line 61 of file lpc54114.c.
gpioHandleKSDK_t D14
Initial value:
= {.base = GPIO,
                        .pinNumber = 26,
                        .mask = 1 << (26),
                        .clockName = kCLOCK_Gpio0,
                        .portNumber = kGINT_Port0}
Definition at line 39 of file lpc54114.c.
gpioHandleKSDK_t D15
Initial value:
= {.base = GPIO,
                        .pinNumber = 25,
                        .mask = 1 << (25),
                        .clockName = kCLOCK_Gpio0,
                        .portNumber = kGINT_Port0}
Definition at line 44 of file lpc54114.c.
gpioHandleKSDK_t D2
Initial value:
= {.base = GPIO,
                       .pinNumber = 10,
                       .mask = 1 << (10),
                       .clockName = kCLOCK_Gpio0,
                       .portNumber = kGINT_Port0}
Definition at line 107 of file lpc54114.c.
gpioHandleKSDK_t D3
Initial value:
= {.base = GPIO,
                       .pinNumber = 12,
                       .mask = 1 << (12),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 112 of file lpc54114.c.
gpioHandleKSDK_t D4
Initial value:
= {.base = GPIO,
                       .pinNumber = 13,
                       .mask = 1 << (13),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 117 of file lpc54114.c.
gpioHandleKSDK_t D5
Initial value:
= {.base = GPIO,
                       .pinNumber = 29,
                       .mask = 1 << (29),
                       .clockName = kCLOCK_Gpio0,
                       .portNumber = kGINT_Port0}
Definition at line 122 of file lpc54114.c.
gpioHandleKSDK_t D6
Initial value:
= {.base = GPIO,
                       .pinNumber = 0,
                       .mask = 1 << (0),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 127 of file lpc54114.c.
gpioHandleKSDK_t D7
Initial value:
= {.base = GPIO,
                       .pinNumber = 14,
                       .mask = 1 << (14),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 132 of file lpc54114.c.
gpioHandleKSDK_t D8
Initial value:
= {.base = GPIO,
                       .pinNumber = 16,
                       .mask = 1 << (16),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 137 of file lpc54114.c.
gpioHandleKSDK_t D9
Initial value:
= {.base = GPIO,
                       .pinNumber = 15,
                       .mask = 1 << (15),
                       .clockName = kCLOCK_Gpio1,
                       .portNumber = kGINT_Port1}
Definition at line 142 of file lpc54114.c.
gpioHandleKSDK_t GREEN_LED
Initial value:
= {.base = GPIO,
                              .pinNumber = 10,
                              .mask = 1 << (10),
                              .clockName = kCLOCK_Gpio1,
                              .portNumber = kGINT_Port1}
Definition at line 159 of file lpc54114.c.
gpioHandleKSDK_t RED_LED
Initial value:
= {.base = GPIO,
                            .pinNumber = 29,
                            .mask = 1 << (29),
                            .clockName = kCLOCK_Gpio0,
                            .portNumber = kGINT_Port0}
Definition at line 154 of file lpc54114.c.