ISSDK: drivers/ads/lpc/auto_detection_service.c File Reference
auto_detection_service.c File Reference
#include <stdio.h>
#include "mma9553.h"
#include "mpl3115.h"
#include "mag3110.h"
#include "mma865x.h"
#include "fxls8962.h"
#include "fxpq3115.h"
#include "fxos8700.h"
#include "fxas21002.h"
#include "fxlc95000.h"
#include "fxls8471q.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "register_io_spi.h"
#include "register_io_i2c.h"
#include "auto_detection_shield.h"
#include "auto_detection_service.h"
#include "fsl_flashiap.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_spi_cmsis.h"
Macros
#define FXLS8471Q_SPI_CMD_LEN (2)
These variables are specific to SPI access to the FXLS8471 for ADS.
#define FXLS8471Q_SS_ACTIVE_VALUE SPI_SS_ACTIVE_LOW
#define FXLS8962_SPI_CMD_LEN (2)
These variables are specific to SPI access to the FXLS8962 for ADS.
#define FXLS8962_SS_ACTIVE_VALUE SPI_SS_ACTIVE_LOW
#define ADS_NVM_SECTOR_NUM (ADS_NVM_ADDR / FSL_FEATURE_SYSCON_FLASH_SECTOR_SIZE_BYTES)
#define ADS_QUERY_NUM (sizeof(ADS_SensorQueryList) / sizeof(sensorAccess_t))
#define ADS_NUM_BOARDS (sizeof(gADS_QueryMap) / ADS_QUERY_NUM)
#define SPI_MAX_MSG_SIZE (64)
Functions
void ADS_FXLS8471Q_SPI_ReadPreprocess (void *pCmdOut, uint32_t offset, uint32_t size)
void ADS_FXLS8471Q_SPI_WritePreprocess (void *pCmdOut, uint32_t offset, uint32_t size, void *pWritebuffer)
void ADS_InitSPI_FXLS8471 ()
ADS_Status_t ADS_FXLS8471Query (uint8_t whoAmiAddr, uint8_t whoAmi)
void ADS_FXLS8962_SPI_ReadPreprocess (void *pCmdOut, uint32_t offset, uint32_t size)
void ADS_FXLS8962_SPI_WritePreprocess (void *pCmdOut, uint32_t offset, uint32_t size, void *pWritebuffer)
void ADS_InitSPI_FXLS8962 ()
ADS_Status_t ADS_FXLS8962Query (uint8_t whoAmiAddr, uint8_t whoAmi)
ADS_Status_t ADS_FXLC95000Query ()
ADS_Status_t ADS_MMA9553Query ()
int ADS_InitI2CBuses ()
int ADS_InitSPIBus ()
int ADS_DeInitI2CBuses ()
int ADS_DeInitSPIBus ()
int ADS_DetectShield (char *pShieldString, size_t bufferLength)
int ADS_DetectLPC (char *pBoardString, size_t bufferLength)
ADS_FlashStatus_t ADS_FlashCompare (char *pResultString)
ADS_Status_t ADS_FlashUpdate (char *pResultString)
void BOARD_RunADS (const char *appName, char *boardString, char *shieldString, size_t bufferLength)
The function to register Application Name and initialte ADS.
Variables
const uint8_t ReadVersionInfo_MMA9553 [4] = {0x00, 0x00, 0x00, 0x0C}
The Read Version Info Command for FXLC95000.
const mcuDEVID_t ADS_ValidDEVIDValues []
This constant data structure contains the expected valid MCU Device ID combinations. Refer : LPC5411x User manual - UM10914, Section: 33.5.12.
const sensorAccess_t ADS_SensorQueryList []
This constant data structure contains the expected valid comm/sensor/who_am_i combinations.
const ADS_Status_t gADS_QueryMap [][ADS_QUERY_NUM]
These are the expected query signatures for the shield boards.
ADS_Status_t gADS_QueryResults [ADS_QUERY_NUM]
This global contains the results from the sensor query.
char ADS_ShieldList [][ADS_MAX_STRING_LENGTH]
ARM_DRIVER_SPI * SPIdrv = &SPI_S_DRIVER
These values hold the ARM CMSIS Driver interface pointers.
ARM_DRIVER_I2C * I2CextDrv = &I2C_S1_DRIVER
GENERIC_DRIVER_GPIO * pGPIODriver = &Driver_GPIO_KSDK
spiSlaveSpecificParams_t spiParams_8471
spiSlaveSpecificParams_t spiParams_8962
uint8_t spiRead_CmdBuffer [SPI_MAX_MSG_SIZE] = {0}
uint8_t spiRead_DataBuffer [SPI_MAX_MSG_SIZE] = {0}
uint8_t spiWrite_CmdDataBuffer [SPI_MAX_MSG_SIZE] = {0}
Macro Definition Documentation
#define ADS_NUM_BOARDS (sizeof(gADS_QueryMap) / ADS_QUERY_NUM)
Definition at line 78 of file auto_detection_service.c.
Referenced by ADS_DetectShield().
#define ADS_NVM_SECTOR_NUM (ADS_NVM_ADDR / FSL_FEATURE_SYSCON_FLASH_SECTOR_SIZE_BYTES)
Definition at line 76 of file auto_detection_service.c.
Referenced by ADS_FlashUpdate().
#define ADS_QUERY_NUM (sizeof(ADS_SensorQueryList) / sizeof(sensorAccess_t))
Definition at line 77 of file auto_detection_service.c.
Referenced by ADS_DetectShield().
#define FXLS8471Q_SPI_CMD_LEN (2)
These variables are specific to SPI access to the FXLS8471 for ADS.
Definition at line 67 of file auto_detection_service.c.
Referenced by ADS_FXLS8471Q_SPI_ReadPreprocess(), ADS_FXLS8471Q_SPI_WritePreprocess(), and ADS_InitSPI_FXLS8471().
#define FXLS8471Q_SS_ACTIVE_VALUE SPI_SS_ACTIVE_LOW
Definition at line 68 of file auto_detection_service.c.
Referenced by ADS_InitSPI_FXLS8471().
#define FXLS8962_SPI_CMD_LEN (2)
These variables are specific to SPI access to the FXLS8962 for ADS.
Definition at line 73 of file auto_detection_service.c.
Referenced by ADS_FXLS8962_SPI_ReadPreprocess(), ADS_FXLS8962_SPI_WritePreprocess(), and ADS_InitSPI_FXLS8962().
#define FXLS8962_SS_ACTIVE_VALUE SPI_SS_ACTIVE_LOW
Definition at line 74 of file auto_detection_service.c.
Referenced by ADS_InitSPI_FXLS8962().
#define SPI_MAX_MSG_SIZE (64)
Definition at line 79 of file auto_detection_service.c.
Function Documentation
int ADS_DeInitI2CBuses ()
De-Initialize the External I2C driver.
Definition at line 525 of file auto_detection_service.c.
References I2CextDrv, and int32_t().
Referenced by ADS_DetectShield().
int ADS_DeInitSPIBus ()
De-Initialize the SPI0 driver.
Definition at line 539 of file auto_detection_service.c.
References int32_t(), and SPIdrv.
Referenced by ADS_DetectShield().
int ADS_DetectLPC (char * pBoardString, size_t bufferLength)
Definition at line 663 of file auto_detection_service.c.
References ADS_LPC_54113J128, ADS_LPC_54113J256, ADS_LPC_54114J256, ADS_NO_BOARD_DETECTED, ADS_ValidDEVIDValues, mcuDEVID_t::board, int32_t(), and mcuDEVID_t::mcuDeviceId.
Referenced by BOARD_RunADS().
int ADS_DetectShield (char * pShieldString, size_t bufferLength)
Definition at line 554 of file auto_detection_service.c.
References ADS_DeInitI2CBuses(), ADS_DeInitSPIBus(), ADS_FAIL, ADS_FXLC95000Query(), ADS_FXLS8471Query(), ADS_FXLS8962Query(), ADS_I2C_EXT, ADS_InitI2CBuses(), ADS_InitSPI_FXLS8471(), ADS_InitSPI_FXLS8962(), ADS_InitSPIBus(), ADS_MMA9553Query(), ADS_NO_SHIELD_DETECTED, ADS_NULL, ADS_NUM_BOARDS, ADS_OK, ADS_QUERY_NUM, ADS_ShieldList, ADS_SPI_DEV, PhysicalSensor::deviceInfo, registerDeviceInfo_t::deviceInstance, FXLC95000, FXLS8471, FXLS8962, gADS_QueryMap, gADS_QueryResults, I2C_S1_DEVICE_INDEX, I2CextDrv, int32_t(), MMA9553, and Register_I2C_Read().
Referenced by BOARD_RunADS().
ADS_FlashStatus_t ADS_FlashCompare (char * pResultString)
Definition at line 713 of file auto_detection_service.c.
References ADS_COOKIE_VALUE, ADS_FLASH_RECORD_CHANGE, ADS_FLASH_RECORD_NO_CHANGE, ADS_NO_FLASH_RECORD, ADS_NVM_ADDR, ADSFlashRecord_t::ADSString, ADSFlashRecord_t::cookie, and ADSFlashRecord_t::length.
Referenced by BOARD_RunADS().
ADS_Status_t ADS_FlashUpdate (char * pResultString)
Definition at line 742 of file auto_detection_service.c.
References ADS_COOKIE_VALUE, ADS_FAIL, ADS_NVM_ADDR, ADS_NVM_SECTOR_NUM, ADS_OK, ADSFlashRecord_t::ADSString, ADSFlashRecord_t::cookie, ADSFlashRecord_t::length, and SystemCoreClock.
Referenced by BOARD_RunADS().
ADS_Status_t ADS_FXLC95000Query ()
Definition at line 413 of file auto_detection_service.c.
References ADS_FAIL, ADS_OK, BOARD_DELAY_ms(), PhysicalSensor::deviceInfo, registerDeviceInfo_t::deviceInstance, FXLC95000_I2C_ADDR, FXLC95000_PART_NUMBER, FXLC95000_PART_NUMBER_OFFSET, FXLC95000_PART_NUMBER_SIZE, I2C_S1_DEVICE_INDEX, I2CextDrv, int32_t(), Register_I2C_BlockWrite(), and Register_I2C_Read().
Referenced by ADS_DetectShield().
void ADS_FXLS8471Q_SPI_ReadPreprocess (void * pCmdOut, uint32_t offset, uint32_t size)
Definition at line 275 of file auto_detection_service.c.
References FXLS8471Q_SPI_CMD_LEN, spi_mater_SlaveCmd::pReadBuffer, spi_mater_SlaveCmd::pWriteBuffer, spi_mater_SlaveCmd::size, spiRead_CmdBuffer, and spiRead_DataBuffer.
Referenced by ADS_InitSPI_FXLS8471().
void ADS_FXLS8471Q_SPI_WritePreprocess (void * pCmdOut, uint32_t offset, uint32_t size, void * pWritebuffer)
Definition at line 292 of file auto_detection_service.c.
References FXLS8471Q_SPI_CMD_LEN, spi_mater_SlaveCmd::pReadBuffer, spi_mater_SlaveCmd::pWriteBuffer, spi_mater_SlaveCmd::size, and spiWrite_CmdDataBuffer.
Referenced by ADS_InitSPI_FXLS8471().
ADS_Status_t ADS_FXLS8471Query (uint8_t whoAmiAddr, uint8_t whoAmi)
Read and store the device's WHO_AM_I.
Definition at line 324 of file auto_detection_service.c.
References ADS_FAIL, ADS_OK, PhysicalSensor::deviceInfo, registerDeviceInfo_t::deviceInstance, int32_t(), Register_SPI_Read(), SPI_S_DEVICE_INDEX, and SPIdrv.
Referenced by ADS_DetectShield().
void ADS_FXLS8962_SPI_ReadPreprocess (void * pCmdOut, uint32_t offset, uint32_t size)
Definition at line 344 of file auto_detection_service.c.
References FXLS8962_SPI_CMD_LEN, spi_mater_SlaveCmd::pReadBuffer, spi_mater_SlaveCmd::pWriteBuffer, spi_mater_SlaveCmd::size, spiRead_CmdBuffer, and spiRead_DataBuffer.
Referenced by ADS_InitSPI_FXLS8962().
void ADS_FXLS8962_SPI_WritePreprocess (void * pCmdOut, uint32_t offset, uint32_t size, void * pWritebuffer)
Definition at line 361 of file auto_detection_service.c.
References FXLS8962_SPI_CMD_LEN, spi_mater_SlaveCmd::pReadBuffer, spi_mater_SlaveCmd::pWriteBuffer, spi_mater_SlaveCmd::size, and spiWrite_CmdDataBuffer.
Referenced by ADS_InitSPI_FXLS8962().
ADS_Status_t ADS_FXLS8962Query (uint8_t whoAmiAddr, uint8_t whoAmi)
Read and store the device's WHO_AM_I.
Definition at line 393 of file auto_detection_service.c.
References ADS_FAIL, ADS_OK, PhysicalSensor::deviceInfo, registerDeviceInfo_t::deviceInstance, int32_t(), Register_SPI_Read(), SPI_S_DEVICE_INDEX, and SPIdrv.
Referenced by ADS_DetectShield().
int ADS_InitI2CBuses ()
Initialize the External I2C driver.
Set the External I2C Power mode.
Set the External I2C bus speed.
Definition at line 469 of file auto_detection_service.c.
References I2C_S1_SIGNAL_EVENT, I2CextDrv, and int32_t().
Referenced by ADS_DetectShield().
void ADS_InitSPI_FXLS8471 ()
Definition at line 312 of file auto_detection_service.c.
References ADS_FXLS8471Q_SPI_ReadPreprocess(), ADS_FXLS8471Q_SPI_WritePreprocess(), FXLS8471_SPI_CS, FXLS8471Q_SPI_CMD_LEN, FXLS8471Q_SS_ACTIVE_VALUE, GPIO_DIRECTION_OUT, GENERIC_DRIVER_GPIO::pin_init, spiSlaveSpecificParams_t::pReadPreprocessFN, spiSlaveSpecificParams_t::pTargetSlavePinID, spiSlaveSpecificParams_t::pWritePreprocessFN, spiSlaveSpecificParams_t::spiCmdLen, and spiSlaveSpecificParams_t::ssActiveValue.
Referenced by ADS_DetectShield().
void ADS_InitSPI_FXLS8962 ()
Initialize the sensor handle.
Definition at line 381 of file auto_detection_service.c.
References ADS_FXLS8962_SPI_ReadPreprocess(), ADS_FXLS8962_SPI_WritePreprocess(), FXLS8962_CS, FXLS8962_SPI_CMD_LEN, FXLS8962_SS_ACTIVE_VALUE, GPIO_DIRECTION_OUT, GENERIC_DRIVER_GPIO::pin_init, spiSlaveSpecificParams_t::pReadPreprocessFN, spiSlaveSpecificParams_t::pTargetSlavePinID, spiSlaveSpecificParams_t::pWritePreprocessFN, spiSlaveSpecificParams_t::spiCmdLen, and spiSlaveSpecificParams_t::ssActiveValue.
Referenced by ADS_DetectShield().
int ADS_InitSPIBus ()
Initialize the SPI driver.
Set the SPI Power mode.
Set the SPI Slave speed.
Definition at line 497 of file auto_detection_service.c.
References int32_t(), SPI_S_BAUDRATE, SPI_S_SIGNAL_EVENT, and SPIdrv.
Referenced by ADS_DetectShield().
ADS_Status_t ADS_MMA9553Query ()
Definition at line 442 of file auto_detection_service.c.
References ADS_FAIL, ADS_OK, BOARD_DELAY_ms(), PhysicalSensor::deviceInfo, registerDeviceInfo_t::deviceInstance, I2C_S1_DEVICE_INDEX, I2CextDrv, int32_t(), MMA9553_HDR_SIZE, MMA9553_I2C_ADDR, ReadVersionInfo_MMA9553, Register_I2C_BlockWrite(), and Register_I2C_Read().
Referenced by ADS_DetectShield().
void BOARD_RunADS (const char * appName, char * boardString, char * shieldString, size_t bufferLength)
The function to register Application Name and initialte ADS.
The API will read the Application Name from the user and return the result string with the ADS detection results. It will also update the FLASH with the new results.
Parameters
[in] pAppName - pointer to a buffer where the application name is placed.
Definition at line 778 of file auto_detection_service.c.
Referenced by main().
Variable Documentation
const sensorAccess_t ADS_SensorQueryList[]
Initial value:
= {
    {ADS_SPI_DEV, FXLS8471, FXLS8471Q_WHO_AM_I, FXLS8471Q_WHO_AM_I_WHOAMI_VALUE},
    {ADS_SPI_DEV, FXLS8962, FXLS8962_WHO_AM_I, FXLS8962_WHOAMI_VALUE},
    {ADS_I2C_EXT, FXLS8962_I2C_ADDR, FXLS8962_WHO_AM_I, FXLS8962_WHOAMI_VALUE},
    {ADS_I2C_EXT, FXAS21002_I2C_ADDR, FXAS21002_WHO_AM_I, FXAS21002_WHO_AM_I_WHOAMI_PROD_VALUE},
    {ADS_I2C_EXT, FXLC95000, ADS_NO_WHO_AM_I, ADS_NO_WHO_AM_I},
    {ADS_I2C_EXT, FXOS8700_I2C_ADDR, FXOS8700_WHO_AM_I, FXOS8700_WHO_AM_I_PROD_VALUE},
    {ADS_I2C_EXT, FXPQ3115_I2C_ADDR, FXPQ3115_WHO_AM_I, FXPQ3115_WHOAMI_VALUE},
    {ADS_I2C_EXT, MAG3110_I2C_ADDR, MAG3110_WHO_AM_I, MAG3110_WHOAMI_VALUE},
    {ADS_I2C_EXT, MMA8652_I2C_ADDR, MMA865x_WHO_AM_I, MMA8652_WHOAMI_VALUE},
    {ADS_I2C_EXT, MMA9553, ADS_NO_WHO_AM_I, ADS_NO_WHO_AM_I},
    {ADS_I2C_EXT, MPL3115_I2C_ADDR, MPL3115_WHO_AM_I, MPL3115_WHOAMI_VALUE},
}
This constant data structure contains the expected valid comm/sensor/who_am_i combinations.
Definition at line 100 of file auto_detection_service.c.
char ADS_ShieldList[][ADS_MAX_STRING_LENGTH]
Initial value:
= {
    "FRDM-STBC-AGM01",  "FRDM-STBC-SA9500", "FRDMSTBC-A8471",   "FRDMSTBC-P3115",  "FRDMSTBC-B3115",
    "FRDM-FXS-MULT2-B", "FRDM-STBC-AGMP03", "FRDM-STBC-AGMP03", "FRDM-STBC-AGM04",
}
Definition at line 254 of file auto_detection_service.c.
Referenced by ADS_DetectShield().
const mcuDEVID_t ADS_ValidDEVIDValues[]
Initial value:
= {
    {0x06254113, ADS_LPC_54113J128},
    {0x36454113, ADS_LPC_54113J256},
    {0x36454114, ADS_LPC_54114J256},
}
This constant data structure contains the expected valid MCU Device ID combinations. Refer : LPC5411x User manual - UM10914, Section: 33.5.12.
Definition at line 91 of file auto_detection_service.c.
Referenced by ADS_DetectLPC().
const ADS_Status_t gADS_QueryMap[][ADS_QUERY_NUM]
These are the expected query signatures for the shield boards.
Definition at line 117 of file auto_detection_service.c.
Referenced by ADS_DetectShield().
ADS_Status_t gADS_QueryResults[ADS_QUERY_NUM]
This global contains the results from the sensor query.
Definition at line 252 of file auto_detection_service.c.
Referenced by ADS_DetectShield().
ARM_DRIVER_I2C* I2CextDrv = &I2C_S1_DRIVER
Definition at line 263 of file auto_detection_service.c.
Referenced by ADS_DeInitI2CBuses(), ADS_DetectShield(), ADS_FXLC95000Query(), ADS_InitI2CBuses(), and ADS_MMA9553Query().
GENERIC_DRIVER_GPIO* pGPIODriver = &Driver_GPIO_KSDK
Definition at line 264 of file auto_detection_service.c.
Referenced by FXAS21002_SPI_Initialize(), FXLC95000_SPI_Initialize(), FXLS8471Q_Init(), FXLS8471Q_SPI_Initialize(), FXLS8962_SPI_Initialize(), FXOS8700_SPI_Initialize(), and MMA9553_SPI_Initialize().
const uint8_t ReadVersionInfo_MMA9553[4] = {0x00, 0x00, 0x00, 0x0C}
The Read Version Info Command for FXLC95000.
Definition at line 85 of file auto_detection_service.c.
Referenced by ADS_MMA9553Query().
ARM_DRIVER_SPI* SPIdrv = &SPI_S_DRIVER
These values hold the ARM CMSIS Driver interface pointers.
Definition at line 262 of file auto_detection_service.c.
Referenced by ADS_DeInitSPIBus(), ADS_FXLS8471Query(), ADS_FXLS8962Query(), and ADS_InitSPIBus().
spiSlaveSpecificParams_t spiParams_8471
Definition at line 266 of file auto_detection_service.c.
spiSlaveSpecificParams_t spiParams_8962
Definition at line 267 of file auto_detection_service.c.
uint8_t spiRead_CmdBuffer[SPI_MAX_MSG_SIZE] = {0}
Definition at line 268 of file auto_detection_service.c.
Referenced by ADS_FXLS8471Q_SPI_ReadPreprocess(), and ADS_FXLS8962_SPI_ReadPreprocess().
uint8_t spiRead_DataBuffer[SPI_MAX_MSG_SIZE] = {0}
Definition at line 269 of file auto_detection_service.c.
Referenced by ADS_FXLS8471Q_SPI_ReadPreprocess(), and ADS_FXLS8962_SPI_ReadPreprocess().
uint8_t spiWrite_CmdDataBuffer[SPI_MAX_MSG_SIZE] = {0}
Definition at line 270 of file auto_detection_service.c.
Referenced by ADS_FXLS8471Q_SPI_WritePreprocess(), and ADS_FXLS8962_SPI_WritePreprocess().