ISSDK: algorithms/sensorfusion/sources/main_freertos_agm02.c File Reference
main_freertos_agm02.c File Reference
FreeRTOS (two task) implementation of sensor fusion on FRDM-K64F/FRDM-FXS-AGM02.
#include "fsl_debug_console.h"
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_port.h"
#include "fsl_i2c.h"
#include "register_io_i2c.h"
#include "fsl_i2c_cmsis.h"
#include "sensor_fusion.h"
#include "control.h"
#include "status.h"
#include "drivers.h"
#include "driver_pit.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"
#include "event_groups.h"
Functions
int main (void)
This is a FreeRTOS (dual task) implementation of the NXP sensor fusion demo build.
Variables
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
ControlSubsystem controlSubsystem
used for serial communications
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
struct PhysicalSensor sensors [3]
This implementation uses three physical sensors.
EventGroupHandle_t event_group = NULL
registerDeviceInfo_t i2cBusInfo
Detailed Description
FreeRTOS (two task) implementation of sensor fusion on FRDM-K64F/FRDM-FXS-AGM02.
This file shows one recommended way to incorporate sensor fusion capabilities into a FreeRTOS project.
Definition in file main_freertos_agm02.c.
Function Documentation
int main (void)
This is a FreeRTOS (dual task) implementation of the NXP sensor fusion demo build.
Definition at line 79 of file main_freertos_agm02.c.
References SensorFusionGlobals::applyPerturbation, B0, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), SensorFusionGlobals::conditionSensorReadings, event_group, FXAS21002_I2C_ADDR, FXAS21002_Init(), FXAS21002_Read(), FXLS8952_Init(), FXLS8952_Read(), HARD_FAULT, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, initializeControlPort(), SensorFusionGlobals::initializeFusionEngine, initializeStatusSubsystem(), initSensorFusionGlobals(), SensorFusionGlobals::installSensor, SensorFusionGlobals::loopcounter, MAG3110_I2C_ADDR, MAG3110_Init(), MAG3110_Read(), NORMAL, OVERSAMPLE_RATE, SensorFusionGlobals::pControlSubsystem, SensorFusionGlobals::queueStatus, SensorFusionGlobals::readSensors, SensorFusionGlobals::runFusion, sensors, SensorFusionGlobals::setStatus, ControlSubsystem::stream, sUARTOutputBuffer, and SensorFusionGlobals::updateStatus.
Variable Documentation
ControlSubsystem controlSubsystem
used for serial communications
Definition at line 64 of file main_freertos_agm02.c.
EventGroupHandle_t event_group = NULL
Definition at line 67 of file main_freertos_agm02.c.
Referenced by main().
registerDeviceInfo_t i2cBusInfo
Initial value:
= {
    .deviceInstance     = I2C_S_DEVICE_INDEX,
    .functionParam      = NULL,
    .idleFunction       = NULL
}
Definition at line 69 of file main_freertos_agm02.c.
struct PhysicalSensor sensors[3]
This implementation uses three physical sensors.
Definition at line 66 of file main_freertos_agm02.c.
Referenced by main().
SensorFusionGlobals sfg
This is the primary sensor fusion data structure.
Definition at line 63 of file main_freertos_agm02.c.
StatusSubsystem statusSubsystem
provides visual (usually LED) status indicator
Definition at line 65 of file main_freertos_agm02.c.