ISSDK: driverexamples/mma865x/mma865x_fifo.c File Reference
mma865x_fifo.c File Reference
The mma865x_fifo.c file implements the ISSDK MMA865x sensor driver example demonstration with FIFO mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "mma865x_drv.h"
#include "systick_utils.h"
Macros
#define FIFO_WATERMARK (16) /* Must be between 1 - 32 */
#define MMA865x_ACCEL_DATA_SIZE (6) /* 2 byte X,Y,Z Axis Data each. */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t cMma865xConfigFifo []
const registerreadlist_t cMma865xFifoStatus [] = {{.readFrom = MMA865x_F_STATUS, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t cMma865xOutputValues []
Detailed Description
The mma865x_fifo.c file implements the ISSDK MMA865x sensor driver example demonstration with FIFO mode.
Definition in file mma865x_fifo.c.
Macro Definition Documentation
#define FIFO_WATERMARK (16) /* Must be between 1 - 32 */
Definition at line 60 of file mma865x_fifo.c.
Referenced by main().
#define MMA865x_ACCEL_DATA_SIZE (6) /* 2 byte X,Y,Z Axis Data each. */
Definition at line 61 of file mma865x_fifo.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the MMA865x sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MMA865x sensor driver with FIFO mode.
Wait for data ready from the MMA865x.
Read the raw sensor data from the MMA865x.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 92 of file mma865x_fifo.c.
References mma865x_acceldata_t::accel, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), FIFO_WATERMARK, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8652_I2C_ADDR, MMA8652_WHOAMI_VALUE, MMA865x_ACCEL_DATA_SIZE, MMA865x_F_STATUS_F_WMKF_MASK, MMA865x_I2C_Configure(), MMA865x_I2C_Initialize(), MMA865x_I2C_ReadData(), MMA865x_I2C_SetIdleTask(), SENSOR_ERROR_NONE, SMC, and SMC_SetPowerModeWait().
Variable Documentation
const registerwritelist_t cMma865xConfigFifo[]
Initial value:
=
    {
     {MMA865x_F_SETUP, MMA865x_F_SETUP_F_MODE_STOP_MODE | FIFO_WATERMARK,
      MMA865x_F_SETUP_F_MODE_MASK | MMA865x_F_SETUP_F_WMRK_MASK},
     {MMA865x_XYZ_DATA_CFG, MMA865x_XYZ_DATA_CFG_FS_2G, MMA865x_XYZ_DATA_CFG_FS_MASK},
     {MMA865x_CTRL_REG1, MMA865x_CTRL_REG1_DR_100HZ, MMA865x_CTRL_REG1_DR_MASK},
     {MMA865x_CTRL_REG2, MMA865x_CTRL_REG2_MODS_HR, MMA865x_CTRL_REG2_MODS_MASK},
     __END_WRITE_DATA__}
Prepare the register write list to configure MMA865x in FIFO mode.
Definition at line 67 of file mma865x_fifo.c.
const registerreadlist_t cMma865xFifoStatus[] = {{.readFrom = MMA865x_F_STATUS, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read the FIFO Status from MMA865x.
Definition at line 80 of file mma865x_fifo.c.
const registerreadlist_t cMma865xOutputValues[]
Initial value:
= {
    {.readFrom = MMA865x_OUT_X_MSB, .numBytes = MMA865x_ACCEL_DATA_SIZE * FIFO_WATERMARK}, __END_READ_DATA__}
Prepare the register read list to read the raw Accel data from MMA865x.
Definition at line 83 of file mma865x_fifo.c.