ISSDK: driverexamples/demos/FRDM-K64F/mma865x_demo.c File Reference
mma865x_demo.c File Reference
The mma865x_demo.c file implements the ISSDK MMA865x sensor demo example demonstration with interrupt mode for FRDM-K64F.
#include "board.h"
#include "pin_mux.h"
#include "fsl_uart.h"
#include "clock_config.h"
#include "Driver_I2C.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_uart_cmsis.h"
#include "issdk_hal.h"
#include "mma865x_drv.h"
#include "gpio_driver.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define MMA865x_ACCEL_DATA_SIZE 6 /* 2 byte X,Y,Z Axis Data each. */
#define MMA865x_STREAM_DATA_SIZE 10
#define APPLICATION_NAME "MMA8652FC"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Functions
void mma865x_int_data_ready_callback (void *pUserData)
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerwritelist_t cMma865xConfigInterrupt []
const registerreadlist_t cMma865xOutputValues []
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bMma865xDataReady = false
volatile bool bMma865xReady = false
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Detailed Description
The mma865x_demo.c file implements the ISSDK MMA865x sensor demo example demonstration with interrupt mode for FRDM-K64F.
Definition in file mma865x_demo.c.
Macro Definition Documentation
#define APPLICATION_NAME "MMA8652FC"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 70 of file mma865x_demo.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 72 of file mma865x_demo.c.
Referenced by main().
#define MMA865x_ACCEL_DATA_SIZE 6 /* 2 byte X,Y,Z Axis Data each. */
Definition at line 66 of file mma865x_demo.c.
Referenced by main().
#define MMA865x_STREAM_DATA_SIZE 10
Definition at line 67 of file mma865x_demo.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize MMA865x pin used by FRDM board
Initialize RGB LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize MMA865x sensor driver.
Set the task to be executed while waiting for SPI transactions to complete.
Configure the MMA865x sensor.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Clear the data ready flag, it will be set again by the ISR.
Read new raw sensor data from the MMA865x.
Convert the raw sensor data to signed 16-bit container for display to the debug port.
Definition at line 198 of file mma865x_demo.c.
References mma865x_acceldata_t::accel, ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bMma865xDataReady, bMma865xReady, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, mma865x_i2c_sensorhandle_t::deviceInfo, embAppName, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, gStreamID, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8652_I2C_ADDR, MMA8652_INT1, MMA8652_WHOAMI_VALUE, MMA865x_ACCEL_DATA_SIZE, MMA865x_I2C_Configure(), MMA865x_I2C_Initialize(), MMA865x_I2C_ReadData(), MMA865x_I2C_SetIdleTask(), mma865x_int_data_ready_callback(), MMA865x_STREAM_DATA_SIZE, mma865x_i2c_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, process_host_command(), RED_LED, SENSOR_ERROR_NONE, SHIELD_NAME, shieldString, SMC, SMC_SetPowerModeWait(), STREAMING_HEADER_LEN, mma865x_acceldata_t::timestamp, and GENERIC_DRIVER_GPIO::toggle_pin.
void mma865x_int_data_ready_callback (void * pUserData)
Set flag to indicate Sensor has signalled data ready.
Definition at line 110 of file mma865x_demo.c.
References bMma865xDataReady.
Referenced by main().
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 116 of file mma865x_demo.c.
References bMma865xReady, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, RED_LED, and shieldString.
Referenced by main().
Variable Documentation
volatile bool bMma865xDataReady = false
Definition at line 102 of file mma865x_demo.c.
Referenced by main(), and mma865x_int_data_ready_callback().
volatile bool bMma865xReady = false
Definition at line 102 of file mma865x_demo.c.
Referenced by main(), and process_host_command().
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 100 of file mma865x_demo.c.
Referenced by main(), and process_host_command().
volatile bool bStreamingEnabled = false
Definition at line 102 of file mma865x_demo.c.
Referenced by main(), and process_host_command().
const registerwritelist_t cMma865xConfigInterrupt[]
Initial value:
=
    {
     {MMA865x_XYZ_DATA_CFG, MMA865x_XYZ_DATA_CFG_FS_2G, MMA865x_XYZ_DATA_CFG_FS_MASK},
     {MMA865x_CTRL_REG1, MMA865x_CTRL_REG1_DR_6_25HZ, MMA865x_CTRL_REG1_DR_MASK},
     {MMA865x_CTRL_REG2, MMA865x_CTRL_REG2_MODS_HR, MMA865x_CTRL_REG2_MODS_MASK},
     {MMA865x_CTRL_REG3, MMA865x_CTRL_REG3_IPOL_ACTIVE_HIGH, MMA865x_CTRL_REG3_IPOL_MASK},
     {MMA865x_CTRL_REG4, MMA865x_CTRL_REG4_INT_EN_DRDY_EN, MMA865x_CTRL_REG4_INT_EN_DRDY_MASK},
     {MMA865x_CTRL_REG5, MMA865x_CTRL_REG5_INT_CFG_DRDY_INT1, MMA865x_CTRL_REG5_INT_CFG_DRDY_MASK},
     __END_WRITE_DATA__}
Prepare the register write list to configure MMA865x in non-FIFO and ISR mode.
Definition at line 78 of file mma865x_demo.c.
const registerreadlist_t cMma865xOutputValues[]
Initial value:
= {{.readFrom = MMA865x_OUT_X_MSB, .numBytes = MMA865x_ACCEL_DATA_SIZE},
                                                   __END_READ_DATA__}
Prepare the register read list to read the raw Accel data from MMA865x.
Definition at line 94 of file mma865x_demo.c.
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 101 of file mma865x_demo.c.
Referenced by main(), and process_host_command().
uint8_t gStreamID
Definition at line 103 of file mma865x_demo.c.
Referenced by main(), and process_host_command().
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 104 of file mma865x_demo.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 100 of file mma865x_demo.c.
Referenced by main(), and process_host_command().