ISSDK: driverexamples/mma8491q/mma8491q_example.c File Reference
mma8491q_example.c File Reference
The mma8491q_example.c file implements the ISSDK MMA8491Q sensor driver example demonstration with polling mode.
#include "board.h"
#include "pin_mux.h"
#include "fsl_lptmr.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "Driver_GPIO.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "mma8491q_drv.h"
#include "systick_utils.h"
#include "gpio_driver.h"
Macros
#define mma8491q_en_callback LPTMR0_IRQHandler
#define LPTMR_T_START_STOP 2U
#define MMA8491Q_T_ODR_ms 10U
Functions
void mma8491q_en_callback (void)
void mma8491q_mode_fwk_init (mma8491q_context_t *pSensorContext, void *pEN)
void mma8491q_mode_activate (mma8491q_context_t *pSensorContext)
void mma8491q_mode_shutdown (mma8491q_context_t *pSensorContext)
int main (void)
Main function.
Variables
const registerreadlist_t cMma8491qStatus [] = {{.readFrom = MMA8491Q_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t cMma8491qOutput []
Address and size of Raw Acceleration Data.
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
gpioConfigKSDK_t gGpioConfigInPins
mma8491q_context_t gSensorContext
Detailed Description
The mma8491q_example.c file implements the ISSDK MMA8491Q sensor driver example demonstration with polling mode.
Definition in file mma8491q_example.c.
Macro Definition Documentation
#define LPTMR_T_START_STOP 2U
Definition at line 67 of file mma8491q_example.c.
Referenced by mma8491q_mode_fwk_init().
#define mma8491q_en_callback LPTMR0_IRQHandler
Definition at line 65 of file mma8491q_example.c.
#define MMA8491Q_T_ODR_ms 10U
Definition at line 69 of file mma8491q_example.c.
Referenced by mma8491q_mode_fwk_init().
Function Documentation
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize MMA8491_EN Pin handling framework.
Set the task to be executed while waiting for I2C transactions to complete.
Wait for data ready from the MMA8491Q.
Read the raw sensor data from the MMA8491Q.
Process the sample and convert the raw sensor data.
Definition at line 202 of file mma8491q_example.c.
References mma8491q_acceldata_t::accel, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8491_EN, MMA8491_I2C_ADDR, MMA8491_XOUT, MMA8491_YOUT, MMA8491_ZOUT, MMA8491Q_DATA_SIZE, MMA8491Q_I2C_Initialize(), MMA8491Q_I2C_ReadData(), MMA8491Q_I2C_SetIdleTask(), mma8491q_mode_activate(), mma8491q_mode_fwk_init(), mma8491q_mode_shutdown(), MMA8491Q_STATUS_ZYXDR_MASK, GENERIC_DRIVER_GPIO::pin_init, GENERIC_DRIVER_GPIO::read_pin, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), mma8491q_acceldata_t::tilt, and mma8491q_acceldata_t::timestamp.
void mma8491q_en_callback (void)
Definition at line 98 of file mma8491q_example.c.
References mma8491q_context_t::inTransition.
void mma8491q_mode_activate (mma8491q_context_t * pSensorContext)
Definition at line 152 of file mma8491q_example.c.
References mma8491q_context_t::inTransition, MMA8491Q_T_ON_TYPICAL, mma8491q_context_t::pGpioEN, SENSOR_MODE_STANDBY, mma8491q_context_t::sensorMode, GENERIC_DRIVER_GPIO::set_pin, SMC, and SMC_SetPowerModeWait().
Referenced by main().
void mma8491q_mode_fwk_init (mma8491q_context_t * pSensorContext, void * pEN)
Definition at line 106 of file mma8491q_example.c.
References mma8491q_context_t::adjustedODR, mma8491q_context_t::inTransition, LPTMR_T_START_STOP, MMA8491Q_T_ODR_ms, MMA8491Q_T_ON_TYPICAL, MMA8491Q_T_RST_MIN, mma8491q_context_t::pGpioEN, SENSOR_MODE_ACTIVE, mma8491q_context_t::sensorMode, GENERIC_DRIVER_GPIO::set_pin, SMC, and SMC_SetPowerModeWait().
Referenced by main().
void mma8491q_mode_shutdown (mma8491q_context_t * pSensorContext)
Definition at line 181 of file mma8491q_example.c.
References mma8491q_context_t::adjustedODR, GENERIC_DRIVER_GPIO::clr_pin, mma8491q_context_t::inTransition, mma8491q_context_t::pGpioEN, SENSOR_MODE_SHUTDOWN, and mma8491q_context_t::sensorMode.
Referenced by main().
Variable Documentation
const registerreadlist_t cMma8491qOutput[]
Initial value:
= {{.readFrom = MMA8491Q_OUT_X_MSB, .numBytes = MMA8491Q_DATA_SIZE},
                                              __END_READ_DATA__}
Address and size of Raw Acceleration Data.
Definition at line 78 of file mma8491q_example.c.
const registerreadlist_t cMma8491qStatus[] = {{.readFrom = MMA8491Q_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 75 of file mma8491q_example.c.
gpioConfigKSDK_t gGpioConfigInPins
Initial value:
=
    {
        .pinConfig = {kGPIO_DigitalInput, 0},
        .interruptMode = kPORT_InterruptOrDMADisabled,
        .portPinConfig = {0},
        .portPinConfig.mux = kPORT_MuxAsGpio,
}
Definition at line 85 of file mma8491q_example.c.
mma8491q_context_t gSensorContext
Definition at line 92 of file mma8491q_example.c.
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 84 of file mma8491q_example.c.
Referenced by main().