ISSDK: driverexamples/demos/FRDM-KL25Z/mma8491q_demo.c File Reference
mma8491q_demo.c File Reference
The mma8491q_demo.c file implements the ISSDK MMA8491Q sensor driver demo demonstration with polling mode on FRDM-KL25Z.
#include "board.h"
#include "pin_mux.h"
#include "fsl_lpsci.h"
#include "fsl_lptmr.h"
#include "clock_config.h"
#include "Driver_I2C.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_lpsci_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "mma8491q_drv.h"
#include "host_io_uart.h"
#include "systick_utils.h"
#include "auto_detection_service.h"
Macros
#define mma8491q_en_callback LPTMR0_IRQHandler
#define LPTMR_T_START_STOP 2U
#define MMA8491Q_T_ODR_ms 100U
#define MMA8491Q_STREAM_DATA_SIZE 13 /* The size of Streaming Data in Host Message. */
#define APPLICATION_NAME "MMA8491Q"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Functions
void mma8491q_en_callback (void)
void mma8491q_mode_fwk_init (mma8491q_context_t *pSensorContext, void *pEN)
void mma8491q_mode_activate (mma8491q_context_t *pSensorContext)
void mma8491q_mode_shutdown (mma8491q_context_t *pSensorContext)
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
const registerreadlist_t cMma8491qStatus [] = {{.readFrom = MMA8491Q_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t cMma8491qOutput []
Address and size of Raw Acceleration Data.
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool bStreamingEnabled = false
volatile bool bMma8491qReady = false
mma8491q_context_t gSensorContext
gpioConfigKSDK_t gGpioConfigInPins
uint8_t gStreamID
GENERIC_DRIVER_GPIO * pGpioDriver = &Driver_GPIO_KSDK
Detailed Description
The mma8491q_demo.c file implements the ISSDK MMA8491Q sensor driver demo demonstration with polling mode on FRDM-KL25Z.
Definition in file mma8491q_demo.c.
Macro Definition Documentation
#define APPLICATION_NAME "MMA8491Q"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 76 of file mma8491q_demo.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 78 of file mma8491q_demo.c.
Referenced by main().
#define LPTMR_T_START_STOP 2U
Definition at line 70 of file mma8491q_demo.c.
Referenced by mma8491q_mode_fwk_init().
#define mma8491q_en_callback LPTMR0_IRQHandler
Definition at line 68 of file mma8491q_demo.c.
#define MMA8491Q_STREAM_DATA_SIZE 13 /* The size of Streaming Data in Host Message. */
Definition at line 73 of file mma8491q_demo.c.
Referenced by main().
#define MMA8491Q_T_ODR_ms 100U
Definition at line 72 of file mma8491q_demo.c.
Referenced by mma8491q_mode_fwk_init().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize GREEN LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the UART driver.
Set the UART Power mode.
Set UART Baud Rate.
Initialize MMA8491_EN Pin handling framework.
Set the task to be executed while waiting for I2C transactions to complete.
Initialize streaming and assign a Stream ID.
Populate streaming header.
Process packets only if streaming has been enabled by Host
Process packets only if data ready is indicated by the MMA8491Q.
Read the raw sensor data from the MMA8491Q.
Process the sample and convert the raw sensor data.
Definition at line 293 of file mma8491q_demo.c.
References mma8491q_acceldata_t::accel, ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, bMma8491qReady, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickElapsedTime_us(), BOARD_SystickEnable(), BOARD_SystickStart(), boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, mma8491q_i2c_sensorhandle_t::deviceInfo, embAppName, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, GREEN_LED, gStreamID, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Init(), Host_IO_Receive(), Host_IO_Send(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8491_EN, MMA8491_I2C_ADDR, MMA8491_XOUT, MMA8491_YOUT, MMA8491_ZOUT, MMA8491Q_DATA_SIZE, MMA8491Q_I2C_Initialize(), MMA8491Q_I2C_ReadData(), MMA8491Q_I2C_SetIdleTask(), mma8491q_mode_activate(), mma8491q_mode_fwk_init(), mma8491q_mode_shutdown(), MMA8491Q_STATUS_ZYXDR_MASK, MMA8491Q_STREAM_DATA_SIZE, mma8491q_i2c_sensorhandle_t::pCommDrv, GENERIC_DRIVER_GPIO::pin_init, process_host_command(), GENERIC_DRIVER_GPIO::read_pin, SENSOR_ERROR_NONE, SHIELD_NAME, shieldString, SMC, SMC_SetPowerModeWait(), STREAMING_HEADER_LEN, mma8491q_acceldata_t::tilt, mma8491q_acceldata_t::timestamp, and GENERIC_DRIVER_GPIO::toggle_pin.
void mma8491q_en_callback (void)
Definition at line 111 of file mma8491q_demo.c.
References mma8491q_context_t::inTransition.
void mma8491q_mode_activate (mma8491q_context_t * pSensorContext)
Definition at line 164 of file mma8491q_demo.c.
References mma8491q_context_t::inTransition, MMA8491Q_T_ON_TYPICAL, mma8491q_context_t::pGpioEN, SENSOR_MODE_STANDBY, mma8491q_context_t::sensorMode, GENERIC_DRIVER_GPIO::set_pin, SMC, and SMC_SetPowerModeWait().
Referenced by main().
void mma8491q_mode_fwk_init (mma8491q_context_t * pSensorContext, void * pEN)
Definition at line 119 of file mma8491q_demo.c.
References mma8491q_context_t::adjustedODR, mma8491q_context_t::inTransition, LPTMR_T_START_STOP, MMA8491Q_T_ODR_ms, MMA8491Q_T_ON_TYPICAL, MMA8491Q_T_RST_MIN, mma8491q_context_t::pGpioEN, SENSOR_MODE_ACTIVE, mma8491q_context_t::sensorMode, GENERIC_DRIVER_GPIO::set_pin, SMC, and SMC_SetPowerModeWait().
Referenced by main().
void mma8491q_mode_shutdown (mma8491q_context_t * pSensorContext)
Definition at line 193 of file mma8491q_demo.c.
References mma8491q_context_t::adjustedODR, GENERIC_DRIVER_GPIO::clr_pin, mma8491q_context_t::inTransition, mma8491q_context_t::pGpioEN, SENSOR_MODE_SHUTDOWN, and mma8491q_context_t::sensorMode.
Referenced by main().
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 211 of file mma8491q_demo.c.
References bMma8491qReady, boardString, bStreamingEnabled, GENERIC_DRIVER_GPIO::clr_pin, embAppName, GREEN_LED, gStreamID, HOST_CMD_START, HOST_CMD_STOP, HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, and shieldString.
Referenced by main().
Variable Documentation
volatile bool bMma8491qReady = false
Definition at line 95 of file mma8491q_demo.c.
Referenced by main(), and process_host_command().
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 93 of file mma8491q_demo.c.
Referenced by main(), and process_host_command().
volatile bool bStreamingEnabled = false
Definition at line 95 of file mma8491q_demo.c.
Referenced by main(), and process_host_command().
const registerreadlist_t cMma8491qOutput[]
Initial value:
= {{.readFrom = MMA8491Q_OUT_X_MSB, .numBytes = MMA8491Q_DATA_SIZE},
                                              __END_READ_DATA__}
Address and size of Raw Acceleration Data.
Definition at line 87 of file mma8491q_demo.c.
const registerreadlist_t cMma8491qStatus[] = {{.readFrom = MMA8491Q_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 84 of file mma8491q_demo.c.
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 94 of file mma8491q_demo.c.
Referenced by main(), and process_host_command().
gpioConfigKSDK_t gGpioConfigInPins
Initial value:
=
    {
        .pinConfig = {kGPIO_DigitalInput, 0},
        .interruptMode = kPORT_InterruptOrDMADisabled,
        .portPinConfig = {0},
        .portPinConfig.mux = kPORT_MuxAsGpio,
}
Definition at line 97 of file mma8491q_demo.c.
mma8491q_context_t gSensorContext
Definition at line 96 of file mma8491q_demo.c.
uint8_t gStreamID
Definition at line 104 of file mma8491q_demo.c.
Referenced by main(), and process_host_command().
GENERIC_DRIVER_GPIO* pGpioDriver = &Driver_GPIO_KSDK
Definition at line 105 of file mma8491q_demo.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 93 of file mma8491q_demo.c.
Referenced by main(), and process_host_command().