ISSDK: driverexamples/mma865x/mma865x_freefall.c File Reference
mma865x_freefall.c File Reference
The mma865x_freefall.c file implements the ISSDK MMA865x sensor driver example demonstration for Freefall Detection.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "mma865x_drv.h"
#include "systick_utils.h"
Macros
#define FF_MT_WT_DBCNT 0x28 /* Debounce count value. */
#define FF_MT_THS_VALUE 0x03 /* Threshold Value. */
Functions
void mma865x_int_event_ready_callback (void *pUserData)
This is the Sensor Event Ready ISR implementation.
int main (void)
Main function.
Variables
const registerwritelist_t cMma865xConfigFreeFall []
Register settings for freefall detection.
const registerreadlist_t cMma865xFreeFallEvent [] = {{.readFrom = MMA865x_FF_MT_SRC, .numBytes = 1}, __END_READ_DATA__}
Address of Freefall Status Register.
volatile bool gMma865xEventReady
Detailed Description
The mma865x_freefall.c file implements the ISSDK MMA865x sensor driver example demonstration for Freefall Detection.
Definition in file mma865x_freefall.c.
Macro Definition Documentation
#define FF_MT_THS_VALUE 0x03 /* Threshold Value. */
Definition at line 67 of file mma865x_freefall.c.
#define FF_MT_WT_DBCNT 0x28 /* Debounce count value. */
Definition at line 66 of file mma865x_freefall.c.
Function Documentation
int main (void)
Main function.
Initialize MMA865x pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the MMA865x sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MMA865x sensor for Freefall detection Mode.
Clear the data ready flag, it will be set again by the ISR.
Read the Freefall event FLAGs from MMA865x.
Display that a freefall event has been detected.
Definition at line 118 of file mma865x_freefall.c.
References BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), Driver_GPIO_KSDK, gMma865xEventReady, GPIO_DIRECTION_IN, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8652_I2C_ADDR, MMA8652_INT1, MMA8652_WHOAMI_VALUE, MMA865x_FF_MT_SRC_EA_MASK, MMA865x_FF_MT_SRC_EA_NONE, MMA865x_I2C_Configure(), MMA865x_I2C_Initialize(), MMA865x_I2C_ReadData(), MMA865x_I2C_SetIdleTask(), mma865x_int_event_ready_callback(), pGpioDriver, GENERIC_DRIVER_GPIO::pin_init, SENSOR_ERROR_NONE, SMC, and SMC_SetPowerModeWait().
void mma865x_int_event_ready_callback (void * pUserData)
This is the Sensor Event Ready ISR implementation.
Set flag to indicate Sensor has signalled data ready.
Definition at line 110 of file mma865x_freefall.c.
References gMma865xEventReady.
Referenced by main().
Variable Documentation
const registerwritelist_t cMma865xConfigFreeFall[]
Initial value:
=
    {
     {MMA865x_XYZ_DATA_CFG, MMA865x_XYZ_DATA_CFG_FS_2G, MMA865x_XYZ_DATA_CFG_FS_MASK},
     {MMA865x_CTRL_REG1, MMA865x_CTRL_REG1_DR_100HZ, MMA865x_CTRL_REG1_DR_MASK},
     {MMA865x_CTRL_REG2, MMA865x_CTRL_REG2_MODS_HR, MMA865x_CTRL_REG2_MODS_MASK},
     {MMA865x_CTRL_REG3, MMA865x_CTRL_REG3_IPOL_ACTIVE_HIGH, MMA865x_CTRL_REG3_IPOL_MASK},
     {MMA865x_CTRL_REG4, MMA865x_CTRL_REG4_INT_EN_FF_MT_EN, MMA865x_CTRL_REG4_INT_EN_FF_MT_MASK},
     {MMA865x_CTRL_REG5, MMA865x_CTRL_REG5_INT_CFG_FF_MT_INT1, MMA865x_CTRL_REG5_INT_CFG_FF_MT_MASK},
     {MMA865x_FF_MT_CFG, MMA865x_FF_MT_CFG_ELE_EN | MMA865x_FF_MT_CFG_OAE_FREEFALL | MMA865x_FF_MT_CFG_XEFE_EN |
                             MMA865x_FF_MT_CFG_YEFE_EN | MMA865x_FF_MT_CFG_ZEFE_EN,
      MMA865x_FF_MT_CFG_ELE_MASK | MMA865x_FF_MT_CFG_OAE_MASK | MMA865x_FF_MT_CFG_XEFE_MASK |
          MMA865x_FF_MT_CFG_YEFE_MASK | MMA865x_FF_MT_CFG_ZEFE_MASK},
     {MMA865x_FF_MT_THS, MMA865x_FF_MT_THS_DBCNTM_INC_CLR | FF_MT_THS_VALUE,
      MMA865x_FF_MT_THS_DBCNTM_MASK | MMA865x_FF_MT_THS_THS_MASK},
     {MMA865x_FF_MT_COUNT, FF_MT_WT_DBCNT, 0},
     __END_WRITE_DATA__}
Register settings for freefall detection.
Definition at line 73 of file mma865x_freefall.c.
const registerreadlist_t cMma865xFreeFallEvent[] = {{.readFrom = MMA865x_FF_MT_SRC, .numBytes = 1}, __END_READ_DATA__}
Address of Freefall Status Register.
Definition at line 99 of file mma865x_freefall.c.
volatile bool gMma865xEventReady
Definition at line 104 of file mma865x_freefall.c.
Referenced by main(), and mma865x_int_event_ready_callback().