ISSDK: driverexamples/mma9553/mma9553_pedometer_spi.c File Reference
mma9553_pedometer_spi.c File Reference
The mma9553_pedometer_spi.c file implements the ISSDK MMA9553L sensor driver example demonstration as a Pedometer in SPI Mode.
#include "board.h"
#include "pin_mux.h"
#include "fsl_lptmr.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_SPI.h"
#include "fsl_spi_cmsis.h"
#include "issdk_hal.h"
#include "gpio_driver.h"
#include "mma9553_drv.h"
#include "systick_utils.h"
Macros
#define SAMPLING_RATE_ms (100) /* Timeout for the ODR Timer. */
#define MMA9553_ACCEL_DATA_SIZE (6) /* 2 byte X,Y,Z Axis Data each. */
#define mma9553_en_callback LPTMR0_IRQHandler /* Timer timeout Callback. */
#define MMA9553_SSB_IO3 D10 /* The SSB_IO3 pin of MMA9553 on the FRDM-STBC-SA955x Board. */
#define RESET_GPIO A3 /* The RESET_GPIO pin of MMA9553 on the FRDM-STBC-SA955x Board. */
Functions
void mma9553_en_callback (void)
int main (void)
Main function.
Variables
const registercommandlist_t cMma9553Config30Hz []
const registerreadlist_t cMma9553ReadRawOutput []
const registercommandlist_t cMma9553ReadPedometerCommand []
const registerreadlist_t cMma9553ReadPedometerOutput []
volatile bool gMma9553DataReady
Detailed Description
The mma9553_pedometer_spi.c file implements the ISSDK MMA9553L sensor driver example demonstration as a Pedometer in SPI Mode.
Definition in file mma9553_pedometer_spi.c.
Macro Definition Documentation
#define MMA9553_ACCEL_DATA_SIZE (6) /* 2 byte X,Y,Z Axis Data each. */
Definition at line 62 of file mma9553_pedometer_spi.c.
#define mma9553_en_callback LPTMR0_IRQHandler /* Timer timeout Callback. */
Definition at line 63 of file mma9553_pedometer_spi.c.
#define MMA9553_SSB_IO3 D10 /* The SSB_IO3 pin of MMA9553 on the FRDM-STBC-SA955x Board. */
Definition at line 64 of file mma9553_pedometer_spi.c.
Referenced by main().
#define RESET_GPIO A3 /* The RESET_GPIO pin of MMA9553 on the FRDM-STBC-SA955x Board. */
Definition at line 65 of file mma9553_pedometer_spi.c.
Referenced by main().
#define SAMPLING_RATE_ms (100) /* Timeout for the ODR Timer. */
Definition at line 61 of file mma9553_pedometer_spi.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware
Initialize the SPI driver.
Set the SPI Power mode.
Set the SPI Slave speed.
Initialize the MMA9553 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MMA9553 sensor driver with 30Hz Mode settings.
Read the Pedometer data from the MMA9553.
Read the raw sensor data from the MMA9553.
Definition at line 108 of file mma9553_pedometer_spi.c.
References mma9553_acceldata_t::accel, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), mma9553_pedometerdata_t::calories, mma9553_pedometerdata_t::distance, gMma9553DataReady, int32_t(), MMA9553_SPI_CommandResponse(), MMA9553_SPI_Configure(), MMA9553_SPI_Initialize(), MMA9553_SPI_SetIdleTask(), MMA9553_SSB_IO3, RESET_GPIO, SAMPLING_RATE_ms, SENSOR_ERROR_NONE, mma9553_pedometerdata_t::sleepCount, SMC, SMC_SetPowerModeWait(), mma9553_pedometerdata_t::speed, SPI_S_BAUDRATE, SPI_S_DEVICE_INDEX, SPI_S_DRIVER, SPI_S_SIGNAL_EVENT, mma9553_pedometerdata_t::statusRegister, and mma9553_pedometerdata_t::stepCount.
void mma9553_en_callback (void)
Definition at line 99 of file mma9553_pedometer_spi.c.
References gMma9553DataReady.
Variable Documentation
const registercommandlist_t cMma9553Config30Hz[]
Initial value:
= {
    {SetFSRange_2g, 0, sizeof(SetFSRange_2g)},
    {SetSampleRate_30Hz, 0, sizeof(SetSampleRate_30Hz)},
    {SetAFEPriority_for30Hz, 0, sizeof(SetAFEPriority_for30Hz)},
    {SetMBoxPriority_for30Hz, 0, sizeof(SetMBoxPriority_for30Hz)},
    __END_WRITE_CMD__}
Prepare the register write list to configure MMA9553L in 30Hz Mode.
Definition at line 71 of file mma9553_pedometer_spi.c.
const registercommandlist_t cMma9553ReadPedometerCommand[]
Initial value:
= {{ReadPedometerData, 0, sizeof(ReadPedometerData)},
                                                              __END_WRITE_CMD__}
Prepare the command list to read the Pedometer data from MMA9553.
Definition at line 83 of file mma9553_pedometer_spi.c.
const registerreadlist_t cMma9553ReadPedometerOutput[]
Initial value:
= {{.readFrom = 0, .numBytes = sizeof(mma9553_pedometerdata_t)},
                                                          __END_READ_DATA__}
Prepare the read list to read the Pedometer data from MMA9553.
Definition at line 87 of file mma9553_pedometer_spi.c.
const registerreadlist_t cMma9553ReadRawOutput[]
Initial value:
= {
    {.readFrom = MMA9553_XYZ_DATA_OFFSET, .numBytes = MMA9553_ACCEL_DATA_SIZE}, __END_READ_DATA__}
Prepare the register read list to read the raw Accel data from MMA9553.
Definition at line 79 of file mma9553_pedometer_spi.c.
volatile bool gMma9553DataReady
Definition at line 93 of file mma9553_pedometer_spi.c.
Referenced by main(), and mma9553_en_callback().