ISSDK: driverexamples/mpl3115/mpl3115_normal.c File Reference
mpl3115_normal.c File Reference
The mpl3115_normal.c file implements the ISSDK MPL3115 sensor driver example demonstration with polling mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "mpl3115_drv.h"
#include "systick_utils.h"
Macros
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
#define MPL3115_SAMPLING_EXPONENT (1) /* 2 seconds */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t cMpl3115ConfigNormal []
Register settings for Normal (non buffered) mode.
const registerreadlist_t cMpl3115Status [] = {{.readFrom = MPL3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
const registerreadlist_t cMpl3115OutputNormal []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Detailed Description
The mpl3115_normal.c file implements the ISSDK MPL3115 sensor driver example demonstration with polling mode.
Definition in file mpl3115_normal.c.
Macro Definition Documentation
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
Definition at line 59 of file mpl3115_normal.c.
Referenced by main().
#define MPL3115_SAMPLING_EXPONENT (1) /* 2 seconds */
In MPL3115 the Auto Acquisition Time Step (ODR) can be set only in powers of 2 (i.e. 2^x, where x is the SAMPLING_EXPONENT). This gives a range of 1 second to 2^15 seconds (9 hours).
Definition at line 63 of file mpl3115_normal.c.
Function Documentation
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize MPL3115 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MPL3115 sensor.
Wait for data ready from the MPL3115.
Read new raw sensor data from the MPL3115.
Process the sample and convert the raw sensor data.
Definition at line 93 of file mpl3115_normal.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MPL3115_DATA_SIZE, MPL3115_DR_STATUS_PTDR_MASK, MPL3115_I2C_ADDR, MPL3115_I2C_Configure(), MPL3115_I2C_Initialize(), MPL3115_I2C_ReadData(), MPL3115_I2C_SetIdleTask(), MPL3115_PRESSURE_CONV_FACTOR, MPL3115_TEMPERATURE_CONV_FACTOR, MPL3115_WHOAMI_VALUE, mpl3115_pressuredata_t::pressure, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), and mpl3115_pressuredata_t::temperature.
Variable Documentation
const registerwritelist_t cMpl3115ConfigNormal[]
Initial value:
= {
    {MPL3115_PT_DATA_CFG,
     MPL3115_PT_DATA_CFG_TDEFE_ENABLED | MPL3115_PT_DATA_CFG_PDEFE_ENABLED | MPL3115_PT_DATA_CFG_DREM_ENABLED,
     MPL3115_PT_DATA_CFG_TDEFE_MASK | MPL3115_PT_DATA_CFG_PDEFE_MASK | MPL3115_PT_DATA_CFG_DREM_MASK},
    {MPL3115_CTRL_REG1, MPL3115_CTRL_REG1_OS_OSR_128, MPL3115_CTRL_REG1_OS_MASK},
    {MPL3115_CTRL_REG2, MPL3115_SAMPLING_EXPONENT, MPL3115_CTRL_REG2_ST_MASK},
    __END_WRITE_DATA__}
Register settings for Normal (non buffered) mode.
Definition at line 69 of file mpl3115_normal.c.
const registerreadlist_t cMpl3115OutputNormal[]
Initial value:
= {{.readFrom = MPL3115_OUT_P_MSB, .numBytes = MPL3115_DATA_SIZE},
                                                   __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 84 of file mpl3115_normal.c.
const registerreadlist_t cMpl3115Status[] = {{.readFrom = MPL3115_STATUS, .numBytes = 1}, __END_READ_DATA__}
Address of Status Register.
Definition at line 81 of file mpl3115_normal.c.