ISSDK: driverexamples/mpl3115/mpl3115_oneshot.c File Reference
mpl3115_oneshot.c File Reference
The mpl3115_oneshot.c file implements the ISSDK MPL3115 sensor driver example demonstration with one shot mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "mpl3115_drv.h"
#include "systick_utils.h"
Macros
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t cMpl3115ConfigAltitude []
Register settings for Altitude readings in One-Shot mode.
const registerwritelist_t cMpl3115SetOST []
Register settings for Triggring One-Shot Sampling.
const registerreadlist_t cMpl3115GetOST [] = {{.readFrom = MPL3115_CTRL_REG1, .numBytes = 1}, __END_READ_DATA__}
Address of Register containing OST Bit.
const registerreadlist_t cMpl3115OutputNormal []
Address and size of Raw Altitude+Temperature Data.
Detailed Description
The mpl3115_oneshot.c file implements the ISSDK MPL3115 sensor driver example demonstration with one shot mode.
Definition in file mpl3115_oneshot.c.
Macro Definition Documentation
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
Definition at line 59 of file mpl3115_oneshot.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize MPL3115 sensor driver.
We do not need to call MPL3115_I2C_Configure() in this case as we are going to read samples on demand. Instead we directly write register settings for One-Shot Mode...
The code contained withing the braces illustrate steps to read one-sample. These can be repated at desired intervals to acquire more samples.
Keep checking the OST FLAG for completion.
Read raw sensor data from the MPL3115.
Process the sample and convert the raw sensor data.
Definition at line 89 of file mpl3115_oneshot.c.
References mpl3115_altitudedata_t::altitude, ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), PhysicalSensor::deviceInfo, registerDeviceInfo_t::deviceInstance, registerDeviceInfo_t::functionParam, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, registerDeviceInfo_t::idleFunction, int32_t(), MPL3115_ALTITUDE_CONV_FACTOR, MPL3115_CTRL_REG1_OST_MASK, MPL3115_DATA_SIZE, MPL3115_I2C_ADDR, MPL3115_I2C_Initialize(), MPL3115_I2C_ReadData(), MPL3115_TEMPERATURE_CONV_FACTOR, MPL3115_WHOAMI_VALUE, mpl3115_i2c_sensorhandle_t::pCommDrv, SENSOR_ERROR_NONE, SENSOR_ERROR_WRITE, Sensor_I2C_Write(), mpl3115_i2c_sensorhandle_t::slaveAddress, SMC, SMC_SetPowerModeWait(), and mpl3115_altitudedata_t::temperature.
Variable Documentation
const registerwritelist_t cMpl3115ConfigAltitude[]
Initial value:
= {
    {MPL3115_CTRL_REG1, MPL3115_CTRL_REG1_ALT_ALT, MPL3115_CTRL_REG1_ALT_MASK},
    __END_WRITE_DATA__}
Register settings for Altitude readings in One-Shot mode.
Definition at line 65 of file mpl3115_oneshot.c.
const registerreadlist_t cMpl3115GetOST[] = {{.readFrom = MPL3115_CTRL_REG1, .numBytes = 1}, __END_READ_DATA__}
Address of Register containing OST Bit.
Definition at line 77 of file mpl3115_oneshot.c.
const registerreadlist_t cMpl3115OutputNormal[]
Initial value:
= {{.readFrom = MPL3115_OUT_P_MSB, .numBytes = MPL3115_DATA_SIZE},
                                                   __END_READ_DATA__}
Address and size of Raw Altitude+Temperature Data.
Definition at line 80 of file mpl3115_oneshot.c.
const registerwritelist_t cMpl3115SetOST[]
Initial value:
= {
    {MPL3115_CTRL_REG1, MPL3115_CTRL_REG1_OST_SET, MPL3115_CTRL_REG1_OST_MASK},
    __END_WRITE_DATA__}
Register settings for Triggring One-Shot Sampling.
Definition at line 71 of file mpl3115_oneshot.c.