ISSDK: driverexamples/mpl3115/mpl3115_normal_interrupt.c File Reference
mpl3115_normal_interrupt.c File Reference
The mpl3115_normal_interrupt.c file implements the ISSDK MPL3115 sensor driver example demonstration with interrupt mode.
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"
#include "Driver_I2C.h"
#include "Driver_GPIO.h"
#include "fsl_i2c_cmsis.h"
#include "issdk_hal.h"
#include "mpl3115_drv.h"
#include "systick_utils.h"
#include "gpio_driver.h"
Macros
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
#define MPL3115_SAMPLING_EXPONENT (1) /* 2 seconds */
Functions
void mpl3115_int_data_ready_callback (void *pUserData)
This is the Sensor Data Ready ISR implementation.
int main (void)
This is the The main function implementation.
Variables
const registerwritelist_t cMpl3115ConfigNormal []
Register settings for Interrupt (non buffered) mode.
const registerreadlist_t cMpl3115OutputNormal []
Address and size of Raw Pressure+Temperature Data in Normal Mode.
volatile uint8_t gMpl3115DataReady
Detailed Description
The mpl3115_normal_interrupt.c file implements the ISSDK MPL3115 sensor driver example demonstration with interrupt mode.
Definition in file mpl3115_normal_interrupt.c.
Macro Definition Documentation
#define MPL3115_DATA_SIZE (5) /* 3 byte Pressure/Altitude and 2 byte Temperature. */
Definition at line 63 of file mpl3115_normal_interrupt.c.
Referenced by main().
#define MPL3115_SAMPLING_EXPONENT (1) /* 2 seconds */
In MPL3115 the Auto Acquisition Time Step (ODR) can be set only in powers of 2 (i.e. 2^x, where x is the SAMPLING_EXPONENT). This gives a range of 1 second to 2^15 seconds (9 hours).
Definition at line 67 of file mpl3115_normal_interrupt.c.
Function Documentation
int main (void)
This is the The main function implementation.
This function invokes board initializes routines, then then brings up the sensor and finally enters an endless loop to continuously read available samples.
Parameters
[in] void This is no input parameter.
Returns
void There is no return value.
Constraints:
None
No
Initialize the MCU hardware.
Initialize MAG3110 pin used by FRDM board
Initialize RGB LED pin used by FRDM board
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize MPL3115 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MAG3110 sensor driver.
Clear the data ready flag, it will be set again by the ISR.
Read new raw sensor data from the MPL3115.
Process the sample and convert the raw sensor data to signed 16-bit container.
Definition at line 124 of file mpl3115_normal_interrupt.c.
References ASK_USER_TO_RESUME, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), Driver_GPIO_KSDK, gMpl3115DataReady, GPIO_DIRECTION_IN, GPIO_DIRECTION_OUT, GREEN_LED, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MPL3115_DATA_SIZE, MPL3115_I2C_ADDR, MPL3115_I2C_Configure(), MPL3115_I2C_Initialize(), MPL3115_I2C_ReadData(), MPL3115_I2C_SetIdleTask(), MPL3115_INT1, mpl3115_int_data_ready_callback(), MPL3115_PRESSURE_CONV_FACTOR, MPL3115_TEMPERATURE_CONV_FACTOR, MPL3115_WHOAMI_VALUE, pGpioDriver, GENERIC_DRIVER_GPIO::pin_init, mpl3115_pressuredata_t::pressure, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), mpl3115_pressuredata_t::temperature, and GENERIC_DRIVER_GPIO::toggle_pin.
void mpl3115_int_data_ready_callback (void * pUserData)
This is the Sensor Data Ready ISR implementation.
This function sets the flag which indicates if a new sample(s) is available for reading.
Parameters
[in] pUserData This is a void pointer to the instance of the user specific data structure for the ISR.
Returns
void There is no return value.
Constraints:
None
Yes
Set flag to indicate Sensor has signalled data ready.
Definition at line 110 of file mpl3115_normal_interrupt.c.
References gMpl3115DataReady.
Referenced by main().
Variable Documentation
const registerwritelist_t cMpl3115ConfigNormal[]
Initial value:
= {
    {MPL3115_PT_DATA_CFG,
     MPL3115_PT_DATA_CFG_TDEFE_ENABLED | MPL3115_PT_DATA_CFG_PDEFE_ENABLED | MPL3115_PT_DATA_CFG_DREM_ENABLED,
     MPL3115_PT_DATA_CFG_TDEFE_MASK | MPL3115_PT_DATA_CFG_PDEFE_MASK | MPL3115_PT_DATA_CFG_DREM_MASK},
    {MPL3115_CTRL_REG1, MPL3115_CTRL_REG1_OS_OSR_128, MPL3115_CTRL_REG1_OS_MASK},
    {MPL3115_CTRL_REG2, MPL3115_SAMPLING_EXPONENT, MPL3115_CTRL_REG2_ST_MASK},
    {MPL3115_CTRL_REG3, MPL3115_CTRL_REG3_IPOL1_HIGH, MPL3115_CTRL_REG3_IPOL1_MASK},
    {MPL3115_CTRL_REG4, MPL3115_CTRL_REG4_INT_EN_DRDY_INTENABLED, MPL3115_CTRL_REG4_INT_EN_DRDY_MASK},
    {MPL3115_CTRL_REG5, MPL3115_CTRL_REG5_INT_CFG_DRDY_INT1, MPL3115_CTRL_REG5_INT_CFG_DRDY_MASK},
    __END_WRITE_DATA__}
Register settings for Interrupt (non buffered) mode.
Definition at line 73 of file mpl3115_normal_interrupt.c.
const registerreadlist_t cMpl3115OutputNormal[]
Initial value:
= {{.readFrom = MPL3115_OUT_P_MSB, .numBytes = MPL3115_DATA_SIZE},
                                                   __END_READ_DATA__}
Address and size of Raw Pressure+Temperature Data in Normal Mode.
Definition at line 91 of file mpl3115_normal_interrupt.c.
volatile uint8_t gMpl3115DataReady
Definition at line 97 of file mpl3115_normal_interrupt.c.
Referenced by main(), and mpl3115_int_data_ready_callback().