ISSDK: driverexamples/demos/FRDM-K64F/orientaion_application_freertos_agm01.c File Reference
orientaion_application_freertos_agm01.c File Reference
The orientaion_application_freertos_agm01.c file implements the ISSDK freeRTOS orientation application for FRDM-STBC-AGM01 using sensor fusion core functional interfaces and host i/o interface.
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"
#include "event_groups.h"
#include "board.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_port.h"
#include "fsl_i2c.h"
#include "Driver_USART.h"
#include "fsl_i2c_cmsis.h"
#include "fsl_uart_cmsis.h"
#include "fxas21002.h"
#include "fxos8700.h"
#include "register_io_i2c.h"
#include "host_io_uart.h"
#include "gpio_driver.h"
#include "auto_detection_service.h"
#include "sensor_fusion.h"
#include "control.h"
#include "status.h"
#include "drivers.h"
Macros
#define TIMESTAMP_DATA_SIZE (4) /* Orientation Packet: TimeStamp field size */
#define QUATERNION_SIZE (8) /* Orientation Packet: Quaternion field size */
#define COORDINATES_SIZE (1) /* Orientation Packet: coordinates field size */
#define BOARDINFO_SIZE (1) /* Orientation Packet: BoardInfo field size */
#define BUILDNAME_SIZE (2) /* Orientation Packet: BuildInfo field size */
#define SYSTICKINFO_SIZE (2) /* Orientation Packet: SysTick field size */
#define APPLICATION_NAME "ORIENTATION-FreeRTOS"
Unique Name for this application which should match the target GUI pkg name.
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
#define STREAMING_PAYLOAD_LEN (TIMESTAMP_DATA_SIZE + QUATERNION_SIZE + COORDINATES_SIZE + BOARDINFO_SIZE + BUILDNAME_SIZE + SYSTICKINFO_SIZE)
Functions
void readAlgoParams (SV_ptr data, Quaternion *fq, int16_t *iPhi, int16_t *iThe, int16_t *iRho, int16_t iOmega[], uint16_t *isystick)
Utility function for reading common algorithm parameters.
bool process_host_command (uint8_t tag, uint8_t *hostCommand, uint8_t *hostResponse, size_t *hostMsgSize, size_t respBufferSize)
int main (void)
Main function.
Variables
SensorFusionGlobals sfg
ControlSubsystem gOrientationControlSubsystem
StatusSubsystem statusSubsystem
char boardString [ADS_MAX_STRING_LENGTH] = {0}
char shieldString [ADS_MAX_STRING_LENGTH] = {0}
char embAppName [ADS_MAX_STRING_LENGTH] = {0}
volatile bool gStreamingEnabled
uint8_t gPrimaryStreamID
uint8_t orientOutputBuffer [STREAMING_HEADER_LEN+STREAMING_PAYLOAD_LEN]
struct PhysicalSensor sensors [2]
EventGroupHandle_t event_group = NULL
registerDeviceInfo_t i2cBusInfo = {.deviceInstance = I2C_S_DEVICE_INDEX, .functionParam = NULL, .idleFunction = NULL}
Detailed Description
The orientaion_application_freertos_agm01.c file implements the ISSDK freeRTOS orientation application for FRDM-STBC-AGM01 using sensor fusion core functional interfaces and host i/o interface.
Definition in file orientaion_application_freertos_agm01.c.
Macro Definition Documentation
#define APPLICATION_NAME "ORIENTATION-FreeRTOS"
Unique Name for this application which should match the target GUI pkg name.
Definition at line 82 of file orientaion_application_freertos_agm01.c.
Referenced by main().
#define APPLICATION_VERSION "1.0"
Version to distinguish between instances the same application based on target Shield and updates.
Definition at line 84 of file orientaion_application_freertos_agm01.c.
Referenced by main().
#define BOARDINFO_SIZE (1) /* Orientation Packet: BoardInfo field size */
Definition at line 77 of file orientaion_application_freertos_agm01.c.
#define BUILDNAME_SIZE (2) /* Orientation Packet: BuildInfo field size */
Definition at line 78 of file orientaion_application_freertos_agm01.c.
#define COORDINATES_SIZE (1) /* Orientation Packet: coordinates field size */
Definition at line 76 of file orientaion_application_freertos_agm01.c.
#define QUATERNION_SIZE (8) /* Orientation Packet: Quaternion field size */
Definition at line 75 of file orientaion_application_freertos_agm01.c.
#define STREAMING_PAYLOAD_LEN (TIMESTAMP_DATA_SIZE + QUATERNION_SIZE + COORDINATES_SIZE + BOARDINFO_SIZE + BUILDNAME_SIZE + SYSTICKINFO_SIZE)
Definition at line 87 of file orientaion_application_freertos_agm01.c.
Referenced by readAlgoParams().
#define SYSTICKINFO_SIZE (2) /* Orientation Packet: SysTick field size */
Definition at line 79 of file orientaion_application_freertos_agm01.c.
#define TIMESTAMP_DATA_SIZE (4) /* Orientation Packet: TimeStamp field size */
Definition at line 74 of file orientaion_application_freertos_agm01.c.
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize and set the KSDK driver for the I2C port
Initialize the UART driver.
Set UART Power mode.
Set UART Baud Rate.
Initialize control sub-system for orientation packet streaming
Initialize sensor fusion status sub-system
Initialize sensor fusion global metadata
Install the sensors to be used by sensor fusion
Initialize streaming and assign Stream IDs.
Initialize sensor fusion engine
Create RTOS tasks for sensor fusion
Set sensor fusion engine status to NORMAL
Start RTOS Scheduler
Definition at line 414 of file orientaion_application_freertos_agm01.c.
References ADS_MAX_STRING_LENGTH, APPLICATION_NAME, APPLICATION_VERSION, BOARD_BootClockRUN, BOARD_DEBUG_UART_BAUDRATE, BOARD_RunADS(), BOARD_SystickEnable(), boardString, PhysicalSensor::bus_driver, PhysicalSensor::deviceInfo, embAppName, event_group, FXAS21002_I2C_ADDR, FXAS21002_Init(), FXAS21002_Read(), FXOS8700_I2C_ADDR, FXOS8700_Init(), FXOS8700_Read(), gPrimaryStreamID, gStreamingEnabled, HARD_FAULT, Host_IO_Init(), HOST_S_DRIVER, HOST_S_SIGNAL_EVENT, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, SensorFusionGlobals::initializeFusionEngine, initializeStatusSubsystem(), initSensorFusionGlobals(), SensorFusionGlobals::installSensor, int32_t(), NORMAL, sensors, SensorFusionGlobals::setStatus, SHIELD_NAME, and shieldString.
bool process_host_command (uint8_t tag, uint8_t * hostCommand, uint8_t * hostResponse, size_t * hostMsgSize, size_t respBufferSize)
Definition at line 128 of file orientaion_application_freertos_agm01.c.
References SensorFusionGlobals::applyPerturbation, B0, boardString, SensorFusionGlobals::conditionSensorReadings, embAppName, event_group, gPrimaryStreamID, gStreamingEnabled, HOST_CMD_START, HOST_CMD_STOP, HOST_FORMAT_HDLC, Host_IO_Receive(), HOST_MSG_CMD_ACT_OFFSET, HOST_MSG_LEN_LSB_OFFSET, HOST_PRO_CMD_W_CFG_TAG, HOST_PRO_INT_CMD_TAG, HOST_PRO_INT_DEV_TAG, SensorFusionGlobals::loopcounter, NORMAL, orientOutputBuffer, OVERSAMPLE_RATE, SensorFusionGlobals::pControlSubsystem, SensorFusionGlobals::queueStatus, SensorFusionGlobals::readSensors, SensorFusionGlobals::runFusion, shieldString, ControlSubsystem::stream, and SensorFusionGlobals::updateStatus.
void readAlgoParams (SV_ptr data, Quaternion * fq, int16_t * iPhi, int16_t * iThe, int16_t * iRho, int16_t iOmega[], uint16_t * isystick)
Utility function for reading common algorithm parameters.
Definition at line 280 of file orientaion_application_freertos_agm01.c.
References ControlSubsystem::AccelCalPacketOn, ControlSubsystem::AltPacketOn, ControlSubsystem::AngularVelocityPacketOn, CHX, CHY, CHZ, ControlSubsystem::DebugPacketOn, ControlSubsystem::DefaultQuaternionPacketType, F_9DOF_GBY_KALMAN, SV_COMMON::fOmega, SV_COMMON::fPhi, SV_COMMON::fq, SV_COMMON::fRho, SV_COMMON::fThe, FUSION_HZ, gPrimaryStreamID, gStreamingEnabled, HOST_FORMAT_HDLC, Host_IO_Add_ISO_Header(), Host_IO_Send(), SensorFusionGlobals::iFlags, orientOutputBuffer, SensorFusionGlobals::pControlSubsystem, Quaternion::q0, Quaternion::q1, Quaternion::q2, Quaternion::q3, Q3, ControlSubsystem::QuaternionPacketType, ControlSubsystem::RPCPacketOn, ControlSubsystem::stream, STREAMING_HEADER_LEN, STREAMING_PAYLOAD_LEN, sUARTOutputBuffer, SV_COMMON::systick, THIS_BOARD, THIS_SHIELD, THISBUILD, and ControlSubsystem::write.
Variable Documentation
char boardString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 96 of file orientaion_application_freertos_agm01.c.
Referenced by main(), and process_host_command().
char embAppName[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 97 of file orientaion_application_freertos_agm01.c.
Referenced by main(), and process_host_command().
EventGroupHandle_t event_group = NULL
Definition at line 104 of file orientaion_application_freertos_agm01.c.
Referenced by main(), and process_host_command().
ControlSubsystem gOrientationControlSubsystem
Definition at line 94 of file orientaion_application_freertos_agm01.c.
uint8_t gPrimaryStreamID
Definition at line 99 of file orientaion_application_freertos_agm01.c.
Referenced by main(), process_host_command(), and readAlgoParams().
volatile bool gStreamingEnabled
Definition at line 98 of file orientaion_application_freertos_agm01.c.
Referenced by main(), process_host_command(), and readAlgoParams().
registerDeviceInfo_t i2cBusInfo = {.deviceInstance = I2C_S_DEVICE_INDEX, .functionParam = NULL, .idleFunction = NULL}
Definition at line 105 of file orientaion_application_freertos_agm01.c.
uint8_t orientOutputBuffer[STREAMING_HEADER_LEN+STREAMING_PAYLOAD_LEN]
Definition at line 101 of file orientaion_application_freertos_agm01.c.
Referenced by process_host_command(), and readAlgoParams().
struct PhysicalSensor sensors[2]
Definition at line 103 of file orientaion_application_freertos_agm01.c.
Referenced by main().
SensorFusionGlobals sfg
Definition at line 93 of file orientaion_application_freertos_agm01.c.
char shieldString[ADS_MAX_STRING_LENGTH] = {0}
Definition at line 96 of file orientaion_application_freertos_agm01.c.
Referenced by main(), and process_host_command().
StatusSubsystem statusSubsystem
Definition at line 95 of file orientaion_application_freertos_agm01.c.