ISSDK: algorithms/pedometer/examples/pedometer_stepcount_mma8652.c File Reference
pedometer_stepcount_mma8652.c File Reference
The pedometer_stepcount_mma8652.c file implements the ISSDK prdometer example using MMA8652 sensor as the acceleration source.
#include "board.h"
#include "fsl_debug_console.h"
#include "pin_mux.h"
#include "fsl_smc.h"
#include "clock_config.h"
#include "fsl_i2c.h"
#include "Driver_I2C.h"
#include "Driver_gpio.h"
#include "fsl_i2c_cmsis.h"
#include "mma865x_drv.h"
#include "pedometer.h"
#include "systick_utils.h"
#include "issdk_hal.h"
Macros
#define MMA865x_ACCEL_DATA_SIZE (6) /* 2 byte X,Y,Z Axis Data each. */
Functions
int main (void)
Main function.
Variables
const registerwritelist_t cMma865xConfigNormal []
const registerreadlist_t cMma865xDataReady [] = {{.readFrom = MMA865x_STATUS, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t cMma865xOutputValues []
volatile uint8_t gMma865xDataReady
Detailed Description
The pedometer_stepcount_mma8652.c file implements the ISSDK prdometer example using MMA8652 sensor as the acceleration source.
Definition in file pedometer_stepcount_mma8652.c.
Macro Definition Documentation
#define MMA865x_ACCEL_DATA_SIZE (6) /* 2 byte X,Y,Z Axis Data each. */
Definition at line 59 of file pedometer_stepcount_mma8652.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware
Initialize the debug console.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the MMA865x sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the MMA865x sensor driver with Non FIFO mode.
Initialize the pedometer
Configure the pedometer
Read the data ready status from MMA865x
Read the raw sensor data from the MMA865x.
Convert the raw sensor data for display to the debug port.
Execute the pedometer Algorithm
Definition at line 116 of file pedometer_stepcount_mma8652.c.
References mma865x_acceldata_t::accel, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), gMma865xDataReady, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), MMA8652_I2C_ADDR, MMA8652_WHOAMI_VALUE, MMA865x_ACCEL_DATA_SIZE, MMA865x_I2C_Configure(), MMA865x_I2C_Initialize(), MMA865x_I2C_ReadData(), MMA865x_I2C_SetIdleTask(), MMA865x_STATUS_ZYXDR_MASK, pedometer_configure(), pedometer_init(), pedometer_run(), SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), pedometer_t::status, and pedometer_t::pedometer_status_tag::stepcount.
Variable Documentation
const registerwritelist_t cMma865xConfigNormal[]
Initial value:
=
    {
     {MMA865x_XYZ_DATA_CFG, MMA865x_XYZ_DATA_CFG_FS_2G, MMA865x_XYZ_DATA_CFG_FS_MASK},
     {MMA865x_CTRL_REG1, MMA865x_CTRL_REG1_DR_50HZ, MMA865x_CTRL_REG1_DR_MASK},
     {MMA865x_CTRL_REG2, MMA865x_CTRL_REG2_MODS_HR, MMA865x_CTRL_REG2_MODS_MASK},
     __END_WRITE_DATA__}
Prepare the register write list to configure MMA865x in Normal mode.
Definition at line 65 of file pedometer_stepcount_mma8652.c.
const registerreadlist_t cMma865xDataReady[] = {{.readFrom = MMA865x_STATUS, .numBytes = 1}, __END_READ_DATA__}
Prepare the register read list to read the Data Ready Status from MMA865x.
Definition at line 75 of file pedometer_stepcount_mma8652.c.
const registerreadlist_t cMma865xOutputValues[]
Initial value:
= {{.readFrom = MMA865x_OUT_X_MSB, .numBytes = MMA865x_ACCEL_DATA_SIZE},
                                                   __END_READ_DATA__}
Prepare the register read list to read the raw Accel data from MMA865x.
Definition at line 78 of file pedometer_stepcount_mma8652.c.
volatile uint8_t gMma865xDataReady
Definition at line 106 of file pedometer_stepcount_mma8652.c.
Referenced by main().