ISSDK: algorithms/pedometer/include/pedometer.h File Reference
pedometer.h File Reference
The pedometer.h file contains the interface and structure definitions for pedometer application.
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "KeynetikPedometer.h"
Data Structures
struct ped_accel_t
This defines the acceleration input data for the pedometer.
struct pedometer_config_t
This defines the configuration structure of the pedometer.
struct pedometer_t
This defines the pedometer instance.
struct pedometer_t::pedometer_status_tag
struct pedometer_t::pedometer_private_tag
Macros
#define PEDO_ONEG_8G 4096 /* One G value for 8G mode.*/
#define PEDO_ONEG_4G 8192 /* One G value for 4G mode.*/
#define PEDO_ONEG_2G 16384 /* One G value for 2G mode.*/
#define PEDO_FREQHZ_DEFAULT 50 /* Default frequency*/
#define PEDO_STEP_THRESHOLD_DEFAULT 130
#define PEDO_SPEED_PERIOD_DEFAULT 5
#define PEDO_FILTER_TIME_DEFAULT 3
#define PEDO_FILTER_STEPS_DEFAULT 4
Typedefs
typedef KeynetikActivityLevel activitylevel_t
typedef uint16_t debounce_count_t
Functions
void pedometer_init (pedometer_t *pPedometer)
The interface function initialize the pedometer.
void pedometer_configure (pedometer_t *pPedometer, const pedometer_config_t *pConfig)
The interface function to configure the pedometer.
int32_t pedometer_run (pedometer_t *pPedometer, ped_accel_t *pData)
The interface function excutes the pedometer algorithm.
Detailed Description
The pedometer.h file contains the interface and structure definitions for pedometer application.
Definition in file pedometer.h.
Macro Definition Documentation
#define PEDO_FILTER_STEPS_DEFAULT 4
Definition at line 57 of file pedometer.h.
#define PEDO_FILTER_TIME_DEFAULT 3
Definition at line 56 of file pedometer.h.
#define PEDO_FREQHZ_DEFAULT 50 /* Default frequency*/
Definition at line 53 of file pedometer.h.
#define PEDO_ONEG_2G 16384 /* One G value for 2G mode.*/
Definition at line 52 of file pedometer.h.
#define PEDO_ONEG_4G 8192 /* One G value for 4G mode.*/
Definition at line 51 of file pedometer.h.
#define PEDO_ONEG_8G 4096 /* One G value for 8G mode.*/
Definition at line 50 of file pedometer.h.
#define PEDO_SPEED_PERIOD_DEFAULT 5
Definition at line 55 of file pedometer.h.
#define PEDO_STEP_THRESHOLD_DEFAULT 130
Definition at line 54 of file pedometer.h.
Typedef Documentation
typedef KeynetikActivityLevel activitylevel_t
Definition at line 48 of file pedometer.h.
typedef uint16_t debounce_count_t
Definition at line 49 of file pedometer.h.
Function Documentation
void pedometer_configure (pedometer_t * pPedometer, const pedometer_config_t * pConfig)
The interface function to configure the pedometer.
Parameters
[in] pedometer_t handle to the pedometer.
[in] config configuration value.
Returns
void.
Constraints:
None
Reentrant: Yes
Definition at line 133 of file pedometer.c.
References pedometer_t::config, pedometer_config_t::frequency, pedometer_config_t::keynetik, pedometer_config_t::oneG, pedometer_t::private, and pedometer_t::pedometer_private_tag::stepchg_stepcount.
Referenced by main().
void pedometer_init (pedometer_t * pPedometer)
The interface function initialize the pedometer.
This function initialize the pedometer structure and return the handle.
Parameters
[in] pPedometer handle to the pedometer.
Returns
void.
Constraints:
None
Reentrant: Yes
Definition at line 119 of file pedometer.c.
References pedometer_t::config, pedometer_config_t::frequency, pedometer_config_t::keynetik, pedometer_config_t::oneG, pedometer_t::private, and pedometer_t::pedometer_private_tag::stepchg_stepcount.
Referenced by main().
int32_t pedometer_run (pedometer_t * pPedometer, ped_accel_t * pData)
The interface function excutes the pedometer algorithm.
Call this function the rate at which accelerometer runs.
Parameters
[in] pPedometer handle to the pedometer.
[in] accel_data acceleration data.
Returns
pedometer_run() returns the status .
Constraints:
None
Reentrant: Yes
Definition at line 147 of file pedometer.c.
References ped_accel_t::accel, pedometer_config_t::activity_dbcntm, pedometer_t::pedometer_private_tag::activitycount, pedometer_config_t::activitycount_threshold, pedometer_config_t::bits, pedometer_t::pedometer_status_tag::bits, pedometer_t::pedometer_status_tag::byte, pedometer_t::pedometer_status_tag::calories, pedometer_t::config, pedometer_t::pedometer_status_tag::distance, PEDOMETER_STATUS_ACTCHG_MASK, PEDOMETER_STATUS_ACTIVITY_BITNUM, PEDOMETER_STATUS_ACTIVITY_MASK, PEDOMETER_STATUS_CHG_MASK, PEDOMETER_STATUS_MRGFLG_MASK, PEDOMETER_STATUS_STEPCHG_MASK, PEDOMETER_STATUS_SUSPCHG_MASK, PEDOMETER_STATUS_SUSPEND_MASK, pedometer_t::private, pedometer_config_t::sleep_dbcntm, pedometer_t::pedometer_status_tag::sleepcount, pedometer_config_t::sleepcount_threshold, pedometer_config_t::sleepmaximum, pedometer_config_t::sleepminimum, pedometer_t::pedometer_status_tag::speed, SQUARED, pedometer_t::pedometer_status_tag::status, pedometer_t::status, pedometer_t::pedometer_private_tag::stepchg_stepcount, pedometer_config_t::stepcoalesce, and pedometer_t::pedometer_status_tag::stepcount.
Referenced by main().