ISSDK: algorithms/pedometer/examples/pedometer_stepcount_fxos8700.c File Reference
pedometer_stepcount_fxos8700.c File Reference
The pedometer_stepcount_fxos8700.c file implements the ISSDK prdometer example using FXOS8700 sensor as the acceleration source.
#include "board.h"
#include "fsl_debug_console.h"
#include "pin_mux.h"
#include "fsl_smc.h"
#include "clock_config.h"
#include "fsl_i2c.h"
#include "Driver_I2C.h"
#include "Driver_gpio.h"
#include "fsl_i2c_cmsis.h"
#include "fxos8700.h"
#include "fxos8700_drv.h"
#include "pedometer.h"
#include "systick_utils.h"
#include "issdk_hal.h"
Macros
#define RAW_ACCEL_DATA_SIZE (6)
Functions
int main (void)
Main function.
Variables
const registerwritelist_t fxos8700_Config []
const registerreadlist_t FXOS8700_WHO_AM_I_READ [] = {{.readFrom = FXOS8700_WHO_AM_I, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t FXOS8700_STATUS_READ [] = {{.readFrom = FXOS8700_STATUS, .numBytes = 1}, __END_READ_DATA__}
const registerreadlist_t FXOS8700_ACCEL_READ []
Detailed Description
The pedometer_stepcount_fxos8700.c file implements the ISSDK prdometer example using FXOS8700 sensor as the acceleration source.
Definition in file pedometer_stepcount_fxos8700.c.
Macro Definition Documentation
#define RAW_ACCEL_DATA_SIZE (6)
Definition at line 60 of file pedometer_stepcount_fxos8700.c.
Referenced by main().
Function Documentation
int main (void)
Main function.
Initialize the MCU hardware.
Initialize the debug console.
Initialize the I2C driver.
Set the I2C Power mode.
Set the I2C bus speed.
Initialize the FXOS8700 sensor driver.
Set the task to be executed while waiting for I2C transactions to complete.
Configure the fxos8700 sensor driver.
Definition at line 114 of file pedometer_stepcount_fxos8700.c.
References fxos8700_acceldata_t::accel, FXOS8700_DR_STATUS_t::b, BOARD_BootClockRUN, BOARD_InitDebugConsole(), BOARD_InitPins(), BOARD_SystickEnable(), FXOS8700_I2C_ADDR, FXOS8700_I2C_Configure(), FXOS8700_I2C_Initialize(), FXOS8700_I2C_ReadData(), FXOS8700_I2C_SetIdleTask(), FXOS8700_WHO_AM_I_PROD_VALUE, I2C_S_DEVICE_INDEX, I2C_S_DRIVER, I2C_S_SIGNAL_EVENT, int32_t(), pedometer_configure(), pedometer_init(), pedometer_run(), RAW_ACCEL_DATA_SIZE, SENSOR_ERROR_NONE, SMC, SMC_SetPowerModeWait(), pedometer_t::status, pedometer_t::pedometer_status_tag::stepcount, and FXOS8700_DR_STATUS_t::zyxdr.
Variable Documentation
const registerreadlist_t FXOS8700_ACCEL_READ[]
Initial value:
= {{.readFrom = FXOS8700_OUT_X_MSB, .numBytes = RAW_ACCEL_DATA_SIZE},
                                                  __END_READ_DATA__}
Command definition to read the Accel Data
Definition at line 103 of file pedometer_stepcount_fxos8700.c.
const registerwritelist_t fxos8700_Config[]
Initial value:
= {
    {FXOS8700_CTRL_REG1, FXOS8700_CTRL_REG1_DR_SINGLE_50_HZ, 0},
    {FXOS8700_M_CTRL_REG2, FXOS8700_M_CTRL_REG2_M_AUTOINC_ACCEL_ONLY_MODE, 0},
    __END_WRITE_DATA__}
Definition at line 68 of file pedometer_stepcount_fxos8700.c.
const registerreadlist_t FXOS8700_STATUS_READ[] = {{.readFrom = FXOS8700_STATUS, .numBytes = 1}, __END_READ_DATA__}
Command definition to read the Data Ready Status
Definition at line 100 of file pedometer_stepcount_fxos8700.c.
const registerreadlist_t FXOS8700_WHO_AM_I_READ[] = {{.readFrom = FXOS8700_WHO_AM_I, .numBytes = 1}, __END_READ_DATA__}
Definition at line 97 of file pedometer_stepcount_fxos8700.c.