/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _EDGEFAST_BLUETOOTH_EXTENSION_CONFIG_GEN_H_
#define _EDGEFAST_BLUETOOTH_EXTENSION_CONFIG_GEN_H_

// #define CONFIG_BT_HOST_CRYPTO 0
#define CONTROLLER_ID kUSB_ControllerIp3516Hs0
#define CONFIG_WORK_QUEUE_TASK_PRIORITY (configMAX_PRIORITIES - 2)
#define CONFIG_WORK_QUEUE_TASK_STACK_SIZE 2048
#define BUTTON_COUNT 0
// #define CONFIG_BT_HOST_USB_ENABLE 0
// #define CONFIG_BT_HOST_USB_IRQ_ENABLE 0
// #define CONFIG_BT_IND_RESET 0
// #define CONFIG_BT_IND_RESET_OOB 0
// #define CONFIG_BT_RF_TEST_MODE 0
// #define CONFIG_BT_WHITELIST 0
// #define CONFIG_BT_GATT_SERVER 0
// #define CONFIG_BLE_ADV_REPORT_BUFFER_FILTER 0
// #define BT_BLE_PLATFORM_INIT_ESCAPE 0

#endif /* _EDGEFAST_BLUETOOTH_EXTENSION_CONFIG_GEN_H_ */
