# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_component_codec_ak4497_adapter_MIMX8MM6 true)
set(CONFIG_USE_component_ii2c_adapter_MIMX8MM6 true)
set(CONFIG_USE_component_codec_wm8524_adapter_MIMX8MM6 true)
set(CONFIG_USE_component_serial_manager_uart_MIMX8MM6 true)
set(CONFIG_USE_driver_iuart_MIMX8MM6 true)
set(CONFIG_USE_middleware_freertos-kernel_MIMX8MM6 true)
