# Add set(CONFIG_USE_middleware_motor_control_bldc_frac_imcat true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

if((CONFIG_DEVICE_ID STREQUAL MC56F81768 OR CONFIG_DEVICE_ID STREQUAL MC56F83789 OR CONFIG_DEVICE_ID STREQUAL MC56F82748 OR CONFIG_DEVICE_ID STREQUAL MC56F84789 OR CONFIG_DEVICE_ID STREQUAL MKE15Z256xxx7 OR CONFIG_DEVICE_ID STREQUAL MKE15Z128xxx7 OR CONFIG_DEVICE_ID STREQUAL MKE16Z64xxx4 OR CONFIG_DEVICE_ID STREQUAL MKE16Z32xxx4 OR CONFIG_DEVICE_ID STREQUAL MKE17Z256xxx7 OR CONFIG_DEVICE_ID STREQUAL MKE17Z128xxx7 OR CONFIG_DEVICE_ID STREQUAL MKE17Z512xxx9 OR CONFIG_DEVICE_ID STREQUAL LPC865 OR CONFIG_DEVICE_ID STREQUAL MIMXRT1176xxxxx))

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
  ${CMAKE_CURRENT_LIST_DIR}/freemaster/bldc/mcat
)

else()

message(SEND_ERROR "middleware_motor_control_bldc_frac_imcat dependency does not meet, please check ${CMAKE_CURRENT_LIST_FILE}.")

endif()
