# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_sdmmc_host_usdhc_MIMXRT595S_cm33 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT595S_cm33 true)
set(CONFIG_USE_middleware_fatfs_mmc_MIMXRT595S_cm33 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT595S_cm33 true)
set(CONFIG_USE_driver_flexcomm_usart_MIMXRT595S_cm33 true)
set(CONFIG_USE_middleware_usb_device_ip3511hs_MIMXRT595S_cm33 true)
set(CONFIG_USE_middleware_baremetal_MIMXRT595S_cm33 true)
