include_guard()
message("middleware_freertos-aws_iot_demos_ota_mqtt component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c
)


include(middleware_freertos-aws_iot_demos_ota_demo_helpers_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_libraries_abstractions_backoff_algorithm_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_libraries_abstractions_mqtt_agent_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_libraries_abstractions_platform_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_libraries_abstractions_transport_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_libraries_c_sdk_standard_common_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_libraries_coremqtt_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_libraries_coremqtt-agent_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_ota_for_aws_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_pkcs11_helpers_MIMXRT685S_cm33)

include(middleware_freertos-kernel_MIMXRT685S_cm33)

include(middleware_freertos-aws_iot_demos_common_mqtt_subscription_manager_MIMXRT685S_cm33)

