/*
 * Copyright 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MKE18F512xxx16
package_id: MKE18F512VLL16
mcu_data: ksdk2_0
processor_version: 0.7.1
pin_labels:
- {pin_num: '20', pin_signal: PTD17/FTM0_FLT2/LPUART2_RX, label: DRV_OC, identifier: DRV_OC}
- {pin_num: '83', pin_signal: ADC1_SE12/PTA15/FTM1_CH2/LPSPI0_PCS3, label: DRV_EN, identifier: DRV_EN}
- {pin_num: '70', pin_signal: ADC1_SE3/PTD3/FTM3_CH5/LPSPI1_PCS0/FXIO_D5/TRGMUX_IN4/NMI_b, label: SW2, identifier: SW2}
- {pin_num: '55', pin_signal: ADC2_SE15/PTC9/LPUART1_TX/FTM1_FLT1/LPUART0_RTS, label: USER_LED, identifier: USER_LED}
- {pin_num: '8', pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/CAN0_TX/FXIO_D7/EWM_IN, label: DRV_RST, identifier: DRV_RST}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "fsl_trgmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    PinTool_FTM();
    PinTool_SPI();
    PinTool_UART();
    PinTool_Misc();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_FTM:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '68', peripheral: FTM0, signal: 'CH, 0', pin_signal: ADC1_SE7/PTB12/FTM0_CH0/FTM3_FLT2}
  - {pin_num: '67', peripheral: FTM0, signal: 'CH, 1', pin_signal: ADC1_SE8/ADC2_SE8/PTB13/FTM0_CH1/FTM3_FLT1}
  - {pin_num: '66', peripheral: FTM0, signal: 'CH, 2', pin_signal: ADC1_SE9/ADC2_SE9/PTB14/FTM0_CH2/LPSPI1_SCK}
  - {pin_num: '65', peripheral: FTM0, signal: 'CH, 3', pin_signal: ADC1_SE14/PTB15/FTM0_CH3/LPSPI1_SIN}
  - {pin_num: '64', peripheral: FTM0, signal: 'CH, 4', pin_signal: ADC1_SE15/PTB16/FTM0_CH4/LPSPI1_SOUT}
  - {pin_num: '63', peripheral: FTM0, signal: 'CH, 5', pin_signal: ADC2_SE3/PTB17/FTM0_CH5/LPSPI1_PCS3}
  - {pin_num: '20', peripheral: FTM0, signal: 'FLT, 2', pin_signal: PTD17/FTM0_FLT2/LPUART2_RX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_FTM
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_FTM(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    /* PORTB12 (pin 68) is configured as FTM0_CH0 */
    PORT_SetPinMux(PORTB, 12U, kPORT_MuxAlt2);

    /* PORTB13 (pin 67) is configured as FTM0_CH1 */
    PORT_SetPinMux(PORTB, 13U, kPORT_MuxAlt2);

    /* PORTB14 (pin 66) is configured as FTM0_CH2 */
    PORT_SetPinMux(PORTB, 14U, kPORT_MuxAlt2);

    /* PORTB15 (pin 65) is configured as FTM0_CH3 */
    PORT_SetPinMux(PORTB, 15U, kPORT_MuxAlt2);

    /* PORTB16 (pin 64) is configured as FTM0_CH4 */
    PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt2);

    /* PORTB17 (pin 63) is configured as FTM0_CH5 */
    PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt2);

    /* PORTD17 (pin 20) is configured as FTM0_FLT2 */
    PORT_SetPinMux(PINTOOL_FTM_DRV_OC_PORT, PINTOOL_FTM_DRV_OC_PIN, kPORT_MuxAlt2);

    SIM->FTMOPT0 = ((SIM->FTMOPT0 &
                     /* Mask bits to zero which are setting */
                     (~(SIM_FTMOPT0_FTM0FLTxSEL_MASK)))

                    /* FTM0 Fault X Select: 0x00u. */
                    | SIM_FTMOPT0_FTM0FLTxSEL(0x00u));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_SPI:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '94', peripheral: LPSPI0, signal: SCK, pin_signal: ADC2_SE7/PTE0/LPSPI0_SCK/TCLK1/LPI2C1_SDA/FTM1_FLT2}
  - {pin_num: '93', peripheral: LPSPI0, signal: SIN, pin_signal: ADC2_SE6/PTE1/LPSPI0_SIN/LPI2C0_HREQ/LPI2C1_SCL/FTM1_FLT1}
  - {pin_num: '85', peripheral: LPSPI0, signal: SOUT, pin_signal: ADC1_SE10/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/FTM3_CH6/PWT_IN3/LPUART1_CTS}
  - {pin_num: '84', peripheral: LPSPI0, signal: PCS2, pin_signal: ADC1_SE11/ACMP0_IN6/PTE6/LPSPI0_PCS2/FTM3_CH7/LPUART1_RTS}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_SPI
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_SPI(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTE0 (pin 94) is configured as LPSPI0_SCK */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt2);

    /* PORTE1 (pin 93) is configured as LPSPI0_SIN */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt2);

    /* PORTE2 (pin 85) is configured as LPSPI0_SOUT */
    PORT_SetPinMux(PORTE, 2U, kPORT_MuxAlt2);

    /* PORTE6 (pin 84) is configured as LPSPI0_PCS2 */
    PORT_SetPinMux(PORTE, 6U, kPORT_MuxAlt2);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_UART:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '54', peripheral: LPUART0, signal: RX, pin_signal: ADC0_SE4/ADC1_SE14/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3}
  - {pin_num: '53', peripheral: LPUART0, signal: TX, pin_signal: ADC0_SE5/ADC1_SE15/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_UART
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_UART(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    /* PORTB0 (pin 54) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt2);

    /* PORTB1 (pin 53) is configured as LPUART0_TX */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt2);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_Misc:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '55', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: ADC2_SE15/PTC9/LPUART1_TX/FTM1_FLT1/LPUART0_RTS, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '83', peripheral: GPIOA, signal: 'GPIO, 15', pin_signal: ADC1_SE12/PTA15/FTM1_CH2/LPSPI0_PCS3, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '70', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: ADC1_SE3/PTD3/FTM3_CH5/LPSPI1_PCS0/FXIO_D5/TRGMUX_IN4/NMI_b, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge,
    passive_filter: enable}
  - {peripheral: PDB0, signal: TRG, pin_signal: FTM0_Trigger}
  - {peripheral: PDB2, signal: TRG, pin_signal: FTM0_Trigger}
  - {pin_num: '8', peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/CAN0_TX/FXIO_D7/EWM_IN, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_Misc
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_Misc(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t DRV_EN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA15 (pin 83)  */
    GPIO_PinInit(PINTOOL_MISC_DRV_EN_GPIO, PINTOOL_MISC_DRV_EN_PIN, &DRV_EN_config);

    gpio_pin_config_t USER_LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin 55)  */
    GPIO_PinInit(PINTOOL_MISC_USER_LED_GPIO, PINTOOL_MISC_USER_LED_PIN, &USER_LED_config);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 70)  */
    GPIO_PinInit(PINTOOL_MISC_SW2_GPIO, PINTOOL_MISC_SW2_PIN, &SW2_config);

    gpio_pin_config_t DRV_RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE5 (pin 8)  */
    GPIO_PinInit(PINTOOL_MISC_DRV_RST_GPIO, PINTOOL_MISC_DRV_RST_PIN, &DRV_RST_config);

    /* PORTA15 (pin 83) is configured as PTA15 */
    PORT_SetPinMux(PINTOOL_MISC_DRV_EN_PORT, PINTOOL_MISC_DRV_EN_PIN, kPORT_MuxAsGpio);

    /* PORTC9 (pin 55) is configured as PTC9 */
    PORT_SetPinMux(PINTOOL_MISC_USER_LED_PORT, PINTOOL_MISC_USER_LED_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin 70) is configured as PTD3 */
    PORT_SetPinMux(PINTOOL_MISC_SW2_PORT, PINTOOL_MISC_SW2_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD3 (pin 70): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(PINTOOL_MISC_SW2_PORT, PINTOOL_MISC_SW2_PIN, kPORT_InterruptRisingEdge);

    PORTD->PCR[3] = ((PORTD->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Passive Filter Enable: Passive input filter is enabled on the corresponding pin, if the
                      * pin is configured as a digital input.
                      * Refer to the device data sheet for filter characteristics. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterEnable));

    /* PORTE5 (pin 8) is configured as PTE5 */
    PORT_SetPinMux(PINTOOL_MISC_DRV_RST_PORT, PINTOOL_MISC_DRV_RST_PIN, kPORT_MuxAsGpio);
    /* FTM0 is selected as PDB0 device trigger input 0 */
    TRGMUX_SetTriggerSource(TRGMUX0, kTRGMUX_Pdb0, kTRGMUX_TriggerInput0, kTRGMUX_SourceFtm0);
    /* FTM0 is selected as PDB2 device trigger input 0 */
    TRGMUX_SetTriggerSource(TRGMUX0, kTRGMUX_Pdb2, kTRGMUX_TriggerInput0, kTRGMUX_SourceFtm0);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
