/* ------------------------------------------------------------------------ */
/* Copyright (c) 2018 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ("Cadence    */
/* Libraries") are the copyrighted works of Cadence Design Systems Inc.	    */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* DSP Library                                                              */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2015-2018 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

/*
    NatureDSP Signal Processing Library. IIR part
    Biquad Real Block IIR, 32x32-bit, Direct Form I
    C code optimized for HiFi4
    IntegrIT, 2006-2018
*/

/* Portable data types. */
#include "NatureDSP_types.h"
/* Signal Processing Library API. */
#include "NatureDSP_Signal_iir.h"
/* Common utility and macros declarations. */
#include "common.h"
/* Filter instance structure. */
#include "stereo_bqriir32x32_df1_common.h"

/*-------------------------------------------------------------------------
  Bi-quad Real Block IIR
  Computes a real IIR filter (cascaded IIR direct form I or II using 5 
  coefficients per bi-quad + gain term). Real input data are stored
  in vector x. The filter output result is stored in vector r. The filter 
  calculates N output samples using SOS and G matrices.
  NOTE:
  1. Bi-quad coefficients may be derived from standard SOS and G matrices 
  generated by MATLAB. However, typically biquad stages have big peaks 
  in their step response which may cause undesirable overflows at the 
  intermediate outputs. To avoid that the additional scale factors 
  coef_g[M] may be applied. These per-section scale factors may require 
  some tuning to find a compromise between quantization noise and possible 
  overflows. Output of the last section is directed to an additional 
  multiplier, with the gain factor being a power of two, either negative 
  or non-negative. It is specified through the total gain shift amount 
  parameter gain of each filter initialization function.
  2. 16x16 filters may suffer more from accumulation of the roundoff errors,
  so filters should be properly designed to match noise requirements

  Precision: 
  16x16         16-bit data, 16-bit coefficients, 16-bit intermediate 
                stage outputs (DF1, DF1 stereo, DF II form)
  32x16         32-bit data, 16-bit coefficients, 32-bit intermediate 
                (DF1, DF1 stereo, DF II form) stage outputs
  32x32         32-bit data, 32-bit coefficients, 32-bit intermediate 
                (DF I, DF1 stereo,  DF II form) stage outputs 
  f             floating point (DF I, DF1 stereo, DF II and DF IIt)

  Input:
  N             length of input sample block
  M             number of bi-quad sections
  S             1 for mono, 2 for stereo API
  s[]           scratch memory area (for fixed-point functions only). 
                Minimum number of bytes depends on selected filter structure 
                and precision:
                  BQRIIR16X16_DF1_SCRATCH_SIZE( N,  M ), or
                  BQRIIR16X16_DF2_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X16_DF1_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X16_DF2_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X32_DF1_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X32_DF2_SCRATCH_SIZE( N,  M ),
                  STEREO_BQRIIR16X16_DF1_SCRATCH_SIZE( N, M ) , or
                  STEREO_BQRIIR32X32_DF1_SCRATCH_SIZE( N, M ) , or
                  STEREO_BQRIIRF_DF1_SCRATCH_SIZE    ( N, M )
                 If a particular macro returns zero, then the corresponding
                 IIR doesn't require a scratch area and parameter s may 
                 hold zero.
  coef_sos[M*5]  filter coefficients stored in blocks of 5 numbers: 
                 b0 b1 b2 a1 a2. 
                 For fixed-point funcions, fixed point format of filter 
                 coefficients is Q1.14 for 16x16 and 32x16, or Q1.30 for 32x32 
  coef_sosl[M*5] filter coefficients for the left channel (stereo filters only)
  coef_sosr[M*5] filter coefficients for the left channel (stereo filters only)
  coef_g[M]      scale factor for each section, Q15 (for fixed-point 
                 functions only)
  coef_gl[M]     scale factor for the left channel (stereo filters only)
  coef_gr[M]     scale factor for the right channel (stereo filters only)
  gain           total gain shift amount applied to output signal of the
                 last section, -48..15
  gainl          total gain shift amount  for the left channel (stereo filters 
                 only)
  gainr          total gain shift amount for the right channel (stereo filters 
                 only)

  x[N*S]         input samples, Q15, Q31 or floating point. Stereo samples 
                 go in interleaved order (left, right)
  Output:
  r[N*S]         output data, Q15, Q31 or floating point. Stereo samples go 
                 in interleaved order (left, right) 

  Restriction:
  x,r,s,coef_g,coef_sos should not overlap
  N   - must be a multiple of 2
  s[] - whenever supplied must be aligned on an 8-bytes boundary
-------------------------------------------------------------------------*/

#define AE_PKSRF32_( st, acc, offs ) \
  {                                  \
    ae_f32x2 st_ = st;               \
    AE_PKSRF32( st_, acc, offs );    \
    st = st_;                        \
  }

void stereo_bqriir32x32_df1( stereo_bqriir32x32_df1_handle_t _bqriir,
                             void    * restrict       s,
                             int32_t * restrict       r,
                       const int32_t *                x, int N )
{
  stereo_bqriir32x32_df1_ptr_t stereo_bqriir = (stereo_bqriir32x32_df1_ptr_t)_bqriir;

  const ae_int32x2*          coef_gsosl;
  const ae_int32x2*          coef_gsosr;
        ae_int32x2* restrict statel;
        ae_int32x2* restrict stater;
  const ae_int32x2* restrict px;
        ae_int32x2* restrict pr;

  int M;
  int m, n;

  NASSERT( stereo_bqriir && stereo_bqriir->magic == STEREO_BQRIIR32X32_DF1_MAGIC && r && x );
  if (N<=0) return;
  NASSERT( N%2==0 );

  M = stereo_bqriir->M;
  coef_gsosl = (const ae_int32x2*)stereo_bqriir->coef_gsosl;
  coef_gsosr = (const ae_int32x2*)stereo_bqriir->coef_gsosr;
  statel     = (      ae_int32x2*)stereo_bqriir->statel;
  stater     = (      ae_int32x2*)stereo_bqriir->stater;

  px = (const ae_int32x2*)x;
  pr = (      ae_int32x2*)r;

  //
  // Perform data block processing for each pair of successive sections. Use the
  // output array r[N] for temporal storage of inter-section signal.
  //

  for ( m=0; m<M/2; m++ )
  {
    ae_int32x2 cf0_b21, cf0_b10, cf0_a21;
    ae_int32x2 cf1_b21, cf1_b10, cf1_a21;

    // accXY: X - section id, Y - sample id
    ae_f64 acc00, acc01, acc10, acc11;

    ae_int32x2 st0, st1, st2;

    ae_int32x2 x01;

	ae_int32x2 x0, x1;

	// FIRST LEFT CHANNEL

	//
    // Load coefficients for the m-th pair of sections.
    //

    AE_L32X2_IP( cf0_b21, coef_gsosl, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf0_a21, coef_gsosl, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf0_b10, coef_gsosl, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf1_b21, coef_gsosl, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf1_a21, coef_gsosl, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf1_b10, coef_gsosl, 2*sizeof(int32_t) );

    //
    // Load sections' state.
    //

    st0 = AE_L32X2_I( statel, 0*sizeof(int32_t) );
    st1 = AE_L32X2_I( statel, 2*sizeof(int32_t) );
    st2 = AE_L32X2_I( statel, 4*sizeof(int32_t) );

    //
    // Pass N/2 sample pairs through 2 sections.
    //

    for ( n = 0; n < (N >> 1); n++ )
    {
      acc00 = AE_MULZAAFD32S_HH_LL( cf0_b21, st0 );

      AE_L32_IP( x0, castxcc(ae_int32,px), 2*sizeof(int32_t) );
      AE_L32_IP( x1, castxcc(ae_int32,px), 2*sizeof(int32_t) );
	  x01 = AE_SEL32_HH( x0, x1 );

      AE_MULAF32S_LH( acc00, cf0_b10, x0 );
      AE_MULSSFD32S_HH_LL( acc00, cf0_a21, st1 );

      acc01 = AE_MULF32S_HL( cf0_b21, st0 );

      acc10 = AE_MULF32S_HH( cf1_b21, st1 );

      AE_PKSRF32_( st1, acc00, 1 );

      AE_MULAAFD32S_HH_LL( acc01, cf0_b10, x01 );
      AE_MULSSFD32S_HH_LL( acc01, cf0_a21, st1 );

      AE_MULAAFD32S_HH_LL( acc10, cf1_b10, st1 );
      AE_MULSSFD32S_HH_LL( acc10, cf1_a21, st2 );
      AE_PKSRF32_( st2, acc10, 1 );

      acc11 = AE_MULF32S_HH( cf1_b21, st1 );

      AE_PKSRF32_( st1, acc01, 1 );

      AE_MULAAFD32S_HH_LL( acc11, cf1_b10, st1 );
      AE_MULSSFD32S_HH_LL( acc11, cf1_a21, st2 );
	  AE_S32_L_IP( st2, castxcc(ae_int32, pr), 2*sizeof(int32_t) );
      AE_PKSRF32_( st2, acc11, 1 );
	  AE_S32_L_IP( st2, castxcc(ae_int32, pr), 2*sizeof(int32_t) );

      st0 = x01;
    }

    //
    // Save sections' state.
    //

    AE_S32X2_IP( st0, statel, 2*sizeof(int32_t) );
    AE_S32X2_IP( st1, statel, 2*sizeof(int32_t) );
    AE_S32X2_IP( st2, statel, 2*sizeof(int32_t) );

	pr = (ae_int32x2 *)((int32_t *)pr - N*2 + 1);
	px = (ae_int32x2 *)((int32_t *)px - N*2 + 1);

	// THEN RIGHT CHANNEL

	//
    // Load coefficients for the m-th pair of sections.
    //

    AE_L32X2_IP( cf0_b21, coef_gsosr, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf0_a21, coef_gsosr, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf0_b10, coef_gsosr, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf1_b21, coef_gsosr, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf1_a21, coef_gsosr, 2*sizeof(int32_t) );
    AE_L32X2_IP( cf1_b10, coef_gsosr, 2*sizeof(int32_t) );

    //
    // Load sections' state.
    //

    st0 = AE_L32X2_I( stater, 0*sizeof(int32_t) );
    st1 = AE_L32X2_I( stater, 2*sizeof(int32_t) );
    st2 = AE_L32X2_I( stater, 4*sizeof(int32_t) );

    //
    // Pass N/2 sample pairs through 2 sections.
    //

    for ( n = 0; n < (N >> 1); n++ )
    {
      acc00 = AE_MULZAAFD32S_HH_LL( cf0_b21, st0 );

      AE_L32_IP( x0, castxcc(ae_int32,px), 2*sizeof(int32_t) );
      AE_L32_IP( x1, castxcc(ae_int32,px), 2*sizeof(int32_t) );
	  x01 = AE_SEL32_HH( x0, x1 );

      AE_MULAF32S_LH( acc00, cf0_b10, x0 );
      AE_MULSSFD32S_HH_LL( acc00, cf0_a21, st1 );

      acc01 = AE_MULF32S_HL( cf0_b21, st0 );

      acc10 = AE_MULF32S_HH( cf1_b21, st1 );

      AE_PKSRF32_( st1, acc00, 1 );

      AE_MULAAFD32S_HH_LL( acc01, cf0_b10, x01 );
      AE_MULSSFD32S_HH_LL( acc01, cf0_a21, st1 );

      AE_MULAAFD32S_HH_LL( acc10, cf1_b10, st1 );
      AE_MULSSFD32S_HH_LL( acc10, cf1_a21, st2 );
      AE_PKSRF32_( st2, acc10, 1 );

      acc11 = AE_MULF32S_HH( cf1_b21, st1 );

      AE_PKSRF32_( st1, acc01, 1 );

      AE_MULAAFD32S_HH_LL( acc11, cf1_b10, st1 );
      AE_MULSSFD32S_HH_LL( acc11, cf1_a21, st2 );
	  AE_S32_L_IP( st2, castxcc(ae_int32, pr), 2*sizeof(int32_t) );
      AE_PKSRF32_( st2, acc11, 1 );
	  AE_S32_L_IP( st2, castxcc(ae_int32, pr), 2*sizeof(int32_t) );

      st0 = x01;
    }

    //
    // Save sections' state.
    //

    AE_S32X2_IP( st0, stater, 2*sizeof(int32_t) );
    AE_S32X2_IP( st1, stater, 2*sizeof(int32_t) );
    AE_S32X2_IP( st2, stater, 2*sizeof(int32_t) );

    // Second to last pair of sections are fed with output signal of the
    // previous pair.
    px = pr = (ae_int32x2*)((int32_t *)pr - N*2 - 1);
  }

  //
  // Process the last section if the number of biquads is odd.
  //

  if ( M & 1 )
  {
    ae_int32x2 cf_b21, cf_b10, cf_a21;

    // accXY: X - section id, Y - sample id
    ae_f64 acc0, acc1;

    ae_int32x2 st0, st1, st2;

    ae_int32x2 x01;

	ae_int32x2 x0, x1;

	// FIRST LEFT CHANNEL

    //
    // Load coefficients for the last section.
    //

    cf_b21 = AE_L32X2_I( coef_gsosl, (0*6+0)*sizeof(int32_t) );
    cf_a21 = AE_L32X2_I( coef_gsosl, (0*6+2)*sizeof(int32_t) );
    cf_b10 = AE_L32X2_I( coef_gsosl, (0*6+4)*sizeof(int32_t) );

    //
    // Load last section's state.
    //

    st0 = AE_L32X2_I( statel, 0*sizeof(int32_t) );
    st1 = AE_L32X2_I( statel, 2*sizeof(int32_t) );
    st2 = AE_L32X2_I( statel, 4*sizeof(int32_t) );

    //
    // Pass N/2 sample pairs through the last section.
    //

    __Pragma( "loop_count min=1" );
    for ( n = 0; n < (N >> 1); n++ )
    {
      AE_L32_IP( x0, castxcc(ae_int32,px), 2*sizeof(int32_t) );
      AE_L32_IP( x1, castxcc(ae_int32,px), 2*sizeof(int32_t) );
	  x01 = AE_SEL32_HH( x0, x1 );

      acc0 = AE_MULF32S_LH( cf_b10, x0 );

      AE_MULAAFD32S_HH_LL( acc0, cf_b21, st0 );
      AE_MULSSFD32S_HH_LL( acc0, cf_a21, st1 );

      AE_PKSRF32_( st1, acc0, 1 );

      acc1 = AE_MULF32S_HL( cf_b21, st0 );

      AE_MULAAFD32S_HH_LL( acc1, cf_b10, x01 );
      AE_MULSSFD32S_HH_LL( acc1, cf_a21, st1 );

	  AE_S32_L_IP( st1, castxcc(ae_int32, pr), 2*sizeof(int32_t) );
      AE_PKSRF32_( st1, acc1, 1 );
	  AE_S32_L_IP( st1, castxcc(ae_int32, pr), 2*sizeof(int32_t) );

      st0 = x01;
    }

    //
    // Save section's state.
    //

    AE_S32X2_I( st0, statel, 0*sizeof(int32_t) );
    AE_S32X2_I( st1, statel, 2*sizeof(int32_t) );
    AE_S32X2_I( st2, statel, 4*sizeof(int32_t) );

	pr = (ae_int32x2 *)((int32_t *)pr - N*2 + 1);
	px = (ae_int32x2 *)((int32_t *)px - N*2 + 1);

	// THEN RIGHT CHANNEL

    //
    // Load coefficients for the last section.
    //

    cf_b21 = AE_L32X2_I( coef_gsosr, (0*6+0)*sizeof(int32_t) );
    cf_a21 = AE_L32X2_I( coef_gsosr, (0*6+2)*sizeof(int32_t) );
    cf_b10 = AE_L32X2_I( coef_gsosr, (0*6+4)*sizeof(int32_t) );

    //
    // Load last section's state.
    //

    st0 = AE_L32X2_I( stater, 0*sizeof(int32_t) );
    st1 = AE_L32X2_I( stater, 2*sizeof(int32_t) );
    st2 = AE_L32X2_I( stater, 4*sizeof(int32_t) );

    //
    // Pass N/2 sample pairs through the last section.
    //

    __Pragma( "loop_count min=1" );
    for ( n = 0; n < (N >> 1); n++ )
    {
      AE_L32_IP( x0, castxcc(ae_int32,px), 2*sizeof(int32_t) );
      AE_L32_IP( x1, castxcc(ae_int32,px), 2*sizeof(int32_t) );
	  x01 = AE_SEL32_HH( x0, x1 );

      acc0 = AE_MULF32S_LH( cf_b10, x0 );

      AE_MULAAFD32S_HH_LL( acc0, cf_b21, st0 );
      AE_MULSSFD32S_HH_LL( acc0, cf_a21, st1 );

      AE_PKSRF32_( st1, acc0, 1 );

      acc1 = AE_MULF32S_HL( cf_b21, st0 );

      AE_MULAAFD32S_HH_LL( acc1, cf_b10, x01 );
      AE_MULSSFD32S_HH_LL( acc1, cf_a21, st1 );

	  AE_S32_L_IP( st1, castxcc(ae_int32, pr), 2*sizeof(int32_t) );
      AE_PKSRF32_( st1, acc1, 1 );
	  AE_S32_L_IP( st1, castxcc(ae_int32, pr), 2*sizeof(int32_t) );

      st0 = x01;
    }

    //
    // Save section's state.
    //

    AE_S32X2_I( st0, stater, 0*sizeof(int32_t) );
    AE_S32X2_I( st1, stater, 2*sizeof(int32_t) );
    AE_S32X2_I( st2, stater, 4*sizeof(int32_t) );
  }

  //
  // Scale output data, if required.
  //

  if ( stereo_bqriir->gainl != 0 )
  {
    ae_int32x2 t0;

    WUR_AE_SAR( stereo_bqriir->gainl );

    px = (const ae_int32x2*)r;
    pr = (      ae_int32x2*)r;

    for ( n=0; n<N; n++ )
    {
      AE_L32_IP( t0, castxcc(ae_int32,px), sizeof(ae_int32x2) );
      t0 = AE_SLAS32S( t0 );
	  AE_S32_L_IP( t0, castxcc(ae_int32,pr), sizeof(ae_int32x2) );
    }
  }
  if ( stereo_bqriir->gainr != 0 )
  {
    ae_int32x2 t0;

    WUR_AE_SAR( stereo_bqriir->gainr );

    px = (const ae_int32x2*)(r+1);
    pr = (      ae_int32x2*)(r+1);

    for ( n=0; n<N; n++ )
    {
      AE_L32_IP( t0, castxcc(ae_int32,px), sizeof(ae_int32x2) );
      t0 = AE_SLAS32S( t0 );
	  AE_S32_L_IP( t0, castxcc(ae_int32,pr), sizeof(ae_int32x2) );
    }
  }
} /* stereo_bqriir32x32_df1() */
