# Add set(CONFIG_USE_middleware_tfm_s_test_crypto true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

      target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/suites/crypto/crypto_tests_common.c
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/suites/crypto/secure/crypto_sec_interface_testsuite.c
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/common_test_services/tfm_secure_client_2/tfm_secure_client_2.c
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/common_test_services/tfm_secure_client_2/tfm_secure_client_2_api.c
        )

  
      target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/suites/crypto
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/suites/crypto/secure
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/common_test_services/tfm_secure_client_service
          ${CMAKE_CURRENT_LIST_DIR}/../tf-m/autogenerated/secure_fw/test_services/tfm_secure_client_service/psa_manifest
          ${CMAKE_CURRENT_LIST_DIR}/../tf-m/autogenerated/secure_fw/test_services/tfm_secure_client_2/psa_manifest
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/common_test_services/tfm_secure_client_2
          ${CMAKE_CURRENT_LIST_DIR}/tests_reg/test/secure_fw/suites/spm/ipc/secure
        )

    if(CONFIG_USE_COMPONENT_CONFIGURATION)
  message("===>Import configuration from ${CMAKE_CURRENT_LIST_FILE}")

      target_compile_definitions(${MCUX_SDK_PROJECT_NAME} PUBLIC
                  -DTFM_PARTITION_CRYPTO
                        -DPLATFORM_DEFAULT_CRYPTO_KEYS
                        -DMBEDTLS_PSA_CRYPTO_DRIVERS
              )
  
  
  endif()

