/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _EDGEFAST_BLUETOOTH_CONFIG_GEN_H_
#define _EDGEFAST_BLUETOOTH_CONFIG_GEN_H_

#define CONFIG_BT_LONG_WQ 1
#define CONFIG_BT_LONG_WQ_STACK_SIZE 1300
#define CONFIG_BT_LONG_WQ_PRIO 10
#define CONFIG_BT_HCI_HOST 1
#define CONFIG_BT_BUF_RESERVE 8
#define CONFIG_BT_SNOOP 1
#define CONFIG_BT_HCI_RESERVE 0
#define CONFIG_BT_HCI_TX_STACK_SIZE 1024
#define CONFIG_BT_HCI_TX_PRIO 7
#define CONFIG_BT_RX_STACK_SIZE 2048
#define CONFIG_BT_RX_PRIO 1
#define CONFIG_BT_PERIPHERAL 1
#define CONFIG_BT_BROADCASTER 1
#define CONFIG_BT_CENTRAL 1
#define CONFIG_BT_OBSERVER 1
// #define CONFIG_BT_EXT_ADV 0
#define CONFIG_BT_LIM_ADV_TIMEOUT 30
#define CONFIG_BT_CONN_TX_USER_DATA_SIZE 8
#define CONFIG_BT_PER_ADV_SYNC_BUF_SIZE 0
#define CONFIG_BT_SMP 1
#define CONFIG_BT_FILTER_ACCEPT_LIST 1
#define CONFIG_BT_DEVICE_NAME "Tester"
// #define CONFIG_BT_DEVICE_APPEARANCE_DYNAMIC 0
#define CONFIG_BT_DEVICE_APPEARANCE 0
#define CONFIG_BT_DEVICE_NAME_DYNAMIC 1
#define CONFIG_BT_DEVICE_NAME_MAX 32
#define CONFIG_BT_ID_MAX 1
#define CONFIG_BT_CONN 1
#define CONFIG_BT_MAX_CONN 3
#define CONFIG_BT_CONN_FRAG_COUNT 3
#define CONFIG_BT_CONN_TX 1
// #define CONFIG_BT_HCI_ACL_FLOW_CONTROL 0
#define CONFIG_BT_PHY_UPDATE 1
#define CONFIG_BT_DATA_LEN_UPDATE 1
// #define CONFIG_BT_PER_ADV_SYNC_TRANSFER_RECEIVER 0
// #define CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER 0
#define CONFIG_BT_CREATE_CONN_TIMEOUT 30
#define CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT 5000
#define CONFIG_BT_CONN_TX_MAX 3
// #define CONFIG_BT_CONN_DISABLE_SECURITY 0
// #define CONFIG_BT_CONN_PARAM_ANY 0
// #define CONFIG_BT_CTLR_LE_POWER_CONTROL_SUPPORT 0
// #define CONFIG_BT_USER_PHY_UPDATE 0
#define CONFIG_BT_AUTO_PHY_UPDATE 1
// #define CONFIG_BT_USER_DATA_LEN_UPDATE 0
#define CONFIG_BT_AUTO_DATA_LEN_UPDATE 1
// #define CONFIG_BT_REMOTE_INFO 0
// #define CONFIG_BT_SMP_SC_ONLY 0
// #define CONFIG_BT_SMP_SC_PAIR_ONLY 0
// #define CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY 0
// #define CONFIG_BT_SMP_DISABLE_LEGACY_JW_PASSKEY 0
// #define CONFIG_BT_PASSKEY_KEYPRESS 0
// #define CONFIG_BT_PRIVACY 0
#define CONFIG_BT_ECC 1
// #define CONFIG_BT_TINYCRYPT_ECC 0
#define CONFIG_BT_TINYCRYPT_ECC_PRIORITY 10
#define CONFIG_BT_HCI_ECC_STACK_SIZE 1140
#define CONFIG_BT_RPA 1
#define CONFIG_BT_RPA_TIMEOUT 900
#define CONFIG_BT_SIGNING 1
#define CONFIG_BT_SMP_APP_PAIRING_ACCEPT 1
#define CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE 1
// #define CONFIG_BT_ID_ALLOW_UNAUTH_OVERWRITE 0
#define CONFIG_BT_ID_UNPAIR_MATCHING_BONDS 0
#define CONFIG_BT_FIXED_PASSKEY 0
#define CONFIG_BT_BONDABLE 1
// #define CONFIG_BT_BONDING_REQUIRED 0
#define CONFIG_BT_BONDABLE_PER_CONNECTION 0
// #define CONFIG_BT_SMP_ENFORCE_MITM 0
// #define CONFIG_BT_OOB_DATA_FIXED 0
// #define CONFIG_BT_KEYS_OVERWRITE_OLDEST 0
// #define CONFIG_BT_EAD 0
#define CONFIG_BT_HOST_CCM 1
#define CONFIG_BT_SMP_MIN_ENC_KEY_SIZE 7
#define CONFIG_BT_L2CAP_TX_BUF_COUNT 3
#define CONFIG_BT_L2CAP_TX_FRAG_COUNT 2
#define CONFIG_BT_L2CAP_TX_MTU 69
#define CONFIG_BT_L2CAP_RESCHED_MS 1000
// #define CONFIG_BT_L2CAP_SEG_RECV 0
#define CONFIG_BT_L2CAP_DYNAMIC_CHANNEL 1
#define CONFIG_BT_L2CAP_ECRED 1
// #define CONFIG_BT_L2CAP_IFRAME_SUPPORT 0
#define CONFIG_BT_ATT_PREPARE_COUNT 12
#define CONFIG_BT_ATT_TX_COUNT 3
// #define CONFIG_BT_ATT_RETRY_ON_SEC_ERR 0
#define CONFIG_BT_ATT_TX_MAX 3
#define CONFIG_BT_ATT_RX_MAX 3
#define CONFIG_BT_EATT 1
#define CONFIG_BT_GATT_READ_MULT_VAR_LEN 1
#define CONFIG_BT_EATT_MAX 5
// #define CONFIG_BT_EATT_AUTO_CONNECT 0
#define CONFIG_BT_EATT_SEC_LEVEL 1
#define CONFIG_BT_GATT_SERVICE_CHANGED 1
// #define CONFIG_BT_GATT_AUTO_RESUBSCRIBE 0
#define CONFIG_BT_GATT_DYNAMIC_DB 1
#define CONFIG_BT_GATT_CACHING 1
#define CONFIG_BT_GATT_NOTIFY_MULTIPLE 1
#define CONFIG_BT_GATT_NOTIFY_MULTIPLE_FLUSH_MS 1
#define CONFIG_BT_GATT_ENFORCE_CHANGE_UNAWARE 0
#define CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION 1
#define CONFIG_BT_GATT_CLIENT 1
#define CONFIG_BT_GATT_READ_MULTIPLE 1
// #define CONFIG_BT_GATT_AUTO_UPDATE_MTU 0
// #define CONFIG_BT_GATT_AUTO_DISCOVER_CCC 0
#define CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS 1
#define CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS 1
#define CONFIG_BT_PERIPHERAL_PREF_MIN_INT 24
#define CONFIG_BT_PERIPHERAL_PREF_MAX_INT 40
#define CONFIG_BT_PERIPHERAL_PREF_LATENCY 0
#define CONFIG_BT_PERIPHERAL_PREF_TIMEOUT 42
#define CONFIG_BT_DEVICE_NAME_GATT_WRITABLE 1
#define CONFIG_DEVICE_NAME_GATT_WRITABLE_ENCRYPT 1
// #define CONFIG_DEVICE_NAME_GATT_WRITABLE_AUTHEN 0
// #define CONFIG_BT_GATT_AUTHORIZATION_CUSTOM 0
#define CONFIG_BT_MAX_PAIRED 3
#define CONFIG_BT_BACKGROUND_SCAN_INTERVAL 2048
#define CONFIG_BT_BACKGROUND_SCAN_WINDOW 18
#define CONFIG_BT_EXT_SCAN_BUF_SIZE 229
// #define CONFIG_BT_SCAN_WITH_IDENTITY 0
// #define CONFIG_BT_ISO_UNICAST 0
// #define CONFIG_BT_ISO_PERIPHERAL 0
// #define CONFIG_BT_ISO_CENTRAL 0
// #define CONFIG_BT_ISO_BROADCASTER 0
// #define CONFIG_BT_ISO_SYNC_RECEIVER 0
// #define CONFIG_BT_ISO_BROADCAST 0
// #define CONFIG_BT_SETTINGS 0
// #define CONFIG_BT_CLASSIC 0
// #define CONFIG_BT_BLE_DISABLE 0
#define CONFIG_BT_BUF_ACL_TX_SIZE 27
#define CONFIG_BT_BUF_ACL_TX_COUNT 3
#define CONFIG_BT_BUF_ACL_RX_SIZE 100
#define CONFIG_BT_BUF_ACL_RX_COUNT 3
#define CONFIG_BT_BUF_EVT_RX_SIZE 255
#define CONFIG_BT_BUF_EVT_RX_COUNT 3
#define CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE 43
#define CONFIG_BT_BUF_EVT_DISCARDABLE_COUNT 20
#define CONFIG_BT_BUF_CMD_TX_SIZE 65
#define CONFIG_BT_BUF_CMD_TX_COUNT 2
#define CONFIG_BT_DIS_MODEL "Simplified BT"
#define CONFIG_BT_DIS_MANUF "NXP"
#define CONFIG_BT_DIS_PNP 1
#define CONFIG_BT_DIS_PNP_VID_SRC 1
#define CONFIG_BT_DIS_PNP_VID 0x0025
#define CONFIG_BT_DIS_PNP_PID 0
#define CONFIG_BT_DIS_PNP_VER 1
#define CONFIG_BT_DIS_SERIAL_NUMBER 1
#define CONFIG_BT_DIS_SERIAL_NUMBER_STR "00000000"
#define CONFIG_BT_DIS_FW_REV 1
#define CONFIG_BT_DIS_FW_REV_STR "00000000"
#define CONFIG_BT_DIS_HW_REV 1
#define CONFIG_BT_DIS_HW_REV_STR "00000000"
#define CONFIG_BT_DIS_SW_REV 1
#define CONFIG_BT_DIS_SW_REV_STR "00000000"
#define CONFIG_NET_BUF_USER_DATA_SIZE 8
#define CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE 512
#define CONFIG_SYSTEM_WORKQUEUE_PRIORITY 4
#define CONFIG_BT_HCI_TRANSPORT_INTERFACE_TYPE (gSerialMgrLpuart_c)
#define CONFIG_BT_HCI_TRANSPORT_INTERFACE_INSTANCE 1
#define CONFIG_BT_HCI_TRANSPORT_INTERFACE_SPEED 115200
#define CONFIG_BT_HCI_TRANSPORT_TX_THREAD 1
#define CONFIG_BT_HCI_TRANSPORT_RX_THREAD 1
#define CONFIG_BT_HCI_TRANSPORT_RX_STACK_SIZE 512
#define CONFIG_BT_HCI_TRANSPORT_TX_STACK_SIZE 512
#define CONFIG_BT_HCI_TRANSPORT_TX_PRIO 8
#define CONFIG_BT_HCI_TRANSPORT_RX_PRIO 6
#define CONFIG_BT_MSG_QUEUE_COUNT 16

#endif /* _EDGEFAST_BLUETOOTH_CONFIG_GEN_H_ */
