/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_EMC_B1_11 (coord D2), LED_GREEN_CTL */
/* Routed pin properties */
#define BOARD_INITPINS_LED_GREEN_CTL_PERIPHERAL                           RGPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_GREEN_CTL_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_GREEN_CTL_CHANNEL                                 11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_CTL_GPIO                                 RGPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_CTL_INIT_GPIO_VALUE                          0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LED_GREEN_CTL_GPIO_PIN                                11U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_GREEN_CTL_GPIO_PIN_MASK                   (1U << 11U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/* GPIO_AD_12 (coord N14), CUR_A */
/* Routed pin properties */
#define BOARD_INITADC_CUR_A_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITADC_CUR_A_SIGNAL                                             A   /*!< Signal name */
#define BOARD_INITADC_CUR_A_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_AD_13 (coord M13), CUR_B */
/* Routed pin properties */
#define BOARD_INITADC_CUR_B_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITADC_CUR_B_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INITADC_CUR_B_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_AD_29 (coord L13), CUR_C */
/* Routed pin properties */
#define BOARD_INITADC_CUR_C_PERIPHERAL                                      ADC2   /*!< Peripheral name */
#define BOARD_INITADC_CUR_C_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INITADC_CUR_C_CHANNEL                                           2U   /*!< Signal channel */

/* GPIO_AD_14 (coord M12), VOLT_DCB */
/* Routed pin properties */
#define BOARD_INITADC_VOLT_DCB_PERIPHERAL                                   ADC1   /*!< Peripheral name */
#define BOARD_INITADC_VOLT_DCB_SIGNAL                                          A   /*!< Signal name */
#define BOARD_INITADC_VOLT_DCB_CHANNEL                                        1U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADC(void);                     /* Function assigned for the Cortex-M7F */

/* GPIO_EMC_B1_12 (coord D7), PWM_AT */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_AT_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_AT_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPWM_PWM_AT_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_EMC_B1_13 (coord E3), PWM_AB */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_AB_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_AB_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPWM_PWM_AB_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_EMC_B1_14 (coord E5), PWM_BT */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_BT_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_BT_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPWM_PWM_BT_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_EMC_B1_15 (coord E2), PWM_BB */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_BB_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_BB_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPWM_PWM_BB_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_EMC_B1_17 (coord C2), PWM_CT */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_CT_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_CT_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPWM_PWM_CT_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_EMC_B1_16 (coord G1), PWM_CB */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_CB_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_CB_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPWM_PWM_CB_CHANNEL                                          2U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWM(void);                     /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART(void);                  /* Function assigned for the Cortex-M7F */

#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_4_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT4 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_5_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT5 function direction select: XBAR_INOUT as input */

/* GPIO_EMC_B1_00 (coord G3), ENC_A */
/* Routed pin properties */
#define BOARD_INITENC_ENC_A_PERIPHERAL                                     EQDC1   /*!< Peripheral name */
#define BOARD_INITENC_ENC_A_SIGNAL                                         PHASE   /*!< Signal name */
#define BOARD_INITENC_ENC_A_CHANNEL                                            A   /*!< Signal channel */

/* GPIO_EMC_B1_01 (coord H4), ENC_B */
/* Routed pin properties */
#define BOARD_INITENC_ENC_B_PERIPHERAL                                     EQDC1   /*!< Peripheral name */
#define BOARD_INITENC_ENC_B_SIGNAL                                         PHASE   /*!< Signal name */
#define BOARD_INITENC_ENC_B_CHANNEL                                            B   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENC(void);                     /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
