# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_sdmmc_host_sdhc_MK64F12 true)
set(CONFIG_USE_middleware_sdmmc_host_sdhc_freertos_MK64F12 true)
set(CONFIG_USE_middleware_fatfs_sd_MK64F12 true)
set(CONFIG_USE_component_serial_manager_uart_MK64F12 true)
set(CONFIG_USE_driver_uart_MK64F12 true)
set(CONFIG_USE_middleware_usb_device_khci_MK64F12 true)
set(CONFIG_USE_middleware_freertos-kernel_MK64F12 true)
