# Add set(CONFIG_USE_middleware_freertos-kernel_config true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

            add_config_file(${CMAKE_CURRENT_LIST_DIR}/template/FreeRTOSConfig.h ${CMAKE_CURRENT_LIST_DIR}/template middleware_freertos-kernel_config)
    
        if(CONFIG_CORE STREQUAL cm0p)
          add_config_file(${CMAKE_CURRENT_LIST_DIR}/template/ARM_CM0/FreeRTOSConfig_Gen.h ${CMAKE_CURRENT_LIST_DIR}/template/ARM_CM4F_4_priority_bits middleware_freertos-kernel_config)
        endif()

        if(CONFIG_CORE STREQUAL cm33 AND (CONFIG_DEVICE_ID STREQUAL KW47B42Z83xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z96xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42Z97xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB3xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB6xxxA OR CONFIG_DEVICE_ID STREQUAL KW47B42ZB7xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42082xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z42092xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B2xxxA OR CONFIG_DEVICE_ID STREQUAL KW47Z420B3xxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727AxxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727CxxxA OR CONFIG_DEVICE_ID STREQUAL MCXW727DxxxA OR CONFIG_DEVICE_ID STREQUAL MCXL255 OR CONFIG_DEVICE_ID STREQUAL MIMXRT1181xxxxx OR CONFIG_DEVICE_ID STREQUAL MIMXRT1182xxxxx OR CONFIG_DEVICE_ID STREQUAL MIMXRT1187xxxxx OR CONFIG_DEVICE_ID STREQUAL MIMXRT1189xxxxx OR CONFIG_DEVICE_ID STREQUAL MIMXRT798S OR CONFIG_DEVICE_ID STREQUAL MIMXRT735S OR CONFIG_DEVICE_ID STREQUAL MIMXRT758S) AND (CONFIG_FPU STREQUAL NO_FPU OR CONFIG_FPU STREQUAL SP_FPU))
          add_config_file(${CMAKE_CURRENT_LIST_DIR}/template/ARM_CM33_3_priority_bits/FreeRTOSConfig_Gen.h ${CMAKE_CURRENT_LIST_DIR}/template/ARM_CM4F_4_priority_bits middleware_freertos-kernel_config)
        endif()

        if(CONFIG_CORE STREQUAL cm7f AND (CONFIG_DEVICE_ID STREQUAL MIMXRT1187xxxxx OR CONFIG_DEVICE_ID STREQUAL MIMXRT1189xxxxx OR CONFIG_DEVICE_ID STREQUAL MCXE31B))
          add_config_file(${CMAKE_CURRENT_LIST_DIR}/template/ARM_CM4F_4_priority_bits/FreeRTOSConfig_Gen.h ${CMAKE_CURRENT_LIST_DIR}/template/ARM_CM4F_4_priority_bits middleware_freertos-kernel_config)
        endif()

  

