/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MIMXRT798S
package_id: MIMXRT798SGFOA
mcu_data: ksdk2_0
processor_version: 0.2412.20
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iopctl.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitUARTPins();
    BOARD_InitCameraPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitMipiPanelPinsEvk:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: K6, peripheral: GPIO3, signal: 'IO, 4', pin_signal: PIO3_4/LPSPI14_PCS3/LP_FLEXCOMM0_P4/LP_FLEXCOMM3_P2}
  - {pin_num: K7, peripheral: GPIO3, signal: 'IO, 5', pin_signal: PIO3_5/LPSPI14_PCS2/LP_FLEXCOMM0_P5/LP_FLEXCOMM3_P3/EZH_PIO21, input_buffer: enable}
  - {pin_num: T2, peripheral: GPIO1, signal: 'IO, 10', pin_signal: PIO1_10/LP_FLEXCOMM1_P3/UTICK0_CAP3/CTIMER2_MAT1/SWD_TRACECLK/CLKOUT_VDD1}
  - {pin_num: P3, peripheral: GPIO1, signal: 'IO, 14', pin_signal: PIO1_14/LP_FLEXCOMM2_P2/CTIMER3_MAT0/SWD_TRACEDATA3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMipiPanelPinsEvk
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitMipiPanelPinsEvk(void)
{
  /* There are conflicts or other incorrect settings in the configuration, the code below is generated only for 
     those registers which are set correctly and without a conflict. Open this file in Pins Tool for more details. */

    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port3_pin5_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT3 PIN5 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(3U, 5U, port3_pin5_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUARTPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: N4, peripheral: LP_FLEXCOMM0, signal: P0, pin_signal: PIO0_31/LP_FLEXCOMM0_P0/UTICK0_CAP2/SCT0_OUT8/CTIMER4_MAT0}
  - {pin_num: N5, peripheral: LP_FLEXCOMM0, signal: P1, pin_signal: PIO1_0/LP_FLEXCOMM0_P1/SCT0_OUT9/CTIMER4_MAT1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitUARTPins(void)
{
    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port0_pin31_config = (/* Pin is configured as LP_FLEXCOMM0_P0 */
                                         IOPCTL_PIO_FUNC1 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI |
                                         /* Selects transmitter current drive 100ohm */
                                         IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN31 (coords: N4) is configured as LP_FLEXCOMM0_P0 */
    IOPCTL_PinMuxSet(0U, 31U, port0_pin31_config);

    const uint32_t port1_pin0_config = (/* Pin is configured as LP_FLEXCOMM0_P1 */
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT1 PIN0 (coords: N5) is configured as LP_FLEXCOMM0_P1 */
    IOPCTL_PinMuxSet(1U, 0U, port1_pin0_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFlexIOPanelPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: H6, peripheral: FLEXIO, signal: 'D, 6', pin_signal: PIO2_6/LPSPI16_PCS3/FLEXIO_D6/LCD_DATA0/LCD_DBI_DATA0, slew_rate: slow, input_buffer: enable, pull_enable: enable}
  - {pin_num: G6, peripheral: FLEXIO, signal: 'D, 7', pin_signal: PIO2_7/LPSPI16_PCS2/EZH_PIO7/FLEXIO_D7/LCD_D1/LCD_DBI_D1, slew_rate: slow, input_buffer: enable,
    pull_enable: enable}
  - {pin_num: G4, peripheral: FLEXIO, signal: 'D, 8', pin_signal: PIO2_8/LPSPI16_PCS1/EZH_PIO8/FLEXIO_D8/LCD_D2/LCD_DBI_D2, slew_rate: slow, input_buffer: enable,
    pull_enable: enable}
  - {pin_num: G5, peripheral: FLEXIO, signal: 'D, 9', pin_signal: PIO2_9/EZH_PIO9/FLEXIO_D9/LCD_D3/LCD_DBI_D3, slew_rate: slow, input_buffer: enable, pull_enable: enable}
  - {pin_num: F5, peripheral: FLEXIO, signal: 'D, 10', pin_signal: PIO2_10/EZH_PIO10/FLEXIO_D10/LCD_D4/LCD_DBI_D4, slew_rate: slow, input_buffer: enable, pull_enable: enable}
  - {pin_num: F3, peripheral: FLEXIO, signal: 'D, 11', pin_signal: PIO2_11/EZH_PIO11/FLEXIO_D11/LCD_D5/LCD_DBI_D5, slew_rate: slow, input_buffer: enable, pull_enable: enable}
  - {pin_num: E3, peripheral: FLEXIO, signal: 'D, 12', pin_signal: PIO2_12/EZH_PIO12/FLEXIO_D12/LCD_D6/LCD_DBI_D6, slew_rate: slow, input_buffer: enable, pull_enable: enable}
  - {pin_num: E4, peripheral: FLEXIO, signal: 'D, 13', pin_signal: PIO2_13/EZH_PIO13/FLEXIO_D13/LCD_D7/LCD_DBI_D7, slew_rate: slow, input_buffer: enable, pull_enable: enable}
  - {pin_num: H2, peripheral: GPIO2, signal: 'IO, 0', pin_signal: PIO2_0/USB0_OVERCURRENTN/EZH_PIO0/FLEXIO_D0/LCD_DBI_CSX_AB, direction: OUTPUT}
  - {pin_num: G2, peripheral: GPIO2, signal: 'IO, 1', pin_signal: PIO2_1/USB0_PORTPWRN/EZH_PIO1/FLEXIO_D1/LCD_DBI_DCX_AB, direction: OUTPUT}
  - {pin_num: D3, peripheral: GPIO2, signal: 'IO, 15', pin_signal: PIO2_15/EZH_PIO15/FLEXIO_D15/CLKCTL0_LOW_FREQ_CLKOUT_N, direction: OUTPUT}
  - {pin_num: G1, peripheral: FLEXIO, signal: 'D, 3', pin_signal: PIO2_3/LPSPI16_SCK/EZH_PIO3/FLEXIO_D3/LCD_DOTCLK/LCD_DBI_RWDX, direction: OUTPUT}
  - {pin_num: G3, peripheral: FLEXIO, signal: 'D, 4', pin_signal: PIO2_4/LPSPI16_SIN/EZH_PIO4/FLEXIO_D4/LCD_HSYNC/LCD_DBI_WRX, direction: OUTPUT, slew_rate: slow,
    input_buffer: enable, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexIOPanelPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitFlexIOPanelPins(void)
{
  /* There are conflicts or other incorrect settings in the configuration, the code below is generated only for 
     those registers which are set correctly and without a conflict. Open this file in Pins Tool for more details. */

    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port2_pin10_config = (/* Pin is configured as  */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Slow mode */
                                         IOPCTL_PIO_SLEW_RATE_SLOW |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN10 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 10U, port2_pin10_config);

    const uint32_t port2_pin11_config = (/* Pin is configured as  */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Slow mode */
                                         IOPCTL_PIO_SLEW_RATE_SLOW |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN11 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 11U, port2_pin11_config);

    const uint32_t port2_pin12_config = (/* Pin is configured as  */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Slow mode */
                                         IOPCTL_PIO_SLEW_RATE_SLOW |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN12 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 12U, port2_pin12_config);

    const uint32_t port2_pin13_config = (/* Pin is configured as  */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Slow mode */
                                         IOPCTL_PIO_SLEW_RATE_SLOW |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN13 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 13U, port2_pin13_config);

    const uint32_t port2_pin4_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Slow mode */
                                        IOPCTL_PIO_SLEW_RATE_SLOW |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN4 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 4U, port2_pin4_config);

    const uint32_t port2_pin6_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Slow mode */
                                        IOPCTL_PIO_SLEW_RATE_SLOW |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN6 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 6U, port2_pin6_config);

    const uint32_t port2_pin7_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Slow mode */
                                        IOPCTL_PIO_SLEW_RATE_SLOW |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN7 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 7U, port2_pin7_config);

    const uint32_t port2_pin8_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Slow mode */
                                        IOPCTL_PIO_SLEW_RATE_SLOW |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN8 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 8U, port2_pin8_config);

    const uint32_t port2_pin9_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Slow mode */
                                        IOPCTL_PIO_SLEW_RATE_SLOW |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN9 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 9U, port2_pin9_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLcdDBIPanelPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D3, peripheral: GPIO2, signal: 'IO, 15', pin_signal: PIO2_15/EZH_PIO15/FLEXIO_D15/CLKCTL0_LOW_FREQ_CLKOUT_N, direction: OUTPUT}
  - {pin_num: H6, peripheral: LCDIF, signal: 'DBI_DATA, 0', pin_signal: PIO2_6/LPSPI16_PCS3/FLEXIO_D6/LCD_DATA0/LCD_DBI_DATA0, pull_select: up, pull_enable: enable}
  - {pin_num: G6, peripheral: LCDIF, signal: 'DBI_DATA, 1', pin_signal: PIO2_7/LPSPI16_PCS2/EZH_PIO7/FLEXIO_D7/LCD_D1/LCD_DBI_D1, pull_select: up, pull_enable: enable}
  - {pin_num: G4, peripheral: LCDIF, signal: 'DBI_DATA, 2', pin_signal: PIO2_8/LPSPI16_PCS1/EZH_PIO8/FLEXIO_D8/LCD_D2/LCD_DBI_D2, pull_select: up, pull_enable: enable}
  - {pin_num: G5, peripheral: LCDIF, signal: 'DBI_DATA, 3', pin_signal: PIO2_9/EZH_PIO9/FLEXIO_D9/LCD_D3/LCD_DBI_D3, pull_select: up, pull_enable: enable}
  - {pin_num: F5, peripheral: LCDIF, signal: 'DBI_DATA, 4', pin_signal: PIO2_10/EZH_PIO10/FLEXIO_D10/LCD_D4/LCD_DBI_D4, pull_select: up, pull_enable: enable}
  - {pin_num: F3, peripheral: LCDIF, signal: 'DBI_DATA, 5', pin_signal: PIO2_11/EZH_PIO11/FLEXIO_D11/LCD_D5/LCD_DBI_D5, pull_select: up, pull_enable: enable}
  - {pin_num: E3, peripheral: LCDIF, signal: 'DBI_DATA, 6', pin_signal: PIO2_12/EZH_PIO12/FLEXIO_D12/LCD_D6/LCD_DBI_D6, pull_select: up, pull_enable: enable}
  - {pin_num: E4, peripheral: LCDIF, signal: 'DBI_DATA, 7', pin_signal: PIO2_13/EZH_PIO13/FLEXIO_D13/LCD_D7/LCD_DBI_D7, pull_select: up, pull_enable: enable}
  - {pin_num: G1, peripheral: LCDIF, signal: DBI_RWDX, pin_signal: PIO2_3/LPSPI16_SCK/EZH_PIO3/FLEXIO_D3/LCD_DOTCLK/LCD_DBI_RWDX, direction: OUTPUT, slew_rate: slow,
    input_buffer: disable, pull_select: up, pull_enable: disable}
  - {pin_num: G3, peripheral: LCDIF, signal: DBI_WRX, pin_signal: PIO2_4/LPSPI16_SIN/EZH_PIO4/FLEXIO_D4/LCD_HSYNC/LCD_DBI_WRX, direction: OUTPUT, slew_rate: standard,
    input_buffer: disable, pull_select: up, pull_enable: disable}
  - {pin_num: H2, peripheral: LCDIF, signal: DBI_CSX_AB, pin_signal: PIO2_0/USB0_OVERCURRENTN/EZH_PIO0/FLEXIO_D0/LCD_DBI_CSX_AB, direction: OUTPUT, slew_rate: standard,
    input_buffer: disable, pull_select: up, pull_enable: disable}
  - {pin_num: G2, peripheral: LCDIF, signal: DBI_DCX_AB, pin_signal: PIO2_1/USB0_PORTPWRN/EZH_PIO1/FLEXIO_D1/LCD_DBI_DCX_AB, direction: OUTPUT, slew_rate: slow, input_buffer: disable,
    pull_select: up, pull_enable: disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLcdDBIPanelPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitLcdDBIPanelPins(void)
{
  /* There are conflicts or other incorrect settings in the configuration, the code below is generated only for 
     those registers which are set correctly and without a conflict. Open this file in Pins Tool for more details. */

    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port2_pin0_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN0 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 0U, port2_pin0_config);

    const uint32_t port2_pin1_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Slow mode */
                                        IOPCTL_PIO_SLEW_RATE_SLOW |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN1 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 1U, port2_pin1_config);

    const uint32_t port2_pin10_config = (/* Pin is configured as LCD_DBI_D4 */
                                         IOPCTL_PIO_FUNC7 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-up function */
                                         IOPCTL_PIO_PULLUP_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN10 (coords: F5) is configured as LCD_DBI_D4 */
    IOPCTL_PinMuxSet(2U, 10U, port2_pin10_config);

    const uint32_t port2_pin11_config = (/* Pin is configured as LCD_DBI_D5 */
                                         IOPCTL_PIO_FUNC7 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-up function */
                                         IOPCTL_PIO_PULLUP_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN11 (coords: F3) is configured as LCD_DBI_D5 */
    IOPCTL_PinMuxSet(2U, 11U, port2_pin11_config);

    const uint32_t port2_pin12_config = (/* Pin is configured as LCD_DBI_D6 */
                                         IOPCTL_PIO_FUNC7 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-up function */
                                         IOPCTL_PIO_PULLUP_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN12 (coords: E3) is configured as LCD_DBI_D6 */
    IOPCTL_PinMuxSet(2U, 12U, port2_pin12_config);

    const uint32_t port2_pin13_config = (/* Pin is configured as LCD_DBI_D7 */
                                         IOPCTL_PIO_FUNC7 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-up function */
                                         IOPCTL_PIO_PULLUP_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN13 (coords: E4) is configured as LCD_DBI_D7 */
    IOPCTL_PinMuxSet(2U, 13U, port2_pin13_config);

    const uint32_t port2_pin3_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Slow mode */
                                        IOPCTL_PIO_SLEW_RATE_SLOW |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN3 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 3U, port2_pin3_config);

    const uint32_t port2_pin4_config = (/* Pin is configured as  */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN4 (coords: ) is configured as  */
    IOPCTL_PinMuxSet(2U, 4U, port2_pin4_config);

    const uint32_t port2_pin6_config = (/* Pin is configured as LCD_DBI_DATA0 */
                                        IOPCTL_PIO_FUNC7 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN6 (coords: H6) is configured as LCD_DBI_DATA0 */
    IOPCTL_PinMuxSet(2U, 6U, port2_pin6_config);

    const uint32_t port2_pin7_config = (/* Pin is configured as LCD_DBI_D1 */
                                        IOPCTL_PIO_FUNC7 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN7 (coords: G6) is configured as LCD_DBI_D1 */
    IOPCTL_PinMuxSet(2U, 7U, port2_pin7_config);

    const uint32_t port2_pin8_config = (/* Pin is configured as LCD_DBI_D2 */
                                        IOPCTL_PIO_FUNC7 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN8 (coords: G4) is configured as LCD_DBI_D2 */
    IOPCTL_PinMuxSet(2U, 8U, port2_pin8_config);

    const uint32_t port2_pin9_config = (/* Pin is configured as LCD_DBI_D3 */
                                        IOPCTL_PIO_FUNC7 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN9 (coords: G5) is configured as LCD_DBI_D3 */
    IOPCTL_PinMuxSet(2U, 9U, port2_pin9_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: J5, peripheral: LP_FLEXCOMM8, signal: P0, pin_signal: PIO0_6/LP_FLEXCOMM4_P2/SCT0_GPIN6/SCT0_OUT6/CTIMER_C_INP10/LP_FLEXCOMM8_P0, open_drain: enable,
    input_buffer: enable}
  - {pin_num: K5, peripheral: LP_FLEXCOMM8, signal: P1, pin_signal: PIO0_7/LP_FLEXCOMM4_P3/SCT0_GPIN7/SCT0_OUT7/CTIMER_C_INP11/LP_FLEXCOMM8_P1, open_drain: enable,
    input_buffer: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitPins(void)
{
    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port0_pin6_config = (/* Pin is configured as LP_FLEXCOMM8_P0 */
                                        IOPCTL_PIO_FUNC5 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Pseudo Output Drain is enabled */
                                        IOPCTL_PIO_PSEDRAIN_EN |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN6 (coords: J5) is configured as LP_FLEXCOMM8_P0 */
    IOPCTL_PinMuxSet(0U, 6U, port0_pin6_config);

    const uint32_t port0_pin7_config = (/* Pin is configured as LP_FLEXCOMM8_P1 */
                                        IOPCTL_PIO_FUNC5 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Pseudo Output Drain is enabled */
                                        IOPCTL_PIO_PSEDRAIN_EN |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN7 (coords: K5) is configured as LP_FLEXCOMM8_P1 */
    IOPCTL_PinMuxSet(0U, 7U, port0_pin7_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCameraPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: H2, peripheral: GPIO2, signal: 'GPIO, 0', pin_signal: PIO2_0/USB0_OVERCURRENTN/EZH_PIO0/FLEXIO_D0/LCD_DBI_CSX_AB, direction: OUTPUT, input_buffer: disable}
  - {pin_num: G2, peripheral: FLEXIO, signal: 'IO, 1', pin_signal: PIO2_1/USB0_PORTPWRN/EZH_PIO1/FLEXIO_D1/LCD_DBI_DCX_AB}
  - {pin_num: H3, peripheral: FLEXIO, signal: 'IO, 2', pin_signal: PIO2_2/LPSPI16_SOUT/EZH_PIO2/FLEXIO_D2/LCD_ENABLE/LCD_DBI_DATA_OEN, input_buffer: enable}
  - {pin_num: J6, peripheral: GPIO2, signal: 'GPIO, 5', pin_signal: PIO2_5/LPSPI16_PCS0/EZH_PIO5/FLEXIO_D5/LCD_VSYNC/LCD_DBI_E, direction: INPUT, input_buffer: enable}
  - {pin_num: H6, peripheral: FLEXIO, signal: 'IO, 6', pin_signal: PIO2_6/LPSPI16_PCS3/FLEXIO_D6/LCD_DATA0/LCD_DBI_DATA0, input_buffer: enable}
  - {pin_num: G6, peripheral: FLEXIO, signal: 'IO, 7', pin_signal: PIO2_7/LPSPI16_PCS2/EZH_PIO7/FLEXIO_D7/LCD_D1/LCD_DBI_D1, input_buffer: enable}
  - {pin_num: G4, peripheral: FLEXIO, signal: 'IO, 8', pin_signal: PIO2_8/LPSPI16_PCS1/EZH_PIO8/FLEXIO_D8/LCD_D2/LCD_DBI_D2, input_buffer: enable}
  - {pin_num: G5, peripheral: FLEXIO, signal: 'IO, 9', pin_signal: PIO2_9/EZH_PIO9/FLEXIO_D9/LCD_D3/LCD_DBI_D3, input_buffer: enable}
  - {pin_num: F5, peripheral: FLEXIO, signal: 'IO, 10', pin_signal: PIO2_10/EZH_PIO10/FLEXIO_D10/LCD_D4/LCD_DBI_D4, input_buffer: enable}
  - {pin_num: F3, peripheral: FLEXIO, signal: 'IO, 11', pin_signal: PIO2_11/EZH_PIO11/FLEXIO_D11/LCD_D5/LCD_DBI_D5, input_buffer: enable}
  - {pin_num: E3, peripheral: FLEXIO, signal: 'IO, 12', pin_signal: PIO2_12/EZH_PIO12/FLEXIO_D12/LCD_D6/LCD_DBI_D6, input_buffer: enable}
  - {pin_num: E4, peripheral: FLEXIO, signal: 'IO, 13', pin_signal: PIO2_13/EZH_PIO13/FLEXIO_D13/LCD_D7/LCD_DBI_D7, input_buffer: enable}
  - {pin_num: D3, peripheral: FLEXIO, signal: 'IO, 15', pin_signal: PIO2_15/EZH_PIO15/FLEXIO_D15/CLKCTL0_LOW_FREQ_CLKOUT_N, input_buffer: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCameraPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitCameraPins(void)
{

    /* Enables the clock for the GPIO2 module */
    CLOCK_EnableClock(kCLOCK_Gpio2);

    gpio_pin_config_t gpio2_pinJ6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_5 (pin J6)  */
    GPIO_PinInit(GPIO2, 5U, &gpio2_pinJ6_config);
    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port2_pin0_config = (/* Pin is configured as PIO2_0 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN0 (coords: H2) is configured as PIO2_0 => RESET, J53-17 */
    IOPCTL_PinMuxSet(2U, 0U, port2_pin0_config);

    const uint32_t port2_pin1_config = (/* Pin is configured as FLEXIO_D1 */
                                        IOPCTL_PIO_FUNC5 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN1 (coords: G2) is configured as FLEXIO_D1 => XCLK, J53-8 */
    IOPCTL_PinMuxSet(2U, 1U, port2_pin1_config);

    const uint32_t port2_pin5_config = (/* Pin is configured as PIO2_5 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN5 (coords: J6) is configured as PIO2_5 => VSYNC, J53-5 */
    IOPCTL_PinMuxSet(2U, 5U, port2_pin5_config);

    const uint32_t flexio_config = (/* Pin is configured as FLEXIO_D10 */
                                         IOPCTL_PIO_FUNC5 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN2 (coords: H3) is configured as FLEXIO_D2 => HREF, J53-6 */
    IOPCTL_PinMuxSet(2U, 2U, flexio_config);
    
    /* PORT2 PIN6 (coords: H6) is configured as FLEXIO_D6 => D0, J53-16 */
    IOPCTL_PinMuxSet(2U, 6U, flexio_config);

    /* PORT2 PIN7 (coords: G6) is configured as FLEXIO_D7 => D1, J53-15 */
    IOPCTL_PinMuxSet(2U, 7U, flexio_config);

    /* PORT2 PIN8 (coords: G4) is configured as FLEXIO_D8 => D2, J53-14 */
    IOPCTL_PinMuxSet(2U, 8U, flexio_config);

    /* PORT2 PIN9 (coords: G5) is configured as FLEXIO_D9 => D3, J53-13 */
    IOPCTL_PinMuxSet(2U, 9U, flexio_config);

    /* PORT2 PIN10 (coords: F5) is configured as FLEXIO_D10 => D4, J53-12 */
    IOPCTL_PinMuxSet(2U, 10U, flexio_config);

    /* PORT2 PIN11 (coords: F3) is configured as FLEXIO_D11 => D5, J53-11 */
    IOPCTL_PinMuxSet(2U, 11U, flexio_config);

    /* PORT2 PIN12 (coords: E3) is configured as FLEXIO_D12 => D6, J53-10 */
    IOPCTL_PinMuxSet(2U, 12U, flexio_config);

    /* PORT2 PIN13 (coords: E4) is configured as FLEXIO_D13 => D7, J53-09 */
    IOPCTL_PinMuxSet(2U, 13U, flexio_config);

    /* PORT2 PIN15 (coords: D3) is configured as FLEXIO_D15 => PCLK, J53-7 */
    IOPCTL_PinMuxSet(2U, 15U, flexio_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPsRamPins_Xspi2
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPsRamPins_Xspi2(void)
{

    RESET_ClearPeripheralReset(kIOPCTL2_RST_SHIFT_RSTn);

	const uint32_t port4_pin0_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 0U, port4_pin0_config);

    const uint32_t port4_pin1_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 1U, port4_pin1_config);

    const uint32_t port4_pin2_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 2U, port4_pin2_config);

    const uint32_t port4_pin3_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 3U, port4_pin3_config);

    const uint32_t port4_pin4_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 4U, port4_pin4_config);

    const uint32_t port4_pin5_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 5U, port4_pin5_config);

    const uint32_t port4_pin6_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 6U, port4_pin6_config);

    const uint32_t port4_pin7_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 7U, port4_pin7_config);

    const uint32_t port4_pin8_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 8U, port4_pin8_config);

    const uint32_t port4_pin9_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 9U, port4_pin9_config);

    const uint32_t port4_pin10_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 10U, port4_pin10_config);

    const uint32_t port4_pin11_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 11U, port4_pin11_config);

    const uint32_t port4_pin12_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 12U, port4_pin12_config);

    const uint32_t port4_pin13_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 13U, port4_pin13_config);

    const uint32_t port4_pin14_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 14U, port4_pin14_config);

    const uint32_t port4_pin15_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 15U, port4_pin15_config);

    const uint32_t port4_pin16_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 16U, port4_pin16_config);

    const uint32_t port4_pin17_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 17U, port4_pin17_config);

    const uint32_t port4_pin18_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 18U, port4_pin18_config);

    const uint32_t port4_pin19_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 19U, port4_pin19_config);

    const uint32_t port4_pin20_config = (
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);

    IOPCTL_PinMuxSet(4U, 20U, port4_pin20_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
