# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_driver_enet_MIMXRT1042 true)
set(CONFIG_USE_middleware_lwip_enet_ethernetif_MIMXRT1042 true)
set(CONFIG_USE_component_mflash_rt1040_MIMXRT1042 true)
set(CONFIG_USE_middleware_mbedtls_rt_MIMXRT1042 true)
set(CONFIG_USE_component_silicon_id_rt10xx_MIMXRT1042 true)
set(CONFIG_USE_middleware_freertos_coremqtt_MIMXRT1042 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT1042 true)
set(CONFIG_USE_driver_lpuart_MIMXRT1042 true)
