/*
 * Copyright 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v10.0
processor: MKV31F512xxx12
package_id: MKV31F512VLL12
mcu_data: ksdk2_0
processor_version: 0.10.7
board: FRDM-KV31F
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 3c2ce4b7-ca2b-4319-b2c3-f2ae36318c83
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * UART0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UART0'
- type: 'uart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'uart_88ab1eca0cddb7ee407685775de016d5'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'UART0'
- config_sets:
  - uartConfig_t:
    - uartConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '19200'
      - parityMode: 'kUART_ParityDisabled'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - idleType: 'kUART_IdleTypeStartBit'
      - enableTx: 'true'
      - enableRx: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const uart_config_t UART0_config = {
  .baudRate_Bps = 19200UL,
  .parityMode = kUART_ParityDisabled,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .idleType = kUART_IdleTypeStartBit,
  .enableTx = true,
  .enableRx = true
};

static void UART0_init(void) {
  assert(UART_Init(UART0_PERIPHERAL, &UART0_config, UART0_CLOCK_SOURCE) == kStatus_Success);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * FreeMASTER initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FreeMASTER'
- type: 'freemaster'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'freemaster_14894d49d87e02d0dca5f799e22554da'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - freemaster_config:
    - FMSTR_DISABLE: 'false'
    - initFreemaster: 'true'
    - generalConfig:
      - commInterface: 'serial'
      - interruptMode: 'polling'
      - initType: 'true'
      - serialConfig:
        - peripheralUART: 'UART0'
        - clockSource: 'genericUartClockSource'
        - clockSourceFreq: 'BOARD_BootClockRUN'
        - enableUserInit: 'false'
        - user_init:
          - initFunctionID: 'UART0_init'
      - FMSTR_COMM_BUFFER_SIZE: 'autoSize'
      - FMSTR_COMM_RQUEUE_SIZE: '32'
      - FMSTR_USE_SCOPE: '2'
      - FMSTR_MAX_SCOPE_VARS: '8'
      - FMSTR_REC_FLOAT_TRIG: 'true'
      - recorders:
        - 0:
          - recID:
            - enableCustomID: 'false'
          - nameRec: 'Description of recorder 0'
          - recBuff:
            - customBuffer: 'false'
            - bufferSize: '4096'
          - basePeriod_ns: '100000'
          - recInit: 'true'
      - FMSTR_USE_TSA: 'true'
      - FMSTR_USE_TSA_INROM: 'true'
      - FMSTR_USE_TSA_SAFETY: 'true'
      - FMSTR_USE_TSA_DYNAMIC: 'true'
      - tsaBufferInit: 'false'
      - tsaBuff:
        - customBuffer: 'false'
        - bufferSize: '(5 * sizeof(FMSTR_TSA_ENTRY))'
      - pipes:
        - 0:
          - pipeID:
            - enableCustomID: 'false'
          - namePipe: 'Description of pipe 1'
          - pipePort: '1'
          - enablePipeHandler: 'false'
          - callbackFunction: 'Pipe1_Handler'
          - rxBuffer:
            - customBuffer: 'false'
            - bufferSize: '32'
          - txBuffer:
            - customBuffer: 'false'
            - bufferSize: '32'
          - pipeInit: 'false'
        - 1:
          - pipeID:
            - enableCustomID: 'false'
          - namePipe: 'Description of pipe 2'
          - pipePort: '2'
          - enablePipeHandler: 'false'
          - callbackFunction: 'Pipe2_Handler'
          - rxBuffer:
            - customBuffer: 'false'
            - bufferSize: '32'
          - txBuffer:
            - customBuffer: 'false'
            - bufferSize: '32'
          - pipeInit: 'false'
        - 2:
          - pipeID:
            - enableCustomID: 'false'
          - namePipe: 'Description of pipe 3'
          - pipePort: '3'
          - enablePipeHandler: 'false'
          - callbackFunction: 'Pipe3_Handler'
          - rxBuffer:
            - customBuffer: 'false'
            - bufferSize: '32'
          - txBuffer:
            - customBuffer: 'false'
            - bufferSize: '32'
          - pipeInit: 'false'
      - FMSTR_USE_READMEM: 'true'
      - FMSTR_USE_WRITEMEM: 'true'
      - FMSTR_USE_WRITEMEMMASK: 'true'
      - passR: ''
      - passRW: ''
      - passRWF: ''
      - FMSTR_USE_HASHED_PASSWORDS: 'false'
      - FMSTR_USE_APPCMD: 'true'
      - FMSTR_APPCMD_BUFF_SIZE: '32'
      - FMSTR_MAX_APPCMD_CALLS: '4'
      - FMSTR_DEBUG_LEVEL: '0'
      - FMSTR_DEBUG_PRINTF: 'debug_console'
      - FMSTR_DEBUG_TX: 'false'
      - FMSTR_CUSTOM_INCLUDES: ''
      - FMSTR_CUSTOM_OPTIONS: ''
    - freemaster_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Recorder0 configuration */
FMSTR_U8 FreeMASTER_RecBuffer0[FREEMASTER_REC_0_SIZE];
/* Pipe0 handle */
FMSTR_HPIPE FreeMASTER_Pipe_handle_1;
/* Pipe0 Rx buffer */
FMSTR_U8 FreeMASTER_RxPipe1[FREEMASTER_RX_PIPE_1_SIZE];
/* Pipe0 Tx buffer */
FMSTR_U8 FreeMASTER_TxPipe1[FREEMASTER_TX_PIPE_1_SIZE];
/* Pipe1 handle */
FMSTR_HPIPE FreeMASTER_Pipe_handle_2;
/* Pipe1 Rx buffer */
FMSTR_U8 FreeMASTER_RxPipe2[FREEMASTER_RX_PIPE_2_SIZE];
/* Pipe1 Tx buffer */
FMSTR_U8 FreeMASTER_TxPipe2[FREEMASTER_TX_PIPE_2_SIZE];
/* Pipe2 handle */
FMSTR_HPIPE FreeMASTER_Pipe_handle_3;
/* Pipe2 Rx buffer */
FMSTR_U8 FreeMASTER_RxPipe3[FREEMASTER_RX_PIPE_3_SIZE];
/* Pipe2 Tx buffer */
FMSTR_U8 FreeMASTER_TxPipe3[FREEMASTER_TX_PIPE_3_SIZE];
FMSTR_REC_BUFF FreeMASTER_Recorder_0 = {
  .name = "Description of recorder 0",
  .addr = (FMSTR_ADDR)FreeMASTER_RecBuffer0,
  .size = FREEMASTER_REC_0_SIZE,
  .basePeriod_ns = 100000UL
};

static void FreeMASTER_init(void) {
  /* FreeMASTER middleware initialization */
  FMSTR_Init();
  /* FreeMASTER recorder 0 configuration initialization  */
  FMSTR_RecorderCreate(0, &FreeMASTER_Recorder_0);
}

/***********************************************************************************************************************
 * MC_PMSM initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MC_PMSM'
- type: 'mc_pmsm'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'mc_pmsm_e46a8ee77e01be2dbe0a6770ae154c23'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - mc_config:
    - initMCPMSM: 'true'
    - timing:
      - pwmPeripheralFTM: 'FTM0'
      - clockSource: '1'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - pwmFreq: 'freq10'
      - M1_FOC_FREQ_VS_PWM_FREQ: '1'
      - slowLoopPeripheralFTM: 'FTM2'
      - SLclockSource: '1'
      - SLclockSourceFreq: 'BOARD_BootClockRUN'
      - slowLoopFreq: 'freq1_0'
    - outputControl:
      - phaseA: '0'
      - phaseB: '1'
      - phaseC: '2'
      - topTrans: 'high'
      - bottomTrans: 'high'
      - M1_PWM_DEADTIME_ENABLE: 'true'
      - pwmDeadtime: '500 ns'
      - M1_FAULT_ENABLE: 'true'
      - faultPinSelect: 'FLT.1'
      - M1_FAULT_POL: 'high'
      - cmpThreshold: '98'
      - dcbusBrakeEnable: 'false'
      - dcbusBrakeGPIO:
        - peripheralGPIO: 'GPIOA'
        - gpioPinSelect: 'GPIO.0'
    - adcSensing:
      - blockADC: []
      - adc0Mux: 'a'
      - adc1Mux: 'a'
      - bothADCs: 'a'
      - PH_A:
        - adc0: 'SE.8'
        - adc1: 'SE.8'
      - PH_B:
        - adcInstance: 'adc1'
        - adc1: 'SE.0'
      - PH_C:
        - adcInstance: 'adc0'
        - adc0: 'SE.0'
      - UDCB:
        - adcInstance: 'adc0'
        - adc0: 'SE.13'
      - AUX:
        - adcInstance: 'adc1'
        - adc1: 'SE.26'
      - ADC_OFFSET_WINDOW: 'offset3'
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
    - inrushRelay:
      - inrushRelayEnable: 'false'
      - inrushRelayDelay: '1 s'
      - inrushRelayGPIO:
        - peripheralGPIO: 'GPIOA'
        - gpioPinSelect: 'GPIO.0'
    - interruptConfig:
      - fastLoopInterrupt:
        - IRQn: 'ADC1_IRQn'
        - enable_custom_name: 'false'
      - slowLoopInterrupt:
        - IRQn: 'FTM2_IRQn'
        - enable_custom_name: 'false'
      - pdbInterrupt:
        - IRQn: 'PDB0_IRQn'
        - enable_custom_name: 'false'
    - mc_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void MC_PMSM_init(void) {
  /* MC_PMSM middleware initialization */
  MCDRV_Init_M1();
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  UART0_init();
  FreeMASTER_init();
  MC_PMSM_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
