PRIMARY_SERVICE(service_wpt, gBleSig_WPTService_d)
        CHARACTERISTIC_UUID128(char_pru_control, uuid_characteristic_pru_control, (gGattCharPropRead_c | gGattCharPropWriteWithoutRsp_c) )
            VALUE_UUID128(value_pru_control, uuid_characteristic_pru_control, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 5, 0x00, 0x00, 0x00, 0x00, 0x00)
        CHARACTERISTIC_UUID128(char_ptu_static, uuid_characteristic_ptu_static, (gGattCharPropRead_c | gGattCharPropWriteWithoutRsp_c))
            VALUE_UUID128(value_ptu_static, uuid_characteristic_ptu_static, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 17, 0x00)
        CHARACTERISTIC_UUID128(char_pru_alert, uuid_characteristic_pru_alert, (gGattCharPropRead_c | gGattCharPropNotify_c))
            VALUE_UUID128(value_pru_alert, uuid_characteristic_pru_alert, (gPermissionFlagReadable_c), 1, 0x00)
            CCCD(cccd_pru_alert)
        CHARACTERISTIC_UUID128(char_pru_static, uuid_characteristic_pru_static, (gGattCharPropRead_c))
            VALUE_UUID128(value_pru_static, uuid_characteristic_pru_static, (gPermissionFlagReadable_c), 20, 0x00)
        CHARACTERISTIC_UUID128(char_pru_dynamic, uuid_characteristic_pru_dynamic, (gGattCharPropRead_c))
            VALUE_UUID128(value_pru_dynamic, uuid_characteristic_pru_dynamic, (gPermissionFlagReadable_c), 20, 0x00)

PRIMARY_SERVICE(service_gap, gBleSig_GenericAccessProfile_d)
    CHARACTERISTIC(char_device_name, gBleSig_GapDeviceName_d, (gGattCharPropRead_c) )
            VALUE(value_device_name, gBleSig_GapDeviceName_d, (gPermissionFlagReadable_c), 12, "WPT PRU")
    CHARACTERISTIC(char_appearance, gBleSig_GapAppearance_d, (gGattCharPropRead_c) )
            VALUE(value_appearance, gBleSig_GapAppearance_d, (gPermissionFlagReadable_c), 2, 0)
    CHARACTERISTIC(char_ppcp, gBleSig_GapPpcp_d, (gGattCharPropRead_c) )
            VALUE(value_ppcp, gBleSig_GapPpcp_d, (gPermissionFlagReadable_c), 8, 0x28, 0x00, 0xC8, 0x00, 0x020, 0x03)
                
PRIMARY_SERVICE(service_gatt, gBleSig_GenericAttributeProfile_d)
        CHARACTERISTIC(char_service_changed, gBleSig_GattServiceChanged_d, (gGattCharPropIndicate_c) )
            VALUE(value_service_changed, gBleSig_GattServiceChanged_d, (gPermissionNone_c), 4, 0x00, 0x00, 0x00, 0x00)