/* @TEST_ANCHOR */
#ifdef CPU_MIMXRT1062DVL6A_cm7
#define WIFI_88W8987_BOARD_AW_CM358_USD
#else
#define WIFI_BOARD_IW61x
#endif
/* @END_TEST_ANCHOR */
/*#define WIFI_IW416_BOARD_AW_AM510_USD*/
/*#define WIFI_88W8987_BOARD_AW_CM358_USD*/
/*#define WIFI_IW416_BOARD_MURATA_1XK_USD*/
/*#define WIFI_88W8987_BOARD_MURATA_1ZM_USD*/

/* Wi-Fi boards configuration */
#if defined(WIFI_88W8977_BOARD_PAN9026_SDIO)
#define SD8977
#define SDMMCHOST_OPERATION_VOLTAGE_3V3
/* #define SDMMCHOST_OPERATION_VOLTAGE_1V8 */
#define SD_CLOCK_MAX (25000000U)
#elif defined(WIFI_BOARD_AW_AM281SM)
#define SD8977
#elif defined(WIFI_88W8801_BOARD_AW_NM191MA)
#define SD8801
#define SDMMCHOST_OPERATION_VOLTAGE_1V8
#elif (defined(WIFI_IW416_BOARD_AW_AM457_USD) || defined(WIFI_IW416_BOARD_AW_AM457MA))
#define SD8978
#define SDMMCHOST_OPERATION_VOLTAGE_3V3
#define SD_CLOCK_MAX (25000000U)
#elif (defined(WIFI_IW416_BOARD_MURATA_1XK_USD))
#define SD8978
#define SDMMCHOST_OPERATION_VOLTAGE_3V3
#define SD_CLOCK_MAX (25000000U)
#elif (defined(WIFI_88W8987_BOARD_AW_CM358_USD) || defined(WIFI_88W8987_BOARD_AW_CM358MA))
#define SD8987
#define SDMMCHOST_OPERATION_VOLTAGE_3V3
#define SD_CLOCK_MAX (25000000U)
#define CONFIG_BT_HCI_BAUDRATE (3000000U)
#elif (defined(WIFI_88W8987_BOARD_MURATA_1ZM_USD))
#define SD8987
#define WIFI_BT_USE_USD_INTERFACE
#define SDMMCHOST_OPERATION_VOLTAGE_1V8
#define SD_CLOCK_MAX (25000000U)
#define CONFIG_BT_HCI_BAUDRATE (3000000U)
#elif defined(WIFI_BOARD_IW61x)
#define IW61x
#define SDMMCHOST_OPERATION_VOLTAGE_3V3
#else
#error "Please define macro related to wifi board"
#endif

#define CONFIG_MAX_AP_ENTRIES 10
#define CONFIG_UAP_AMPDU_TX   1
#define CONFIG_UAP_AMPDU_RX   1
#define CONFIG_WIFI_MAX_PRIO (configMAX_PRIORITIES - 1)


#if defined(SD8977) || defined(SD8978) || defined(SD8987)
#define CONFIG_5GHz_SUPPORT 1
#endif

#if defined(SD8987)
#define CONFIG_11AC
#undef CONFIG_WMM
#endif

/* Logs */
#define CONFIG_ENABLE_ERROR_LOGS   1
#define CONFIG_ENABLE_WARNING_LOGS 1

/* WLCMGR debug */
#undef CONFIG_WLCMGR_DEBUG

/*
 * Wifi extra debug options
 */
#undef CONFIG_WIFI_EXTRA_DEBUG
#undef CONFIG_WIFI_EVENTS_DEBUG
#undef CONFIG_WIFI_CMD_RESP_DEBUG
#undef CONFIG_WIFI_SCAN_DEBUG
#undef CONFIG_WIFI_IO_INFO_DUMP
#undef CONFIG_WIFI_IO_DEBUG
#undef CONFIG_WIFI_IO_DUMP
#undef CONFIG_WIFI_MEM_DEBUG
#undef CONFIG_WIFI_AMPDU_DEBUG
#undef CONFIG_WIFI_TIMER_DEBUG
#undef CONFIG_WIFI_SDIO_DEBUG

