/* ------------------------------------------------------------------------ */
/* Copyright (c) 2018 by Cadence Design Systems, Inc. ALL RIGHTS RESERVED.  */
/* These coded instructions, statements, and computer programs ("Cadence    */
/* Libraries") are the copyrighted works of Cadence Design Systems Inc.	    */
/* Cadence IP is licensed for use with Cadence processor cores only and     */
/* must not be used for any other processors and platforms. Your use of the */
/* Cadence Libraries is subject to the terms of the license agreement you   */
/* have entered into with Cadence Design Systems, or a sublicense granted   */
/* to you by a direct Cadence licensee.                                     */
/* ------------------------------------------------------------------------ */
/*  IntegrIT, Ltd.   www.integrIT.com, info@integrIT.com                    */
/*                                                                          */
/* DSP Library                                                              */
/*                                                                          */
/* This library contains copyrighted materials, trade secrets and other     */
/* proprietary information of IntegrIT, Ltd. This software is licensed for  */
/* use with Cadence processor cores only and must not be used for any other */
/* processors and platforms. The license to use these sources was given to  */
/* Cadence, Inc. under Terms and Condition of a Software License Agreement  */
/* between Cadence, Inc. and IntegrIT, Ltd.                                 */
/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2015-2018 IntegrIT, Limited.                      */
/*                      All Rights Reserved.                                */
/* ------------------------------------------------------------------------ */

/*
  NatureDSP Signal Processing Library. IIR part
    Bi-quad Real Block IIR, 16x16-bit, Direct Form I
    Code optimized for HiFi4
  IntegrIT, 2006-2018
*/

/* Portable data types. */
#include "NatureDSP_types.h"
/* Signal Processing Library API. */
#include "NatureDSP_Signal_iir.h"
/* Common utility and macros declarations. */
#include "common.h"

/*-------------------------------------------------------------------------
  Bi-quad Real Block IIR
  Computes a real IIR filter (cascaded IIR direct form I or II using 5 
  coefficients per bi-quad + gain term). Real input data are stored
  in vector x. The filter output result is stored in vector r. The filter 
  calculates N output samples using SOS and G matrices.
  NOTE:
  1. Bi-quad coefficients may be derived from standard SOS and G matrices 
  generated by MATLAB. However, typically biquad stages have big peaks 
  in their step response which may cause undesirable overflows at the 
  intermediate outputs. To avoid that the additional scale factors 
  coef_g[M] may be applied. These per-section scale factors may require 
  some tuning to find a compromise between quantization noise and possible 
  overflows. Output of the last section is directed to an additional 
  multiplier, with the gain factor being a power of two, either negative 
  or non-negative. It is specified through the total gain shift amount 
  parameter gain of each filter initialization function.
  2. 16x16 filters may suffer more from accumulation of the roundoff errors,
  so filters should be properly designed to match noise requirements

  Precision: 
  16x16         16-bit data, 16-bit coefficients, 16-bit intermediate 
                stage outputs (DF1, DF1 stereo, DF II form)
  32x16         32-bit data, 16-bit coefficients, 32-bit intermediate 
                (DF1, DF1 stereo, DF II form) stage outputs
  32x32         32-bit data, 32-bit coefficients, 32-bit intermediate 
                (DF I, DF1 stereo,  DF II form) stage outputs 
  f             floating point (DF I, DF1 stereo, DF II and DF IIt)

  Input:
  N             length of input sample block
  M             number of bi-quad sections
  S             1 for mono, 2 for stereo API
  s[]           scratch memory area (for fixed-point functions only). 
                Minimum number of bytes depends on selected filter structure 
                and precision:
                  BQRIIR16X16_DF1_SCRATCH_SIZE( N,  M ), or
                  BQRIIR16X16_DF2_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X16_DF1_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X16_DF2_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X32_DF1_SCRATCH_SIZE( N,  M ), or
                  BQRIIR32X32_DF2_SCRATCH_SIZE( N,  M ),
                  STEREO_BQRIIR16X16_DF1_SCRATCH_SIZE( N, M ) , or
                  STEREO_BQRIIR32X32_DF1_SCRATCH_SIZE( N, M ) , or
                  STEREO_BQRIIRF_DF1_SCRATCH_SIZE    ( N, M )
                 If a particular macro returns zero, then the corresponding
                 IIR doesn't require a scratch area and parameter s may 
                 hold zero.
  coef_sos[M*5]  filter coefficients stored in blocks of 5 numbers: 
                 b0 b1 b2 a1 a2. 
                 For fixed-point funcions, fixed point format of filter 
                 coefficients is Q1.14 for 16x16 and 32x16, or Q1.30 for 32x32 
  coef_sosl[M*5] filter coefficients for the left channel (stereo filters only)
  coef_sosr[M*5] filter coefficients for the left channel (stereo filters only)
  coef_g[M]      scale factor for each section, Q15 (for fixed-point 
                 functions only)
  coef_gl[M]     scale factor for the left channel (stereo filters only)
  coef_gr[M]     scale factor for the right channel (stereo filters only)
  gain           total gain shift amount applied to output signal of the
                 last section, -48..15
  gainl          total gain shift amount  for the left channel (stereo filters 
                 only)
  gainr          total gain shift amount for the right channel (stereo filters 
                 only)

  x[N*S]         input samples, Q15, Q31 or floating point. Stereo samples 
                 go in interleaved order (left, right)
  Output:
  r[N*S]         output data, Q15, Q31 or floating point. Stereo samples go 
                 in interleaved order (left, right) 

  Restriction:
  x,r,s,coef_g,coef_sos should not overlap
  N   - must be a multiple of 2
  s[] - whenever supplied must be aligned on an 8-bytes boundary
-------------------------------------------------------------------------*/


/* Instance pointer validation number. */
#define MAGIC     0x915f4a88

/* Reserve memory for alignment. */
#define ALIGNED_SIZE( size, align ) \
      ( (size_t)(size) + (align) - 1 )

/* Align address on a specified boundary. */
#define ALIGNED_ADDR( addr, align ) \
      (void*)( ( (uintptr_t)(addr) + ( (align) - 1 ) ) & ~( (align) - 1 ) )

#define sz_i16 sizeof(int16_t)
#define sz_i32 sizeof(int32_t)

/* Filter instance structure. */
typedef struct tag_bqriir16x16_df1_t
{
  uint32_t        magic; // Instance pointer validation number
  int             M;     // Number of sections
  int16_t         gain;  // Total gain shift amount for the last biquad
  const int16_t * coef;  // Num/den coefs (Q14) and gain (Q15) for each biquad
  int16_t *       state; // 4 state elements per section, Q15

} bqriir16x16_df1_t, *bqriir16x16_df1_ptr_t;

/* Returns: size of memory in bytes to be allocated */
size_t bqriir16x16_df1_alloc( int M )
{
  if (M<=0) return 0;

  return ( ALIGNED_SIZE( sizeof(bqriir16x16_df1_t), 4 )
           + // 4 state elements for each of M DFI sections.
           ALIGNED_SIZE( 4*M*sz_i16, 4*sz_i16 )
           + // 6+2 coefficients for each of M sections
           ALIGNED_SIZE( 8*M*sz_i16, 4*sz_i16 ) );
} /* bqriir16x16_df1_alloc() */

/* Returns: handle to the object */
bqriir16x16_df1_handle_t bqriir16x16_df1_init( void * objmem,  int M, 
                                               const int16_t * coef_sos,
                                               const int16_t * coef_g,
                                               int16_t         gain )
{
  bqriir16x16_df1_ptr_t bqriir;

  int16_t * sectState;
  int16_t * sectCoef;
  void *    ptr;

  int m;

  ASSERT( objmem &&  coef_sos && coef_g );
  ASSERT( -48 <= gain && gain <= 15 );
  if (M <= 0) return NULL;

  //
  // Partition the memory block
  //

  ptr = objmem;

  bqriir    = (bqriir16x16_df1_ptr_t)ALIGNED_ADDR( ptr, 4 );
  ptr       = bqriir + 1;
  sectState = (int16_t *)ALIGNED_ADDR( ptr, 4*sz_i16 );
  ptr       = sectState + 4*M;
  sectCoef  = (int16_t *)ALIGNED_ADDR( ptr, 4*sz_i16 );
  ptr       = sectCoef + 8*M;

  ASSERT( (int8_t*)ptr - (int8_t*)objmem <= (int)bqriir16x16_df1_alloc(M ) );

  //
  // Copy filter coefficients for M sections, zero the state elements.
  //

  for ( m=0; m<M; m++ )
  {
    sectCoef[8*m+0] = coef_g[m];                        //   g, Q15
    sectCoef[8*m+1] = coef_g[m];
    sectCoef[8*m+2] = AE_NEG16S_scalar(coef_sos[5*m+3]);// -a1, Q14
    sectCoef[8*m+3] = AE_NEG16S_scalar(coef_sos[5*m+4]);// -a2, Q14
    sectCoef[8*m+4] = coef_sos[5*m+0];                  //  b0, Q14
    sectCoef[8*m+5] = coef_sos[5*m+1];                  //  b1, Q14
    sectCoef[8*m+6] = coef_sos[5*m+2];                  //  b2, Q14
    sectCoef[8*m+7] = 0;

    sectState[4*m+0] = 0;
    sectState[4*m+1] = 0;
    sectState[4*m+2] = 0;
    sectState[4*m+3] = 0;
  }

  //
  // Initialize the filter instance.
  //

  bqriir->magic = MAGIC;
  bqriir->M     = M;
  bqriir->gain  = gain;
  bqriir->coef  = sectCoef;
  bqriir->state = sectState;

  return (bqriir);

} /* bqriir16x16_df1_init() */

/* Update the delay line and compute filter output */
void bqriir16x16_df1( bqriir16x16_df1_handle_t _bqriir,
                      void    * restrict       s,
                      int16_t * restrict       r,
                const int16_t *                x, int N )
{
  bqriir16x16_df1_ptr_t bqriir = (bqriir16x16_df1_ptr_t)_bqriir;

  const ae_int16   * restrict X;
        ae_int16x4 * restrict R;
        ae_int16x4 * restrict St;
  const ae_int16x4 * restrict Cf;

  int16_t x0, x1;
  ae_int16x4 inx, y0, y1;
  ae_int16x4 Asxsr, Asx, Asr;
  ae_int16x4 Bsxsr, Bsx, Bsr;
  ae_int16x4 Ab0b1b2_0, A_0b0b1b2, A_00_a2a1,
             Bb0b1b2_0, B_00_a2a1;
  ae_int16x4 cf0, cf1, cf2, cf3, Ag, Bg;
  ae_int16x4 _0;
  ae_int32x2 ty0, ty1;
  ae_f32x2   A32, B32;
  ae_int64   acc0, acc1;
  int M, gain;
  int n, m;

  ASSERT( bqriir && bqriir->magic == MAGIC && r && x );
  NASSERT(N%2==0);
  if(N<=0) return;
  M = bqriir->M;

  St = (ae_int16x4 *)bqriir->state;
  Cf = (ae_int16x4 *)bqriir->coef;
  X = (const ae_int16 *)x;
  gain = bqriir->gain;
  _0 = AE_ZERO16();

  // Perform data block processing for each section, by 2 sections simulateously.
  // Use the output array r[N] for temporal storage of inter-section signal.
  for ( m=0; m<((M-1)>>1); m++ )
  {
    ae_int16x4 AgBg, Bb0_0b2b1, Bb1b0_0b2;
    //
    // Load 16-bit section coefficients.
    //
    AE_L16X4_IP(cf0, Cf, 4*sz_i16);
    AE_L16X4_IP(cf1, Cf, 4*sz_i16);
    AE_L16X4_IP(cf2, Cf, 4*sz_i16);
    AE_L16X4_IP(cf3, Cf, 4*sz_i16);
    Ab0b1b2_0 = cf1;
    A_0b0b1b2 = AE_SEL16_4321(cf1, cf1);
    A_00_a2a1 = AE_SEL16_5410(cf0, _0);
    cf3 = AE_SHORTSWAP(cf3);
    Bb0_0b2b1 = AE_SEL16_4321(cf3, cf3);
    Bb1b0_0b2 = AE_SEL16_5432(cf3, cf3);
    B_00_a2a1 = AE_SEL16_5410(cf2, _0);
    AgBg = AE_SEL16_7632(cf0, cf2);

    //
    // Load 16-bit section's state elements.
    //
    Asxsr = AE_L16X4_I(St, 0);
    Asx = AE_SEL16_7632(Asxsr, _0);
    A32 = AE_CVT32X2F16_10(Asxsr);
    A32 = AE_SRAI32(A32, 16);
    Bsxsr = AE_L16X4_I(St, 4*sz_i16);
    Bsx = AE_SEL16_7632(Bsxsr, _0);
    B32 = AE_CVT32X2F16_10(Bsxsr);
    B32 = AE_SRAI32(B32, 16);
    
    R = (ae_int16x4 *)r;

    //
    // Pass the block of input samples through 2 sections. n-th sample at the
    // output of a biquad section:
    //   r[n] = g*x[n]*b0 + g*x[n-1]*b1 + g*x[n-2]*b2 - r[n-1]*a1 - r[n-2]*a2
    //
    __Pragma("loop_count min=1");
    for ( n=0; n<(N>>1); n++ )
    {
      // Load input sample.
      x0 = *((const int16_t *)X++);
      x1 = *((const int16_t *)X++);
      inx = AE_MOVDA16X2(x1, x0);
      // inx <- g*x[n]
      // y0  <- g*dy0, dy0 - delayed output from previous section.
      // Q15 <- Q15*Q15 - 15 w/ rounding. No saturation is necessary.
      inx = AE_MULFP16X4RAS(inx, AgBg);
      Asx = AE_SEL16_7632(inx, Asx);

      // Section 0 / sample 0
      // y[n] = g*x[n]*b0 + g*x[n-1]*b1 + g*x[n-2]*b2
      // y[n] = y[n] - r[n-1]*a1 - r[n-2]*a2
      // Q29 <- Q15*Q14
      acc0 = AE_MULZAAAAQ16(Asx, A_0b0b1b2);
      AE_MULAAD32X16_H2_L3(acc0, A32, A_00_a2a1);
      AE_PKSR32(A32, acc0, 2);

      // pass computed samples from the 1st section
      // to the input of the 2nd section.
      y0 = AE_SAT16X4(A32, A32);
      y0 = AE_MULFP16X4RAS(y0, AgBg);
      Bsx = AE_SEL16_5432(y0, Bsx);

      // Section 0 / sample 1
      acc0 = AE_MULZAAAAQ16(Asx, Ab0b1b2_0);
      AE_MULAAD32X16_H2_L3(acc0, A32, A_00_a2a1);
      AE_PKSR32(A32, acc0, 2);

      // Section 1 / sample 0
      acc1 = AE_MULZAAAAQ16(Bsx, Bb0_0b2b1);
      AE_MULAAD32X16_H2_L3(acc1, B32, B_00_a2a1);
      AE_PKSR32(B32, acc1, 2);
      // Save output y[2*n]
      y1 = AE_SAT16X4(B32, B32);
      AE_S16_0_IP(y1, castxcc(ae_int16, R), sz_i16);

      // Section 1 / sample 1
      acc1 = AE_MULZAAAAQ16(Bsx, Bb1b0_0b2);
      AE_MULAAD32X16_H2_L3(acc1, B32, B_00_a2a1);
      AE_PKSR32(B32, acc1, 2);
      // Save output y[2*n+1]
      y1 = AE_SAT16X4(B32, B32);
      AE_S16_0_IP(y1, castxcc(ae_int16, R), sz_i16);
    }

    //
    // Save section's state elements.
    //
    Asr = AE_SAT16X4(A32, A32);
    Asxsr = AE_SEL16_7632(Asx, Asr);
    AE_S16X4_IP(Asxsr, St, 4*sz_i16);
    Bsr = AE_SAT16X4(B32, B32);
    Bsxsr = AE_SEL16_7632(Bsx, Bsr);
    AE_S16X4_IP(Bsxsr, St, 4*sz_i16);

    //
    // Next sections are fed with output samples of the preceding biquad.
    //
    X = (const ae_int16 *)r;
  }
  //------------------------------------------------------------------------
  // Pass signal through the last biquads (1 or 2) and apply the total gain.
  //------------------------------------------------------------------------
  if (M&1)
  {
    // Process 1 last biquad

    //
    // Load 16-bit section coefficients.
    //
    AE_L16X4_IP(cf0, Cf, 4*sz_i16);
    AE_L16X4_IP(cf1, Cf, 4*sz_i16);
    Ag = AE_SEL16_7632(cf0, cf0);
    Ab0b1b2_0 = cf1;
    A_0b0b1b2 = AE_SEL16_4321(cf1, cf1);
    A_00_a2a1 = AE_SEL16_5410(cf0, _0);

    //
    // Load 16-bit section's state elements.
    //
    Asxsr = AE_L16X4_I(St, 0);
    Asx = AE_SEL16_7632(Asxsr, _0);
    A32 = AE_CVT32X2F16_10(Asxsr);
    A32 = AE_SRAI32(A32, 16);
    
    R = (ae_int16x4 *)r;

    // Process by 2 samples per iteration
    __Pragma("loop_count min=1");
    for ( n=0; n<(N>>1); n++ )
    {
      // Load 2 input samples.
      x0 = *((const int16_t *)X++);
      x1 = *((const int16_t *)X++);
      inx = AE_MOVDA16X2(x1, x0);
      // inx <- g*x[n+1] g*x[n]
      // Q15 <- Q15*Q15 - 15 w/ rounding. No saturation is necessary.
      inx = AE_MULFP16X4RAS(inx, Ag);

      Asx = AE_SEL16_5432(inx, Asx);
      // y[n] = g*x[n]*b0 + g*x[n-1]*b1 + g*x[n-2]*b2
      // y[n] = y[n] - r[n-1]*a1 - r[n-2]*a2
      // Q29 <- Q15*Q14
      acc0 = AE_MULZAAAAQ16(Asx, A_0b0b1b2);
      AE_MULAAD32X16_H2_L3(acc0, A32, A_00_a2a1);
      // Update the section's state elements.
      // Q15 <- Q29 - 14 w/ rounding
      AE_PKSR32(A32, acc0, 2);
      // y[n+1] = g*x[n+1]*b0 + g*x[n]*b1 + g*x[n-1]*b2
      // y[n+1] = y[n+1] - r[n]*a1 - r[n-1]*a2
      // Q29 <- Q15*Q14
      acc1 = AE_MULZAAAAQ16(Asx, Ab0b1b2_0);
      AE_MULAAD32X16_H2_L3(acc1, A32, A_00_a2a1);
      // Update the section's state elements.
      // Q15 <- Q29 - 14 w/ rounding
      AE_PKSR32(A32, acc1, 2);
      
      // Apply the total gain shift and format outputs y[n], y[n+1]
      // Q(15+gain) <- Q(29 - 14 + gain) w/ rounding and saturation
      ty0 = AE_MOVINT32X2_FROMF64(acc0);
      ty1 = AE_MOVINT32X2_FROMF64(acc1);
      ty0 = AE_SRAA32RS(ty0, 14-gain);
      ty1 = AE_SRAA32RS(ty1, 14-gain);
      y0 = AE_SAT16X4(ty0, ty0);
      y1 = AE_SAT16X4(ty1, ty1);
      AE_S16_0_IP(y0, castxcc(ae_int16, R), sz_i16);
      AE_S16_0_IP(y1, castxcc(ae_int16, R), sz_i16);
    }
    
    //
    // Save section's state elements.
    //
    Asr = AE_SAT16X4(A32, A32);
    Asxsr = AE_SEL16_7632(Asx, Asr);
    AE_S16X4_IP(Asxsr, St, 4*sz_i16);
  }
  else
  {
    // Process 2 last biquads simultaneously

    //
    // Load 16-bit section coefficients.
    //
    AE_L16X4_IP(cf0, Cf, 4*sz_i16);
    AE_L16X4_IP(cf1, Cf, 4*sz_i16);
    Ag = AE_SEL16_7632(cf0, cf0);
    Ab0b1b2_0 = cf1;
    A_00_a2a1  = AE_SEL16_5410(cf0, _0);
    AE_L16X4_IP(cf0, Cf, 4*sz_i16);
    AE_L16X4_IP(cf1, Cf, 4*sz_i16);
    Bg = AE_SEL16_7632(cf0, cf0);
    Bb0b1b2_0 = cf1;
    B_00_a2a1  = AE_SEL16_5410(cf0, _0);

    //
    // Load 16-bit section's state elements.
    //
    
    Asxsr = AE_L16X4_I(St, 0);
    Asx = AE_SEL16_7632(Asxsr, _0);
    A32 = AE_CVT32X2F16_10(Asxsr);
    A32 = AE_SRAI32(A32, 16);
    Bsxsr = AE_L16X4_I(St, 4*sz_i16);
    Bsx = AE_SEL16_7632(Bsxsr, _0);
    B32 = AE_CVT32X2F16_10(Bsxsr);
    B32 = AE_SRAI32(B32, 16);
    
    R = (ae_int16x4 *)r;

    __Pragma("loop_count min=2, factor=2");
    for ( n=0; n<N; n++ )
    {
      // Load input sample.
      AE_L16_IP(inx,X,sz_i16);
      // inx <- g*x[n]
      // y0  <- g*dy0, dy0 - delayed output from previous section.
      // Q15 <- Q15*Q15 - 15 w/ rounding. No saturation is necessary.
      inx = AE_MULFP16X4RAS(inx, Ag);
      Asx = AE_SEL16_4321(inx, Asx);
      y0 = AE_SAT16X4(A32, A32);
      y0 = AE_MULFP16X4RAS(y0, Bg);
      Bsx = AE_SEL16_4321(y0, Bsx);

      // y[n] = g*x[n]*b0 + g*x[n-1]*b1 + g*x[n-2]*b2
      // y[n] = y[n] - r[n-1]*a1 - r[n-2]*a2
      // Q29 <- Q15*Q14
      acc0 = AE_MULZAAAAQ16(Asx, Ab0b1b2_0);
      AE_MULAAD32X16_H2_L3(acc0, A32, A_00_a2a1);
      acc1 = AE_MULZAAAAQ16(Bsx, Bb0b1b2_0);
      AE_MULAAD32X16_H2_L3(acc1, B32, B_00_a2a1);
      // Update the sections' state elements.
      // Q15 <- Q29 + 2 - 16 w/ rounding and saturation
      AE_PKSR32(A32, acc0, 2);
      AE_PKSR32(B32, acc1, 2);
      
      // Apply the total gain shift and format output y[n]
      // Q(15+gain) <- Q(29 - 14 + gain) w/ rounding and saturation
      ty0 = AE_MOVINT32X2_FROMF64(acc1);
      ty0 = AE_SRAA32RS(ty0, 14-gain);
      y1 = AE_SAT16X4(ty0, ty0);
      AE_S16_0_IP(y1, castxcc(ae_int16, R), sz_i16);
    }
    
    //
    // Save sections' state elements.
    //
    Asr = AE_SAT16X4(A32, A32);
    Asxsr = AE_SEL16_7632(Asx, Asr);
    AE_S16X4_IP(Asxsr, St, 4*sz_i16);
    Bsr = AE_SAT16X4(B32, B32);
    Bsxsr = AE_SEL16_7632(Bsx, Bsr);
    AE_S16X4_IP(Bsxsr, St, 4*sz_i16);
  }

} /* bqriir16x16_df1() */
