/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

// #define USE_RGB565 0
#define APP_PS_ULC_X 0
#define APP_PS_ULC_Y 0
#define DEMO_PANEL 10
// #define CONFIG_DEMO_PANEL_RK043FN02H 0
#define CONFIG_DEMO_PANEL_RK043FN66HS 1
#define CONFIG_FLASH_BASE_ADDRESS 0x70000000
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
