# Add set(CONFIG_USE_middleware_azure_rtos_gx_lib true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/gx_source.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1555xrgb_canvas_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1555xrgb_jpeg_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1555xrgb_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1555xrgb_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1555xrgb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1555xrgb_png_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1555xrgb_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_mouse_capture.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_mouse_restore.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_pixelmap_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_pixelmap_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_rotated_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_row_pitch_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_16bpp_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_glyph_1bpp_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_mouse_capture.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_mouse_restore.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_row_pitch_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_1bpp_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_canvas_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_jpeg_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_mouse_capture.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_mouse_restore.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_pixelmap_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_png_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_rotated_canvas_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_rotated_jpeg_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_rotated_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_rotated_png_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_rotated_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_24xrgb_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32argb_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32argb_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32argb_pixelmap_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32argb_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32argb_rotated_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32argb_rotated_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32argb_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_glyph_1bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_glyph_1bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_pixelmap_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_rotated_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_row_pitch_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_32bpp_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_332rgb_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_332rgb_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_332rgb_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_332rgb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_332rgb_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4444argb_canvas_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4444argb_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4444argb_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4444argb_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4444argb_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4444argb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4444argb_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_glyph_1bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_glyph_4bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_grayscale_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_mouse_capture.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_mouse_restore.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_row_pitch_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_4bpp_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_canvas_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_glyph_1bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_jpeg_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_png_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_rotated_canvas_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_rotated_glyph_1bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_rotated_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_rotated_jpeg_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_rotated_pixel_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_rotated_png_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_rotated_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_565rgb_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bit_palette_native_color_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bit_palette_rotated_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bit_palette_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_glyph_1bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_glyph_3bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_glyph_4bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_mouse_capture.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_mouse_restore.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_pixelmap_blend.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_block_move.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_canvas_copy.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_glyph_1bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_glyph_3bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_glyph_4bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_horizontal_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_horizontal_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_horizontal_pixelmap_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_pixel_write.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_pixelmap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_rotated_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_row_pitch_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_simple_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_vertical_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_8bpp_vertical_pattern_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_arc_clipping_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_arc_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_circle_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_ellipse_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_filled_circle_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_fixed_point_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_wide_arc_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_wide_circle_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_wide_ellipse_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_aliased_wide_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_alphamap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_arc_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_arc_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_circle_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_circle_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_drawing_complete.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_drawing_initiate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_ellipse_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_ellipse_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_filled_circle_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_glyph_4bpp_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_glyph_8bpp_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_mouse_cursor_define.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_mouse_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_mouse_enable.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_mouse_position_set.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_pie_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_polygon_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_polygon_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_alphamap_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_arc_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_circle_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_ellipse_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_glyph_4bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_glyph_8bit_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_pie_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_polygon_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_rotated_wide_line_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_simple_pie_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_simple_wide_line_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_wide_arc_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_wide_circle_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_wide_ellipse_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_wide_line_fill.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_generic_wide_line_points_calculate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_horizontal_line_alpha_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_monochrome_setup.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_simple_line_alpha_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_display_driver_vertical_line_alpha_draw.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_system_font_4bpp.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_system_font_8bpp.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_system_font_mono.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_system_initialize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_1555xrgb_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_1555xrgb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_16bpp_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_1bpp_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_1bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_32argb_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_32argb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_332rgb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_4444argb_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_4444argb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_4bpp_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_4bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_565rgb_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_8bpp_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_8bpp_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_alphamap_create.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_bidi_arabic_shaping.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_bidi_bracket_pair_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_bidi_character_type_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_bidi_mirroring_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_bidi_paragraph_reorder.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_bidi_resolved_text_info_delete.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_canvas_to_bmp.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_circle_point_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_easing_function_calculate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_gradient_create.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_gradient_delete.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_ltoa.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_math_acos.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_math_asin.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_math_cos.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_math_sin.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_math_sqrt.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_pixelmap_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_pixelmap_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_pixelmap_simple_rotate.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_center.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_center_find.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_combine.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_compare.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_define.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_inside_detect.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_overlap_detect.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_point_detect.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_resize.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_rectangle_shift.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_string_compare.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_string_length_check.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_string_to_alphamap.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_thai_glyph_shaping.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_unicode_to_utf8.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_utf8_string_backward_character_length_get.c
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/src/gx_utility_utf8_string_character_get.c
)

target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
  ${CMAKE_CURRENT_LIST_DIR}/threadx/common/inc
  ${CMAKE_CURRENT_LIST_DIR}/guix/common/inc
)

if(CONFIG_TOOLCHAIN STREQUAL iar AND CONFIG_CORE STREQUAL cm7f)
target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
  ${CMAKE_CURRENT_LIST_DIR}/threadx/ports/cortex_m7/iar/inc
  ${CMAKE_CURRENT_LIST_DIR}/guix/ports/cortex_m7/iar/inc
)
endif()

if(CONFIG_TOOLCHAIN STREQUAL mdk AND CONFIG_CORE STREQUAL cm7f)
target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
  ${CMAKE_CURRENT_LIST_DIR}/threadx/ports/cortex_m7/ac6/inc
  ${CMAKE_CURRENT_LIST_DIR}/guix/ports/cortex_m7/ac6/inc
)
endif()

if(CONFIG_TOOLCHAIN STREQUAL mcux AND CONFIG_CORE STREQUAL cm7f)
target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
  ${CMAKE_CURRENT_LIST_DIR}/threadx/ports/cortex_m7/gnu/inc
  ${CMAKE_CURRENT_LIST_DIR}/guix/ports/cortex_m7/gnu/inc
)
endif()

if(CONFIG_USE_COMPONENT_CONFIGURATION)
  message("===>Import configuration from ${CMAKE_CURRENT_LIST_FILE}")

  target_compile_definitions(${MCUX_SDK_PROJECT_NAME} PUBLIC
    -DTX_INCLUDE_USER_DEFINE_FILE
    -DGX_INCLUDE_USER_DEFINE_FILE
  )

endif()

