# Add set(CONFIG_USE_middleware_aws_iot_ota_unused true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
  ${CMAKE_CURRENT_LIST_DIR}/source/portable/os/ota_os_posix.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Free_FreeRTOS/Free_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Malloc_FreeRTOS/Malloc_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_ActivateNewImage/OTA_ActivateNewImage_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_CBOR_Decode_GetStreamResponseMessage/OTA_CBOR_Decode_GetStreamResponseMessage_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_CBOR_Encode_GetStreamRequestMessage/OTA_CBOR_Encode_GetStreamRequestMessage_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_CheckForUpdate/OTA_CheckForUpdate_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_Err_strerror/OTA_Err_strerror_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_EventProcess/OTA_EventProcess_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_EventProcessingTask/OTA_EventProcessingTask_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_GetImageState/OTA_GetImageState_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_GetState/OTA_GetState_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_GetStatistics/OTA_GetStatistics_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_HTTP_strerror/OTA_HTTP_strerror_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_Init/OTA_Init_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_JobParse_strerror/OTA_JobParse_strerror_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_MQTT_strerror/OTA_MQTT_strerror_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_OsStatus_strerror/OTA_OsStatus_strerror_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_PalStatus_strerror/OTA_PalStatus_strerror_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_Resume/OTA_Resume_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_SetImageState/OTA_SetImageState_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_Shutdown/OTA_Shutdown_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_SignalEvent/OTA_SignalEvent_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OTA_Suspend/OTA_Suspend_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OtaDeinitEvent_FreeRTOS/OtaDeinitEvent_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OtaDeleteTimer_FreeRTOS/OtaDeleteTimer_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OtaInitEvent_FreeRTOS/OtaInitEvent_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OtaReceiveEvent_FreeRTOS/OtaReceiveEvent_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OtaSendEvent_FreeRTOS/OtaSendEvent_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OtaStartTimer_FreeRTOS/OtaStartTimer_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/OtaStopTimer_FreeRTOS/OtaStopTimer_FreeRTOS_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_OtaDeinitEvent/Posix_OtaDeinitEvent_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_OtaDeleteTimer/Posix_OtaDeleteTimer_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_OtaInitEvent/Posix_OtaInitEvent_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_OtaReceiveEvent/Posix_OtaReceiveEvent_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_OtaSendEvent/Posix_OtaSendEvent_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_OtaStartTimer/Posix_OtaStartTimer_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_OtaStopTimer/Posix_OtaStopTimer_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_RequestTimerCallback/requestTimerCallback_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/Posix_selfTestTimerCallback/selfTestTimerCallback_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/STDC_FREE/STDC_Free_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/STDC_Malloc/STDC_Malloc_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/agentShutdownCleanup/agentShutdownCleanup_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/base64Decode/base64Decode_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/buildStatusMessageReceiving/buildStatusMessageReceiving_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/checkDataType/checkDataType_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/cleanupControl_Mqtt/cleanupControl_Mqtt_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/cleanupData_Http/cleanupData_Http_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/cleanupData_Mqtt/cleanupData_Mqtt_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/closeFileHandler/closeFileHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/dataHandlerCleanup/dataHandlerCleanup_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/decodeAndStoreDataBlock/decodeAndStoreDataBlock_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/decodeAndStoreKey/decodeAndStoreKey_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/decodeBase64IndexBuffer/decodeBase64IndexBuffer_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/decodeFileBlock_Http/decodeFileBlock_Http_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/decodeFileBlock_Mqtt/decodeFileBlock_Mqtt_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/executeHandler/executeHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/extractAndStoreArray/extractAndStoreArray_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/extractParameter/extractParameter_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/freeFileContextMem/freeFileContextMem_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/getFileContextFromJob/getFileContextFromJob_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/handleCustomJob/handleCustomJob_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/handleJobParsingError/handleJobParsingError_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/handleSelfTestJobDoc/handleSelfTestJobDoc_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/handleUnexpectedEvents/handleUnexpectedEvents_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/inSelfTestHandler/inSelfTestHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/ingestDataBlock/ingestDataBlock_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/ingestDataBlockCleanup/ingestDataBlockCleanup_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/initDocModel/initDocModel_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/initFileHandler/initFileHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/initFileTransfer_Http/initFileTransfer_Http_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/initFileTransfer_Mqtt/initFileTransfer_Mqtt_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/initializeAppBuffers/initializeAppBuffers_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/initializeLocalBuffers/initializeLocalBuffers_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/jobNotificationHandler/jobNotificationHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/otaClose/otaClose_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/otaTimerCallback/otaTimerCallback_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/parseJSONbyModel/parseJSONbyModel_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/parseJobDoc/parseJobDoc_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/platformInSelftest/platformInSelftest_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/preprocessBase64Index/preprocessBase64Index_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/processDataBlock/processDataBlock_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/processDataHandler/processDataHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/processJobHandler/processJobHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/processNullFileContext/processNullFileContext_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/processValidFileContext/processValidFileContext_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/prvBuildStatusMessageFinish/prvBuildStatusMessageFinish_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/prvBuildStatusMessageSelfTest/prvBuildStatusMessageSelfTest_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/publishStatusMessage/publishStatusMessage_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/receiveAndProcessOtaEvent/receiveAndProcessOtaEvent_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/requestDataBlock_Http/requestDataBlock_Http_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/requestDataHandler/requestDataHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/requestFileBlock_Mqtt/requestFileBlock_Mqtt_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/requestJobHandler/requestJobHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/requestJob_Mqtt/requestJob_Mqtt_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/requestTimerCallback/requestTimerCallback_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/resetEventQueue/resetEventQueue_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/resumeHandler/resumeHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/searchTransition/searchTransition_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/selfTestTimerCallback/selfTestTimerCallback_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/setControlInterface/setControlInterface_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/setDataInterface/setDataInterface_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/setImageStateWithReason/setImageStateWithReason_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/shutdownHandler/shutdownHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/startHandler/startHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/stringBuilder/stringBuilder_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/stringBuilderUInt32Decimal/stringBuilderUInt32Decimal_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/stringBuilderUInt32Hex/stringBuilderUInt32Hex_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/subscribeToJobNotificationTopics/subscribeToJobNotificationTopics_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/suspendHandler/suspendHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/unsubscribeFromDataStream/unsubscribeFromDataStream_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/unsubscribeFromJobNotificationTopic/unsubscribeFromJobNotificationTopic_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/updateBase64DecodingBuffer/updateBase64DecodingBuffer_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/updateJobStatusFromImageState/updateJobStatusFromImageState_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/updateJobStatus_Mqtt/updateJobStatus_Mqtt_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/userAbortHandler/userAbortHandler_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/validateAndStartJob/validateAndStartJob_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/validateDataBlock/validateDataBlock_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/validateJSON/validateJSON_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/validateUpdateVersion/validateUpdateVersion_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/verifyActiveJobStatus/verifyActiveJobStatus_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/proofs/verifyRequiredParamsExtracted/verifyRequiredParamsExtracted_harness.c
  ${CMAKE_CURRENT_LIST_DIR}/test/cbmc/source/stubs.c
  ${CMAKE_CURRENT_LIST_DIR}/test/unit-test/ota_base64_utest.c
  ${CMAKE_CURRENT_LIST_DIR}/test/unit-test/ota_cbor_utest.c
  ${CMAKE_CURRENT_LIST_DIR}/test/unit-test/ota_os_posix_utest.c
  ${CMAKE_CURRENT_LIST_DIR}/test/unit-test/ota_utest.c
  ${CMAKE_CURRENT_LIST_DIR}/test/unit-test/utest_helpers.c
)

