if(NOT MIDDLEWARE_ARM_PELION_MIMXRT1062_INCLUDED)
    
    set(MIDDLEWARE_ARM_PELION_MIMXRT1062_INCLUDED true CACHE BOOL "middleware_arm_pelion component is included.")

    target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/pdmc-port/pdmc-bsp/common/FlashIAP.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/RTOS/pal_rtos.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/DRBG/pal_drbg.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/ROT/pal_rot.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/Networking/pal_network.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/Entropy/pal_entropy.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/Crypto/pal_Crypto.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/Time/pal_time.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/TLS/pal_TLS.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/Storage/Flash/pal_internalFlash.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/pal_init.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Storage/Flash/pal_plat_internalFlash_FlashOverFilesystem.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/DRBG/SOTP/pal_plat_drbg_sotp.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/DRBG/pal_plat_drbg_noise.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/DRBG/PSA/pal_plat_drbg_psa.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/ROT/External/pal_plat_rot_hw.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/ROT/SOTP/pal_plat_rot_sotp.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/ROT/PSA/pal_plat_rot_psa.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Storage/FileSystem/pal_plat_fileSystem_FsOverRam.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Entropy/SOTP/pal_plat_entropy_sotp.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Entropy/PSA/pal_plat_entropy_psa.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/SST/kvstore_impl/pal_plat_sst_impl.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Time/pal_plat_time.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Lib_Specific/mbedTLS/DRBG/pal_plat_drbg_w_entropy_sources.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/OS_Specific/NXP/RTOS/pal_plat_rtos.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/OS_Specific/NXP/Networking/LWIP/pal_plat_network.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Lib_Specific/mbedTLS/Crypto/pal_plat_Crypto.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Lib_Specific/mbedTLS/TLS/pal_plat_TLS.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-trace/source/mbed_trace.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/crypto-service/source/cs_der_certs.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/crypto-service/source/cs_der_keys_and_csrs.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/crypto-service/source/cs_hash.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/crypto-service/source/cs_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/sotp/sotp.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/sotp/sotp_log.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/sotp/sotp_no_sotp.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/sotp/sotp_shared_lock.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/esfs_file_name.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/esfs_performance.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/psa-driver/source/psa_driver_ps.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/psa-driver/source/psa_driver_dispatcher.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/psa-driver/source/psa_driver_common.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/psa-driver/source/psa_driver_crypto.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/source/key_slot_allocator.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/source/storage_common.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/source/storage_non_psa.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/source/storage_pal_sst.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/source/storage_pelion_sst.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/source/storage_psa.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/key-config-manager/source/key_config_manager.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/factory-configurator-client/source/factory_configurator_client.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/factory-configurator-client/source/fcc_dev_flow.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/factory-configurator-client/source/fcc_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/factory-configurator-client/source/fcc_verification.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/source/fcc_bundle_certificate_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/source/fcc_bundle_common_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/source/fcc_bundle_config_params_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/source/fcc_bundle_csr_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/source/fcc_bundle_handler.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/source/fcc_bundle_key_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-output-info-handler/source/fcc_output_info_handler.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/ftcd-comm-base/source/ftcd_comm_base.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/ftcd-comm-socket/source/ftcd_comm_socket.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-trace-helper/source/mbed-trace-helper.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/utils/source/common_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/utils/source/fcc_stats.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/utils/source/fcc_time_profiling.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/utils/source/general_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/utils/source/pv_error_handling.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/source/CertificateEnrollmentClient.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/source/CertificateEnrollmentClientCommon.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/source/CertificateRenewalData.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/source/ce_safe_renewal_internal.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/source/ce_tlv.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/source/certificate_enrollment.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/helpers/FlashIAPBlockDevice.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/helpers/BufferedBlockDevice.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/helpers/pal_plat_rot.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/helpers/DeviceKey.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/helpers/FlashSimBlockDevice.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/helpers/SlicingBlockDevice.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/tdbstore/TDBStore.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/global_api/kvstore_global_api.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/kv_map/KVMap.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/conf/kv_config.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/securestore/SecureStore.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src/cborencoder.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src/cborencoder_close_container_checked.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src/cborerrorstrings.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src/cborparser.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src/cborparser_dup_string.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src/cborpretty.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src/cborvalidation.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/helpers/source/sda_data_token.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/mem/source/sda_malloc.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/sda-bundle-parser/source/sda_bundle_parser.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/sda-cose/source/sda_cose.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/secure-device-access/source/sda_error_translation.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/secure-device-access/source/sda_nonce_mgr.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/secure-device-access/source/sda_trust_anchor.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/secure-device-access/source/sda_verification.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/secure-device-access/source/secure_device_access.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/Cose.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/Encrypt.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/Encrypt0.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/MacMessage.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/MacMessage0.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/Recipient.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/Sign.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/Sign0.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/SignerInfo.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/bcrypt.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/cbor.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/mbedtls.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/source/mbedtls_tiny_cbor.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/ns-hal-pal/arm_hal_interrupt.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/ns-hal-pal/arm_hal_random.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/ns-hal-pal/arm_hal_timer.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/ns-hal-pal/ns_event_loop.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/ns-hal-pal/ns_hal_init.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/nanostack-libservice/source/libBits/common_functions.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/nanostack-libservice/source/libList/ns_list.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/nanostack-libservice/source/libip6string/ip6tos.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-randlib/source/randLIB.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop/source/ns_timeout.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop/source/ns_timer.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-coap/source/sn_coap_builder.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-coap/source/sn_coap_header_check.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-coap/source/sn_coap_parser.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-classic/source/m2mconnectionhandler.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-classic/source/m2mconnectionhandlerpimpl.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-classic/source/m2mtimer.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-classic/source/m2mtimerpimpl.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_nsdl.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-mbed-tls/source/m2mconnectionsecuritypimpl.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mbase.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mblockmessage.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mcallbackstorage.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mendpoint.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mdevice.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mfirmware.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2minterfacefactory.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2minterfaceimpl.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mnotificationhandler.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mnsdlinterface.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mobject.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mobjectinstance.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mreporthandler.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mresource.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mresourcebase.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mresourceinstance.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mserver.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2msecurity.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mstring.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mstringbufferbase.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mtlvdeserializer.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/m2mtlvserializer.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/nsdlaccesshelper.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/uriqueryparser.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/source/atomic-queue.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/source/atomic.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/source/atomic-cm3.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/source/critical-posix.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/source/critical-pal.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/source/critical.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/source/arm_uc_crypto_mbedtls.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/source/arm_uc_crypto_pal.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/source/arm_uc_error.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/source/arm_uc_scheduler.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/source/arm_uc_hw_plat.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/source/arm_uc_test_rot.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/source/arm_uc_utilities.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/control-center/source/arm_uc_certificate_kcm_api.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/control-center/source/arm_uc_certificate.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/control-center/source/arm_uc_certificate_raw_api.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/control-center/source/arm_uc_control_center.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/control-center/source/arm_uc_pre_shared_key.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/device-identity/source/arm_uc_device_identity.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/device-identity/source/arm_uc_device_identity_kcm.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/device-identity/source/arm_uc_device_identity_nvstore.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/device-identity/source/arm_uc_device_identity_raw.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/firmware-manager/source/arm_uc_firmware_manager.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/DeviceMetadataResource.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/FirmwareUpdateResource.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/device_metadata.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/firmware_update.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/lwm2m-control.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/lwm2m-monitor.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/lwm2m-source.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/update-lwm2m-mbed-apis.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source/update_lwm2m_monitor.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmCommon.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmCryptoUtils.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmDerManifestAccessors.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmDerManifestParser.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmGetLatestTimestamp.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmFetchFirmwareInfo.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmInit.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmInsertManifest.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/manifest-manager-api.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source/arm_uc_mmStateSelector.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/metadata-header/source/arm_uc_buffer_utilities.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/metadata-header/source/arm_uc_metadata_header_v2.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/metadata-header/source/arm_uc_crypto_hmac_mbedtls.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/paal/source/arm_uc_paal_update.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-blockdevice/source/arm_uc_pal_blockdevice.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-blockdevice/source/arm_uc_pal_blockdevice_implementation.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-blockdevice/source/arm_uc_pal_blockdevice_mbed.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap-mcuboot/source/arm_uc_pal_flashiap_flash.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap-mcuboot/source/arm_uc_pal_flashiap_mcuboot_implementation.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap-mcuboot/source/arm_uc_pal_flashiap_mcuboot.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap/source/arm_uc_pal_flashiap.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap/source/arm_uc_pal_flashiap_implementation.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap/source/arm_uc_pal_flashiap_mbed.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/source-manager/source/arm_uc_source_manager.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/source/update_client_hub.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/source/update_client_hub_error_handler.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/source/update_client_hub_event_handlers.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/source/update_client_hub_state_machine.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/CloudClientStorage.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/EstClient.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/ConnectorClient.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/CertificateParser.c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/MbedCloudClient.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/ServiceClient.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/SimpleM2MResource.cpp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/UpdateClient.cpp
    )


    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/pdmc-port/pdmc-bsp/common
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/certificate-enrollment-client/certificate-enrollment-client
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/crypto-service/crypto-service
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/crypto-service/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/factory-configurator-client/factory-configurator-client
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/factory-configurator-client/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/fcc-bundle-handler
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/fcc-output-info-handler/fcc-output-info-handler
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/ftcd-comm-base/ftcd-comm-base
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/ftcd-comm-socket/ftcd-comm-socket
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/key-config-manager/key-config-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/logger/logger
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source/sotp
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/mbed-trace-helper/mbed-trace-helper
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/psa-driver/psa-driver
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/storage
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/storage/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/utils/utils
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/conf
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/helpers
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/kv_map
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/global_api
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/tdbstore
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/kvstore/securestore
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-c/nsdl-c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-c/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-classic/mbed-client-classic
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-mbed-tls/mbed-client-mbedtls
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Configs/mbedTLS
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Configs/pal_config/FreeRTOS
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Configs/pal_config/NXP
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Services-API
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source/Port/Platform-API
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-randlib/mbed-client-randlib
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-randlib/mbed-client-randlib/platform
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-cloud-client
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-coap/mbed-coap
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-coap/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-trace/mbed-trace
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/nanostack-libservice/mbed-client-libservice
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/nanostack-libservice/mbed-client-libservice/platform
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/ns-hal-pal
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop/nanostack-event-loop
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop/nanostack-event-loop/platform
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/logger/logger
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/helpers/helpers
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/mem/mem
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/sda-bundle-parser/sda-bundle-parser
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/secure-device-access/secure-device-access
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/secure-device-access/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/sda-cose/sda-cose
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/cose-c/cose-c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/tinycbor/src
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/delta-tool-internal/include
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/atomic-queue
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common/update-client-common
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/control-center/update-client-control-center
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/device-identity/pal4life-device-identity
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/firmware-manager/update-client-firmware-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/update-client-lwm2m
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/update-client-manifest-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/metadata-header/update-client-metadata-header
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/monitor/update-client-monitor
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/paal/update-client-paal
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-blockdevice/update-client-pal-blockdevice
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap/update-client-pal-flashiap
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/source-manager/update-client-source-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/source/update-client-source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/source-http/update-client-source-http
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/update-client-hub
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/factory-configurator-client/key-config-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-c
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-classic
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/mbed-client-mbed-tls
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-pal/Source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-client-randlib
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-coap
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/mbed-trace
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/nanostack-libservice
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/sal-stack-nanostack-eventloop
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/secure-device-access-client/platform/platform
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/atomic-queue
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/common
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/control-center
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/device-identity
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/firmware-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/manifest-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/metadata-header
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/monitor
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/paal
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-blockdevice
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/pal-flashiap-mcuboot
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/source-manager
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/source
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub/modules/source-http
        ${CMAKE_CURRENT_LIST_DIR}/mbed-cloud-client/update-client-hub
    )


    include(middleware_lwip_MIMXRT1062)

    include(middleware_mbedtls_MIMXRT1062)

    include(middleware_freertos-kernel_heap_3_MIMXRT1062)

endif()
