/*
 *  Copyright 2023 - 2024 NXP
 *  All rights reserved.
 *
 *  SPDX-License-Identifier: BSD-3-Clause
 */

#include "edgefast_bluetooth_config_Gen.h"
#include "edgefast_bluetooth_audio_config_Gen.h"
#include "edgefast_bluetooth_debug_config_Gen.h"
#include "edgefast_bluetooth_extension_config_Gen.h"

/* Controller config
 * Supported controller list,
 * WIFI_IW416_BOARD_MURATA_1XK_M2
 * WIFI_88W8987_BOARD_MURATA_1ZM_M2
 * WIFI_IW612_BOARD_MURATA_2EL_M2
 *
 * If Embedded Artists Type 1XK(EAR00385 M2 only) used, define macro WIFI_IW416_BOARD_MURATA_1XK_M2 in following.
 * If Embedded Artists Type 1ZM(EAR00364 M2 only) used, define macro WIFI_88W8987_BOARD_MURATA_1ZM_M2 in following.
 * If Murata Type 2EL module(Rev-A1 M2 only) used , define macro WIFI_IW612_BOARD_MURATA_2EL_M2 in following.
 */

/* @TEST_ANCHOR */
#define WIFI_IW612_BOARD_MURATA_2EL_M2
/* @END_TEST_ANCHOR */
/*#define WIFI_IW416_BOARD_MURATA_1XK_M2*/
/*#define WIFI_88W8987_BOARD_MURATA_1ZM_M2*/
/*#define WIFI_IW612_BOARD_MURATA_2EL_M2*/

#if (defined(WIFI_IW416_BOARD_MURATA_1XK_M2) || defined(WIFI_88W8987_BOARD_MURATA_1ZM_M2) || \
     defined(WIFI_IW612_BOARD_MURATA_2EL_M2))
#include "wifi_bt_module_config.h"
#include "wifi_config.h"
#else
#error The transceiver module is unsupported
#endif

/* To enable the BT IND Reset. */
/* If ID Reset is enabled, use BT UART to download controller firmware. */
#if (defined(CONFIG_BT_IND_RESET) && (CONFIG_BT_IND_RESET > 0U))
#define CONFIG_BT_IND_DNLD       1
#define BOARD_BT_IND_RESET_OOB_PORT (1U)
#define BOARD_BT_IND_RESET_OOB_PIN  (18U)
#endif /*#define CONFIG_BT_IND_RESET*/

#if CONFIG_BT_ISO
#undef CONFIG_BT_EXT_ADV
#define CONFIG_BT_EXT_ADV                        1
#undef CONFIG_BT_EXT_ADV_LEGACY_SUPPORT
#define CONFIG_BT_EXT_ADV_LEGACY_SUPPORT         1
#undef CONFIG_BT_PER_ADV
#define CONFIG_BT_PER_ADV                        1
#undef CONFIG_BT_PER_ADV_SYNC
#define CONFIG_BT_PER_ADV_SYNC                   1
#undef CONFIG_BT_PER_ADV_SYNC_TRANSFER_RECEIVER
#define CONFIG_BT_PER_ADV_SYNC_TRANSFER_RECEIVER 1

#undef CONFIG_BT_ISO_UNICAST
#define CONFIG_BT_ISO_UNICAST                    1
#undef CONFIG_BT_ISO_BROADCAST
#define CONFIG_BT_ISO_BROADCAST                  1
#undef CONFIG_BT_ISO_BROADCASTER
#define CONFIG_BT_ISO_BROADCASTER                1
#undef CONFIG_BT_ISO_SYNC_RECEIVER
#define CONFIG_BT_ISO_SYNC_RECEIVER              1

#undef CONFIG_BT_ISO_PERIPHERAL
#define CONFIG_BT_ISO_PERIPHERAL                 1
#undef CONFIG_BT_ISO_CENTRAL
#define CONFIG_BT_ISO_CENTRAL                    1

#undef CONFIG_BT_GATT_AUTO_UPDATE_MTU
#define CONFIG_BT_GATT_AUTO_UPDATE_MTU           1

#undef CONFIG_BT_ISO_MAX_CHAN
#define CONFIG_BT_ISO_MAX_CHAN      4
#define CONFIG_BT_ISO_TEST_PARAMS   1
#undef CONFIG_BT_ISO_TX_BUF_COUNT
#define CONFIG_BT_ISO_TX_BUF_COUNT  10
#undef CONFIG_BT_ISO_RX_BUF_COUNT
#define CONFIG_BT_ISO_RX_BUF_COUNT  20
#undef CONFIG_BT_ISO_TX_MTU
#define CONFIG_BT_ISO_TX_MTU        310
#undef CONFIG_BT_ISO_RX_MTU
#define CONFIG_BT_ISO_RX_MTU        310
#endif

#if 0 /* This part of the shell functionality is not ready and should not be enabled. */
#undef CONFIG_BT_AUDIO
#define CONFIG_BT_AUDIO                   0
#undef CONFIG_BT_AUDIO_TX
#define CONFIG_BT_AUDIO_TX                0
#undef CONFIG_BT_AUDIO_RX
#define CONFIG_BT_AUDIO_RX                0
#undef CONFIG_BT_AICS
#define CONFIG_BT_AICS                    0
#undef CONFIG_BT_AICS_CLIENT
#define CONFIG_BT_AICS_CLIENT             0
#undef CONFIG_BT_BAP_UNICAST
#define CONFIG_BT_BAP_UNICAST             0
#undef CONFIG_BT_BAP_UNICAST_SERVER
#define CONFIG_BT_BAP_UNICAST_SERVER      0
#undef CONFIG_BT_BAP_UNICAST_CLIENT
#define CONFIG_BT_BAP_UNICAST_CLIENT      0
#undef CONFIG_BT_BAP_BROADCAST_SOURCE
#define CONFIG_BT_BAP_BROADCAST_SOURCE    0
#undef CONFIG_BT_BAP_BROADCAST_SINK
#define CONFIG_BT_BAP_BROADCAST_SINK      0
#undef CONFIG_BT_BAP_SCAN_DELEGATOR
#define CONFIG_BT_BAP_SCAN_DELEGATOR      0
#undef CONFIG_BT_BAP_BROADCAST_ASSISTANT
#define CONFIG_BT_BAP_BROADCAST_ASSISTANT 0
#undef CONFIG_BT_CAP_ACCEPTOR
#define CONFIG_BT_CAP_ACCEPTOR            0
#undef CONFIG_BT_CAP_INITIATOR
#define CONFIG_BT_CAP_INITIATOR           0
#undef CONFIG_BT_CAP_COMMANDER
#define CONFIG_BT_CAP_COMMANDER           0
#undef CONFIG_BT_CSIP_SET_MEMBER
#define CONFIG_BT_CSIP_SET_MEMBER         0
#undef CONFIG_BT_CSIP_SET_COORDINATOR
#define CONFIG_BT_CSIP_SET_COORDINATOR    0
#undef CONFIG_BT_HAS
#define CONFIG_BT_HAS                     0
#undef CONFIG_BT_HAS_CLIENT
#define CONFIG_BT_HAS_CLIENT              0
#undef CONFIG_BT_MCS
#define CONFIG_BT_MCS                     0
#undef CONFIG_BT_MCC
#define CONFIG_BT_MCC                     0
#undef CONFIG_BT_MCC_OTS
#define CONFIG_BT_MCC_OTS                 0
#undef CONFIG_MCTL
#define CONFIG_MCTL                       0
#undef CONFIG_BT_MICP_MIC_DEV
#define CONFIG_BT_MICP_MIC_DEV            0
#undef CONFIG_BT_MICP_MIC_CTLR
#define CONFIG_BT_MICP_MIC_CTLR           0
#undef CONFIG_BT_MPL
#define CONFIG_BT_MPL                     0
#undef CONFIG_BT_TBS
#define CONFIG_BT_TBS                     0
#undef CONFIG_BT_TBS_CLIENT_TBS
#define CONFIG_BT_TBS_CLIENT_TBS          0
#undef CONFIG_BT_TBS_CLIENT_GTBS
#define CONFIG_BT_TBS_CLIENT_GTBS         0
#undef CONFIG_BT_VCP_VOL_REND
#define CONFIG_BT_VCP_VOL_REND            0
#undef CONFIG_BT_VCP_VOL_CTLR
#define CONFIG_BT_VCP_VOL_CTLR            0
#undef CONFIG_BT_VOCS
#define CONFIG_BT_VOCS                    0
#undef CONFIG_BT_VOCS_CLIENT
#define CONFIG_BT_VOCS_CLIENT             0
#undef CONFIG_BT_OTS
#define CONFIG_BT_OTS                     0
#undef CONFIG_BT_OTS_CLIENT
#define CONFIG_BT_OTS_CLIENT              0
#undef CONFIG_BT_TMAP
#define CONFIG_BT_TMAP                    0
#undef CONFIG_BT_GMAP
#define CONFIG_BT_GMAP                    0
#undef CONFIG_BT_PBP
#define CONFIG_BT_PBP                     0
#define CONFIG_BT_IAS                     0
#define CONFIG_BT_IAS_CLIENT              0
#endif

#if CONFIG_BT_AUDIO
#undef CONFIG_BT_L2CAP_ECRED
#define CONFIG_BT_L2CAP_ECRED 1
#undef CONFIG_BT_EATT
#define CONFIG_BT_EATT        1
#endif

#if CONFIG_BT_BAP_UNICAST_SERVER
#undef CONFIG_BT_ASCS_ASE_SNK_COUNT
#define CONFIG_BT_ASCS_ASE_SNK_COUNT 2
#undef CONFIG_BT_ASCS_ASE_SRC_COUNT
#define CONFIG_BT_ASCS_ASE_SRC_COUNT 2

#undef CONFIG_BT_ATT_PREPARE_COUNT
#define CONFIG_BT_ATT_PREPARE_COUNT 5
#undef CONFIG_BT_ASCS
#define CONFIG_BT_ASCS 1
#undef CONFIG_BT_PAC_SNK
#define CONFIG_BT_PAC_SNK 1
#undef CONFIG_BT_PAC_SRC
#define CONFIG_BT_PAC_SRC 1

#undef CONFIG_BT_PACS_SUPPORTED_CONTEXT_NOTIFIABLE
#define CONFIG_BT_PACS_SUPPORTED_CONTEXT_NOTIFIABLE 1
#undef CONFIG_BT_PAC_SNK_LOC_NOTIFIABLE
#define CONFIG_BT_PAC_SNK_LOC_NOTIFIABLE 1
#undef CONFIG_BT_PAC_SRC_LOC_NOTIFIABLE
#define CONFIG_BT_PAC_SRC_LOC_NOTIFIABLE 1
#undef CONFIG_BT_PAC_SRC_NOTIFIABLE
#define CONFIG_BT_PAC_SRC_NOTIFIABLE 1
#undef CONFIG_BT_PAC_SNK_NOTIFIABLE
#define CONFIG_BT_PAC_SNK_NOTIFIABLE 1
#undef CONFIG_BT_PAC_SNK_LOC_WRITEABLE
#define CONFIG_BT_PAC_SNK_LOC_WRITEABLE 1
#undef CONFIG_BT_PAC_SRC_LOC_WRITEABLE
#define CONFIG_BT_PAC_SRC_LOC_WRITEABLE 1
#endif

#if CONFIG_BT_BAP_UNICAST_CLIENT
#undef CONFIG_BT_BAP_UNICAST_CLIENT_GROUP_STREAM_COUNT
#define CONFIG_BT_BAP_UNICAST_CLIENT_GROUP_STREAM_COUNT 4
#undef CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT
#define CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT      2
#undef CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT
#define CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT      2
#endif

#if CONFIG_BT_BAP_BROADCAST_SOURCE
#undef CONFIG_BT_BAP_BROADCAST_SRC_SUBGROUP_COUNT
#define CONFIG_BT_BAP_BROADCAST_SRC_SUBGROUP_COUNT 4
#undef CONFIG_BT_BAP_BROADCAST_SRC_STREAM_COUNT
#define CONFIG_BT_BAP_BROADCAST_SRC_STREAM_COUNT   4
#endif

#if CONFIG_BT_BAP_BROADCAST_SINK
#undef CONFIG_BT_BAP_BROADCAST_SNK_SUBGROUP_COUNT
#define CONFIG_BT_BAP_BROADCAST_SNK_SUBGROUP_COUNT 2
#undef CONFIG_BT_BAP_BROADCAST_SNK_STREAM_COUNT
#define CONFIG_BT_BAP_BROADCAST_SNK_STREAM_COUNT   4
#endif

#if CONFIG_BT_BAP_BROADCAST_ASSISTANT
#undef CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER
#define CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER 1
#endif

#if CONFIG_BT_CAP_ACCEPTOR
#undef CONFIG_BT_CAP_ACCEPTOR_SET_MEMBER
#define CONFIG_BT_CAP_ACCEPTOR_SET_MEMBER 1
#endif

#if CONFIG_BT_VCP_VOL_REND
#undef CONFIG_BT_VCP_VOL_REND_VOCS_INSTANCE_COUNT
#define CONFIG_BT_VCP_VOL_REND_VOCS_INSTANCE_COUNT  1
#undef CONFIG_BT_VCP_VOL_REND_AICS_INSTANCE_COUNT
#define CONFIG_BT_VCP_VOL_REND_AICS_INSTANCE_COUNT  1
#undef CONFIG_BT_VCP_VOL_REND_VOL_FLAGS_NOTIFIABLE
#define CONFIG_BT_VCP_VOL_REND_VOL_FLAGS_NOTIFIABLE 1
#endif

#if CONFIG_BT_VCP_VOL_CTLR
#ifndef CONFIG_BT_GATT_AUTO_DISCOVER_CCC
#undef CONFIG_BT_GATT_AUTO_DISCOVER_CCC
#define CONFIG_BT_GATT_AUTO_DISCOVER_CCC 1
#endif
#undef CONFIG_BT_VCP_VOL_CTLR_MAX_VOCS_INST
#define CONFIG_BT_VCP_VOL_CTLR_MAX_VOCS_INST 1
#undef CONFIG_BT_VCP_VOL_CTLR_MAX_AICS_INST
#define CONFIG_BT_VCP_VOL_CTLR_MAX_AICS_INST 0
#endif

#if CONFIG_BT_MICP_MIC_DEV
#undef CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT
#define CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT 1
#endif

#if CONFIG_BT_MICP_MIC_CTLR
#undef CONFIG_BT_MICP_MIC_CTLR_MAX_AICS_INST
#define CONFIG_BT_MICP_MIC_CTLR_MAX_AICS_INST 1
#endif

#if CONFIG_BT_CSIP_SET_MEMBER
#undef CONFIG_BT_CSIP_SET_COORDINATOR
#define CONFIG_BT_CSIP_SET_COORDINATOR 1
#undef CONFIG_BT_CSIP_SET_COORDINATOR_MAX_CSIS_INSTANCES
#define CONFIG_BT_CSIP_SET_COORDINATOR_MAX_CSIS_INSTANCES 2
#endif

#if CONFIG_BT_VOCS
#undef CONFIG_BT_VOCS_MAX_INSTANCE_COUNT
#define CONFIG_BT_VOCS_MAX_INSTANCE_COUNT 1
#endif

#if CONFIG_BT_VOCS_CLIENT
#undef CONFIG_BT_VOCS_CLIENT_MAX_INSTANCE_COUNT
#define CONFIG_BT_VOCS_CLIENT_MAX_INSTANCE_COUNT 1
#endif

#if CONFIG_BT_AICS
#undef CONFIG_BT_AICS_MAX_INSTANCE_COUNT
#define CONFIG_BT_AICS_MAX_INSTANCE_COUNT 1
#endif

#if CONFIG_BT_AICS_CLIENT
#undef CONFIG_BT_AICS_CLIENT_MAX_INSTANCE_COUNT
#define CONFIG_BT_AICS_CLIENT_MAX_INSTANCE_COUNT 1
#endif

#if CONFIG_BT_HAS
#undef CONFIG_UTF8
#define CONFIG_UTF8 1
#undef CONFIG_BT_HAS_FEATURES_NOTIFIABLE
#define CONFIG_BT_HAS_FEATURES_NOTIFIABLE 1
#undef CONFIG_BT_HAS_PRESET_NAME_DYNAMIC
#define CONFIG_BT_HAS_PRESET_NAME_DYNAMIC 1
#undef CONFIG_BT_HAS_PRESET_COUNT
#define CONFIG_BT_HAS_PRESET_COUNT 4
#undef CONFIG_BT_HAS_FEATURES_NOTIFIABLE
#define CONFIG_BT_HAS_FEATURES_NOTIFIABLE 1
#undef CONFIG_BT_HAS_PRESET_CONTROL_POINT_NOTIFIABLE
#define CONFIG_BT_HAS_PRESET_CONTROL_POINT_NOTIFIABLE 1
#endif

#if CONFIG_BT_MCS
#undef CONFIG_MCTL_LOCAL_PLAYER_REMOTE_CONTROL
#define CONFIG_MCTL_LOCAL_PLAYER_REMOTE_CONTROL 1
#undef CONFIG_BT_CCID
#define CONFIG_BT_CCID 1
#endif

#if CONFIG_BT_MCC
#undef CONFIG_BT_MCC_SHELL
#define CONFIG_BT_MCC_SHELL 1

#undef CONFIG_BT_MCC_TOTAL_OBJ_CONTENT_MEM
#define CONFIG_BT_MCC_TOTAL_OBJ_CONTENT_MEM 4096
#endif

#if CONFIG_BT_MCC_OTS
#undef CONFIG_BT_OTS_CLIENT
#define CONFIG_BT_OTS_CLIENT 1
#endif

#if CONFIG_MCTL
#undef CONFIG_MCTL_LOCAL_PLAYER_CONTROL
#define CONFIG_MCTL_LOCAL_PLAYER_CONTROL            1
#undef CONFIG_MCTL_LOCAL_PLAYER_LOCAL_CONTROL
#define CONFIG_MCTL_LOCAL_PLAYER_LOCAL_CONTROL      1
#undef CONFIG_MCTL_LOCAL_PLAYER_REMOTE_CONTROL
#define CONFIG_MCTL_LOCAL_PLAYER_REMOTE_CONTROL     1
#undef CONFIG_MCTL_REMOTE_PLAYER_CONTROL
#define CONFIG_MCTL_REMOTE_PLAYER_CONTROL           1
#undef CONFIG_MCTL_REMOTE_PLAYER_CONTROL_OBJECTS
#define CONFIG_MCTL_REMOTE_PLAYER_CONTROL_OBJECTS   1
#endif

#if CONFIG_BT_MPL
#undef CONFIG_BT_MPL_OBJECTS
#define CONFIG_BT_MPL_OBJECTS 1
#undef CONFIG_BT_MPL_MAX_OBJ_SIZE
#define CONFIG_BT_MPL_MAX_OBJ_SIZE      600
#undef CONFIG_BT_MPL_ICON_BITMAP_SIZE
#define CONFIG_BT_MPL_ICON_BITMAP_SIZE  321
#undef CONFIG_BT_MPL_TRACK_MAX_SIZE
#define CONFIG_BT_MPL_TRACK_MAX_SIZE    50

#undef CONFIG_BT_MPL_LOG_LEVEL_DBG
#define CONFIG_BT_MPL_LOG_LEVEL_DBG 1
#define CONFIG_BT_TESTING 1
#endif

#if CONFIG_BT_TBS
#undef CONFIG_BT_TBS_SUPPORTED_FEATURES
#define CONFIG_BT_TBS_SUPPORTED_FEATURES 3
#endif

#if CONFIG_BT_TBS_CLIENT_TBS || CONFIG_BT_TBS_CLIENT_GTBS
#undef CONFIG_BT_TBS_CLIENT_ACCEPT_CALL
#define CONFIG_BT_TBS_CLIENT_ACCEPT_CALL 1
#undef CONFIG_BT_TBS_CLIENT_TERMINATE_CALL
#define CONFIG_BT_TBS_CLIENT_TERMINATE_CALL 1
#undef CONFIG_BT_TBS_CLIENT_HOLD_CALL
#define CONFIG_BT_TBS_CLIENT_HOLD_CALL 1
#undef CONFIG_BT_TBS_CLIENT_RETRIEVE_CALL
#define CONFIG_BT_TBS_CLIENT_RETRIEVE_CALL 1
#undef CONFIG_BT_TBS_CLIENT_ORIGINATE_CALL
#define CONFIG_BT_TBS_CLIENT_ORIGINATE_CALL 1
#undef CONFIG_BT_TBS_CLIENT_JOIN_CALLS
#define CONFIG_BT_TBS_CLIENT_JOIN_CALLS 1
#undef CONFIG_BT_TBS_CLIENT_MAX_CALLS
#define CONFIG_BT_TBS_CLIENT_MAX_CALLS 2
#endif

#if CONFIG_BT_OTS
#undef CONFIG_BT_OTS_SECONDARY_SVC
#define CONFIG_BT_OTS_SECONDARY_SVC 1
#undef CONFIG_BT_OTS_MAX_OBJ_CNT
#define CONFIG_BT_OTS_MAX_OBJ_CNT   0x30
#endif

#if CONFIG_BT_BAP_SCAN_DELEGATOR
#undef CONFIG_BT_BAP_BASS_MAX_SUBGROUPS
#define CONFIG_BT_BAP_BASS_MAX_SUBGROUPS 2
#endif

#if 0
#undef CONFIG_BT_EXT_ADV
#define CONFIG_BT_EXT_ADV 1
#undef CONFIG_BT_PER_ADV
#define CONFIG_BT_PER_ADV 1
#endif

#if 0
#define CONFIG_BT_SMP_SELFTEST 1

#undef CONFIG_BT_DEBUG
#define CONFIG_BT_DEBUG 1

#define CONFIG_NET_BUF_LOG        1
#define CONFIG_NET_BUF_POOL_USAGE 1
#endif

#ifdef K32W061_TRANSCEIVER
#undef CONFIG_BT_CLASSIC
#endif

#define SHELL_BUFFER_SIZE 512U
#if ((defined(CONFIG_BT_MAP_MCE) && (CONFIG_BT_MAP_MCE > 0U)) || \
     (defined(CONFIG_BT_PBAP_PCE) && (CONFIG_BT_PBAP_PCE > 0U)))
#define SHELL_MAX_ARGS    40
#else
#define SHELL_MAX_ARGS    20
#endif

