/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define DEMO_PANEL 2
// #define CONFIG_DEMO_PANEL_RK055AHD091 0
// #define CONFIG_DEMO_PANEL_RK055IQH091 0
#define CONFIG_DEMO_PANEL_RK055MHD091A0 1
// #define CONFIG_DEMO_PANEL_G1120B0MIPI 0
// #define CONFIG_DEMO_PANEL_TFT_PROTO_5 0
// #define CONFIG_DEMO_PANEL_RASPI_7INCH 0
// #define CONFIG_DEMO_PANEL_ZC143AC72MIPI 0
#define SSD1963_DRIVEN_BY 1
// #define CONFIG_DEMO_PANEL_TFT_PROTO_5_FLEXIO 0
#define CONFIG_DEMO_PANEL_TFT_PROTO_5_LCDIF 1
// #define DEMO_SSD1963_BUFFER_FORMAT 0
// #define DEMO_RM67162_BUFFER_FORMAT 0
// #define DEMO_CO5300_BUFFER_FORMAT 0
#define CONFIG_FLASH_BASE_ADDRESS 0x28000000
#define CONFIG_FLEXIO_MCULCD_LEGACY_GPIO_FUNC 1
#define CONFIG_SEMA42_BUSY_POLL_COUNT 0
#define DBI_USE_MIPI_PANEL 1
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0
// #define CONFIG_FREERTOS_USE_CUSTOM_CONFIG_FRAGMENT 0
// #define MPU_SUPPORT 0
// #define USE_PERCEPIO_TRACELYZER 0

#endif /* _MCUX_CONFIG_H_ */
