/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef _APP_H_
#define _APP_H_

/*******************************************************************************
 * Definitions
 ******************************************************************************/
/*${macro:start}*/
#define APP_TARGET_POWER_NUM (11U)
#define APP_POWER_NAME                                                                                \
    {                                                                                                 \
        "Setpoint0, CM7 domain WAIT", "Setpoint1, CM7 domain STOP", "Setpoint2, CM7 domain STOP",     \
            "Setpoint3, CM7 domain STOP", "Setpoint4, CM7 domain STOP", "Setpoint5, CM7 domain STOP", \
            "Setpoint6, CM7 domain STOP", "Setpoint7, CM7 domain STOP", "Setpoint8, CM7 domain STOP", \
            "Setpoint9, CM7 domain SUSPEND", "Setpoint10, CM7 domain SUSPEND",                        \
    }

/* To test all resources' constraints, user application no need to cover all constraints. */
#define APP_SETPOINT0_CONSTRAINTS                                                                                    \
    43U, PM_RESC_CORE_DOMAIN_WAIT, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,       \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_ON, PM_RESC_OSC_RC_24M_CLK_ON, PM_RESC_ARM_PLL_ON,                \
        PM_RESC_ARM_PLL_CLK_ON, PM_RESC_SYS_PLL2_ON, PM_RESC_SYS_PLL2_CLK_ON, PM_RESC_SYS_PLL2_PFD0_ON,              \
        PM_RESC_SYS_PLL2_PFD1_ON, PM_RESC_SYS_PLL2_PFD2_ON, PM_RESC_SYS_PLL2_PFD3_ON, PM_RESC_SYS_PLL3_ON,           \
        PM_RESC_SYS_PLL3_CLK_ON, PM_RESC_SYS_PLL3_DVI2_ON, PM_RESC_SYS_PLL3_PFD0_ON, PM_RESC_SYS_PLL3_PFD1_ON,       \
        PM_RESC_SYS_PLL3_PFD2_ON, PM_RESC_SYS_PLL3_PFD3_ON, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,          \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_ON, PM_RESC_AUDIO_PLL_CLK_ON,        \
        PM_RESC_VIDEO_PLL_ON, PM_RESC_VIDEO_PLL_CLK_ON, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,                 \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                       \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_ON

#define APP_SETPOINT1_CONSTRAINTS                                                                                   \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,      \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_ON, PM_RESC_OSC_RC_24M_CLK_ON, PM_RESC_ARM_PLL_ON,               \
        PM_RESC_ARM_PLL_CLK_ON, PM_RESC_SYS_PLL2_ON, PM_RESC_SYS_PLL2_CLK_ON, PM_RESC_SYS_PLL2_PFD0_ON,             \
        PM_RESC_SYS_PLL2_PFD1_ON, PM_RESC_SYS_PLL2_PFD2_ON, PM_RESC_SYS_PLL2_PFD3_ON, PM_RESC_SYS_PLL3_ON,          \
        PM_RESC_SYS_PLL3_CLK_ON, PM_RESC_SYS_PLL3_DVI2_ON, PM_RESC_SYS_PLL3_PFD0_ON, PM_RESC_SYS_PLL3_PFD1_ON,      \
        PM_RESC_SYS_PLL3_PFD2_ON, PM_RESC_SYS_PLL3_PFD3_ON, PM_RESC_SYS_PLL1_ON, PM_RESC_SYS_PLL1_CLK_ON,           \
        PM_RESC_SYS_PLL1_DIV2_ON, PM_RESC_SYS_PLL1_DIV5_ON, PM_RESC_AUDIO_PLL_ON, PM_RESC_AUDIO_PLL_CLK_ON,         \
        PM_RESC_VIDEO_PLL_ON, PM_RESC_VIDEO_PLL_CLK_ON, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,                \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                      \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_ON, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_ON
#define APP_SETPOINT2_CONSTRAINTS                                                                                  \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,     \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_ON, PM_RESC_OSC_RC_24M_CLK_ON, PM_RESC_ARM_PLL_ON,              \
        PM_RESC_ARM_PLL_CLK_ON, PM_RESC_SYS_PLL2_ON, PM_RESC_SYS_PLL2_CLK_ON, PM_RESC_SYS_PLL2_PFD0_ON,            \
        PM_RESC_SYS_PLL2_PFD1_ON, PM_RESC_SYS_PLL2_PFD2_ON, PM_RESC_SYS_PLL2_PFD3_ON, PM_RESC_SYS_PLL3_ON,         \
        PM_RESC_SYS_PLL3_CLK_ON, PM_RESC_SYS_PLL3_DVI2_ON, PM_RESC_SYS_PLL3_PFD0_ON, PM_RESC_SYS_PLL3_PFD1_ON,     \
        PM_RESC_SYS_PLL3_PFD2_ON, PM_RESC_SYS_PLL3_PFD3_ON, PM_RESC_SYS_PLL1_ON, PM_RESC_SYS_PLL1_CLK_ON,          \
        PM_RESC_SYS_PLL1_DIV2_ON, PM_RESC_SYS_PLL1_DIV5_ON, PM_RESC_AUDIO_PLL_ON, PM_RESC_AUDIO_PLL_CLK_ON,        \
        PM_RESC_VIDEO_PLL_ON, PM_RESC_VIDEO_PLL_CLK_ON, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,               \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                     \
        PM_RESC_LPSR_DIG_LDO_ON, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_ON, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_ON
#define APP_SETPOINT3_CONSTRAINTS                                                                                  \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,     \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_ON, PM_RESC_OSC_RC_24M_CLK_ON, PM_RESC_ARM_PLL_ON,              \
        PM_RESC_ARM_PLL_CLK_ON, PM_RESC_SYS_PLL2_ON, PM_RESC_SYS_PLL2_CLK_ON, PM_RESC_SYS_PLL2_PFD0_ON,            \
        PM_RESC_SYS_PLL2_PFD1_ON, PM_RESC_SYS_PLL2_PFD2_ON, PM_RESC_SYS_PLL2_PFD3_ON, PM_RESC_SYS_PLL3_ON,         \
        PM_RESC_SYS_PLL3_CLK_ON, PM_RESC_SYS_PLL3_DVI2_ON, PM_RESC_SYS_PLL3_PFD0_ON, PM_RESC_SYS_PLL3_PFD1_ON,     \
        PM_RESC_SYS_PLL3_PFD2_ON, PM_RESC_SYS_PLL3_PFD3_ON, PM_RESC_SYS_PLL1_ON, PM_RESC_SYS_PLL1_CLK_ON,          \
        PM_RESC_SYS_PLL1_DIV2_ON, PM_RESC_SYS_PLL1_DIV5_ON, PM_RESC_AUDIO_PLL_ON, PM_RESC_AUDIO_PLL_CLK_ON,        \
        PM_RESC_VIDEO_PLL_ON, PM_RESC_VIDEO_PLL_CLK_ON, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,               \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                     \
        PM_RESC_LPSR_DIG_LDO_ON, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_ON, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_ON
#define APP_SETPOINT4_CONSTRAINTS                                                                                   \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,      \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_ON, PM_RESC_OSC_RC_24M_CLK_ON, PM_RESC_ARM_PLL_ON,               \
        PM_RESC_ARM_PLL_CLK_ON, PM_RESC_SYS_PLL2_ON, PM_RESC_SYS_PLL2_CLK_ON, PM_RESC_SYS_PLL2_PFD0_ON,             \
        PM_RESC_SYS_PLL2_PFD1_ON, PM_RESC_SYS_PLL2_PFD2_ON, PM_RESC_SYS_PLL2_PFD3_ON, PM_RESC_SYS_PLL3_ON,          \
        PM_RESC_SYS_PLL3_CLK_ON, PM_RESC_SYS_PLL3_DVI2_ON, PM_RESC_SYS_PLL3_PFD0_ON, PM_RESC_SYS_PLL3_PFD1_ON,      \
        PM_RESC_SYS_PLL3_PFD2_ON, PM_RESC_SYS_PLL3_PFD3_ON, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,         \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_ON, PM_RESC_AUDIO_PLL_CLK_ON,       \
        PM_RESC_VIDEO_PLL_ON, PM_RESC_VIDEO_PLL_CLK_ON, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,                \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                      \
        PM_RESC_LPSR_DIG_LDO_ON, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_ON
#define APP_SETPOINT5_CONSTRAINTS                                                                                    \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,       \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_ON, PM_RESC_OSC_RC_24M_CLK_ON, PM_RESC_ARM_PLL_OFF,               \
        PM_RESC_ARM_PLL_CLK_OFF, PM_RESC_SYS_PLL2_ON, PM_RESC_SYS_PLL2_CLK_ON, PM_RESC_SYS_PLL2_PFD0_ON,             \
        PM_RESC_SYS_PLL2_PFD1_ON, PM_RESC_SYS_PLL2_PFD2_ON, PM_RESC_SYS_PLL2_PFD3_ON, PM_RESC_SYS_PLL3_ON,           \
        PM_RESC_SYS_PLL3_CLK_ON, PM_RESC_SYS_PLL3_DVI2_ON, PM_RESC_SYS_PLL3_PFD0_ON, PM_RESC_SYS_PLL3_PFD1_ON,       \
        PM_RESC_SYS_PLL3_PFD2_ON, PM_RESC_SYS_PLL3_PFD3_ON, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,          \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_ON, PM_RESC_AUDIO_PLL_CLK_ON,        \
        PM_RESC_VIDEO_PLL_ON, PM_RESC_VIDEO_PLL_CLK_ON, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,                 \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                       \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_ON
#define APP_SETPOINT6_CONSTRAINTS                                                                                    \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,       \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_ON, PM_RESC_OSC_RC_24M_CLK_ON, PM_RESC_ARM_PLL_OFF,               \
        PM_RESC_ARM_PLL_CLK_OFF, PM_RESC_SYS_PLL2_ON, PM_RESC_SYS_PLL2_CLK_ON, PM_RESC_SYS_PLL2_PFD0_ON,             \
        PM_RESC_SYS_PLL2_PFD1_ON, PM_RESC_SYS_PLL2_PFD2_ON, PM_RESC_SYS_PLL2_PFD3_ON, PM_RESC_SYS_PLL3_ON,           \
        PM_RESC_SYS_PLL3_CLK_ON, PM_RESC_SYS_PLL3_DVI2_ON, PM_RESC_SYS_PLL3_PFD0_ON, PM_RESC_SYS_PLL3_PFD1_ON,       \
        PM_RESC_SYS_PLL3_PFD2_ON, PM_RESC_SYS_PLL3_PFD3_ON, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,          \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_ON, PM_RESC_AUDIO_PLL_CLK_ON,        \
        PM_RESC_VIDEO_PLL_ON, PM_RESC_VIDEO_PLL_CLK_ON, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,                 \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                       \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_ON
#define APP_SETPOINT7_CONSTRAINTS                                                                                    \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,       \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_OFF, PM_RESC_OSC_RC_24M_CLK_OFF, PM_RESC_ARM_PLL_OFF,             \
        PM_RESC_ARM_PLL_CLK_OFF, PM_RESC_SYS_PLL2_OFF, PM_RESC_SYS_PLL2_CLK_OFF, PM_RESC_SYS_PLL2_PFD0_OFF,          \
        PM_RESC_SYS_PLL2_PFD1_OFF, PM_RESC_SYS_PLL2_PFD2_OFF, PM_RESC_SYS_PLL2_PFD3_OFF, PM_RESC_SYS_PLL3_OFF,       \
        PM_RESC_SYS_PLL3_CLK_OFF, PM_RESC_SYS_PLL3_DVI2_OFF, PM_RESC_SYS_PLL3_PFD0_OFF, PM_RESC_SYS_PLL3_PFD1_OFF,   \
        PM_RESC_SYS_PLL3_PFD2_OFF, PM_RESC_SYS_PLL3_PFD3_OFF, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,        \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_OFF, PM_RESC_AUDIO_PLL_CLK_OFF,      \
        PM_RESC_VIDEO_PLL_OFF, PM_RESC_VIDEO_PLL_CLK_OFF, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,               \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                       \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_OFF
#define APP_SETPOINT8_CONSTRAINTS                                                                                  \
    43U, PM_RESC_CORE_DOMAIN_STOP, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,     \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_OFF, PM_RESC_OSC_RC_24M_CLK_OFF, PM_RESC_ARM_PLL_OFF,           \
        PM_RESC_ARM_PLL_CLK_OFF, PM_RESC_SYS_PLL2_OFF, PM_RESC_SYS_PLL2_CLK_OFF, PM_RESC_SYS_PLL2_PFD0_OFF,        \
        PM_RESC_SYS_PLL2_PFD1_OFF, PM_RESC_SYS_PLL2_PFD2_OFF, PM_RESC_SYS_PLL2_PFD3_OFF, PM_RESC_SYS_PLL3_OFF,     \
        PM_RESC_SYS_PLL3_CLK_OFF, PM_RESC_SYS_PLL3_DVI2_OFF, PM_RESC_SYS_PLL3_PFD0_OFF, PM_RESC_SYS_PLL3_PFD1_OFF, \
        PM_RESC_SYS_PLL3_PFD2_OFF, PM_RESC_SYS_PLL3_PFD3_OFF, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,      \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_OFF, PM_RESC_AUDIO_PLL_CLK_OFF,    \
        PM_RESC_VIDEO_PLL_OFF, PM_RESC_VIDEO_PLL_CLK_OFF, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,             \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                     \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_ON, PM_RESC_RBB_LPSR_ON, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_OFF
#define APP_SETPOINT9_CONSTRAINTS                                                                                    \
    43U, PM_RESC_CORE_DOMAIN_SUSPEND, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,    \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_OFF, PM_RESC_OSC_RC_24M_CLK_OFF, PM_RESC_ARM_PLL_OFF,             \
        PM_RESC_ARM_PLL_CLK_OFF, PM_RESC_SYS_PLL2_OFF, PM_RESC_SYS_PLL2_CLK_OFF, PM_RESC_SYS_PLL2_PFD0_OFF,          \
        PM_RESC_SYS_PLL2_PFD1_OFF, PM_RESC_SYS_PLL2_PFD2_OFF, PM_RESC_SYS_PLL2_PFD3_OFF, PM_RESC_SYS_PLL3_OFF,       \
        PM_RESC_SYS_PLL3_CLK_OFF, PM_RESC_SYS_PLL3_DVI2_OFF, PM_RESC_SYS_PLL3_PFD0_OFF, PM_RESC_SYS_PLL3_PFD1_OFF,   \
        PM_RESC_SYS_PLL3_PFD2_OFF, PM_RESC_SYS_PLL3_PFD3_OFF, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,        \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_OFF, PM_RESC_AUDIO_PLL_CLK_OFF,      \
        PM_RESC_VIDEO_PLL_OFF, PM_RESC_VIDEO_PLL_CLK_OFF, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,               \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                       \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_OFF, PM_RESC_RBB_LPSR_OFF, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_OFF
#define APP_SETPOINT10_CONSTRAINTS                                                                                 \
    43U, PM_RESC_CORE_DOMAIN_SUSPEND, PM_RESC_OSC_RC_16M_ON, PM_RESC_OSC_RC_48M_OFF, PM_RESC_OSC_RC_48M_DIV2_OFF,  \
        PM_RESC_OSC_RC_400M_ON, PM_RESC_OSC_RC_24M_OFF, PM_RESC_OSC_RC_24M_CLK_OFF, PM_RESC_ARM_PLL_OFF,           \
        PM_RESC_ARM_PLL_CLK_OFF, PM_RESC_SYS_PLL2_OFF, PM_RESC_SYS_PLL2_CLK_OFF, PM_RESC_SYS_PLL2_PFD0_OFF,        \
        PM_RESC_SYS_PLL2_PFD1_OFF, PM_RESC_SYS_PLL2_PFD2_OFF, PM_RESC_SYS_PLL2_PFD3_OFF, PM_RESC_SYS_PLL3_OFF,     \
        PM_RESC_SYS_PLL3_CLK_OFF, PM_RESC_SYS_PLL3_DVI2_OFF, PM_RESC_SYS_PLL3_PFD0_OFF, PM_RESC_SYS_PLL3_PFD1_OFF, \
        PM_RESC_SYS_PLL3_PFD2_OFF, PM_RESC_SYS_PLL3_PFD3_OFF, PM_RESC_SYS_PLL1_OFF, PM_RESC_SYS_PLL1_CLK_OFF,      \
        PM_RESC_SYS_PLL1_DIV2_OFF, PM_RESC_SYS_PLL1_DIV5_OFF, PM_RESC_AUDIO_PLL_OFF, PM_RESC_AUDIO_PLL_CLK_OFF,    \
        PM_RESC_VIDEO_PLL_OFF, PM_RESC_VIDEO_PLL_CLK_OFF, PM_RESC_MEGA_MIX_ON, PM_RESC_DISPLAY_MIX_ON,             \
        PM_RESC_WAKEUP_MIX_ON, PM_RESC_LPSR_MIX_ON, PM_RESC_DCDC_ON, PM_RESC_LPSR_ANA_LDO_OFF,                     \
        PM_RESC_LPSR_DIG_LDO_OFF, PM_RESC_BANDGAP_ON, PM_RESC_FBB_M7_OFF, PM_RESC_RBB_SOC_ON, PM_RESC_RBB_LPSR_ON, \
        PM_RESC_STANDBY_REQ_OFF, PM_RESC_PLL_LDO_OFF

#define APP_WAKEUP_BUTTON_GPIO        BOARD_USER_BUTTON_GPIO
#define APP_WAKEUP_BUTTON_GPIO_PIN    BOARD_USER_BUTTON_GPIO_PIN
#define APP_WAKEUP_BUTTON_IRQ         BOARD_USER_BUTTON_IRQ
#define APP_WAKEUP_BUTTON_IRQ_HANDLER BOARD_USER_BUTTON_IRQ_HANDLER
#define APP_WAKEUP_BUTTON_NAME        BOARD_USER_BUTTON_NAME
#define APP_WAKEUP_BUTTON_WSID        PM_WSID_GPIO13_COMBINED_0_31_IRQ

/*${macro:end}*/

/*******************************************************************************
 * Prototypes
 ******************************************************************************/
/*${prototype:start}*/
void BOARD_InitHardware(void);
void APP_InitWakeupSource(void);
void APP_RegisterNotify(void);
void APP_SetConstraints(uint8_t powerMode);
void APP_ReleaseConstraints(uint8_t powerMode);
uint32_t APP_GetWakeupTimeout(void);
/*${prototype:end}*/

#endif /* _APP_H_ */
