/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define CONFIG_CPU_CORTEX_M 1
#define CONFIG_FLASH_BASE_ADDRESS 0x04000000
#define CONFIG_FLASH_DEFAULT_APP_OFFSET 0x400
#define CONFIG_HAS_FLASH_LOAD_OFFSET 1
#define CONFIG_FLASH_LOAD_OFFSET 0x400
#define CONFIG_UART_RETRY_TIMES 0
// #define CONFIG_FLASH_DRIVER_EXECUTES_FROM_RAM 0
// #define CONFIG_ENABLE_QUICKACCESS_SECTION_IN_XSPI_DRIVER 0
#define DEBUG_CONSOLE_SYNCHRONIZATION_MODE 0
// #define SERIAL_MANAGER_NON_BLOCKING_MODE 0
// #define CONFIG_STREAM_FLASH 0
#define LITTLEFS_START_ADDR 0x400000
#define LITTLEFS_LOOKAHEAD_SIZE 16
#define LITTLEFS_READ_SIZE 16
#define LITTLEFS_PROG_SIZE 256
#define LITTLEFS_BLOCK_SIZE 4096
#define LITTLEFS_BLOCK_COUNT 1024
#define LITTLEFS_BLOCK_CYCLES 100
#define LITTLEFS_CACHE_SIZE 256
// #define LFS_FREE 0
// #define LFS_MALLOC 0
// #define LFS_NO_DEBUG 0
// #define LFS_NO_ERROR 0
// #define LFS_NO_INTRINSICS 0
// #define LFS_NO_MALLOC 0
// #define LFS_NO_WARN 0
// #define LFS_YES_TRACE 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
