/*
 * Copyright 2019 NXP.
 * This software is owned or controlled by NXP and may only be used strictly in accordance with the
 * license terms that accompany it. By expressly accepting such terms or by downloading, installing,
 * activating and/or otherwise using the software, you are agreeing that you have read, and that you
 * agree to comply with and are bound by, such license terms. If you do not agree to be bound by the
 * applicable license terms, then you may not retain, install, activate or otherwise use the software.
 */

#ifndef _SLN_FILE_TABLE_
#define _SLN_FILE_TABLE_

#include "sln_flash_mgmt.h"

/*! Addresses for files */
#define SLN_FLASH_TBL_RES           RESERVED
#define SLN_FLASH_TBL_STR(x)        #x
#define SLN_FLASH_TBL_PRINT(x)      SLN_FLASH_TBL_STR(x)
#define SLN_FLASH_TBL_CAT_OUT(a, b) a##b
#define SLN_FLASH_TBL_CAT(a, b)     SLN_FLASH_TBL_CAT_OUT(a, b)

#define SLN_FLASH_INDEX 0

#define SLN_FLASH_ENTRY(name, index, encrypt)          \
    {                                                  \
        name, SLN_FLASH_MGMT_FILE_ADDR(index), encrypt \
    }

const sln_flash_entry_t g_fileTable[] = {

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 1

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 2

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 3

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 4

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 5

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 6

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 7

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 8

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 9

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 10

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 11

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 12

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 13

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 14

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

// Start of NXP defined files; DO NOT edit below if using NXP kit & eco-system
#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 15

#ifdef AMZ_WW_MODEL_FILE_NAME
    SLN_FLASH_ENTRY(AMZ_WW_MODEL_FILE_NAME, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 16

#ifdef AIS_REGISTRATION_INFO_FILE_NAME
    SLN_FLASH_ENTRY(AIS_REGISTRATION_INFO_FILE_NAME, SLN_FLASH_INDEX, SLN_FLASH_ENCRYPTED),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 17

#ifdef AIS_ALERT_FILE_NAME
    SLN_FLASH_ENTRY(AIS_ALERT_FILE_NAME, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 18

#ifdef DEVICE_CONFIG_FILE_NAME
    SLN_FLASH_ENTRY(DEVICE_CONFIG_FILE_NAME, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 19

#ifdef WIFI_CRED_FILE_NAME
    SLN_FLASH_ENTRY(WIFI_CRED_FILE_NAME, SLN_FLASH_INDEX, SLN_FLASH_ENCRYPTED),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 20

#ifdef clientcredentialCLIENT_CERTIFICATE_PEM
    SLN_FLASH_ENTRY(clientcredentialCLIENT_CERTIFICATE_PEM, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 21

#ifdef clientcredentialCLIENT_PRIVATE_KEY_PEM
    SLN_FLASH_ENTRY(clientcredentialCLIENT_PRIVATE_KEY_PEM, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 22

#ifdef FAULT_STATUSREG_LOG_FILE_NAME
    SLN_FLASH_ENTRY(FAULT_STATUSREG_LOG_FILE_NAME, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 23

#ifdef ROOT_CA_CERT
    SLN_FLASH_ENTRY(ROOT_CA_CERT, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 24

#ifdef APP_A_SIGNING_CERT
    SLN_FLASH_ENTRY(APP_A_SIGNING_CERT, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 25

#ifdef APP_B_SIGNING_CERT
    SLN_FLASH_ENTRY(APP_B_SIGNING_CERT, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 26

#ifdef CRED_SIGNING_CERT
    SLN_FLASH_ENTRY(CRED_SIGNING_CERT, SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 27

#ifdef BLE_LTK_FILE
    SLN_FLASH_ENTRY(BLE_LTK_FILE, SLN_FLASH_INDEX, SLN_FLASH_ENCRYPTED),
#else
    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),
#endif
// End of NXP defined files

#undef SLN_FLASH_INDEX
#define SLN_FLASH_INDEX 28

    SLN_FLASH_ENTRY(
        SLN_FLASH_TBL_PRINT(SLN_FLASH_TBL_CAT(SLN_FLASH_TBL_RES, SLN_FLASH_INDEX)), SLN_FLASH_INDEX, SLN_FLASH_PLAIN),

    SLN_FLASH_ENTRY("", 0, 0)

};

#endif /* _SLN_FILE_TABLE_ */
