/*
 * Copyright 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MKV11Z128xxx7
package_id: MKV11Z128VLH7
mcu_data: ksdk2_0
processor_version: 0.7.1
board: TWR-KV11Z75M
pin_labels:
- {pin_num: '17', pin_signal: CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0, label: 'J18[12]/J22[B52]/J22[D52]/CMP0_IN5', identifier: SPI_PREDRIVER}
- {pin_num: '27', pin_signal: PTA5/FTM0_CH2/FTM5_FLT0, label: 'J22[B21]', identifier: USER_LED}
- {pin_num: '29', pin_signal: PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/FTM1_QD_PHB, label: 'J5[3]/U4[8]', identifier: BREAKING_RESISTOR}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    PinTool_FTM();
    PinTool_SPI();
    PinTool_UART();
    PinTool_Misc();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_FTM:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '44', peripheral: FTM0, signal: 'CH, 0', pin_signal: ADC1_SE3/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FTM2_CH0, direction: INPUT}
  - {pin_num: '45', peripheral: FTM0, signal: 'CH, 1', pin_signal: ADC0_SE11/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FTM2_CH1, direction: INPUT}
  - {pin_num: '46', peripheral: FTM0, signal: 'CH, 2', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/FTM3_FLT0, direction: INPUT}
  - {pin_num: '49', peripheral: FTM0, signal: 'CH, 3', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT, direction: INPUT}
  - {pin_num: '61', peripheral: FTM0, signal: 'CH, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FTM2_CH0/EWM_IN/SPI0_PCS0, direction: INPUT}
  - {pin_num: '62', peripheral: FTM0, signal: 'CH, 5', pin_signal: ADC0_SE3/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/FTM2_CH1/EWM_OUT_b/SPI0_SCK, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_FTM
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_FTM(void)
{
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    /* PORTC1 (pin 44) is configured as FTM0_CH0 */
    PORT_SetPinMux(PINTOOL_FTM_LED_GREEN1_PORT, PINTOOL_FTM_LED_GREEN1_PIN, kPORT_MuxAlt4);

    /* PORTC2 (pin 45) is configured as FTM0_CH1 */
    PORT_SetPinMux(PINTOOL_FTM_LED_YELLOW1_PORT, PINTOOL_FTM_LED_YELLOW1_PIN, kPORT_MuxAlt4);

    /* PORTC3 (pin 46) is configured as FTM0_CH2 */
    PORT_SetPinMux(PINTOOL_FTM_LED_GREEN2_PORT, PINTOOL_FTM_LED_GREEN2_PIN, kPORT_MuxAlt4);

    /* PORTC4 (pin 49) is configured as FTM0_CH3 */
    PORT_SetPinMux(PINTOOL_FTM_LED_YELLOW2_PORT, PINTOOL_FTM_LED_YELLOW2_PIN, kPORT_MuxAlt4);

    /* PORTD4 (pin 61) is configured as FTM0_CH4 */
    PORT_SetPinMux(PINTOOL_FTM_LED_GREEN3_PORT, PINTOOL_FTM_LED_GREEN3_PIN, kPORT_MuxAlt4);

    /* PORTD5 (pin 62) is configured as FTM0_CH5 */
    PORT_SetPinMux(PINTOOL_FTM_LED_YELLOW3_PORT, PINTOOL_FTM_LED_YELLOW3_PIN, kPORT_MuxAlt4);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_SPI:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '43', peripheral: SPI0, signal: PCS0_SS, pin_signal: ADC1_SE11/PTC0/SPI0_PCS4/PDB_EXTRG0/CMP0_OUT/FTM0_FLT0/SPI0_PCS0}
  - {pin_num: '50', peripheral: SPI0, signal: SCK, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2}
  - {pin_num: '59', peripheral: SPI0, signal: SOUT, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART0_RX/FTM0_CH2/FTM3_CH2/I2C0_SCL}
  - {pin_num: '60', peripheral: SPI0, signal: SIN, pin_signal: PTD3/SPI0_SIN/UART0_TX/FTM0_CH3/FTM3_CH3/I2C0_SDA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_SPI
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_SPI(void)
{
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    /* PORTC0 (pin 43) is configured as SPI0_PCS0 */
    PORT_SetPinMux(PORTC, 0U, kPORT_MuxAlt7);

    /* PORTC5 (pin 50) is configured as SPI0_SCK */
    PORT_SetPinMux(PORTC, 5U, kPORT_MuxAlt2);

    /* PORTD2 (pin 59) is configured as SPI0_SOUT */
    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt2);

    /* PORTD3 (pin 60) is configured as SPI0_SIN */
    PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt2);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_UART:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: UART0, signal: RX, pin_signal: PTB16/UART0_RX/FTM_CLKIN2/CAN0_TX/EWM_IN}
  - {pin_num: '40', peripheral: UART0, signal: TX, pin_signal: PTB17/UART0_TX/FTM_CLKIN1/CAN0_RX/EWM_OUT_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_UART
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_UART(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    /* PORTB16 (pin 39) is configured as UART0_RX */
    PORT_SetPinMux(PINTOOL_UART_DEBUG_UART_RX_PORT, PINTOOL_UART_DEBUG_UART_RX_PIN, kPORT_MuxAlt3);

    /* PORTB17 (pin 40) is configured as UART0_TX */
    PORT_SetPinMux(PINTOOL_UART_DEBUG_UART_TX_PORT, PINTOOL_UART_DEBUG_UART_TX_PIN, kPORT_MuxAlt3);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK)))

                  /* UART 0 Transmit Data Source Select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

                  /* UART 0 Receive Data Source Select: UART0_RX pin. */
                  | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PinTool_Misc:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '29', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/FTM1_QD_PHB, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '26', peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: PTA4/LLWU_P3/FTM0_CH1/FTM4_FLT0/FTM0_FLT3/NMI_b, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge,
    passive_filter: enable}
  - {pin_num: '27', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/FTM0_CH2/FTM5_FLT0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '17', peripheral: GPIOE, signal: 'GPIO, 29', pin_signal: CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '18', peripheral: GPIOE, signal: 'GPIO, 30', pin_signal: ADC1_SE4/CMP1_IN4/DAC0_OUT/PTE30/FTM0_CH3/FTM_CLKIN1}
  - {pin_num: '37', peripheral: FTM0, signal: 'FLT, 1', pin_signal: ADC0_SE10/ADC1_SE10/ADC1_DM2/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT1/FTM0_FLT3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PinTool_Misc
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PinTool_Misc(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA4 (pin 26)  */
    GPIO_PinInit(PINTOOL_MISC_SW2_GPIO, PINTOOL_MISC_SW2_PIN, &SW2_config);

    gpio_pin_config_t USER_LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA5 (pin 27)  */
    GPIO_PinInit(PINTOOL_MISC_USER_LED_GPIO, PINTOOL_MISC_USER_LED_PIN, &USER_LED_config);

    gpio_pin_config_t BREAKING_RESISTOR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 29)  */
    GPIO_PinInit(PINTOOL_MISC_BREAKING_RESISTOR_GPIO, PINTOOL_MISC_BREAKING_RESISTOR_PIN, &BREAKING_RESISTOR_config);

    gpio_pin_config_t SPI_PREDRIVER_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE29 (pin 17)  */
    GPIO_PinInit(PINTOOL_MISC_SPI_PREDRIVER_GPIO, PINTOOL_MISC_SPI_PREDRIVER_PIN, &SPI_PREDRIVER_config);

    /* PORTA13 (pin 29) is configured as PTA13 */
    PORT_SetPinMux(PINTOOL_MISC_BREAKING_RESISTOR_PORT, PINTOOL_MISC_BREAKING_RESISTOR_PIN, kPORT_MuxAsGpio);

    /* PORTA4 (pin 26) is configured as PTA4 */
    PORT_SetPinMux(PINTOOL_MISC_SW2_PORT, PINTOOL_MISC_SW2_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA4 (pin 26): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(PINTOOL_MISC_SW2_PORT, PINTOOL_MISC_SW2_PIN, kPORT_InterruptRisingEdge);

    PORTA->PCR[4] = ((PORTA->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Passive Filter Enable: Passive input filter is enabled on the corresponding pin, if the
                      * pin is configured as a digital input.
                      * Refer to the device data sheet for filter characteristics. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterEnable));

    /* PORTA5 (pin 27) is configured as PTA5 */
    PORT_SetPinMux(PINTOOL_MISC_USER_LED_PORT, PINTOOL_MISC_USER_LED_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 37) is configured as FTM0_FLT1 */
    PORT_SetPinMux(PINTOOL_MISC_THM3N_PORT, PINTOOL_MISC_THM3N_PIN, kPORT_MuxAlt4);

    /* PORTE29 (pin 17) is configured as PTE29 */
    PORT_SetPinMux(PINTOOL_MISC_SPI_PREDRIVER_PORT, PINTOOL_MISC_SPI_PREDRIVER_PIN, kPORT_MuxAsGpio);

    /* PORTE30 (pin 18) is configured as PTE30 */
    PORT_SetPinMux(PORTE, 30U, kPORT_MuxAsGpio);

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_FTM0FLT1_MASK)))

                  /* FTM0 Fault 1 Select: FTM0_FLT1 pin. */
                  | SIM_SOPT4_FTM0FLT1(SOPT4_FTM0FLT1_FTM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
