/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define APP_PHY_LINKUP_TIMEOUT_COUNT 800000U
#define APP_PHY_AUTONEGO_TIMEOUT_COUNT 800000U
#define APP_PHY_STABILITY_DELAY_US 500000U
// #define APP_USER_DEFINED_MAC_ADDRESS 0
#define APP_MAC_ADDRESS2 {0xd3, 0xbe, 0xd9, 0x45, 0x22, 0x60}
// #define APP_PHY_LINK_INTR_SUPPORT 0
#define CONFIG_FLASH_BASE_ADDRESS 0x08002000
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
