if(NOT MIDDLEWARE_MCU-BOOT_MIMXRT1062_DRIVERS_MIMXRT1062_INCLUDED)
    
    set(MIDDLEWARE_MCU-BOOT_MIMXRT1062_DRIVERS_MIMXRT1062_INCLUDED true CACHE BOOL "middleware_mcu-boot_MIMXRT1062_drivers component is included.")


    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/targets/MIMXRT1062/src
    )

endif()
