if(NOT DEVICE_MIMXRT595S_STARTUP_MIMXRT595S_cm33_INCLUDED)
    
    set(DEVICE_MIMXRT595S_STARTUP_MIMXRT595S_cm33_INCLUDED true CACHE BOOL "device_MIMXRT595S_startup component is included.")

    target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/gcc/startup_MIMXRT595S_cm33.S
    )


endif()
