if(NOT MIDDLEWARE_ISSDK_ALGORITHMS_PEDOMETER_LIB_CM4_MCIMX7U5_INCLUDED)
    
    set(MIDDLEWARE_ISSDK_ALGORITHMS_PEDOMETER_LIB_CM4_MCIMX7U5_INCLUDED true CACHE BOOL "middleware_issdk_algorithms_pedometer_lib_cm4 component is included.")

endif()
