# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_mbedtls_rt2_MIMXRT1176_cm7 true)
set(CONFIG_USE_middleware_usb_device_ehci_MIMXRT1176_cm7 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT1176_cm7 true)
set(CONFIG_USE_driver_lpuart_MIMXRT1176_cm7 true)
set(CONFIG_USE_middleware_baremetal_MIMXRT1176_cm7 true)
