# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_wifi_sdio_MIMXRT1042 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_MIMXRT1042 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT1042 true)
set(CONFIG_USE_middleware_wifi_MIMXRT1042 true)
set(CONFIG_USE_middleware_freertos-kernel_MIMXRT1042 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT1042 true)
set(CONFIG_USE_driver_lpuart_MIMXRT1042 true)
