if(NOT MIDDLEWARE_RTCESL_CM0_MKV11Z7_INCLUDED)
    
    set(MIDDLEWARE_RTCESL_CM0_MKV11Z7_INCLUDED true CACHE BOOL "middleware_rtcesl_cm0 component is included.")


    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/CM0_RTCESL_4.6_MCUX/AMCLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM0_RTCESL_4.6_MCUX/GDFLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM0_RTCESL_4.6_MCUX/GFLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM0_RTCESL_4.6_MCUX/GMCLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM0_RTCESL_4.6_MCUX/MLIB/Include
    )

endif()
