# Add set(CONFIG_USE_middleware_rtcesl_cm33f true) in config.cmake to use this component

include_guard(GLOBAL)
message("${CMAKE_CURRENT_LIST_FILE} component is included.")

      if(CONFIG_TOOLCHAIN STREQUAL iar AND CONFIG_CORE STREQUAL cm33 AND CONFIG_FPU STREQUAL SP_FPU)
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/AMCLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/GDFLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/GFLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/GMCLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/MLIB/Include
        )
    endif()

        if(CONFIG_TOOLCHAIN STREQUAL mdk AND CONFIG_CORE STREQUAL cm33 AND CONFIG_FPU STREQUAL SP_FPU)
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/AMCLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/GDFLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/GFLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/GMCLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/MLIB/Include
        )
    endif()

        if(CONFIG_TOOLCHAIN STREQUAL mcux AND CONFIG_CORE STREQUAL cm33 AND CONFIG_FPU STREQUAL SP_FPU)
    target_include_directories(${MCUX_SDK_PROJECT_NAME} PUBLIC
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/AMCLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/GDFLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/GFLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/GMCLIB/Include
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/MLIB/Include
        )
    endif()

  
      if(CONFIG_TOOLCHAIN STREQUAL iar AND CONFIG_CORE STREQUAL cm33 AND CONFIG_FPU STREQUAL SP_FPU)
    target_link_libraries(${MCUX_SDK_PROJECT_NAME} PRIVATE
    -Wl,--start-group
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/AMCLIB/AMCLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/GFLIB/GFLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/GDFLIB/GDFLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/GMCLIB/GMCLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_IAR/MLIB/MLIB.a
        -Wl,--end-group
    )
    endif()

        if(CONFIG_TOOLCHAIN STREQUAL mdk AND CONFIG_CORE STREQUAL cm33 AND CONFIG_FPU STREQUAL SP_FPU)
    target_link_libraries(${MCUX_SDK_PROJECT_NAME} PRIVATE
    -Wl,--start-group
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/AMCLIB/AMCLIB.lib
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/GFLIB/GFLIB.lib
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/GDFLIB/GDFLIB.lib
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/GMCLIB/GMCLIB.lib
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_KEIL/MLIB/MLIB.lib
        -Wl,--end-group
    )
    endif()

        if(CONFIG_TOOLCHAIN STREQUAL mcux AND CONFIG_CORE STREQUAL cm33 AND CONFIG_FPU STREQUAL SP_FPU)
    target_link_libraries(${MCUX_SDK_PROJECT_NAME} PRIVATE
    -Wl,--start-group
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/AMCLIB/libAMCLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/GFLIB/libGFLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/GDFLIB/libGDFLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/GMCLIB/libGMCLIB.a
          ${CMAKE_CURRENT_LIST_DIR}/CM33F_RTCESL_4.8.1_MCUX/MLIB/libMLIB.a
        -Wl,--end-group
    )
    endif()

  