if(NOT MIDDLEWARE_RTCESL_CM7F_MIMXRT1011_INCLUDED)
    
    set(MIDDLEWARE_RTCESL_CM7F_MIMXRT1011_INCLUDED true CACHE BOOL "middleware_rtcesl_cm7f component is included.")


    target_include_directories(${MCUX_SDK_PROJECT_NAME} PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/CM7F_RTCESL_4.6_MCUX/AMCLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM7F_RTCESL_4.6_MCUX/GDFLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM7F_RTCESL_4.6_MCUX/GFLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM7F_RTCESL_4.6_MCUX/GMCLIB/Include
        ${CMAKE_CURRENT_LIST_DIR}/CM7F_RTCESL_4.6_MCUX/MLIB/Include
    )

endif()
