/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define DEMO_PANEL 2
// #define CONFIG_DEMO_PANEL_RK055AHD091 0
// #define CONFIG_DEMO_PANEL_RK055IQH091 0
#define CONFIG_DEMO_PANEL_RK055MHD091A0 1
// #define CONFIG_DEMO_PANEL_G1120B0MIPI 0
// #define CONFIG_DEMO_PANEL_TFT_PROTO_5 0
// #define CONFIG_DEMO_PANEL_ZC143AC72MIPI 0
#define CONFIG_FLASH_BASE_ADDRESS 0x08000000
#define CONFIG_FLEXIO_MCULCD_LEGACY_GPIO_FUNC 1
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN 
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST 
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
