# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_usb_host_khci_MK66F18 true)
set(CONFIG_USE_middleware_usb_host_ehci_MK66F18 true)
set(CONFIG_USE_middleware_lwip_usb_ethernetif_MK66F18 true)
set(CONFIG_USE_component_serial_manager_uart_MK66F18 true)
set(CONFIG_USE_driver_uart_MK66F18 true)
set(CONFIG_USE_middleware_baremetal_MK66F18 true)
