# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_CMSIS_Include_core_cm7_MIMXRT1166_cm7 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT1166_cm7 true)
set(CONFIG_USE_driver_lpuart_MIMXRT1166_cm7 true)
set(CONFIG_USE_middleware_usb_host_ehci_MIMXRT1166_cm7 true)
set(CONFIG_USE_middleware_baremetal_MIMXRT1166_cm7 true)
