/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define DEMO_PANEL 2
// #define CONFIG_DEMO_PANEL_RK055AHD091 0
// #define CONFIG_DEMO_PANEL_RK055IQH091 0
#define CONFIG_DEMO_PANEL_RK055MHD091A0 1
// #define CONFIG_DEMO_PANEL_G1120B0MIPI 0
// #define CONFIG_DEMO_PANEL_TFT_PROTO_5 0
// #define CONFIG_DEMO_PANEL_RASPI_7INCH 0
// #define CONFIG_DEMO_PANEL_ZC143AC72MIPI 0
#define SSD1963_DRIVEN_BY 1
// #define CONFIG_DEMO_PANEL_TFT_PROTO_5_FLEXIO 0
#define CONFIG_DEMO_PANEL_TFT_PROTO_5_LCDIF 1
// #define DEMO_SSD1963_BUFFER_FORMAT 0
// #define DEMO_RM67162_BUFFER_FORMAT 0
// #define DEMO_CO5300_BUFFER_FORMAT 0
#define CONFIG_FLASH_BASE_ADDRESS 0x28000000
#define CONFIG_FLEXIO_MCULCD_LEGACY_GPIO_FUNC 1
#define DBI_USE_MIPI_PANEL 1
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
#define CONFIG_LV_OS_CUSTOM_INCLUDE "stdint.h"
#define CONFIG_LV_DRAW_SW_ASM_CUSTOM_INCLUDE ""
#define CONFIG_LV_ASSERT_HANDLER_INCLUDE "assert.h"
#define CONFIG_LV_GLOBAL_CUSTOM_INCLUDE "lv_global.h"
#define CONFIG_LV_TXT_BREAK_CHARS " ,.;:-_)}"
#define CONFIG_LV_PROFILER_INCLUDE "lvgl/src/misc/lv_profiler_builtin.h"
#define CONFIG_LV_TXT_COLOR_CMD "#"
#define CONFIG_LV_MONDAY_STR "Mo"
#define CONFIG_LV_TUESDAY_STR "Tu"
#define CONFIG_LV_WEDNESDAY_STR "We"
#define CONFIG_LV_THURSDAY_STR "Th"
#define CONFIG_LV_FRIDAY_STR "Fr"
#define CONFIG_LV_SATURDAY_STR "Sa"
#define CONFIG_LV_SUNDAY_STR "Su"
// #define CONFIG_LV_USE_DRAW_SW 0
#define CONFIG_LV_USE_DRAW_VGLITE 1
// #define CONFIG_LV_USE_PXP 0
#define CONFIG_LV_DEMO_BENCHMARK_ALIGNED_FONTS 1
// #define CONFIG_LV_CONF_SKIP 0
#define CONFIG_LV_CONF_MINIMAL 1
// #define CONFIG_LV_COLOR_DEPTH_32 0
// #define CONFIG_LV_COLOR_DEPTH_24 0
#define CONFIG_LV_COLOR_DEPTH_16 1
// #define CONFIG_LV_COLOR_DEPTH_8 0
// #define CONFIG_LV_COLOR_DEPTH_1 0
#define CONFIG_LV_COLOR_DEPTH 16
#define CONFIG_LV_USE_BUILTIN_MALLOC 1
// #define CONFIG_LV_USE_CLIB_MALLOC 0
// #define CONFIG_LV_USE_MICROPYTHON_MALLOC 0
// #define CONFIG_LV_USE_RTTHREAD_MALLOC 0
// #define CONFIG_LV_USE_CUSTOM_MALLOC 0
#define CONFIG_LV_USE_BUILTIN_STRING 1
// #define CONFIG_LV_USE_CLIB_STRING 0
// #define CONFIG_LV_USE_CUSTOM_STRING 0
#define CONFIG_LV_USE_BUILTIN_SPRINTF 1
// #define CONFIG_LV_USE_CLIB_SPRINTF 0
// #define CONFIG_LV_USE_CUSTOM_SPRINTF 0
#define CONFIG_LV_MEM_SIZE_KILOBYTES 64
#define CONFIG_LV_MEM_POOL_EXPAND_SIZE_KILOBYTES 0
#define CONFIG_LV_MEM_ADR 0x0
#define CONFIG_LV_DEF_REFR_PERIOD 33
#define CONFIG_LV_DPI_DEF 130
// #define CONFIG_LV_OS_NONE 0
// #define CONFIG_LV_OS_PTHREAD 0
#define CONFIG_LV_OS_FREERTOS 1
// #define CONFIG_LV_OS_CMSIS_RTOS2 0
// #define CONFIG_LV_OS_RTTHREAD 0
// #define CONFIG_LV_OS_WINDOWS 0
// #define CONFIG_LV_OS_MQX 0
// #define CONFIG_LV_OS_CUSTOM 0
#define CONFIG_LV_USE_FREERTOS_TASK_NOTIFY 1
#define CONFIG_LV_DRAW_BUF_STRIDE_ALIGN 1
#define CONFIG_LV_DRAW_BUF_ALIGN 64
#define CONFIG_LV_DRAW_LAYER_MAX_MEMORY 0
#define CONFIG_LV_DRAW_THREAD_STACK_SIZE 8192
#define CONFIG_LV_DRAW_THREAD_PRIO 3
// #define CONFIG_LV_USE_VGLITE_BLIT_SPLIT 0
#define CONFIG_LV_USE_VGLITE_DRAW_THREAD 1
#define CONFIG_LV_USE_VGLITE_DRAW_ASYNC 1
// #define CONFIG_LV_USE_VGLITE_ASSERT 0
// #define CONFIG_LV_USE_VGLITE_CHECK_ERROR 0
// #define CONFIG_LV_USE_DRAW_G2D 0
// #define CONFIG_LV_USE_DRAW_DAVE2D 0
// #define CONFIG_LV_USE_DRAW_SDL 0
// #define CONFIG_LV_USE_DRAW_VG_LITE 0
// #define CONFIG_LV_USE_VECTOR_GRAPHIC 0
// #define CONFIG_LV_USE_DRAW_DMA2D 0
#define CONFIG_LV_USE_LOG 1
// #define CONFIG_LV_LOG_LEVEL_TRACE 0
// #define CONFIG_LV_LOG_LEVEL_INFO 0
// #define CONFIG_LV_LOG_LEVEL_WARN 0
#define CONFIG_LV_LOG_LEVEL_ERROR 1
// #define CONFIG_LV_LOG_LEVEL_USER 0
// #define CONFIG_LV_LOG_LEVEL_NONE 0
#define CONFIG_LV_LOG_LEVEL 3
// #define CONFIG_LV_LOG_PRINTF 0
#define CONFIG_LV_LOG_USE_TIMESTAMP 1
#define CONFIG_LV_LOG_USE_FILE_LINE 1
#define CONFIG_LV_LOG_TRACE_MEM 1
#define CONFIG_LV_LOG_TRACE_TIMER 1
#define CONFIG_LV_LOG_TRACE_INDEV 1
#define CONFIG_LV_LOG_TRACE_DISP_REFR 1
#define CONFIG_LV_LOG_TRACE_EVENT 1
#define CONFIG_LV_LOG_TRACE_OBJ_CREATE 1
#define CONFIG_LV_LOG_TRACE_LAYOUT 1
#define CONFIG_LV_LOG_TRACE_ANIM 1
#define CONFIG_LV_LOG_TRACE_CACHE 1
// #define CONFIG_LV_USE_ASSERT_NULL 0
// #define CONFIG_LV_USE_ASSERT_MALLOC 0
// #define CONFIG_LV_USE_ASSERT_STYLE 0
// #define CONFIG_LV_USE_ASSERT_MEM_INTEGRITY 0
// #define CONFIG_LV_USE_ASSERT_OBJ 0
// #define CONFIG_LV_USE_REFR_DEBUG 0
// #define CONFIG_LV_USE_LAYER_DEBUG 0
// #define CONFIG_LV_USE_PARALLEL_DRAW_DEBUG 0
// #define CONFIG_LV_ENABLE_GLOBAL_CUSTOM 0
#define CONFIG_LV_COLOR_MIX_ROUND_OFS 128
// #define CONFIG_LV_OBJ_STYLE_CACHE 0
// #define CONFIG_LV_USE_OBJ_ID 0
// #define CONFIG_LV_USE_OBJ_NAME 0
// #define CONFIG_LV_USE_OBJ_PROPERTY 0
// #define CONFIG_LV_BIG_ENDIAN_SYSTEM 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN_SIZE 64
// #define CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM 0
// #define CONFIG_LV_USE_FLOAT 0
// #define CONFIG_LV_USE_MATRIX 0
// #define CONFIG_LV_USE_PRIVATE_API 0
// #define CONFIG_LV_FONT_MONTSERRAT_8 0
// #define CONFIG_LV_FONT_MONTSERRAT_10 0
// #define CONFIG_LV_FONT_MONTSERRAT_12 0
// #define CONFIG_LV_FONT_MONTSERRAT_14 0
#define CONFIG_LV_FONT_MONTSERRAT_16 1
// #define CONFIG_LV_FONT_MONTSERRAT_18 0
// #define CONFIG_LV_FONT_MONTSERRAT_20 0
// #define CONFIG_LV_FONT_MONTSERRAT_22 0
#define CONFIG_LV_FONT_MONTSERRAT_24 1
// #define CONFIG_LV_FONT_MONTSERRAT_26 0
// #define CONFIG_LV_FONT_MONTSERRAT_28 0
// #define CONFIG_LV_FONT_MONTSERRAT_30 0
// #define CONFIG_LV_FONT_MONTSERRAT_32 0
// #define CONFIG_LV_FONT_MONTSERRAT_34 0
// #define CONFIG_LV_FONT_MONTSERRAT_36 0
// #define CONFIG_LV_FONT_MONTSERRAT_38 0
// #define CONFIG_LV_FONT_MONTSERRAT_40 0
// #define CONFIG_LV_FONT_MONTSERRAT_42 0
// #define CONFIG_LV_FONT_MONTSERRAT_44 0
// #define CONFIG_LV_FONT_MONTSERRAT_46 0
// #define CONFIG_LV_FONT_MONTSERRAT_48 0
// #define CONFIG_LV_FONT_MONTSERRAT_28_COMPRESSED 0
// #define CONFIG_LV_FONT_DEJAVU_16_PERSIAN_HEBREW 0
// #define CONFIG_LV_FONT_SIMSUN_14_CJK 0
// #define CONFIG_LV_FONT_SIMSUN_16_CJK 0
// #define CONFIG_LV_FONT_SOURCE_HAN_SANS_SC_14_CJK 0
// #define CONFIG_LV_FONT_SOURCE_HAN_SANS_SC_16_CJK 0
#define CONFIG_LV_FONT_UNSCII_8 1
// #define CONFIG_LV_FONT_UNSCII_16 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_8 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_10 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_12 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_14 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_18 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_22 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_24 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_30 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_32 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_34 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_36 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_38 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_40 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_42 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_44 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_46 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_48 0
// #define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28_COMPRESSED 0
// #define CONFIG_LV_FONT_DEFAULT_DEJAVU_16_PERSIAN_HEBREW 0
// #define CONFIG_LV_FONT_DEFAULT_SIMSUN_14_CJK 0
// #define CONFIG_LV_FONT_DEFAULT_SIMSUN_16_CJK 0
// #define CONFIG_LV_FONT_DEFAULT_SOURCE_HAN_SANS_SC_14_CJK 0
// #define CONFIG_LV_FONT_DEFAULT_SOURCE_HAN_SANS_SC_16_CJK 0
#define CONFIG_LV_FONT_DEFAULT_UNSCII_8 1
// #define CONFIG_LV_FONT_DEFAULT_UNSCII_16 0
// #define CONFIG_LV_FONT_FMT_TXT_LARGE 0
// #define CONFIG_LV_USE_FONT_COMPRESSED 0
#define CONFIG_LV_USE_FONT_PLACEHOLDER 1
// #define CONFIG_LV_TXT_ENC_UTF8 0
#define CONFIG_LV_TXT_ENC_ASCII 1
#define CONFIG_LV_TXT_LINE_BREAK_LONG_LEN 0
// #define CONFIG_LV_USE_BIDI 0
// #define CONFIG_LV_USE_ARABIC_PERSIAN_CHARS 0
// #define CONFIG_LV_WIDGETS_HAS_DEFAULT_VALUE 0
// #define CONFIG_LV_USE_ANIMIMG 0
// #define CONFIG_LV_USE_ARC 0
// #define CONFIG_LV_USE_BAR 0
// #define CONFIG_LV_USE_BUTTON 0
// #define CONFIG_LV_USE_BUTTONMATRIX 0
// #define CONFIG_LV_USE_CALENDAR 0
// #define CONFIG_LV_USE_CANVAS 0
// #define CONFIG_LV_USE_CHART 0
// #define CONFIG_LV_USE_CHECKBOX 0
// #define CONFIG_LV_USE_DROPDOWN 0
// #define CONFIG_LV_USE_IMAGE 0
// #define CONFIG_LV_USE_IMAGEBUTTON 0
// #define CONFIG_LV_USE_KEYBOARD 0
#define CONFIG_LV_USE_LABEL 1
#define CONFIG_LV_LABEL_TEXT_SELECTION 1
#define CONFIG_LV_LABEL_LONG_TXT_HINT 1
#define CONFIG_LV_LABEL_WAIT_CHAR_COUNT 3
// #define CONFIG_LV_USE_LED 0
// #define CONFIG_LV_USE_LINE 0
// #define CONFIG_LV_USE_LIST 0
// #define CONFIG_LV_USE_MENU 0
// #define CONFIG_LV_USE_MSGBOX 0
// #define CONFIG_LV_USE_ROLLER 0
// #define CONFIG_LV_USE_SCALE 0
// #define CONFIG_LV_USE_SLIDER 0
// #define CONFIG_LV_USE_SPAN 0
// #define CONFIG_LV_USE_SPINBOX 0
// #define CONFIG_LV_USE_SPINNER 0
// #define CONFIG_LV_USE_SWITCH 0
// #define CONFIG_LV_USE_TEXTAREA 0
// #define CONFIG_LV_USE_TABLE 0
// #define CONFIG_LV_USE_TABVIEW 0
// #define CONFIG_LV_USE_TILEVIEW 0
// #define CONFIG_LV_USE_WIN 0
#define CONFIG_LV_USE_THEME_DEFAULT 1
// #define CONFIG_LV_THEME_DEFAULT_DARK 0
#define CONFIG_LV_THEME_DEFAULT_GROW 1
#define CONFIG_LV_THEME_DEFAULT_TRANSITION_TIME 80
// #define CONFIG_LV_USE_THEME_SIMPLE 0
// #define CONFIG_LV_USE_THEME_MONO 0
// #define CONFIG_LV_USE_FLEX 0
// #define CONFIG_LV_USE_GRID 0
#define CONFIG_LV_FS_DEFAULT_DRIVER_LETTER 0
// #define CONFIG_LV_USE_FS_STDIO 0
// #define CONFIG_LV_USE_FS_POSIX 0
// #define CONFIG_LV_USE_FS_WIN32 0
// #define CONFIG_LV_USE_FS_FATFS 0
// #define CONFIG_LV_USE_FS_RAWFS 0
// #define CONFIG_LV_USE_FS_MEMFS 0
// #define CONFIG_LV_USE_FS_LITTLEFS 0
// #define CONFIG_LV_USE_FS_ARDUINO_ESP_LITTLEFS 0
// #define CONFIG_LV_USE_FS_ARDUINO_SD 0
// #define CONFIG_LV_USE_FS_UEFI 0
// #define CONFIG_LV_USE_LODEPNG 0
// #define CONFIG_LV_USE_LIBPNG 0
// #define CONFIG_LV_USE_BMP 0
// #define CONFIG_LV_USE_TJPGD 0
// #define CONFIG_LV_USE_LIBJPEG_TURBO 0
// #define CONFIG_LV_USE_GIF 0
// #define CONFIG_LV_BIN_DECODER_RAM_LOAD 0
// #define CONFIG_LV_USE_RLE 0
// #define CONFIG_LV_USE_QRCODE 0
// #define CONFIG_LV_USE_BARCODE 0
// #define CONFIG_LV_USE_FREETYPE 0
// #define CONFIG_LV_USE_TINY_TTF 0
// #define CONFIG_LV_USE_RLOTTIE 0
// #define CONFIG_LV_USE_THORVG 0
// #define CONFIG_LV_USE_LZ4 0
// #define CONFIG_LV_USE_FFMPEG 0
// #define CONFIG_LV_USE_SNAPSHOT 0
#define CONFIG_LV_USE_SYSMON 1
#define CONFIG_LV_USE_PERF_MONITOR 1
// #define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_LEFT 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_MID 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_TOP_RIGHT 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_LEFT 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_MID 0
#define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_RIGHT 1
// #define CONFIG_LV_PERF_MONITOR_ALIGN_LEFT_MID 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_RIGHT_MID 0
// #define CONFIG_LV_PERF_MONITOR_ALIGN_CENTER 0
// #define CONFIG_LV_USE_PERF_MONITOR_LOG_MODE 0
// #define CONFIG_LV_USE_MEM_MONITOR 0
// #define CONFIG_LV_USE_PROFILER 0
// #define CONFIG_LV_USE_MONKEY 0
// #define CONFIG_LV_USE_GRIDNAV 0
// #define CONFIG_LV_USE_FRAGMENT 0
// #define CONFIG_LV_USE_IMGFONT 0
#define CONFIG_LV_USE_OBSERVER 1
// #define CONFIG_LV_USE_IME_PINYIN 0
// #define CONFIG_LV_USE_FILE_EXPLORER 0
// #define CONFIG_LV_USE_FONT_MANAGER 0
// #define CONFIG_LV_USE_TEST 0
// #define CONFIG_LV_USE_XML 0
// #define CONFIG_LV_USE_COLOR_FILTER 0
#define CONFIG_LVGL_VERSION_MAJOR 9
#define CONFIG_LVGL_VERSION_MINOR 3
#define CONFIG_LVGL_VERSION_PATCH 0
// #define CONFIG_LV_USE_SDL 0
// #define CONFIG_LV_USE_X11 0
// #define CONFIG_LV_USE_WAYLAND 0
// #define CONFIG_LV_USE_LINUX_FBDEV 0
// #define CONFIG_LV_USE_NUTTX 0
// #define CONFIG_LV_USE_LINUX_DRM 0
// #define CONFIG_LV_USE_TFT_ESPI 0
// #define CONFIG_LV_USE_EVDEV 0
// #define CONFIG_LV_USE_LIBINPUT 0
// #define CONFIG_LV_USE_ST7735 0
// #define CONFIG_LV_USE_ST7789 0
// #define CONFIG_LV_USE_ST7796 0
// #define CONFIG_LV_USE_ILI9341 0
// #define CONFIG_LV_USE_GENERIC_MIPI 0
// #define CONFIG_LV_USE_RENESAS_GLCDC 0
// #define CONFIG_LV_USE_ST_LTDC 0
// #define CONFIG_LV_USE_FT81X 0
// #define CONFIG_LV_USE_UEFI 0
// #define CONFIG_LV_USE_OPENGLES 0
// #define CONFIG_LV_USE_QNX 0
// #define CONFIG_LV_BUILD_EXAMPLES 0
// #define CONFIG_LV_BUILD_DEMOS 0
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN __attribute__((aligned(LV_ATTRIBUTE_MEM_ALIGN_SIZE)))
#define CONFIG_LV_ATTRIBUTE_LARGE_CONST __attribute__((section("DataQuickAccess")))
#define CONFIG_LV_SYSMON_GET_IDLE getIdleTaskPct
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0
#define CONFIG_FREERTOS_USE_CUSTOM_CONFIG_FRAGMENT 1
// #define MPU_SUPPORT 0
// #define USE_PERCEPIO_TRACELYZER 0

#endif /* _MCUX_CONFIG_H_ */
