# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_component_mflash_rt685_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_wifi_wiced_MURATA_TYPE1DX_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_MIMXRT685S_cm33 true)
set(CONFIG_USE_component_serial_manager_uart_MIMXRT685S_cm33 true)
set(CONFIG_USE_driver_flexcomm_usart_MIMXRT685S_cm33 true)
