# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_sdmmc_host_usdhc_K32L3A60_cm4 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_freertos_K32L3A60_cm4 true)
set(CONFIG_USE_component_serial_manager_uart_K32L3A60_cm4 true)
set(CONFIG_USE_driver_lpuart_K32L3A60_cm4 true)
set(CONFIG_USE_CMSIS_Include_core_cm4_K32L3A60_cm4 true)
